import { randomUUID } from 'node:crypto';import type { Phase3Repository,Segment3,SegmentVersion3,SegmentEstimate3,StoredEvent3,Flow3,FlowVersion3 } from '../../../application/src/ports/phase3-repository.js';import type { GenericEventInput,GenericEventSchema } from '../../../domain/src/phase3/generic-events.js';import type { SegmentRule } from '../../../domain/src/phase3/segment-rules.js';import type { FlowGraph3 } from '../../../domain/src/phase3/flow.js';import {flowGraphHash} from '../../../domain/src/phase3/flow.js';
export class InMemoryPhase3Repository implements Phase3Repository{
 segments=new Map<string,Segment3>();versions=new Map<string,SegmentVersion3[]>();schemas=new Map<string,GenericEventSchema>();events=new Map<string,StoredEvent3>();flows=new Map<string,Flow3>();flowVersions=new Map<string,FlowVersion3[]>();constructor(public phase2Gate=false,public profileUniverse:Array<{id:string;workspaceId:string;eligible:boolean;country?:string}>=[]){ }
 async createSegment(i:{workspaceId:string;name:string;description?:string;rule:SegmentRule}){const x:Segment3={id:randomUUID(),workspaceId:i.workspaceId,name:i.name,description:i.description??'',status:'draft',draftRule:i.rule,createdAt:new Date(),updatedAt:new Date()};this.segments.set(x.id,x);return x}
 async updateSegment(i:{workspaceId:string;segmentId:string;name?:string;rule?:SegmentRule}){const x=await this.segment(i.workspaceId,i.segmentId);if(!x)throw new Error('SEGMENT_NOT_FOUND');const y={...x,name:i.name??x.name,draftRule:i.rule??x.draftRule,updatedAt:new Date()};this.segments.set(x.id,y);return y}
 async listSegments(w:string){return [...this.segments.values()].filter(x=>x.workspaceId===w)}async segment(w:string,id:string){const x=this.segments.get(id);return x?.workspaceId===w?x:null}
 async publishSegment(w:string,id:string){const x=await this.segment(w,id);if(!x)throw new Error('SEGMENT_NOT_FOUND');const arr=this.versions.get(id)??[];const v:SegmentVersion3={id:randomUUID(),workspaceId:w,segmentId:id,versionNumber:arr.length+1,rule:structuredClone(x.draftRule),publishedAt:new Date()};arr.push(v);this.versions.set(id,arr);this.segments.set(id,{...x,status:'active'});return v}
 async estimateSegment(w:string,id:string){if(!await this.segment(w,id))throw new Error('SEGMENT_NOT_FOUND');const p=this.profileUniverse.filter(x=>x.workspaceId===w);const result:SegmentEstimate3={segmentId:id,count:p.length,eligibleCount:p.filter(x=>x.eligible).length,sampleProfileIds:p.slice(0,5).map(x=>x.id),evaluatedAt:new Date(),status:'current',exact:true};return result}
 async saveEventSchema(w:string,s:GenericEventSchema){this.schemas.set(`${w}|${s.name}|${s.version}`,structuredClone(s))}async eventSchema(w:string,n:string,v:number){return this.schemas.get(`${w}|${n}|${v}`)??null}
 async insertEvent(w:string,i:GenericEventInput){const key=`${w}|${i.source}|${i.idempotencyKey}`;const old=this.events.get(key);if(old)return {event:old,duplicate:true};const e:StoredEvent3={...structuredClone(i),id:randomUUID(),workspaceId:w,receivedAt:new Date().toISOString()};this.events.set(key,e);return {event:e,duplicate:false}}
 async eventById(w:string,id:string){return [...this.events.values()].find(x=>x.workspaceId===w&&x.id===id)??null}
 async listEvents(w:string){return [...this.events.values()].filter(x=>x.workspaceId===w)}
 async createFlow(i:{workspaceId:string;name:string;graph:FlowGraph3}){const f:Flow3={id:randomUUID(),workspaceId:i.workspaceId,name:i.name,status:'draft',draftGraph:structuredClone(i.graph),rowVersion:1,updatedAt:new Date()};this.flows.set(f.id,f);return f}
 async updateFlow(i:{workspaceId:string;flowId:string;graph:FlowGraph3;rowVersion:number;name?:string}){const f=await this.flow(i.workspaceId,i.flowId);if(!f)throw new Error('FLOW_NOT_FOUND');if(f.rowVersion!==i.rowVersion)throw new Error('FLOW_CONFLICT');const name=i.name?.trim();if(i.name!==undefined&&!name)throw new Error('FLOW_NAME_REQUIRED');const u={...f,...(name?{name}:{}),draftGraph:structuredClone(i.graph),rowVersion:f.rowVersion+1,updatedAt:new Date()};this.flows.set(f.id,u);return u}
 async flow(w:string,id:string){const f=this.flows.get(id);return f?.workspaceId===w?f:null}async listFlows(w:string){return [...this.flows.values()].filter(x=>x.workspaceId===w)}
 async publishFlow(w:string,id:string,expectedRowVersion?:number){const f=await this.flow(w,id);if(!f)throw new Error('FLOW_NOT_FOUND');if(expectedRowVersion!==undefined&&f.rowVersion!==expectedRowVersion)throw new Error('FLOW_CONFLICT');const a=this.flowVersions.get(id)??[];const v:FlowVersion3={id:randomUUID(),workspaceId:w,flowId:id,versionNumber:a.length+1,graph:structuredClone(f.draftGraph),graphHash:flowGraphHash(f.draftGraph),publishedAt:new Date()};a.push(v);this.flowVersions.set(id,a);return v}
 async publishedFlowVersion(w:string,id:string){for(const versions of this.flowVersions.values()){const match=versions.find(v=>v.id===id&&v.workspaceId===w);if(match)return structuredClone(match)}return null}
 async activateFlow(w:string,id:string,v:string,status:'testing'|'active'){const f=await this.flow(w,id);if(!f)throw new Error('FLOW_NOT_FOUND');if(!(this.flowVersions.get(id)??[]).some(x=>x.id===v))throw new Error('FLOW_VERSION_NOT_FOUND');const u={...f,status,activeVersionId:v,updatedAt:new Date()};this.flows.set(id,u);return u}
 async scheduleProfileDateEntries(_: {workspaceId:string;flowId:string;flowVersionId:string;activatedAt:Date}){return {scheduled:0,skipped:0}}
 async phase2ExternalGatePassed(){return this.phase2Gate}
}
