import { randomUUID } from "node:crypto";
import type { Phase2Repository, P2BrandKit, P2ContentVariable, P2DeliveryAttempt, P2EmailTemplate, P2Hold, P2MediaAsset, P2Message, P2Profile, P2SenderDomain, P2SenderIdentity, P2TemplateUsage, P2TemplateVersion, P2TrackingLink, P2UniversalBlock, P2Workspace, P2WorkspaceProviderConfig } from "../../../application/src/ports/phase2-repository.js";
import type { EmailDraft, PublishedEmailVersion, StructuredEmailDocument } from "../../../domain/src/phase2/content.js";
import type { MessagePolicyDecision } from "../../../domain/src/phase2/message-policy.js";
import type { SendPolicyConfig } from "../../../domain/src/phase2/send-policy.js";

function clone<T>(v:T):T{return structuredClone(v)}

export class InMemoryPhase2Repository implements Phase2Repository {
  members=new Map<string,string>(); workspaces=new Map<string,P2Workspace>(); profiles=new Map<string,P2Profile>(); subscriptions=new Map<string,string>(); protectedSuppression=new Set<string>();
  identities=new Map<string,P2SenderIdentity>(); domains=new Map<string,P2SenderDomain>(); providerConfigs=new Map<string,P2WorkspaceProviderConfig>(); templates=new Map<string,P2EmailTemplate>();
  universalBlocks=new Map<string,P2UniversalBlock>(); mediaAssets=new Map<string,P2MediaAsset>(); brandKits=new Map<string,P2BrandKit>(); contentVariables=new Map<string,P2ContentVariable>();   templateVersions=new Map<string,P2TemplateVersion[]>(); templateUsages=new Map<string,P2TemplateUsage[]>();
  audits:Array<{workspaceId:string;actorId:string;action:string;objectType:string;objectId?:string;riskLevel:string;before?:unknown;after?:unknown}>=[];
  private assetKeys=new Map<string,string>();
  emails=new Map<string,EmailDraft>(); versions=new Map<string,PublishedEmailVersion[]>(); testSnapshots=new Map<string,any>(); messages=new Map<string,P2Message>(); traces=new Map<string,Array<{kind:string;occurredAt:Date;detail:unknown}>>();
  policies=new Map<string,SendPolicyConfig>(); holds=new Map<string,P2Hold>(); frequency=new Map<string,{workspaceId:string;profileId:string;messageId:string;reservedAt:Date;expiresAt:Date;consumedAt?:Date;releasedAt?:Date}>();
  artifacts=new Map<string,{objectKey:string;mimeHash:string;contentHash:string}>(); attempts=new Map<string,P2DeliveryAttempt>(); deliveryEvents=new Set<string>(); deliveryFacts:Array<{workspaceId:string;messageId:string;eventType:string;occurredAt:Date}>=[]; tracking=new Map<string,P2TrackingLink>(); engagement:Array<{workspaceId:string;messageId:string;kind:string;classification:string;occurredAt:Date}> = [];

  seedWorkspace(workspace:P2Workspace,userId="owner",role="owner"){this.workspaces.set(workspace.id,clone(workspace));this.members.set(`${workspace.id}:${userId}`,role)}
  seedProfile(profile:P2Profile,consent="granted"){this.profiles.set(`${profile.workspaceId}:${profile.id}`,clone(profile));this.subscriptions.set(`${profile.workspaceId}:${profile.id}`,consent)}
  seedSender(domain:P2SenderDomain,identity:P2SenderIdentity){this.domains.set(`${domain.workspaceId}:${domain.id}`,clone(domain));this.identities.set(`${identity.workspaceId}:${identity.id}`,clone(identity))}
  seedWorkspaceProviderConfig(workspaceId:string,config:P2WorkspaceProviderConfig){this.providerConfigs.set(`${workspaceId}:${config.provider}`,clone(config))}
  setProtectedSuppression(workspaceId:string,profileId:string,on=true){const k=`${workspaceId}:${profileId}`;if(on)this.protectedSuppression.add(k);else this.protectedSuppression.delete(k)}
  async transaction<T>(fn:(tx:Phase2Repository)=>Promise<T>):Promise<T>{return fn(this)}
  async memberRole(w:string,u:string){return this.members.get(`${w}:${u}`)??null}
  async workspace(w:string){return clone(this.workspaces.get(w)??null)}
  async profile(w:string,p:string){return clone(this.profiles.get(`${w}:${p}`)??null)}
  async searchProfiles(w:string,query:string,limit:number){const q=query.toLowerCase();return [...this.profiles.values()].filter(profile=>profile.workspaceId===w&&(`${profile.firstName??""} ${profile.lastName??""} ${profile.originalEmail}`).toLowerCase().includes(q)).slice(0,limit).map(clone)}
  async eventSample(_w:string,_eventId:string,_profileId:string){return null}
  async subscriptionStatus(w:string,p:string){return this.subscriptions.get(`${w}:${p}`)??"unknown"}
  async activeProtectedSuppression(w:string,p:string){return this.protectedSuppression.has(`${w}:${p}`)}
  async senderIdentity(w:string,id:string){return clone(this.identities.get(`${w}:${id}`)??null)}
  async senderDomain(w:string,id:string){return clone(this.domains.get(`${w}:${id}`)??null)}
  async workspaceProviderConfig(w:string,provider:string){return clone(this.providerConfigs.get(`${w}:${provider}`)??null)}
  async createEmail(input:{workspaceId:string;name:string;authoringMode:string;draftDocument:StructuredEmailDocument;plainText:string}){const now=new Date().toISOString();const d:EmailDraft={id:randomUUID(),workspaceId:input.workspaceId,internalName:input.name,authoringMode:input.authoringMode as any,subject:"",preheader:"",senderIdentityId:null,replyTo:"",structuredDocument:clone(input.draftDocument),htmlSource:null,plainText:input.plainText,trackingEnabled:true,openTrackingEnabled:false,rowVersion:1,state:"draft",createdAt:now,updatedAt:now};this.emails.set(d.id,d);return clone(d)}
  async emailDraft(w:string,id:string){const d=this.emails.get(id);return d&&d.workspaceId===w?clone(d):null}
  async listEmails(w:string){return [...this.emails.values()].filter(x=>x.workspaceId===w).map(clone)}
  async listEmailLibrary(w:string,input:{cursor?:string;limit:number;query?:string;sort?:"updated"|"name";archived?:boolean}){let items=[...this.emails.values()].filter(x=>x.workspaceId===w&&Boolean(x.archivedAt)===Boolean(input.archived));if(input.query){const q=input.query.toLowerCase();items=items.filter(x=>x.internalName.toLowerCase().includes(q)||x.subject.toLowerCase().includes(q))}items.sort(input.sort==="name"?(a,b)=>a.internalName.localeCompare(b.internalName):(a,b)=>b.updatedAt.localeCompare(a.updatedAt));const page=items.slice(0,input.limit);return {items:page.map(x=>({id:x.id,internalName:x.internalName,subject:x.subject,rowVersion:x.rowVersion,draftState:x.archivedAt?"archived":"draft",latestPublishedVersion:(this.versions.get(x.id)??[]).at(-1)??null,usedByFlowCount:0,preflight:{state:"not_run"},updatedAt:x.updatedAt})),nextCursor:null}}
  async updateEmailDraft(input:{workspaceId:string;emailId:string;expectedRowVersion:number;patch:Partial<EmailDraft>}){const d=this.emails.get(input.emailId);if(!d||d.workspaceId!==input.workspaceId)throw new Error("EMAIL_NOT_FOUND");if(d.rowVersion!==input.expectedRowVersion)throw new Error("CONCURRENCY_CONFLICT");const next={...d,...clone(input.patch),id:d.id,workspaceId:d.workspaceId,rowVersion:d.rowVersion+1,updatedAt:new Date().toISOString()};this.emails.set(d.id,next);return clone(next)}
  async listEmailVersions(w:string,id:string){const d=await this.emailDraft(w,id);if(!d)throw new Error("EMAIL_NOT_FOUND");return clone(this.versions.get(id)??[])}
  async emailVersion(w:string,versionId:string){for(const list of this.versions.values()){const v=list.find(x=>x.id===versionId&&x.workspaceId===w);if(v)return clone(v)}return null}
  async insertEmailVersion(v:PublishedEmailVersion){const list=this.versions.get(v.emailDefinitionId)??[];if(list.some(x=>x.versionNumber===v.versionNumber))throw new Error("EMAIL_VERSION_EXISTS");list.push(clone(v));this.versions.set(v.emailDefinitionId,list);return clone(v)}
  async savePreflight(_i:{workspaceId:string;emailId:string;result:unknown;fingerprint:string}){}
  async archiveEmail(i:{workspaceId:string;emailId:string;actorId:string;archived:boolean}){const d=await this.emailDraft(i.workspaceId,i.emailId);if(!d)throw new Error("EMAIL_NOT_FOUND");d.archivedAt=i.archived?new Date().toISOString():null;this.emails.set(d.id,d);return clone(d)}
  async createTestSnapshot(i:any){const snapshot={...i,createdAt:i.createdAt??new Date()};this.testSnapshots.set(i.id,clone(snapshot));return clone(snapshot)}
  async testSnapshot(w:string,id:string){const x=this.testSnapshots.get(id);return x?.workspaceId===w?clone(x):null}
  async emailDependencies(_w:string,_id:string){return []}
  async listEmailTemplates(w:string,input:{cursor?:string;limit:number;query?:string;archived?:boolean}){const query=input.query?.toLocaleLowerCase();const items=[...this.templates.values()].filter(template=>template.workspaceId===w&&Boolean(template.archivedAt)===Boolean(input.archived)&&(!query||template.name.toLocaleLowerCase().includes(query)||(template.category??"").toLocaleLowerCase().includes(query))).sort((a,b)=>b.updatedAt.getTime()-a.updatedAt.getTime()||b.id.localeCompare(a.id));const afterCursor=input.cursor?items.findIndex(template=>template.id===input.cursor)+1:0;const page=items.slice(Math.max(0,afterCursor),Math.max(0,afterCursor)+input.limit);return {items:page.map(clone),nextCursor:items.length>Math.max(0,afterCursor)+page.length?page.at(-1)?.id??null:null}}
  async emailTemplate(w:string,id:string,input:{includeArchived?:boolean}={}){const template=this.templates.get(id);return template&&template.workspaceId===w&&(input.includeArchived||!template.archivedAt)?clone(template):null}
  async createEmailTemplate(input:{workspaceId:string;name:string;category?:string;document:StructuredEmailDocument;subject:string;preheader:string;plainText:string;settings?:Record<string,unknown>;editorType?:"visual"|"html"|"text";sourceType?:string;actorId:string}){const now=new Date(),template:P2EmailTemplate={id:randomUUID(),workspaceId:input.workspaceId,name:input.name,category:input.category??null,document:clone(input.document),subject:input.subject,preheader:input.preheader,plainText:input.plainText,settings:clone(input.settings??null),editorType:input.editorType??"visual",sourceType:input.sourceType??"blank",templateType:"native",importMethod:null,originalFilename:null,originalSourceHtml:null,sanitizedHtml:null,conversionStatus:"not_requested",importWarnings:null,importedAt:null,importedByUserId:null,createdById:input.actorId,updatedById:input.actorId,archivedAt:null,createdAt:now,updatedAt:now};this.templates.set(template.id,template);return clone(template)}
  async createImportedEmailTemplate(input:{workspaceId:string;name:string;category?:string;document:StructuredEmailDocument;subject:string;preheader:string;plainText:string;settings?:Record<string,unknown>;actorId:string;templateType:string;importMethod:string;originalFilename:string|null;originalSourceHtml:string;sanitizedHtml:string;conversionStatus:string;importWarnings:P2EmailTemplate["importWarnings"];importedAt:Date;importedByUserId:string}){const now=new Date(),template:P2EmailTemplate={id:randomUUID(),workspaceId:input.workspaceId,name:input.name,category:input.category??null,document:clone(input.document),subject:input.subject,preheader:input.preheader,plainText:input.plainText,settings:clone(input.settings??null),editorType:"html",sourceType:input.importMethod,templateType:input.templateType,importMethod:input.importMethod,originalFilename:input.originalFilename,originalSourceHtml:input.originalSourceHtml,sanitizedHtml:input.sanitizedHtml,conversionStatus:input.conversionStatus,importWarnings:clone(input.importWarnings),importedAt:input.importedAt,importedByUserId:input.importedByUserId,createdById:input.actorId,updatedById:input.actorId,archivedAt:null,createdAt:now,updatedAt:now};this.templates.set(template.id,template);return clone(template)}
  async updateEmailTemplate(input:{workspaceId:string;templateId:string;name?:string;category?:string|null;document?:StructuredEmailDocument;subject?:string;preheader?:string;plainText?:string;settings?:Record<string,unknown>|null;originalSourceHtml?:string|null;sanitizedHtml?:string|null;conversionStatus?:string;templateType?:string;importWarnings?:P2EmailTemplate["importWarnings"];actorId?:string}){const template=await this.emailTemplate(input.workspaceId,input.templateId);if(!template)throw new Error("TEMPLATE_NOT_FOUND");if(input.name!==undefined)template.name=input.name;if(input.category!==undefined)template.category=input.category;if(input.document!==undefined)template.document=clone(input.document);if(input.subject!==undefined)template.subject=input.subject;if(input.preheader!==undefined)template.preheader=input.preheader;if(input.plainText!==undefined)template.plainText=input.plainText;if(input.settings!==undefined)template.settings=clone(input.settings);if(input.originalSourceHtml!==undefined)template.originalSourceHtml=input.originalSourceHtml;if(input.sanitizedHtml!==undefined)template.sanitizedHtml=input.sanitizedHtml;if(input.conversionStatus!==undefined)template.conversionStatus=input.conversionStatus;if(input.templateType!==undefined)template.templateType=input.templateType;if(input.importWarnings!==undefined)template.importWarnings=clone(input.importWarnings);if(input.actorId!==undefined)template.updatedById=input.actorId;template.updatedAt=new Date();this.templates.set(template.id,template);return clone(template)}
  async archiveEmailTemplate(input:{workspaceId:string;templateId:string;archived:boolean}){const template=await this.emailTemplate(input.workspaceId,input.templateId,{includeArchived:true});if(!template)throw new Error("TEMPLATE_NOT_FOUND");template.archivedAt=input.archived?new Date():null;template.updatedAt=new Date();this.templates.set(template.id,template);return clone(template)}
  async deleteEmailTemplate(input:{workspaceId:string;templateId:string}){const template=this.templates.get(input.templateId);if(!template||template.workspaceId!==input.workspaceId)throw new Error("TEMPLATE_NOT_FOUND");this.templates.delete(input.templateId)}
  async listUniversalBlocks(w:string,input:{archived?:boolean}){return [...this.universalBlocks.values()].filter(x=>x.workspaceId===w&&Boolean(x.archivedAt)===Boolean(input.archived)).sort((a,b)=>b.updatedAt.getTime()-a.updatedAt.getTime()).map(clone)}
  async createUniversalBlock(i:{workspaceId:string;name:string;category?:string;blocks:StructuredEmailDocument["blocks"];actorId:string}){const now=new Date(),x:P2UniversalBlock={id:randomUUID(),workspaceId:i.workspaceId,name:i.name,category:i.category??null,blocks:clone(i.blocks),archivedAt:null,createdAt:now,updatedAt:now};this.universalBlocks.set(x.id,x);return clone(x)}
  async updateUniversalBlock(i:{workspaceId:string;blockId:string;name?:string;category?:string|null;blocks?:StructuredEmailDocument["blocks"]}){const x=this.universalBlocks.get(i.blockId);if(!x||x.workspaceId!==i.workspaceId||x.archivedAt)throw new Error("UNIVERSAL_BLOCK_NOT_FOUND");if(i.name!==undefined)x.name=i.name;if(i.category!==undefined)x.category=i.category;if(i.blocks!==undefined)x.blocks=clone(i.blocks);x.updatedAt=new Date();return clone(x)}
  async archiveUniversalBlock(i:{workspaceId:string;blockId:string;archived:boolean}){const x=this.universalBlocks.get(i.blockId);if(!x||x.workspaceId!==i.workspaceId)throw new Error("UNIVERSAL_BLOCK_NOT_FOUND");x.archivedAt=i.archived?new Date():null;x.updatedAt=new Date();return clone(x)}
  async listMediaAssets(w:string,input:{archived?:boolean}){return [...this.mediaAssets.values()].filter(x=>x.workspaceId===w&&Boolean(x.archivedAt)===Boolean(input.archived)).sort((a,b)=>b.updatedAt.getTime()-a.updatedAt.getTime()).map(clone)}
  async createMediaAsset(i:{workspaceId:string;name:string;url:string;altText:string;mimeType:string;actorId:string;objectKey?:string;assetId?:string}){const now=new Date(),x:P2MediaAsset={id:i.assetId??randomUUID(),workspaceId:i.workspaceId,name:i.name,url:i.url,altText:i.altText,mimeType:i.mimeType,archivedAt:null,createdAt:now,updatedAt:now};this.mediaAssets.set(x.id,x);if(i.objectKey)this.assetKeys.set(`${i.workspaceId}:${x.id}`,i.objectKey);return clone(x)}
  async contentAssetObjectKey(w:string,assetId:string){return this.assetKeys.get(`${w}:${assetId}`)??null}
  async archiveMediaAsset(i:{workspaceId:string;assetId:string;archived:boolean}){const x=this.mediaAssets.get(i.assetId);if(!x||x.workspaceId!==i.workspaceId)throw new Error("MEDIA_ASSET_NOT_FOUND");x.archivedAt=i.archived?new Date():null;x.updatedAt=new Date();return clone(x)}
  async brandKit(w:string){return clone(this.brandKits.get(w)??null)}
  async upsertBrandKit(i:{workspaceId:string;logoUrl:string|null;primaryColor:string;secondaryColor:string;fontFamily:string}){const x:P2BrandKit={workspaceId:i.workspaceId,logoUrl:i.logoUrl,primaryColor:i.primaryColor,secondaryColor:i.secondaryColor,fontFamily:i.fontFamily,updatedAt:new Date()};this.brandKits.set(i.workspaceId,x);return clone(x)}
  async listContentVariables(w:string,input:{archived?:boolean}){return [...this.contentVariables.values()].filter(x=>x.workspaceId===w&&Boolean(x.archivedAt)===Boolean(input.archived)).sort((a,b)=>a.label.localeCompare(b.label)).map(clone)}
  async createContentVariable(i:{workspaceId:string;key:string;label:string;defaultValue:string;type:"text"|"url";actorId:string}){const now=new Date(),x:P2ContentVariable={id:randomUUID(),workspaceId:i.workspaceId,key:i.key,label:i.label,defaultValue:i.defaultValue,type:i.type,archivedAt:null,createdAt:now,updatedAt:now};this.contentVariables.set(x.id,x);return clone(x)}
  async archiveContentVariable(i:{workspaceId:string;variableId:string;archived:boolean}){const x=this.contentVariables.get(i.variableId);if(!x||x.workspaceId!==i.workspaceId)throw new Error("CONTENT_VARIABLE_NOT_FOUND");x.archivedAt=i.archived?new Date():null;x.updatedAt=new Date();return clone(x)}
  async listTemplateVersions(w:string,templateId:string){return clone((this.templateVersions.get(templateId)??[]).filter(x=>x.workspaceId===w).sort((a,b)=>b.versionNumber-a.versionNumber))}
  async insertTemplateVersion(i:Omit<P2TemplateVersion,"id">){const list=this.templateVersions.get(i.templateId)??[];const x:P2TemplateVersion={...clone(i),id:randomUUID()};list.push(x);this.templateVersions.set(i.templateId,list);return clone(x)}
  async recordTemplateUsage(i:{workspaceId:string;templateId:string;templateVersionId?:string;usageType:"email";referenceId:string;label:string}){const x:P2TemplateUsage={id:randomUUID(),workspaceId:i.workspaceId,templateId:i.templateId,templateVersionId:i.templateVersionId??null,usageType:i.usageType,referenceId:i.referenceId,label:i.label,createdAt:new Date()};this.templateUsages.set(i.templateId,[...(this.templateUsages.get(i.templateId)??[]),x])}
  async recordTemplateImportAudit(_i:{workspaceId:string;userId:string;importMethod:string;filename:string|null;templateId:string;processingResult:string;warningCount:number}){}
  async templateUsage(w:string,templateId:string){return clone((this.templateUsages.get(templateId)??[]).filter(x=>x.workspaceId===w))}
  async audit(input:{workspaceId:string;actorId:string;action:string;objectType:string;objectId?:string;riskLevel:string;before?:unknown;after?:unknown}){this.audits.push(clone(input))}
  async createMessage(input:{workspaceId:string;sourceType:string;sourceId:string;flowRunId?:string;nodeId?:string;profileId:string;emailVersionId?:string;emailTestSnapshotId?:string;idempotencyKey:string;scheduledFor:Date}){const existing=[...this.messages.values()].find(m=>m.workspaceId===input.workspaceId&&m.idempotencyKey===input.idempotencyKey);if(existing)return clone(existing);const m:P2Message={id:randomUUID(),...input,emailVersionId:input.emailVersionId??input.emailTestSnapshotId??"",state:"created",firstOpenedAt:null,lastOpenedAt:null,openCount:0,createdAt:new Date()};this.messages.set(m.id,m);await this.addTrace({workspaceId:m.workspaceId,messageId:m.id,kind:"message.intent_created",detail:{sourceType:m.sourceType,sourceId:m.sourceId}});return clone(m)}
  async message(w:string,id:string){const m=this.messages.get(id);return m&&m.workspaceId===w?clone(m):null}
  async messageByIdempotency(w:string,key:string){const m=[...this.messages.values()].find(x=>x.workspaceId===w&&x.idempotencyKey===key);return clone(m??null)}
  async updateMessage(input:{workspaceId:string;messageId:string;state:string;policyDecision?:MessagePolicyDecision;renderedHash?:string;renderedAt?:Date;submittedAt?:Date;finalAt?:Date}){const m=this.messages.get(input.messageId);if(!m||m.workspaceId!==input.workspaceId)throw new Error("MESSAGE_NOT_FOUND");const next={...m,state:input.state,policyDecision:input.policyDecision??m.policyDecision,renderedAt:input.renderedAt??m.renderedAt,submittedAt:input.submittedAt??m.submittedAt,finalAt:input.finalAt??m.finalAt};this.messages.set(m.id,next);return clone(next)}
  async trace(w:string,id:string){const m=await this.message(w,id);if(!m)throw new Error("MESSAGE_NOT_FOUND");return (this.traces.get(id)??[]).map(x=>({kind:x.kind,occurredAt:new Date(x.occurredAt),detail:clone(x.detail)}))}
  async addTrace(i:{workspaceId:string;messageId:string;kind:string;detail:unknown}){const m=await this.message(i.workspaceId,i.messageId);if(!m)throw new Error("MESSAGE_NOT_FOUND");const list=this.traces.get(i.messageId)??[];list.push({kind:i.kind,occurredAt:new Date(),detail:clone(i.detail)});this.traces.set(i.messageId,list)}
  async activeSendPolicy(w:string){return clone(this.policies.get(w)??{version:1,frequencyWindowSeconds:86400,frequencyMax:3})}
  async saveSendPolicy(w:string,_actor:string,c:SendPolicyConfig){this.policies.set(w,clone(c))}
  async activeHolds(w:string){return [...this.holds.values()].filter(h=>h.workspaceId===w&&h.state==="active").map(clone)}
  async createHold(i:{workspaceId:string;scopeType:string;scopeId?:string;reason:string;actorId:string}){const h:P2Hold={id:randomUUID(),workspaceId:i.workspaceId,scopeType:i.scopeType,scopeId:i.scopeId,reason:i.reason,state:"active",createdAt:new Date()};this.holds.set(h.id,h);return clone(h)}
  async releaseHold(i:{workspaceId:string;holdId:string;reason:string}){const h=this.holds.get(i.holdId);if(!h||h.workspaceId!==i.workspaceId)throw new Error("HOLD_NOT_FOUND");h.state="released";h.releasedAt=new Date()}
  async frequencyCount(w:string,p:string,since:Date){return [...this.frequency.values()].filter(x=>x.workspaceId===w&&x.profileId===p&&x.reservedAt>=since&&!x.releasedAt).length}
  async reserveFrequency(i:{workspaceId:string;profileId:string;messageId:string;expiresAt:Date}){if([...this.frequency.values()].some(x=>x.workspaceId===i.workspaceId&&x.messageId===i.messageId))return true;this.frequency.set(i.messageId,{...i,reservedAt:new Date()});return true}
  async consumeFrequency(w:string,m:string){const x=this.frequency.get(m);if(x&&x.workspaceId===w)x.consumedAt=new Date()}
  async releaseFrequency(w:string,m:string){const x=this.frequency.get(m);if(x&&x.workspaceId===w)x.releasedAt=new Date()}
  async submittedToday(w:string,since:Date){return [...this.messages.values()].filter(m=>m.workspaceId===w&&m.submittedAt&&m.submittedAt>=since).length}
  async feedbackSafetyCurrent(w:string,staleAfterSeconds:number,now:Date){const submitted=[...this.messages.values()].some(m=>m.workspaceId===w&&m.sourceType!=="test"&&m.submittedAt);if(!submitted)return true;const latest=this.deliveryFacts.filter(x=>x.workspaceId===w).map(x=>x.occurredAt.getTime()).sort((a,b)=>b-a)[0];return latest!==undefined&&latest>=now.getTime()-staleAfterSeconds*1000}
  async saveArtifact(i:{workspaceId:string;messageId:string;objectKey:string;contentHash:string;mimeHash:string;byteSize:number;compilerVersion:string;sanitizerVersion:string}){this.artifacts.set(i.messageId,{objectKey:i.objectKey,mimeHash:i.mimeHash,contentHash:i.contentHash})}
  async artifact(w:string,m:string){const msg=await this.message(w,m);if(!msg)return null;return clone(this.artifacts.get(m)??null)}
  async createAttempt(i:{workspaceId:string;messageId:string;attemptNumber:number;provider:string;requestFingerprint:string}){const existing=[...this.attempts.values()].find(a=>a.messageId===i.messageId&&a.attemptNumber===i.attemptNumber);if(existing)return clone(existing);const a:P2DeliveryAttempt={id:randomUUID(),...i,state:"created"};this.attempts.set(a.id,a);return clone(a)}
  async updateAttempt(i:{workspaceId:string;attemptId:string;state:string;providerMessageId?:string;errorCode?:string}){const a=this.attempts.get(i.attemptId);if(!a||a.workspaceId!==i.workspaceId)throw new Error("ATTEMPT_NOT_FOUND");a.state=i.state;if(i.providerMessageId)a.providerMessageId=i.providerMessageId}
  async attemptByProviderMessageId(id:string){const a=[...this.attempts.values()].find(x=>x.providerMessageId===id);return clone(a??null)}
  async recordDeliveryEvent(i:{workspaceId:string;messageId:string;provider:string;providerEventId:string;eventType:string;occurredAt:Date;payload:unknown}){const k=`${i.provider}:${i.providerEventId}`;if(this.deliveryEvents.has(k))return false;this.deliveryEvents.add(k);this.deliveryFacts.push({workspaceId:i.workspaceId,messageId:i.messageId,eventType:i.eventType,occurredAt:i.occurredAt});return true}
  async recordMessageOpen(i:{workspaceId:string;messageId:string;occurredAt:Date}){const message=await this.message(i.workspaceId,i.messageId);if(!message)throw new Error("MESSAGE_NOT_FOUND");message.firstOpenedAt=!message.firstOpenedAt||message.firstOpenedAt>i.occurredAt?i.occurredAt:message.firstOpenedAt;message.lastOpenedAt=!message.lastOpenedAt||message.lastOpenedAt<i.occurredAt?i.occurredAt:message.lastOpenedAt;message.openCount+=1;this.messages.set(message.id,message)}
  async createProtectedSuppression(i:{workspaceId:string;profileId:string;reason:"hard_bounce"|"complaint";sourceReference:string}){this.setProtectedSuppression(i.workspaceId,i.profileId,true)}
  async createTrackingLink(i:{workspaceId:string;messageId:string;destination:string;destinationHash:string}){const x:P2TrackingLink={id:randomUUID(),workspaceId:i.workspaceId,messageId:i.messageId,destination:i.destination};this.tracking.set(x.id,x);return clone(x)}
  async trackingLink(w:string,id:string){const x=this.tracking.get(id);return x&&x.workspaceId===w?clone(x):null}
  async engagementFact(i:{workspaceId:string;messageId:string;kind:"click"|"open";classification:string;occurredAt:Date;metadata?:unknown}){this.engagement.push({...i})}
  async analyticsSummary(w:string,since:Date){const msgs=[...this.messages.values()].filter(m=>m.workspaceId===w&&m.createdAt>=since&&m.sourceType!=="test");const out:Record<string,number>={intents:msgs.length,submitted:0,delivered:0,bounced:0,complained:0,failed:0,held:0,skipped:0,cancelled:0,clicks:0,opens:0};for(const m of msgs){if(m.submittedAt)out.submitted!++;if(out[m.state]!==undefined)out[m.state]!++}for(const e of this.engagement.filter(e=>e.workspaceId===w&&e.occurredAt>=since))out[e.kind==="click"?"clicks":"opens"]!++;return out}
  async analyticsPeriod(w:string,from:Date,to:Date){const submitted=[...this.messages.values()].filter(m=>m.workspaceId===w&&m.sourceType!=="test"&&m.submittedAt&&m.submittedAt>=from&&m.submittedAt<=to).length;const events=this.deliveryFacts.filter(x=>x.workspaceId===w&&x.occurredAt>=from&&x.occurredAt<=to);const count=(...types:string[])=>events.filter(x=>types.includes(x.eventType)).length;const unique=(kind:"click"|"open")=>new Set(this.engagement.filter(x=>x.workspaceId===w&&x.kind===kind&&x.occurredAt>=from&&x.occurredAt<=to).map(x=>x.messageId)).size;return {submitted,delivered:count("delivery","delivered"),bounces:count("bounce","soft_bounce","hard_bounce"),complaints:count("complaint"),uniqueClicks:unique("click"),uniqueOpens:unique("open"),from,to,freshness:new Date()}}
}
