import { randomUUID } from 'node:crypto';
import type { Phase3RuntimeRepository,RuntimeFlow3,RuntimeFlowRun3,RuntimeFlowVersion3,RuntimeNodeExecution3,RuntimeProfileContext3,RuntimeScheduledAction3,RuntimeTrace3,FlowRunState3,DeadLetter3 } from '../../../application/src/ports/phase3-runtime-repository.js';

export class InMemoryPhase3RuntimeRepository implements Phase3RuntimeRepository{
  flows=new Map<string,RuntimeFlow3>();versions=new Map<string,RuntimeFlowVersion3>();profiles=new Map<string,RuntimeProfileContext3>();runs=new Map<string,RuntimeFlowRun3>();executions=new Map<string,RuntimeNodeExecution3>();actions=new Map<string,RuntimeScheduledAction3>();traces=new Map<string,RuntimeTrace3[]>();deadLetters=new Map<string,DeadLetter3>();
  async transaction<T>(fn:(tx:Phase3RuntimeRepository)=>Promise<T>):Promise<T>{return fn(this)}
  seedFlow(flow:RuntimeFlow3,version:RuntimeFlowVersion3){this.flows.set(flow.id,structuredClone(flow));this.versions.set(version.id,structuredClone(version))}
  seedProfile(p:RuntimeProfileContext3){this.profiles.set(p.id,structuredClone(p))}
  async flow(w:string,id:string){const x=this.flows.get(id);return x?.workspaceId===w?structuredClone(x):null}
  async flowVersion(w:string,id:string){const x=this.versions.get(id);return x?.workspaceId===w?structuredClone(x):null}
  async profileContext(w:string,id:string){const x=this.profiles.get(id);return x?.workspaceId===w?structuredClone(x):null}
  async latestRunForProfile(w:string,f:string,p:string){return [...this.runs.values()].filter(x=>x.workspaceId===w&&x.flowId===f&&x.profileId===p).sort((a,b)=>b.enteredAt.getTime()-a.enteredAt.getTime())[0]??null}
  async createRunIfAbsent(i:{workspaceId:string;flowId:string;flowVersionId:string;profileId:string;triggerEventId?:string;deduplicationKey:string;firstNodeId:string;enteredAt:Date}){const old=[...this.runs.values()].find(x=>x.workspaceId===i.workspaceId&&x.flowVersionId===i.flowVersionId&&x.deduplicationKey===i.deduplicationKey);if(old)return {run:structuredClone(old),duplicate:true};const r:RuntimeFlowRun3={id:randomUUID(),workspaceId:i.workspaceId,flowId:i.flowId,flowVersionId:i.flowVersionId,profileId:i.profileId,triggerEventId:i.triggerEventId??null,deduplicationKey:i.deduplicationKey,state:'active',currentNodeId:i.firstNodeId,enteredAt:new Date(i.enteredAt),nextActionAt:new Date(i.enteredAt),rowVersion:1};this.runs.set(r.id,r);return {run:structuredClone(r),duplicate:false}}
  async run(w:string,id:string){const x=this.runs.get(id);return x?.workspaceId===w?structuredClone(x):null}
  async listRuns(w:string,f:string){return [...this.runs.values()].filter(x=>x.workspaceId===w&&x.flowId===f).map(x=>structuredClone(x))}
  async updateRun(i:{workspaceId:string;runId:string;state?:FlowRunState3;currentNodeId?:string;nextActionAt?:Date|null;endedAt?:Date|null;exitReason?:string|null}){const x=await this.run(i.workspaceId,i.runId);if(!x)throw new Error('FLOW_RUN_NOT_FOUND');const y={...x,state:i.state??x.state,currentNodeId:i.currentNodeId??x.currentNodeId,nextActionAt:i.nextActionAt===undefined?x.nextActionAt:i.nextActionAt,endedAt:i.endedAt===undefined?x.endedAt:i.endedAt,exitReason:i.exitReason===undefined?x.exitReason:i.exitReason,rowVersion:x.rowVersion+1};this.runs.set(x.id,y);return structuredClone(y)}
  async beginNodeExecution(i:{workspaceId:string;flowRunId:string;nodeId:string;scheduledAt?:Date;inputSnapshot?:unknown}){const prior=[...this.executions.values()].filter(x=>x.flowRunId===i.flowRunId&&x.nodeId===i.nodeId).sort((a,b)=>b.attemptSequence-a.attemptSequence)[0];if(prior&&prior.state!=='failed')return {execution:structuredClone(prior),duplicate:true};const x:RuntimeNodeExecution3={id:randomUUID(),workspaceId:i.workspaceId,flowRunId:i.flowRunId,nodeId:i.nodeId,attemptSequence:(prior?.attemptSequence??0)+1,state:'started',scheduledAt:i.scheduledAt??null,startedAt:new Date(),inputSnapshot:i.inputSnapshot};this.executions.set(x.id,x);return {execution:structuredClone(x),duplicate:false}}
  async completeNodeExecution(i:{workspaceId:string;executionId:string;evaluationResult?:unknown}){const x=this.executions.get(i.executionId);if(!x||x.workspaceId!==i.workspaceId)throw new Error('NODE_EXECUTION_NOT_FOUND');this.executions.set(x.id,{...x,state:'completed',completedAt:new Date(),evaluationResult:i.evaluationResult})}
  async failNodeExecution(i:{workspaceId:string;executionId:string;error:unknown}){const x=this.executions.get(i.executionId);if(!x||x.workspaceId!==i.workspaceId)throw new Error('NODE_EXECUTION_NOT_FOUND');this.executions.set(x.id,{...x,state:'failed',completedAt:new Date(),error:i.error})}
  async scheduleAction(i:{workspaceId:string;flowRunId:string;nodeId:string;deduplicationKey:string;dueAt:Date}){const old=[...this.actions.values()].find(x=>x.deduplicationKey===i.deduplicationKey);if(old)return structuredClone(old);const x:RuntimeScheduledAction3={id:randomUUID(),workspaceId:i.workspaceId,flowRunId:i.flowRunId,nodeId:i.nodeId,deduplicationKey:i.deduplicationKey,dueAt:new Date(i.dueAt),state:'pending',attemptCount:0,createdAt:new Date()};this.actions.set(x.id,x);return structuredClone(x)}
  async claimDueActions(i:{now:Date;leaseOwner:string;leaseMs:number;limit:number}){const due=[...this.actions.values()].filter(x=>x.state==='pending'&&x.dueAt<=i.now).sort((a,b)=>a.dueAt.getTime()-b.dueAt.getTime()).slice(0,i.limit);for(const x of due)this.actions.set(x.id,{...x,state:'leased',leaseOwner:i.leaseOwner,leaseExpiresAt:new Date(i.now.getTime()+i.leaseMs),attemptCount:x.attemptCount+1});return due.map(x=>structuredClone(this.actions.get(x.id)!))}
  async scheduledAction(w:string,id:string){const x=this.actions.get(id);return x?.workspaceId===w?structuredClone(x):null}
  async completeAction(w:string,id:string){const x=this.actions.get(id);if(!x||x.workspaceId!==w)return;this.actions.set(id,{...x,state:'completed',completedAt:new Date(),leaseOwner:null,leaseExpiresAt:null})}
  async releaseExpiredLeases(now:Date){let n=0;for(const [id,x] of this.actions){if(x.state==='leased'&&x.leaseExpiresAt&&x.leaseExpiresAt<=now){this.actions.set(id,{...x,state:'pending',leaseOwner:null,leaseExpiresAt:null});n++}}return n}
  async addTrace(w:string,r:string,kind:string,detail:Record<string,unknown>,occurredAt=new Date()){const run=await this.run(w,r);if(!run)throw new Error('FLOW_RUN_NOT_FOUND');const a=this.traces.get(r)??[];a.push({kind,detail:structuredClone(detail),occurredAt:new Date(occurredAt)});this.traces.set(r,a)}
  async trace(w:string,r:string){if(!await this.run(w,r))throw new Error('FLOW_RUN_NOT_FOUND');return (this.traces.get(r)??[]).map(x=>structuredClone(x)).sort((a,b)=>a.occurredAt.getTime()-b.occurredAt.getTime())}
  async setFlowExecutionState(i:{workspaceId:string;flowId:string;entryState:'open'|'blocked';executionState:'running'|'paused';pausedAt?:Date|null;status?:RuntimeFlow3['status']}){const x=await this.flow(i.workspaceId,i.flowId);if(!x)throw new Error('FLOW_NOT_FOUND');this.flows.set(x.id,{...x,entryState:i.entryState,executionState:i.executionState,pausedAt:i.pausedAt===undefined?x.pausedAt:i.pausedAt,status:i.status??x.status})}
  async holdPendingActions(w:string,f:string){const runIds=new Set((await this.listRuns(w,f)).filter(r=>['active','waiting','held'].includes(r.state)).map(r=>r.id));let n=0;for(const [id,x] of this.actions){if(x.workspaceId===w&&runIds.has(x.flowRunId)&&['pending','leased'].includes(x.state)){this.actions.set(id,{...x,state:'held',leaseOwner:null,leaseExpiresAt:null});n++}}for(const id of runIds){const r=this.runs.get(id)!;if(['active','waiting'].includes(r.state))this.runs.set(id,{...r,state:'held'})}return n}
  async resumeHeldActions(i:{workspaceId:string;flowId:string;now:Date;pausedAt?:Date|null;overduePolicy:'immediate'|'shift_by_pause_duration'}){const runIds=new Set((await this.listRuns(i.workspaceId,i.flowId)).filter(r=>r.state==='held').map(r=>r.id));const shift=i.pausedAt?Math.max(0,i.now.getTime()-i.pausedAt.getTime()):0;let n=0;for(const [id,x] of this.actions){if(x.workspaceId===i.workspaceId&&runIds.has(x.flowRunId)&&x.state==='held'){const due=i.overduePolicy==='shift_by_pause_duration'?new Date(x.dueAt.getTime()+shift):(x.dueAt<i.now?new Date(i.now):x.dueAt);this.actions.set(id,{...x,state:'pending',dueAt:due});n++}}for(const id of runIds){const r=this.runs.get(id)!;this.runs.set(id,{...r,state:'waiting'})}return n}
  async cancelPendingRunsAndActions(w:string,f:string,now:Date){const runs=(await this.listRuns(w,f)).filter(r=>['active','waiting','held','failed'].includes(r.state));const ids=new Set(runs.map(r=>r.id));let actions=0;for(const [id,x] of this.actions){if(x.workspaceId===w&&ids.has(x.flowRunId)&&!['completed','cancelled'].includes(x.state)){this.actions.set(id,{...x,state:'cancelled',completedAt:now,leaseOwner:null,leaseExpiresAt:null});actions++}}for(const r of runs)this.runs.set(r.id,{...r,state:'cancelled',endedAt:now,exitReason:'OPERATOR_CANCEL'});return {runs:runs.length,actions,runIds:[...ids]}}
  async exitRunAndCancelPending(i:{workspaceId:string;runId:string;actionId:string;now:Date;reason:string;detail:Record<string,unknown>}){const run=await this.run(i.workspaceId,i.runId);if(!run)throw new Error('FLOW_RUN_NOT_FOUND');let cancelledActions=0;for(const [id,action] of this.actions){if(action.workspaceId===i.workspaceId&&action.flowRunId===i.runId&&id!==i.actionId&&!['completed','cancelled'].includes(action.state)){this.actions.set(id,{...action,state:'cancelled',completedAt:i.now,leaseOwner:null,leaseExpiresAt:null});cancelledActions++}}await this.completeAction(i.workspaceId,i.actionId);await this.updateRun({workspaceId:i.workspaceId,runId:i.runId,state:'exited',endedAt:i.now,exitReason:i.reason,nextActionAt:null});await this.addTrace(i.workspaceId,i.runId,'flow.exited',i.detail,i.now);return {cancelledActions,cancelledMessages:0}}
  async runCounts(w:string,f:string){const out:Record<string,number>={total:0,active:0,waiting:0,held:0,completed:0,exited:0,cancelled:0,failed:0};for(const r of await this.listRuns(w,f)){out.total!++;out[r.state]=(out[r.state]??0)+1}return out}
  async recordDeadLetter(i:{workspaceId:string;resourceType:string;resourceId:string;jobType:string;businessKey:string;error:unknown}){const old=[...this.deadLetters.values()].find(x=>x.workspaceId===i.workspaceId&&x.businessKey===i.businessKey&&x.state==='open');if(old)return structuredClone(old);const x:DeadLetter3={id:randomUUID(),workspaceId:i.workspaceId,resourceType:i.resourceType,resourceId:i.resourceId,jobType:i.jobType,businessKey:i.businessKey,error:structuredClone(i.error),state:'open',createdAt:new Date()};this.deadLetters.set(x.id,x);return structuredClone(x)}
  async listDeadLetters(w:string,flowId?:string){let items=[...this.deadLetters.values()].filter(x=>x.workspaceId===w);if(flowId){const runIds=new Set((await this.listRuns(w,flowId)).map(r=>r.id));items=items.filter(x=>{const a=this.actions.get(x.resourceId);return a?runIds.has(a.flowRunId):false})}return items.map(x=>structuredClone(x))}
  async replayDeadLetter(w:string,id:string,at:Date){const d=this.deadLetters.get(id);if(!d||d.workspaceId!==w||d.state!=='open')throw new Error('DEAD_LETTER_NOT_REPLAYABLE');if(d.resourceType!=='scheduled_action')throw new Error('DEAD_LETTER_UNSUPPORTED');const a=this.actions.get(d.resourceId);if(!a||a.workspaceId!==w)throw new Error('SCHEDULED_ACTION_NOT_FOUND');if(a.state==='completed'||a.state==='cancelled')throw new Error('DEAD_LETTER_ALREADY_FINAL');const next={...a,state:'pending' as const,leaseOwner:null,leaseExpiresAt:null,dueAt:at};this.actions.set(a.id,next);this.deadLetters.set(id,{...d,state:'replayed',replayedAt:at});return structuredClone(next)}

}
