import { randomUUID, createHash, randomBytes } from "node:crypto";
import { assertPermission, type Permission, type Role } from "../../../domain/src/phase1/permissions.js";
import { normalizeEmail, neutralizeSpreadsheetFormula, type PropertyType, validatePropertyValue } from "../../../domain/src/phase1/profile.js";
import { explainEligibility, isProtectedSuppression, type ConsentStatus, type SuppressionReason } from "../../../domain/src/phase1/consent.js";
import { previewCsv, parseCsvLine } from "../../../domain/src/phase1/csv.js";
import { workspaceReadiness, type WorkspaceReadinessInput } from "../../../domain/src/phase1/readiness.js";
import { paginateById } from "../../../domain/src/phase1/pagination.js";
import { normalizeDomain } from "../../../domain/src/phase1/dns.js";
import { newInvitationToken, hashInvitationToken } from "../../../domain/src/phase1/invitations.js";
import { validateImportPolicy, type ImportMapping, type ImportPolicy } from "../../../domain/src/phase1/import-policy.js";

export interface Workspace { id:string; name:string; legalName:string; businessAddress:string; timezone:string; locale:string; status:"setup"|"active"|"paused"; rowVersion:number; createdAt:string; updatedAt:string; }
export interface Member { id:string; workspaceId:string; userId:string; email:string; role:Role; status:"active"|"invited"|"disabled"; createdAt:string; updatedAt:string; }
export interface Invitation { id:string; workspaceId:string; email:string; role:Exclude<Role,"owner">; tokenHash:string; invitedBy:string; expiresAt:string; acceptedAt?:string; revokedAt?:string; }
export interface Profile { id:string; workspaceId:string; normalizedEmail:string; originalEmail:string; firstName?:string; lastName?:string; locale?:string; timezone?:string; countryCode?:string; region?:string; city?:string; source:string; sourceDetails?:Record<string,unknown>; properties:Record<string,unknown>; createdAt:string; updatedAt:string; rowVersion:number; deletedAt?:string; }
export interface PropertyDef { id:string; workspaceId:string; key:string; displayName:string; dataType:PropertyType; status:"active"|"archived"; }
export interface Consent { id:string; workspaceId:string; profileId:string; status:ConsentStatus; source:string; occurredAt:string; recordedAt:string; evidenceNote?:string; }
export interface SubscriptionProjection { workspaceId:string; profileId:string; currentStatus:ConsentStatus; effectiveAt:string; sourceConsentRecordId:string; revision:number; }
export interface Suppression { id:string; workspaceId:string; profileId:string; reason:SuppressionReason; source:string; protected:boolean; createdAt:string; revokedAt?:string|null; expiresAt?:string|null; }
export interface AudienceList { id:string; workspaceId:string; name:string; description?:string; status:"active"|"archived"; archivedAt?:string; createdAt:string; }
export interface Membership { workspaceId:string; listId:string; profileId:string; state:"active"|"left"; source:string; sourceId?:string; joinedAt:string; leftAt?:string; }
export interface Audit { id:string; workspaceId:string; actorId:string; action:string; objectType:string; objectId:string; occurredAt:string; detail?:unknown; riskLevel:"low"|"medium"|"high"; }
export interface SenderDomain { id:string; workspaceId:string; domain:string; status:"pending"|"verified"|"warning"|"failed"; expected:Record<string,string>; observed:Record<string,string>; createdAt:string; updatedAt:string; lastCheckedAt?:string; }
export interface SenderIdentity { id:string; workspaceId:string; domainId:string; fromName:string; fromEmail:string; replyTo:string; purpose:"marketing"; status:"active"; }
export interface ImportRowResult { rowNumber:number; status:"valid"|"invalid"|"created"|"updated"|"skipped"|"rolled_back"; profileId?:string; errors:string[]; }
export interface ImportJob { id:string; workspaceId:string; hash:string; state:"uploaded"|"mapping"|"validated"|"processing"|"completed"|"completed_with_errors"|"rolled_back"|"failed"; fileName:string; csv:string; mapping?:ImportMapping; policy?:ImportPolicy; preview?:ReturnType<typeof previewCsv>; rows:ImportRowResult[]; result?:Record<string,unknown>; createdAt:string; completedAt?:string; }
export interface ImportChange { id:string; workspaceId:string; importJobId:string; profileId:string; changeType:"profile_created"|"profile_updated"|"membership_created"|"consent_appended"; fieldKey?:string; before?:unknown; after?:unknown; revision?:number; }
export interface ExportJob { id:string; workspaceId:string; state:"queued"|"processing"|"completed"|"failed"; expiresAt:string; csv?:string; token:string; fields:string[]; profileIds:string[]; createdAt:string; completedAt?:string; }
export interface TimelineItem { id:string; kind:string; occurredAt:string; detail:unknown; }

export class Phase1Platform {
  workspaces=new Map<string,Workspace>(); members=new Map<string,Member>(); invitations=new Map<string,Invitation>();
  profiles=new Map<string,Profile>(); propertyDefs=new Map<string,PropertyDef>(); consents:Consent[]=[]; subscriptionStates=new Map<string,SubscriptionProjection>(); suppressions:Suppression[]=[];
  lists=new Map<string,AudienceList>(); memberships:Membership[]=[]; audits:Audit[]=[]; domains=new Map<string,SenderDomain>(); identities=new Map<string,SenderIdentity>();
  imports=new Map<string,ImportJob>(); importChanges:ImportChange[]=[]; exports=new Map<string,ExportJob>();

  createWorkspace(actor:{userId:string;email:string},input:Omit<Workspace,"id"|"status"|"rowVersion"|"createdAt"|"updatedAt">):Workspace{
    const now=new Date().toISOString(); const workspace:Workspace={id:randomUUID(),status:"setup",rowVersion:1,createdAt:now,updatedAt:now,...input}; this.workspaces.set(workspace.id,workspace);
    const member:Member={id:randomUUID(),workspaceId:workspace.id,userId:actor.userId,email:normalizeEmail(actor.email),role:"owner",status:"active",createdAt:now,updatedAt:now};this.members.set(member.id,member);this.audit(workspace.id,actor.userId,"workspace.create","workspace",workspace.id,undefined,"high");return workspace;
  }
  memberFor(workspaceId:string,userId:string):Member{const m=[...this.members.values()].find(x=>x.workspaceId===workspaceId&&x.userId===userId&&x.status==="active");if(!m)throw new Error("WORKSPACE_ACCESS_DENIED");return m}
  authorize(workspaceId:string,userId:string,permission:Permission):Member{const m=this.memberFor(workspaceId,userId);assertPermission(m.role,permission);return m}
  listWorkspaces(userId:string):Workspace[]{const ids=new Set([...this.members.values()].filter(m=>m.userId===userId&&m.status==="active").map(m=>m.workspaceId));return [...this.workspaces.values()].filter(w=>ids.has(w.id))}
  getWorkspace(workspaceId:string,actorId:string):Workspace{this.authorize(workspaceId,actorId,"workspace.read");const w=this.workspaces.get(workspaceId);if(!w)throw new Error("NOT_FOUND");return w}
  updateWorkspace(workspaceId:string,actorId:string,patch:Partial<Pick<Workspace,"name"|"legalName"|"businessAddress"|"timezone"|"locale">>&{expectedRowVersion?:number}):Workspace{this.authorize(workspaceId,actorId,"workspace.manage");const w=this.getWorkspace(workspaceId,actorId);if(patch.expectedRowVersion!==undefined&&patch.expectedRowVersion!==w.rowVersion)throw new Error("CONCURRENCY_CONFLICT");const before={...w};for(const k of ["name","legalName","businessAddress","timezone","locale"] as const)if(patch[k]!==undefined)(w as any)[k]=patch[k];w.rowVersion++;w.updatedAt=new Date().toISOString();this.audit(workspaceId,actorId,"workspace.update","workspace",w.id,{before,after:w},"medium");return w}
  listMembers(workspaceId:string,actorId:string):Member[]{this.authorize(workspaceId,actorId,"workspace.read");return [...this.members.values()].filter(m=>m.workspaceId===workspaceId)}
  invite(workspaceId:string,actorId:string,email:string,role:Exclude<Role,"owner">,ttlHours=72):Member&{invitationId:string;token:string;expiresAt:string}{this.authorize(workspaceId,actorId,"members.manage");const normalized=normalizeEmail(email);const now=new Date().toISOString();const pair=newInvitationToken();const invitation:Invitation={id:randomUUID(),workspaceId,email:normalized,role,tokenHash:pair.hash,invitedBy:actorId,expiresAt:new Date(Date.now()+ttlHours*3600_000).toISOString()};this.invitations.set(invitation.id,invitation);const member:Member={id:randomUUID(),workspaceId,userId:`invited:${invitation.id}`,email:normalized,role,status:"invited",createdAt:now,updatedAt:now};this.members.set(member.id,member);this.audit(workspaceId,actorId,"member.invite","workspace_member",member.id,{role,email:normalized},"medium");return {...member,invitationId:invitation.id,token:pair.token,expiresAt:invitation.expiresAt}}
  acceptInvitation(token:string,userId:string,email:string):Member{const hash=hashInvitationToken(token);const inv=[...this.invitations.values()].find(i=>i.tokenHash===hash&&!i.acceptedAt&&!i.revokedAt);if(!inv||Date.parse(inv.expiresAt)<=Date.now())throw new Error("INVITATION_INVALID");if(normalizeEmail(email)!==inv.email)throw new Error("INVITATION_EMAIL_MISMATCH");const m=[...this.members.values()].find(x=>x.workspaceId===inv.workspaceId&&x.status==="invited"&&x.email===inv.email);if(!m)throw new Error("INVITATION_INVALID");m.userId=userId;m.status="active";m.updatedAt=new Date().toISOString();inv.acceptedAt=m.updatedAt;this.audit(inv.workspaceId,userId,"member.invitation.accept","workspace_member",m.id,undefined,"medium");return m}
  updateMemberRole(workspaceId:string,actorId:string,memberId:string,role:Role):Member{this.authorize(workspaceId,actorId,"members.manage");const m=this.members.get(memberId);if(!m||m.workspaceId!==workspaceId)throw new Error("NOT_FOUND");if(m.role==="owner"&&role!=="owner"&&this.listMembers(workspaceId,actorId).filter(x=>x.role==="owner"&&x.status==="active").length<=1)throw new Error("LAST_OWNER_PROTECTED");m.role=role;m.updatedAt=new Date().toISOString();this.audit(workspaceId,actorId,"member.role.update","workspace_member",m.id,{role},"high");return m}

  defineProperty(workspaceId:string,actorId:string,key:string,displayName:string,dataType:PropertyType):PropertyDef{this.authorize(workspaceId,actorId,"profiles.write");const normalizedKey=key.trim().toLowerCase().replace(/[^a-z0-9_]+/g,"_");const existing=this.propertyDefs.get(`${workspaceId}:${normalizedKey}`);if(existing&&existing.dataType!==dataType)throw new Error("PROPERTY_DEFINITION_CONFLICT");if(existing)return existing;const def={id:randomUUID(),workspaceId,key:normalizedKey,displayName,dataType,status:"active" as const};this.propertyDefs.set(`${workspaceId}:${normalizedKey}`,def);this.audit(workspaceId,actorId,"property.define","profile_property_definition",def.id,{key:normalizedKey,dataType},"low");return def}
  upsertProfile(workspaceId:string,actorId:string,input:{email:string;firstName?:string;lastName?:string;locale?:string;timezone?:string;countryCode?:string;region?:string;city?:string;source:string;sourceDetails?:Record<string,unknown>;properties?:Record<string,unknown>;expectedRowVersion?:number}):Profile{this.authorize(workspaceId,actorId,"profiles.write");const normalizedEmail=normalizeEmail(input.email);let p=[...this.profiles.values()].find(x=>x.workspaceId===workspaceId&&x.normalizedEmail===normalizedEmail&&!x.deletedAt);const now=new Date().toISOString();if(p){if(input.expectedRowVersion!==undefined&&input.expectedRowVersion!==p.rowVersion)throw new Error("CONCURRENCY_CONFLICT");const before={...p,properties:{...p.properties}};for(const k of ["firstName","lastName","locale","timezone","countryCode","region","city"] as const)if(input[k]!==undefined)(p as any)[k]=input[k];if(input.properties)this.applyProperties(workspaceId,p,input.properties);p.updatedAt=now;p.rowVersion++;this.audit(workspaceId,actorId,"profile.update","profile",p.id,{before,after:p},"low");return p}p={id:randomUUID(),workspaceId,normalizedEmail,originalEmail:input.email,firstName:input.firstName,lastName:input.lastName,locale:input.locale,timezone:input.timezone,countryCode:input.countryCode,region:input.region,city:input.city,source:input.source,sourceDetails:input.sourceDetails,properties:{},createdAt:now,updatedAt:now,rowVersion:1};if(input.properties)this.applyProperties(workspaceId,p,input.properties);this.profiles.set(p.id,p);this.audit(workspaceId,actorId,"profile.create","profile",p.id,undefined,"low");return p}
  private applyProperties(workspaceId:string,p:Profile,props:Record<string,unknown>):void{for(const [key,value] of Object.entries(props)){const d=this.propertyDefs.get(`${workspaceId}:${key}`);if(!d)throw new Error(`UNKNOWN_PROPERTY:${key}`);if(!validatePropertyValue(d.dataType,value))throw new Error(`PROPERTY_TYPE_CONFLICT:${key}`);p.properties[key]=value}}
  getProfile(workspaceId:string,actorId:string,profileId:string):Profile{this.authorize(workspaceId,actorId,"profiles.read");const p=this.profiles.get(profileId);if(!p||p.workspaceId!==workspaceId||p.deletedAt)throw new Error("NOT_FOUND");return p}
  listProfiles(workspaceId:string,actorId:string,query=""):Profile[]{this.authorize(workspaceId,actorId,"profiles.read");const q=query.toLowerCase();return [...this.profiles.values()].filter(x=>x.workspaceId===workspaceId&&!x.deletedAt&&(!q||x.normalizedEmail.toLowerCase().includes(q)||x.firstName?.toLowerCase().includes(q)||x.lastName?.toLowerCase().includes(q)))}
  pageProfiles(workspaceId:string,actorId:string,input:{q?:string;limit?:number;cursor?:string|null}={}){return paginateById(this.listProfiles(workspaceId,actorId,input.q??""),input.limit,input.cursor)}
  profileTimeline(workspaceId:string,actorId:string,profileId:string):TimelineItem[]{this.getProfile(workspaceId,actorId,profileId);const items:TimelineItem[]=[];for(const a of this.audits.filter(a=>a.workspaceId===workspaceId&&(a.objectId===profileId||(typeof a.detail==="object"&&a.detail&&JSON.stringify(a.detail).includes(profileId)))))items.push({id:a.id,kind:a.action,occurredAt:a.occurredAt,detail:a.detail??{}});for(const c of this.consents.filter(c=>c.workspaceId===workspaceId&&c.profileId===profileId))items.push({id:c.id,kind:"consent",occurredAt:c.occurredAt,detail:c});for(const s of this.suppressions.filter(s=>s.workspaceId===workspaceId&&s.profileId===profileId))items.push({id:s.id,kind:"suppression",occurredAt:s.createdAt,detail:s});return items.sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt))}
  mergeProfiles(workspaceId:string,actorId:string,canonicalId:string,sourceId:string):Profile{this.authorize(workspaceId,actorId,"profiles.write");const canonical=this.getProfile(workspaceId,actorId,canonicalId),source=this.getProfile(workspaceId,actorId,sourceId);if(canonical.id===source.id)throw new Error("MERGE_INVALID");for(const[k,v]of Object.entries(source.properties))if(canonical.properties[k]===undefined)canonical.properties[k]=v;if(!canonical.firstName&&source.firstName)canonical.firstName=source.firstName;if(!canonical.lastName&&source.lastName)canonical.lastName=source.lastName;for(const c of this.consents)if(c.workspaceId===workspaceId&&c.profileId===source.id)c.profileId=canonical.id;for(const s of this.suppressions)if(s.workspaceId===workspaceId&&s.profileId===source.id)s.profileId=canonical.id;for(const m of this.memberships)if(m.workspaceId===workspaceId&&m.profileId===source.id){if(!this.memberships.some(x=>x!==m&&x.workspaceId===workspaceId&&x.listId===m.listId&&x.profileId===canonical.id&&x.state==="active"))m.profileId=canonical.id;else{m.state="left";m.leftAt=new Date().toISOString()}}source.deletedAt=new Date().toISOString();canonical.rowVersion++;canonical.updatedAt=new Date().toISOString();this.rebuildSubscription(workspaceId,canonical.id);this.audit(workspaceId,actorId,"profile.merge","profile",canonical.id,{sourceId},"high");return canonical}

  createList(workspaceId:string,actorId:string,name:string,description?:string):AudienceList{this.authorize(workspaceId,actorId,"audiences.write");const l={id:randomUUID(),workspaceId,name:name.trim(),description,status:"active" as const,createdAt:new Date().toISOString()};if(!l.name)throw new Error("LIST_NAME_REQUIRED");this.lists.set(l.id,l);this.audit(workspaceId,actorId,"list.create","list",l.id,undefined,"low");return l}
  listLists(workspaceId:string,actorId:string):AudienceList[]{this.authorize(workspaceId,actorId,"audiences.read");return [...this.lists.values()].filter(l=>l.workspaceId===workspaceId)}
  getList(workspaceId:string,actorId:string,listId:string):AudienceList{this.authorize(workspaceId,actorId,"audiences.read");const l=this.lists.get(listId);if(!l||l.workspaceId!==workspaceId)throw new Error("NOT_FOUND");return l}
  addToList(workspaceId:string,actorId:string,listId:string,profileId:string,source="manual",sourceId?:string):Membership{this.authorize(workspaceId,actorId,"audiences.write");const l=this.getList(workspaceId,actorId,listId);const p=this.getProfile(workspaceId,actorId,profileId);if(l.status!=="active")throw new Error("LIST_ARCHIVED");let m=this.memberships.find(x=>x.workspaceId===workspaceId&&x.listId===listId&&x.profileId===profileId);if(m){m.state="active";m.leftAt=undefined;return m}m={workspaceId,listId,profileId:p.id,state:"active",source,sourceId,joinedAt:new Date().toISOString()};this.memberships.push(m);this.audit(workspaceId,actorId,"list.member.add","profile",profileId,{listId,source},"low");return m}
  removeFromList(workspaceId:string,actorId:string,listId:string,profileId:string):Membership{this.authorize(workspaceId,actorId,"audiences.write");const m=this.memberships.find(x=>x.workspaceId===workspaceId&&x.listId===listId&&x.profileId===profileId&&x.state==="active");if(!m)throw new Error("NOT_FOUND");m.state="left";m.leftAt=new Date().toISOString();this.audit(workspaceId,actorId,"list.member.remove","profile",profileId,{listId},"low");return m}
  archiveList(workspaceId:string,actorId:string,listId:string):AudienceList{this.authorize(workspaceId,actorId,"audiences.write");const l=this.getList(workspaceId,actorId,listId);l.status="archived";l.archivedAt=new Date().toISOString();this.audit(workspaceId,actorId,"list.archive","list",listId,undefined,"medium");return l}

  recordConsent(workspaceId:string,actorId:string,profileId:string,status:ConsentStatus,source:string,occurredAt=new Date().toISOString(),evidenceNote?:string):Consent{this.authorize(workspaceId,actorId,"consent.write");this.getProfile(workspaceId,actorId,profileId);if(status==="granted"&&!evidenceNote&&source.startsWith("import:"))throw new Error("CONSENT_EVIDENCE_REQUIRED");const rec={id:randomUUID(),workspaceId,profileId,status,source,occurredAt,recordedAt:new Date().toISOString(),evidenceNote};this.consents.push(rec);this.rebuildSubscription(workspaceId,profileId);this.audit(workspaceId,actorId,"consent.record","profile",profileId,{status,source},"high");return rec}
  private rebuildSubscription(workspaceId:string,profileId:string):void{const latest=this.consents.filter(c=>c.workspaceId===workspaceId&&c.profileId===profileId).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)||b.recordedAt.localeCompare(a.recordedAt))[0];const key=`${workspaceId}:${profileId}`;if(!latest){this.subscriptionStates.delete(key);return}const prev=this.subscriptionStates.get(key);this.subscriptionStates.set(key,{workspaceId,profileId,currentStatus:latest.status,effectiveAt:latest.occurredAt,sourceConsentRecordId:latest.id,revision:(prev?.revision??0)+1})}
  listConsent(workspaceId:string,actorId:string,profileId:string):Consent[]{this.authorize(workspaceId,actorId,"consent.read");this.getProfile(workspaceId,actorId,profileId);return this.consents.filter(c=>c.workspaceId===workspaceId&&c.profileId===profileId).sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt))}
  suppress(workspaceId:string,actorId:string,profileId:string,reason:SuppressionReason,source="manual",expiresAt?:string):Suppression{this.authorize(workspaceId,actorId,"suppressions.manage");this.getProfile(workspaceId,actorId,profileId);const existing=this.suppressions.find(x=>x.workspaceId===workspaceId&&x.profileId===profileId&&x.reason===reason&&!x.revokedAt&&(!x.expiresAt||Date.parse(x.expiresAt)>Date.now()));if(existing)return existing;const item={id:randomUUID(),workspaceId,profileId,reason,source,protected:isProtectedSuppression(reason),createdAt:new Date().toISOString(),expiresAt:expiresAt??null};this.suppressions.push(item);this.audit(workspaceId,actorId,"suppression.create","profile",profileId,{reason,source},"high");return item}
  revokeSuppression(workspaceId:string,actorId:string,suppressionId:string):Suppression{this.authorize(workspaceId,actorId,"suppressions.manage");const s=this.suppressions.find(x=>x.id===suppressionId&&x.workspaceId===workspaceId);if(!s)throw new Error("NOT_FOUND");if(s.protected)throw new Error("PROTECTED_SUPPRESSION");if(!s.revokedAt)s.revokedAt=new Date().toISOString();this.audit(workspaceId,actorId,"suppression.revoke","suppression",s.id,undefined,"high");return s}
  listSuppressions(workspaceId:string,actorId:string):Suppression[]{this.authorize(workspaceId,actorId,"consent.read");return this.suppressions.filter(s=>s.workspaceId===workspaceId)}
  eligibility(workspaceId:string,actorId:string,profileId:string){this.authorize(workspaceId,actorId,"profiles.read");this.getProfile(workspaceId,actorId,profileId);const projection=this.subscriptionStates.get(`${workspaceId}:${profileId}`);const active=this.suppressions.filter(x=>x.workspaceId===workspaceId&&x.profileId===profileId&&!x.revokedAt&&(!x.expiresAt||Date.parse(x.expiresAt)>Date.now()));return explainEligibility({consent:projection?.currentStatus??"unknown",suppressions:active,identifierValid:true})}

  createImport(workspaceId:string,actorId:string,input:{fileName:string;csv:string}):ImportJob{this.authorize(workspaceId,actorId,"profiles.write");if(Buffer.byteLength(input.csv)>50*1024*1024)throw new Error("IMPORT_FILE_TOO_LARGE");const hash=createHash("sha256").update(input.csv).digest("hex");const job:ImportJob={id:randomUUID(),workspaceId,hash,state:"uploaded",fileName:input.fileName,csv:input.csv,rows:[],createdAt:new Date().toISOString()};this.imports.set(job.id,job);this.audit(workspaceId,actorId,"import.upload","import_job",job.id,{fileName:input.fileName},"medium");return job}
  setImportMapping(workspaceId:string,actorId:string,importId:string,mapping:ImportMapping,policy:ImportPolicy):ImportJob{this.authorize(workspaceId,actorId,"profiles.write");const j=this.imports.get(importId);if(!j||j.workspaceId!==workspaceId)throw new Error("NOT_FOUND");validateImportPolicy(mapping,policy);j.mapping=mapping;j.policy=policy;j.state="mapping";return j}
  validateImport(workspaceId:string,actorId:string,importId:string):ImportJob{this.authorize(workspaceId,actorId,"profiles.write");const j=this.imports.get(importId);if(!j||j.workspaceId!==workspaceId)throw new Error("NOT_FOUND");if(!j.mapping||!j.policy)throw new Error("IMPORT_MAPPING_REQUIRED");j.preview=previewCsv(j.csv);j.rows=j.preview.rows.map(r=>({rowNumber:r.rowNumber,status:r.valid?"valid":"invalid",errors:r.errors}));j.state="validated";return j}
  commitStagedImport(workspaceId:string,actorId:string,importId:string):ImportJob{this.authorize(workspaceId,actorId,"profiles.write");const j=this.imports.get(importId);if(!j||j.workspaceId!==workspaceId)throw new Error("NOT_FOUND");if(j.state==="completed"||j.state==="completed_with_errors")return j;if(j.state!=="validated"||!j.mapping||!j.policy||!j.preview)throw new Error("IMPORT_NOT_VALIDATED");const lines=j.csv.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);const headers=parseCsvLine(lines[0]!).map(h=>h.trim());const byName=(name?:string)=>name?headers.findIndex(h=>h.toLowerCase()===name.toLowerCase()):-1;const emailIndex=byName(j.mapping.email),firstIndex=byName(j.mapping.firstName),lastIndex=byName(j.mapping.lastName);j.state="processing";let created=0,updated=0,skipped=0;for(const row of j.preview.rows){const result=j.rows.find(x=>x.rowNumber===row.rowNumber)!;if(!row.valid){skipped++;continue}const vals=parseCsvLine(lines[row.rowNumber-1]??"");const email=vals[emailIndex]??row.email!;const normalized=normalizeEmail(email);const prior=[...this.profiles.values()].find(x=>x.workspaceId===workspaceId&&x.normalizedEmail===normalized&&!x.deletedAt);if(prior&&!j.policy.upsert){result.status="skipped";skipped++;continue}const before=prior?{...prior,properties:{...prior.properties}}:undefined;const p=this.upsertProfile(workspaceId,actorId,{email,firstName:firstIndex>=0?(vals[firstIndex]||undefined):undefined,lastName:lastIndex>=0?(vals[lastIndex]||undefined):undefined,source:j.policy.source});if(prior){updated++;result.status="updated";this.importChanges.push({id:randomUUID(),workspaceId,importJobId:j.id,profileId:p.id,changeType:"profile_updated",before,after:{...p,properties:{...p.properties}},revision:p.rowVersion})}else{created++;result.status="created";this.importChanges.push({id:randomUUID(),workspaceId,importJobId:j.id,profileId:p.id,changeType:"profile_created",after:{...p},revision:p.rowVersion})}result.profileId=p.id;if(j.policy.destinationListId){const existing=this.memberships.find(m=>m.workspaceId===workspaceId&&m.listId===j.policy!.destinationListId&&m.profileId===p.id&&m.state==="active");this.addToList(workspaceId,actorId,j.policy.destinationListId,p.id,`import:${j.id}`,j.id);if(!existing)this.importChanges.push({id:randomUUID(),workspaceId,importJobId:j.id,profileId:p.id,changeType:"membership_created",after:{listId:j.policy.destinationListId}})}if(j.policy.consent){this.recordConsent(workspaceId,actorId,p.id,j.policy.consent.status,`import:${j.policy.consent.source}`,undefined,j.policy.consent.evidenceNote);this.importChanges.push({id:randomUUID(),workspaceId,importJobId:j.id,profileId:p.id,changeType:"consent_appended",after:{status:j.policy.consent.status}})}}j.state=skipped>0?"completed_with_errors":"completed";j.completedAt=new Date().toISOString();j.result={created,updated,skipped,invalid:j.preview.totals.invalid};this.audit(workspaceId,actorId,"import.commit","import_job",j.id,j.result,"high");return j}
  rollbackImport(workspaceId:string,actorId:string,importId:string):ImportJob{this.authorize(workspaceId,actorId,"profiles.write");const j=this.imports.get(importId);if(!j||j.workspaceId!==workspaceId)throw new Error("NOT_FOUND");if(!["completed","completed_with_errors"].includes(j.state))throw new Error("IMPORT_NOT_ROLLBACKABLE");const changes=this.importChanges.filter(c=>c.workspaceId===workspaceId&&c.importJobId===j.id).reverse();for(const c of changes){if(c.changeType==="membership_created"){const m=this.memberships.find(m=>m.workspaceId===workspaceId&&m.profileId===c.profileId&&m.sourceId===j.id&&m.state==="active");if(m){m.state="left";m.leftAt=new Date().toISOString()}}else if(c.changeType==="profile_created"){/* Profile identity is intentionally retained. Import rollback is compensating, not destructive. */}else if(c.changeType==="profile_updated"){const p=this.profiles.get(c.profileId);if(p&&c.revision===p.rowVersion&&c.before){const b=c.before as Profile;Object.assign(p,b)}}/* consent is intentionally never rolled back */}for(const r of j.rows)if(r.status==="created"||r.status==="updated")r.status="rolled_back";j.state="rolled_back";this.audit(workspaceId,actorId,"import.rollback","import_job",j.id,undefined,"high");return j}
  getImport(workspaceId:string,actorId:string,importId:string):ImportJob{this.authorize(workspaceId,actorId,"profiles.read");const j=this.imports.get(importId);if(!j||j.workspaceId!==workspaceId)throw new Error("NOT_FOUND");return j}
  listImports(workspaceId:string,actorId:string):ImportJob[]{this.authorize(workspaceId,actorId,"profiles.read");return [...this.imports.values()].filter(j=>j.workspaceId===workspaceId)}
  previewImport(workspaceId:string,actorId:string,csv:string){this.authorize(workspaceId,actorId,"profiles.write");return previewCsv(csv)}
  commitImport(workspaceId:string,actorId:string,csv:string,options:{source:string;listId?:string;consent?:{status:ConsentStatus;source:string;evidenceNote?:string}}):ImportJob{const hash=createHash("sha256").update(csv+JSON.stringify(options)).digest("hex");const prior=[...this.imports.values()].find(j=>j.workspaceId===workspaceId&&j.hash===hash&&(j.state==="completed"||j.state==="completed_with_errors"));if(prior)return prior;const j=this.createImport(workspaceId,actorId,{fileName:"inline.csv",csv});j.hash=hash;this.setImportMapping(workspaceId,actorId,j.id,{email:"email",firstName:"first_name",lastName:"last_name"},{source:options.source,upsert:true,blankPolicy:"ignore",destinationListId:options.listId,consent:options.consent});this.validateImport(workspaceId,actorId,j.id);return this.commitStagedImport(workspaceId,actorId,j.id)}

  createExport(workspaceId:string,actorId:string,ttlSeconds=300,fields=["email","first_name","last_name"],profileIds?:string[]):ExportJob{this.authorize(workspaceId,actorId,"profiles.export");const ids=profileIds??this.listProfiles(workspaceId,actorId).map(p=>p.id);const j:ExportJob={id:randomUUID(),workspaceId,state:"queued",expiresAt:new Date(Date.now()+ttlSeconds*1000).toISOString(),token:randomBytes(24).toString("base64url"),fields,profileIds:ids,createdAt:new Date().toISOString()};this.exports.set(j.id,j);this.audit(workspaceId,actorId,"export.create","export_job",j.id,{count:ids.length,fields},"high");return this.generateExport(workspaceId,j.id)}
  generateExport(workspaceId:string,jobId:string):ExportJob{const j=this.exports.get(jobId);if(!j||j.workspaceId!==workspaceId)throw new Error("EXPORT_NOT_FOUND");j.state="processing";const header=j.fields.join(",");const rows=j.profileIds.map(id=>this.profiles.get(id)).filter((p):p is Profile=>Boolean(p&&p.workspaceId===workspaceId&&!p.deletedAt)).map(p=>j.fields.map(f=>{const v=f==="email"?p.originalEmail:f==="first_name"?(p.firstName??""):f==="last_name"?(p.lastName??""):String(p.properties[f]??"");return JSON.stringify(neutralizeSpreadsheetFormula(v))}).join(","));j.csv=[header,...rows].join("\n");j.state="completed";j.completedAt=new Date().toISOString();return j}
  getExport(workspaceId:string,actorId:string,jobId:string):ExportJob{this.authorize(workspaceId,actorId,"profiles.export");const j=this.exports.get(jobId);if(!j||j.workspaceId!==workspaceId)throw new Error("EXPORT_NOT_FOUND");return j}
  downloadExport(workspaceId:string,jobId:string,token:string,now=new Date()):string{const j=this.exports.get(jobId);if(!j||j.workspaceId!==workspaceId||j.token!==token)throw new Error("EXPORT_NOT_FOUND");if(now.getTime()>=Date.parse(j.expiresAt))throw new Error("EXPORT_EXPIRED");if(j.state!=="completed"||j.csv===undefined)throw new Error("EXPORT_NOT_READY");return j.csv}

  createDomain(workspaceId:string,actorId:string,domain:string):SenderDomain{this.authorize(workspaceId,actorId,"domains.manage");const normalized=normalizeDomain(domain);const existing=[...this.domains.values()].find(d=>d.workspaceId===workspaceId&&d.domain===normalized);if(existing)return existing;if([...this.domains.values()].some(d=>d.workspaceId===workspaceId))throw new Error("WORKSPACE_SENDING_DOMAIN_EXISTS");const now=new Date().toISOString();const d={id:randomUUID(),workspaceId,domain:normalized,status:"pending" as const,expected:{},observed:{},createdAt:now,updatedAt:now};this.domains.set(d.id,d);this.audit(workspaceId,actorId,"domain.create","sender_domain",d.id,undefined,"high");return d}
  setDomainExpectedRecords(workspaceId:string,actorId:string,domainId:string,expected:Record<string,string>):SenderDomain{this.authorize(workspaceId,actorId,"domains.manage");const d=this.domains.get(domainId);if(!d||d.workspaceId!==workspaceId)throw new Error("NOT_FOUND");d.expected={...expected};d.updatedAt=new Date().toISOString();return d}
  markDomainVerified(workspaceId:string,actorId:string,domainId:string,observed:Record<string,string>):SenderDomain{this.authorize(workspaceId,actorId,"domains.manage");const d=this.domains.get(domainId);if(!d||d.workspaceId!==workspaceId)throw new Error("NOT_FOUND");d.status="verified";d.observed=observed;d.lastCheckedAt=new Date().toISOString();d.updatedAt=d.lastCheckedAt;this.audit(workspaceId,actorId,"domain.verify","sender_domain",d.id,{observed},"high");return d}
  listDomains(workspaceId:string,actorId:string):SenderDomain[]{this.authorize(workspaceId,actorId,"domains.read");return [...this.domains.values()].filter(d=>d.workspaceId===workspaceId)}
  createSenderIdentity(workspaceId:string,actorId:string,input:{domainId:string;fromName:string;fromEmail:string;replyTo:string}):SenderIdentity{this.authorize(workspaceId,actorId,"domains.manage");const d=this.domains.get(input.domainId);if(!d||d.workspaceId!==workspaceId||d.status!=="verified")throw new Error("DOMAIN_NOT_VERIFIED");const from=normalizeEmail(input.fromEmail);if(from.split("@")[1]!==d.domain)throw new Error("FROM_DOMAIN_MISMATCH");const reply=normalizeEmail(input.replyTo);const i={id:randomUUID(),workspaceId,...input,fromEmail:from,replyTo:reply,purpose:"marketing" as const,status:"active" as const};this.identities.set(i.id,i);this.audit(workspaceId,actorId,"sender_identity.create","sender_identity",i.id,undefined,"high");return i}
  listSenderIdentities(workspaceId:string,actorId:string):SenderIdentity[]{this.authorize(workspaceId,actorId,"domains.read");return [...this.identities.values()].filter(i=>i.workspaceId===workspaceId)}
  readiness(workspaceId:string,actorId:string,flags:Partial<Pick<WorkspaceReadinessInput,"feedbackReady"|"unsubscribeReady"|"profilesReady"|"emailReady"|"testSendReady"|"flowReady">>={}){this.authorize(workspaceId,actorId,"workspace.read");const w=this.workspaces.get(workspaceId);if(!w)throw new Error("NOT_FOUND");return workspaceReadiness({legalName:w.legalName,businessAddress:w.businessAddress,senderIdentityCount:this.listSenderIdentities(workspaceId,actorId).length,verifiedDomainCount:this.listDomains(workspaceId,actorId).filter(d=>d.status==="verified").length,feedbackReady:false,unsubscribeReady:false,profilesReady:false,emailReady:false,testSendReady:false,flowReady:false,...flags})}
  listAudit(workspaceId:string,actorId:string):Audit[]{this.authorize(workspaceId,actorId,"audit.read");return this.audits.filter(a=>a.workspaceId===workspaceId).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt))}
  private audit(workspaceId:string,actorId:string,action:string,objectType:string,objectId:string,detail?:unknown,riskLevel:Audit["riskLevel"]="low"):void{this.audits.push({id:randomUUID(),workspaceId,actorId,action,objectType,objectId,occurredAt:new Date().toISOString(),detail,riskLevel})}
}
