"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { phase1Api } from "../lib/phase1-api";
import { apiBaseUrl } from "../lib/api-url";

type Filter = { range: string; from: string; to: string; timezone: string; flowId: string; emailVersionId: string; messageStatus: string };
type Metric = { key: string; label: string; value: number; numerator: number | null; denominator: number | null; rate: number | null; definition: string; knownLimitations: string | null };
type TrendPoint = { date: string; submitted: number; delivered: number; uniqueOpens: number; uniqueClicks: number };
type FlowOption = { id: string; name: string; status: string };
type EmailOption = { id: string; label: string };
type FlowPerformance = { flowId: string; flowVersionId: string; flowName: string; versionNumber: number; entries: number; submitted: number; delivered: number; uniqueOpens: number; uniqueClicks: number; complaints: number };
type ContentPerformance = { emailVersionId: string | null; name: string; versionNumber: number; submitted: number; delivered: number; uniqueOpens: number; uniqueClicks: number };
type RecentEvent = { messageId: string; kind: "engagement.open" | "engagement.click"; occurredAt: string };
type RecentMessage = { id: string; state: string; createdAt: string; submittedAt: string | null; emailVersionLabel: string | null; policyReason: string | null; flowId: string | null };
type RecipientStatus = "all" | "opened" | "not_opened" | "clicked" | "not_clicked";
type RecipientFilter = Exclude<RecipientStatus, "all">;
type RecipientRow = { messageId: string; profileId: string; email: string | null; name: string | null; phone: string | null; unsubscribed: boolean | null; emailName: string; emailVersionNumber: number | null; sourceType: string; flowName: string | null; state: string; sentAt: string; delivered: boolean; opened: boolean; openCount: number; firstOpenedAt: string | null; lastOpenedAt: string | null; clicked: boolean; clickCount: number; firstClickedAt: string | null; lastClickedAt: string | null; clickedUrls: string | null };
type RecipientReport = { total: number; matchingCount: number; page: number; limit: number; counts: { opened: number; notOpened: number; clicked: number; notClicked: number }; items: RecipientRow[] };
type Dashboard = {
  filters: { domain: { domain: string } | null; flows: FlowOption[]; emailVersions: EmailOption[] };
  freshness: { state: string; refreshedAt: string; sourceLatestAt: string | null; detail: string };
  metrics: Metric[];
  values: { submitted: number; delivered: number; uniqueOpens: number; uniqueClicks: number; hardBounces: number; softBounces: number; complaints: number; unsubscribes: number; activeRuns: number };
  engagement: { totalOpens: number; totalClicks: number; uniqueOpens: number; uniqueClicks: number };
  trend: TrendPoint[];
  deliveryOutcomes: { held: number; skipped: number; cancelled: number; failed: number; softBounces: number };
  topContent: ContentPerformance[];
  recentEvents: RecentEvent[];
  flowComparison: FlowPerformance[];
  recentMessages: RecentMessage[];
  definitions: { opens: string; exclusion: string; lateFeedback: string; attribution: string };
};

const number = (value: number) => new Intl.NumberFormat().format(value);
const percent = (value: number | null | undefined) => value === null || value === undefined ? "—" : `${(value * 100).toFixed(value * 100 >= 10 ? 1 : 2)}%`;
const timestamp = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "No data yet";
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const rate = (numerator: number, denominator: number) => denominator > 0 ? numerator / denominator : null;
const dateShort = (value: string) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(`${value}T00:00:00`));

export function AnalyticsConsole({ workspaceId }: { workspaceId: string }) {
  const [data, setData] = useState<Dashboard | null>(null);
  const [filters, setFilters] = useState<Filter>({ range: "30", from: "", to: "", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", flowId: "", emailVersionId: "", messageStatus: "all" });
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [refreshKey, setRefreshKey] = useState(0);
  const [series, setSeries] = useState<"engagement" | "delivery">("engagement");
  const [view, setView] = useState<"overview" | "content" | "flows" | "messages" | "recipients">("overview");
  const [recipientSelections, setRecipientSelections] = useState<RecipientFilter[]>([]);
  const [recipientSearchDraft, setRecipientSearchDraft] = useState("");
  const [recipientSearch, setRecipientSearch] = useState("");
  const [recipientPage, setRecipientPage] = useState(1);
  const [recipientReport, setRecipientReport] = useState<RecipientReport | null>(null);
  const [recipientLoading, setRecipientLoading] = useState(false);
  const [recipientError, setRecipientError] = useState("");
  const recipientRequest = useRef(0);
  const query = useMemo(() => { const params = new URLSearchParams(); for (const [key, value] of Object.entries(filters)) if (value) params.set(key, value); return params.toString(); }, [filters]);
  const recipientQuery = useMemo(() => { const params = new URLSearchParams(query); params.set("openStatus", recipientSelections.filter(item => item === "opened" || item === "not_opened").join(",") || "all"); params.set("clickStatus", recipientSelections.filter(item => item === "clicked" || item === "not_clicked").join(",") || "all"); params.set("page", String(recipientPage)); params.set("limit", "50"); if (recipientSearch) params.set("search", recipientSearch); return params.toString(); }, [query, recipientPage, recipientSearch, recipientSelections]);
  const load = useCallback(async () => {
    setLoading(true);
    try { const result = await phase1Api<Dashboard>(`/api/v1/workspaces/${workspaceId}/analytics/dashboard?${query}`); setData(result); setError(""); window.history.replaceState(null, "", `?${query}`); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load analytics."); }
    finally { setLoading(false); }
  }, [query, workspaceId]);
  useEffect(() => { void load(); }, [load, refreshKey]);
  const loadRecipients = useCallback(async () => {
    const request = ++recipientRequest.current;
    setRecipientLoading(true);
    try { const result = await phase1Api<RecipientReport>(`/api/v1/workspaces/${workspaceId}/analytics/recipients?${recipientQuery}`); if (request === recipientRequest.current) { setRecipientReport(result); setRecipientError(""); } }
    catch (cause) { if (request === recipientRequest.current) { setRecipientReport(null); setRecipientError(cause instanceof Error ? cause.message : "Unable to load recipient activity."); } }
    finally { if (request === recipientRequest.current) setRecipientLoading(false); }
  }, [recipientQuery, workspaceId]);
  useEffect(() => { if (view === "recipients") void loadRecipients(); }, [view, loadRecipients, refreshKey]);
  const set = (key: keyof Filter, value: string) => { setRecipientPage(1); setFilters(current => {
    if (key === "range" && value === "custom" && (!current.from || !current.to)) { const to = new Date(), from = new Date(to.getTime() - 7 * 86_400_000); return { ...current, range: value, from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) }; }
    return { ...current, [key]: value };
  }); };
  const downloadCsv = async (path: string, filename: string) => {
    try { const base = apiBaseUrl(), token = window.localStorage.getItem("emailPlatformAccessToken"); const response = await fetch(`${base}/api/v1/workspaces/${workspaceId}/${path}`, { credentials: "include", headers: token ? { authorization: `Bearer ${token}` } : { "x-dev-user": process.env.NEXT_PUBLIC_EMAIL_PLATFORM_DEV_USER ?? "dev-owner" } }); if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(body?.error ?? "Export unavailable. Narrow the filters and try again."); } const url = URL.createObjectURL(await response.blob()), anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }
    catch (cause) { if (path.includes("recipients")) setRecipientError(cause instanceof Error ? cause.message : "Recipient export unavailable."); else setError(cause instanceof Error ? cause.message : "Export unavailable."); }
  };
  if (loading && !data) return <AnalyticsSkeleton/>;
  if (!data) return <section className="analytics-v2-error" role="alert"><strong>Analytics could not be loaded.</strong><p>{error || "Try refreshing this page."}</p><button className="button-primary" onClick={() => setRefreshKey(value => value + 1)}>Retry</button></section>;
  const metric = (key: string) => data.metrics.find(item => item.key === key);
  const primaryMetrics = ["submitted", "delivered", "unique_opens", "unique_clicks"].map(metric).filter((item): item is Metric => Boolean(item));
  return <section className="analytics-v2">
    <header className="analytics-v2-hero analytics-v2-hero-compact"><div><span className="analytics-v2-eyebrow"><i/>Performance intelligence</span><h1>Email analytics</h1><p>Delivery and engagement across your live campaigns and automations.</p></div><div className="analytics-v2-actions"><span className={`analytics-v2-live ${data.freshness.state === "current" ? "is-current" : ""}`} title={data.freshness.detail}><i/>{title(data.freshness.state)} · {timestamp(data.freshness.sourceLatestAt)}</span><button className="button-secondary" onClick={() => setRefreshKey(value => value + 1)} disabled={loading}>{loading ? "Refreshing…" : "Refresh"}</button><button className="button-primary" onClick={() => void downloadCsv(`analytics/export?${query}`, "velivoo-analytics.csv")}>Export CSV</button></div></header>
    <FilterBar data={data} filters={filters} set={set}/>{error && <div className="analytics-v2-error" role="alert"><strong>Update failed.</strong><p>{error}</p></div>}
    <section className="analytics-v2-kpis" aria-label="Primary metrics">{primaryMetrics.map(item => <MetricCard key={item.key} metric={item}/>)}</section>
    <nav className="analytics-v2-views" aria-label="Analytics reports">
      {(["overview", "content", "flows", "messages", "recipients"] as const).map(item => <button key={item} className={view === item ? "active" : ""} aria-pressed={view === item} onClick={() => setView(item)}>{item === "overview" ? "Overview" : item === "recipients" ? "Recipient activity" : title(item)}</button>)}
    </nav>
    {view === "overview" && <>
      <section className="analytics-v2-performance"><TrendCard trend={data.trend} series={series} onSeries={setSeries}/><EngagementCard values={data.values} engagement={data.engagement}/></section>
      <section className="analytics-v2-grid analytics-v2-overview-grid"><SignalFeed events={data.recentEvents} workspaceId={workspaceId}/><DeliveryHealth values={data.values} outcomes={data.deliveryOutcomes} workspaceId={workspaceId}/></section>
    </>}
    {view === "content" && <section className="analytics-v2-report"><ContentTable content={data.topContent}/></section>}
    {view === "flows" && <section className="analytics-v2-report"><FlowTable flows={data.flowComparison} workspaceId={workspaceId}/></section>}
    {view === "messages" && <section className="analytics-v2-report"><MessageTable messages={data.recentMessages} workspaceId={workspaceId}/></section>}
    {view === "recipients" && <RecipientActivity report={recipientReport} loading={recipientLoading} error={recipientError} workspaceId={workspaceId} selections={recipientSelections} searchDraft={recipientSearchDraft} onSearchDraft={setRecipientSearchDraft} onSearch={() => { setRecipientPage(1); setRecipientSearch(recipientSearchDraft.trim()); }} onStatus={next => { setRecipientPage(1); setRecipientSelections(current => { if (next === "all") return []; if (current.includes(next)) return current.filter(item => item !== next); const opposite: Record<RecipientFilter, RecipientFilter> = { opened: "not_opened", not_opened: "opened", clicked: "not_clicked", not_clicked: "clicked" }; return [...current.filter(item => item !== opposite[next]), next]; }); }} onPage={setRecipientPage} onDownload={() => void downloadCsv(`analytics/recipients/export?${recipientQuery}`, "velivoo-recipient-activity.csv")} onRetry={() => void loadRecipients()}/>}
    <details className="analytics-v2-notes"><summary>How metrics are calculated</summary><p>{data.definitions.opens}</p><p>{data.definitions.exclusion}</p><p>{data.definitions.lateFeedback}</p><p>{data.definitions.attribution}</p></details>
  </section>;
}

function FilterBar({ data, filters, set }: { data: Dashboard; filters: Filter; set: (key: keyof Filter, value: string) => void }) { const clear = () => { set("flowId", ""); set("emailVersionId", ""); set("messageStatus", "all"); }; const hasExtraFilters = Boolean(filters.emailVersionId) || filters.messageStatus !== "all"; return <section className="analytics-v2-filters analytics-v2-filters-compact" aria-label="Analytics filters"><div className="analytics-v2-filter-title"><span>Reporting period</span><strong>{filters.range === "today" ? "Today" : filters.range === "custom" ? "Custom range" : `Last ${filters.range} days`}</strong></div><label>Date range<select value={filters.range} onChange={event => set("range", event.target.value)}><option value="today">Today</option><option value="7">Last 7 days</option><option value="14">Last 14 days</option><option value="30">Last 30 days</option><option value="custom">Custom</option></select></label>{filters.range === "custom" && <><label>From<input type="date" value={filters.from} onChange={event => set("from", event.target.value)}/></label><label>To<input type="date" value={filters.to} onChange={event => set("to", event.target.value)}/></label></>}<label>Flow<select value={filters.flowId} onChange={event => set("flowId", event.target.value)}><option value="">All flows</option>{data.filters.flows.map(flow => <option value={flow.id} key={flow.id}>{flow.name}</option>)}</select></label><details className="analytics-v2-more-filters"><summary>More filters{hasExtraFilters ? " • Active" : ""}</summary><div><label>Content<select value={filters.emailVersionId} onChange={event => set("emailVersionId", event.target.value)}><option value="">All content</option>{data.filters.emailVersions.map(version => <option value={version.id} key={version.id}>{version.label}</option>)}</select></label><label>Status<select value={filters.messageStatus} onChange={event => set("messageStatus", event.target.value)}>{["all", "created", "held", "skipped", "submitted", "delivered", "bounced", "complained", "failed", "cancelled"].map(state => <option value={state} key={state}>{title(state)}</option>)}</select></label><label>Timezone<select value={filters.timezone} onChange={event => set("timezone", event.target.value)}>{[filters.timezone, "UTC", "Asia/Karachi", "Europe/London", "America/New_York", "Asia/Tokyo"].filter((value, index, values) => values.indexOf(value) === index).map(zone => <option value={zone} key={zone}>{zone}</option>)}</select></label><button type="button" className="button-secondary" onClick={clear} disabled={!hasExtraFilters}>Clear filters</button></div></details></section>; }

function RecipientActivity({ report, loading, error, workspaceId, selections, searchDraft, onSearchDraft, onSearch, onStatus, onPage, onDownload, onRetry }: { report: RecipientReport | null; loading: boolean; error: string; workspaceId: string; selections: RecipientFilter[]; searchDraft: string; onSearchDraft: (value: string) => void; onSearch: () => void; onStatus: (value: RecipientStatus) => void; onPage: (page: number) => void; onDownload: () => void; onRetry: () => void }) {
  const filterButton = (key: RecipientStatus, label: string, count: number | null) => { const active = key === "all" ? selections.length === 0 : selections.includes(key); return <button type="button" key={key} className={active ? "active" : ""} aria-pressed={active} onClick={() => onStatus(key)}>{label}<span>{count === null ? "—" : number(count)}</span></button>; };
  return <section className="analytics-v2-report analytics-recipient-report" aria-label="Recipient activity report">
    <div className="analytics-v2-card">
      <header><div><span>Recipient activity</span><h2>Who engaged with each email</h2></div><button type="button" className="button-primary" onClick={onDownload} disabled={!report || loading}>Download filtered CSV</button></header>
      <p className="analytics-recipient-intro">One row per sent email and recipient. Choose one Open option and one Click option together. Date, Flow, and content filters also apply. Test sends are excluded.</p>
      <div className="analytics-recipient-tabs" role="group" aria-label="Engagement filters">{filterButton("all", "All sent", report?.total ?? null)}<span className="analytics-recipient-filter-label">Open</span>{filterButton("opened", "Opened", report?.counts.opened ?? null)}{filterButton("not_opened", "No open recorded", report?.counts.notOpened ?? null)}<span className="analytics-recipient-filter-label">Click</span>{filterButton("clicked", "Clicked", report?.counts.clicked ?? null)}{filterButton("not_clicked", "No click recorded", report?.counts.notClicked ?? null)}</div>
      <form className="analytics-recipient-search" onSubmit={event => { event.preventDefault(); onSearch(); }}><label htmlFor="analytics-recipient-search">Find a recipient</label><input id="analytics-recipient-search" type="search" maxLength={160} value={searchDraft} placeholder="Search name, phone, or email" onChange={event => onSearchDraft(event.target.value)}/><button type="submit" className="button-secondary">Search</button><span>{report ? `${number(report.matchingCount)} matching sent emails` : ""}</span></form>
      {error && <div className="analytics-recipient-error" role="alert">{error} <button type="button" onClick={onRetry}>Retry</button></div>}
      <div className="analytics-v2-table-wrap analytics-recipient-table"><table aria-label="Recipient engagement sheet"><thead><tr><th>Name</th><th>Phone number</th><th>Email</th><th>Email opened</th><th>Link clicked</th><th>Unsubscribed</th></tr></thead><tbody>{loading || !report || !report.items.length ? <tr className="analytics-recipient-placeholder"><td colSpan={6}>{loading ? "Loading recipient sheet…" : error ? "The recipient sheet could not load. Use Retry above; if the error is NOT_FOUND, restart npm run dev:stack." : report ? "No recipients match these filters. Try a wider date range or clear a filter." : "Preparing recipient sheet…"}</td></tr> : report.items.map(row => <tr key={row.messageId}><td>{row.email ? <Link href={`/w/${workspaceId}/profiles/${row.profileId}`}><strong>{row.name || "No name"}</strong></Link> : <strong>Deleted profile</strong>}<details className="analytics-recipient-details"><summary>Send details</summary><div><span>{row.emailName}{row.emailVersionNumber ? ` · v${row.emailVersionNumber}` : ""}</span><span>{row.flowName ? `Flow · ${row.flowName}` : title(row.sourceType)} · {timestamp(row.sentAt)}</span><span>{row.delivered ? "Delivered" : title(row.state)}{row.opened ? ` · ${number(row.openCount)} opens` : ""}{row.clicked ? ` · ${number(row.clickCount)} clicks` : ""}</span>{row.clickedUrls && <span className="analytics-recipient-detail-links">Links: {row.clickedUrls}</span>}<Link href={`/w/${workspaceId}/messages/${row.messageId}`}>View message trace →</Link></div></details></td><td>{row.phone || "—"}</td><td className="analytics-recipient-email">{row.email || "—"}</td><td><span className={`analytics-recipient-state ${row.opened ? "positive" : "neutral"}`} title={row.firstOpenedAt ? `First open: ${timestamp(row.firstOpenedAt)}` : "No open event recorded"}>{row.opened ? "Yes" : "No"}</span></td><td><span className={`analytics-recipient-state ${row.clicked ? "positive" : "neutral"}`} title={row.firstClickedAt ? `First click: ${timestamp(row.firstClickedAt)}` : "No tracked click recorded"}>{row.clicked ? "Yes" : "No"}</span></td><td><span className={`analytics-recipient-state ${row.unsubscribed === true ? "warning" : "neutral"}`} title="Current marketing unsubscribe status">{row.unsubscribed === null ? "—" : row.unsubscribed ? "Yes" : "No"}</span></td></tr>)}</tbody></table></div>
      {report && report.matchingCount > report.limit && <div className="analytics-recipient-pagination"><span>Page {report.page} of {Math.ceil(report.matchingCount / report.limit)}</span><button type="button" className="button-secondary" disabled={loading || report.page <= 1} onClick={() => onPage(report.page - 1)}>Previous</button><button type="button" className="button-secondary" disabled={loading || report.page * report.limit >= report.matchingCount} onClick={() => onPage(report.page + 1)}>Next</button></div>}
      <p className="analytics-recipient-note">Open and click show recorded events for this sent email. “No” does not prove an email was unread: image blocking and privacy protections can hide opens. Unsubscribed shows the recipient’s current marketing status; “No” does not imply consent. Missing phone numbers appear as a dash.</p>
    </div>
  </section>;
}

function MetricCard({ metric }: { metric: Metric }) { const isRatio = metric.key === "click_to_open", display = isRatio ? percent(metric.value) : number(metric.value); return <article className={`analytics-v2-kpi analytics-v2-kpi-${metric.key.replaceAll("_", "-")}`} title={metric.knownLimitations ?? metric.definition}><span>{metric.label}</span><strong>{display}</strong>{metric.numerator !== null && <small>{isRatio ? `${number(metric.numerator)} clicks from ${number(metric.denominator ?? 0)} opens` : `${percent(metric.rate)} of sent`}</small>}<i aria-hidden="true">{metric.key === "submitted" ? "↗" : metric.key === "delivered" ? "✓" : metric.key.includes("open") ? "◉" : metric.key.includes("click") ? "↗" : "!"}</i></article>; }

function TrendCard({ trend, series, onSeries }: { trend: TrendPoint[]; series: "engagement" | "delivery"; onSeries: (next: "engagement" | "delivery") => void }) { const keys = series === "engagement" ? ["uniqueOpens", "uniqueClicks"] as const : ["submitted", "delivered"] as const, max = Math.max(1, ...trend.flatMap(point => keys.map(key => point[key]))), line = (key: typeof keys[number]) => trend.map((point, index) => `${trend.length < 2 ? 50 : index / (trend.length - 1) * 100},${100 - point[key] / max * 83 - 7}`).join(" "), total = trend.reduce((sum, point) => sum + keys.reduce((subTotal, key) => subTotal + point[key], 0), 0), labels = series === "engagement" ? ["Unique opens", "Unique clicks"] : ["Sent", "Delivered"]; return <section className="analytics-v2-card analytics-v2-chart"><header><div><span>Performance over time</span><h2>{series === "engagement" ? "Engagement signals" : "Delivery progress"}</h2></div><div className="analytics-v2-segment"><button className={series === "engagement" ? "active" : ""} onClick={() => onSeries("engagement")}>Engagement</button><button className={series === "delivery" ? "active" : ""} onClick={() => onSeries("delivery")}>Delivery</button></div></header>{total ? <><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`${labels[0]} and ${labels[1]} trend`}><polyline className="analytics-v2-line primary" points={line(keys[0])}/><polyline className="analytics-v2-line secondary" points={line(keys[1])}/></svg><div className="analytics-v2-chart-footer"><span><i className="primary"/>{labels[0]}</span><span><i className="secondary"/>{labels[1]}</span><small>{trend.length ? `${dateShort(trend[0].date)} – ${dateShort(trend.at(-1)?.date ?? trend[0].date)}` : ""}</small></div></> : <div className="analytics-v2-empty"><strong>No production signals yet</strong><p>Send a production campaign or let a Flow reach an email step to populate this chart.</p></div>}</section>; }

function EngagementCard({ values, engagement }: { values: Dashboard["values"]; engagement: Dashboard["engagement"] }) { const cards = [["Open rate", percent(rate(engagement.uniqueOpens, values.submitted)), "Unique recipients who opened"], ["Click rate", percent(rate(engagement.uniqueClicks, values.submitted)), "Unique recipients who clicked"], ["Total opens", number(engagement.totalOpens), "All recorded open events"], ["Total clicks", number(engagement.totalClicks), "All tracked link clicks"]] as const; return <section className="analytics-v2-card analytics-v2-engagement"><header><div><span>Engagement</span><h2>Recipient activity</h2></div><a href="#message-activity">View messages →</a></header><div>{cards.map(([name, value, description]) => <article key={name}><small>{name}</small><strong>{value}</strong><span>{description}</span></article>)}</div><p>Clicks are generally a stronger signal than opens because mail apps can load images automatically.</p></section>; }

function ContentTable({ content }: { content: ContentPerformance[] }) { return <section className="analytics-v2-card analytics-v2-table-card"><header><div><span>Content performance</span><h2>Top performing emails</h2></div><small>Ranked by engagement</small></header>{content.length ? <div className="analytics-v2-table-wrap"><table><thead><tr><th>Email</th><th>Sent</th><th>Opens</th><th>Clicks</th></tr></thead><tbody>{content.map(item => <tr key={item.emailVersionId ?? item.name}><td><strong>{item.name}</strong><small>Version {item.versionNumber}</small></td><td>{number(item.submitted)}</td><td>{number(item.uniqueOpens)} <small>{percent(rate(item.uniqueOpens, item.submitted))}</small></td><td>{number(item.uniqueClicks)} <small>{percent(rate(item.uniqueClicks, item.submitted))}</small></td></tr>)}</tbody></table></div> : <div className="analytics-v2-empty"><strong>No email performance yet</strong><p>Production messages will appear here when they are sent.</p></div>}</section>; }

function SignalFeed({ events, workspaceId }: { events: RecentEvent[]; workspaceId: string }) { return <section className="analytics-v2-card analytics-v2-signals"><header><div><span>Live activity</span><h2>Recent engagement</h2></div><span className="analytics-v2-pulse"><i/>Live</span></header>{events.length ? <ol>{events.map((event, index) => <li key={`${event.messageId}-${event.occurredAt}-${index}`}><i className={event.kind.endsWith("open") ? "open" : "click"}/><div><strong>{event.kind.endsWith("open") ? "Email opened" : "Tracked link clicked"}</strong><small>{timestamp(event.occurredAt)}</small></div><Link href={`/w/${workspaceId}/messages/${event.messageId}`}>Trace</Link></li>)}</ol> : <div className="analytics-v2-empty"><strong>Waiting for engagement</strong><p>New opens and clicks will appear here automatically.</p></div>}</section>; }

function FlowTable({ flows, workspaceId }: { flows: FlowPerformance[]; workspaceId: string }) { return <section className="analytics-v2-card analytics-v2-table-card"><header><div><span>Automation performance</span><h2>Flow results</h2></div><small>Published versions stay separate</small></header>{flows.length ? <div className="analytics-v2-table-wrap"><table><thead><tr><th>Flow</th><th>Entered</th><th>Sent</th><th>Opened</th><th>Clicked</th><th/></tr></thead><tbody>{flows.map(flow => <tr key={flow.flowVersionId}><td><strong>{flow.flowName}</strong><small>Version {flow.versionNumber}</small></td><td>{number(flow.entries)}</td><td>{number(flow.submitted)}</td><td>{number(flow.uniqueOpens)}</td><td>{number(flow.uniqueClicks)}</td><td><Link href={`/w/${workspaceId}/flows/${flow.flowId}/runs`}>Runs</Link></td></tr>)}</tbody></table></div> : <div className="analytics-v2-empty"><strong>No Flow performance yet</strong><p>Activate a Flow and process a real entry to populate this report.</p></div>}</section>; }

function DeliveryHealth({ values, outcomes, workspaceId }: { values: Dashboard["values"]; outcomes: Dashboard["deliveryOutcomes"]; workspaceId: string }) { const rows = [["Delivered", values.delivered, rate(values.delivered, values.submitted), "good"], ["Hard bounces", values.hardBounces, rate(values.hardBounces, values.submitted), values.hardBounces ? "danger" : "good"], ["Soft bounces", outcomes.softBounces, rate(outcomes.softBounces, values.submitted), outcomes.softBounces ? "warning" : "good"], ["Spam complaints", values.complaints, rate(values.complaints, values.submitted), values.complaints ? "danger" : "good"], ["Unsubscribes", values.unsubscribes, rate(values.unsubscribes, values.submitted), values.unsubscribes ? "warning" : "good"]] as const; return <section className="analytics-v2-card analytics-v2-health"><header><div><span>Deliverability health</span><h2>Outcome monitoring</h2></div><Link href={`/w/${workspaceId}/deliverability`}>Open deliverability →</Link></header>{rows.map(([name, value, metricRate, state]) => <div className="analytics-v2-health-row" key={name}><span><i className={state}/>{name}</span><strong>{number(value)}</strong><small>{percent(metricRate)}</small></div>)}</section>; }

function MessageTable({ messages, workspaceId }: { messages: RecentMessage[]; workspaceId: string }) { return <section className="analytics-v2-card analytics-v2-messages" id="message-activity"><header><div><span>Message activity</span><h2>Recent production sends</h2></div><small>Open a trace for detailed delivery and engagement evidence.</small></header>{messages.length ? <div className="analytics-v2-table-wrap"><table><thead><tr><th>Message</th><th>Content</th><th>State</th><th>Submitted</th><th>Action</th></tr></thead><tbody>{messages.slice(0, 12).map(message => <tr key={message.id}><td><code>{message.id.slice(0, 8)}…</code></td><td>{message.emailVersionLabel ?? "Archived content"}</td><td><span className={`analytics-v2-status ${message.state}`}>{title(message.state)}</span></td><td>{timestamp(message.submittedAt)}</td><td><Link href={`/w/${workspaceId}/messages/${message.id}`}>View trace</Link></td></tr>)}</tbody></table></div> : <div className="analytics-v2-empty"><strong>No production sends in this period</strong><p>Try a wider date range or remove a filter.</p></div>}</section>; }

function AnalyticsSkeleton() { return <section className="analytics-v2 analytics-v2-skeleton"><div/><div/><div/><div/><div/><div/></section>; }
