'use client';
import {useCallback,useEffect,useState} from 'react';
import {phase1Api} from '../lib/phase1-api';

export function AudienceOverview({workspaceId}:{workspaceId:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 const load=useCallback(async()=>{try{setError('');setData(await phase1Api<any>(`/api/v1/workspaces/${workspaceId}/audiences/overview`))}catch(e){setError(e instanceof Error?e.message:'Unable to load Audience overview.')}},[workspaceId]);
 useEffect(()=>{void load()},[load]);
 if(error)return <section className="panel profile-error"><h1>Unable to load Audience overview.</h1><p>{error}</p><button className="button-secondary" onClick={load}>Retry</button></section>;
 if(!data)return <section><div className="page-heading"><div><div className="skeleton skeleton-title"/><div className="skeleton skeleton-subtitle"/></div></div><div className="metric-grid">{[1,2,3,4].map(x=><div key={x} className="metric-card skeleton-card"/>)}</div></section>;
 const cards=[['Total profiles',data.summary.totalProfiles,'violet'],['Reachable profiles',data.summary.reachableProfiles,'mint'],['Active lists',data.summary.activeLists,'peach'],['Active segments',data.summary.activeSegments,'blue']];
 return <section><div className="page-heading"><div><h1>Audience</h1><p>Static Lists and dynamic Segments use the same canonical profile eligibility.</p></div><div className="page-heading-actions"><a className="button-secondary" href={`/w/${workspaceId}/audiences/lists`}>Lists</a><a className="button-primary" href={`/w/${workspaceId}/audiences/segments`}>Segments</a></div></div><div className="metric-grid">{cards.map(([label,value,tone])=><article key={String(label)} className={`metric-card ${tone}`}><div className="metric-label">{label}</div><div className="metric-value">{Number(value).toLocaleString()}</div></article>)}</div><div className="home-grid"><section className="panel"><div className="panel-heading"><h2>Audience guidance</h2></div><div className="audience-note"><strong>Membership does not grant marketing consent.</strong><span>Reachability is recalculated from the profile identifier, current subscription state, and active suppressions.</span></div><div className="audience-note"><strong>Segments are dynamic.</strong><span>Only a projection refreshed within 15 minutes is presented as current, and flow entries come from future membership transitions.</span></div></section><section className="panel"><div className="panel-heading"><h2>Recent activity</h2></div>{data.recentActivity.length?<div className="activity-list">{data.recentActivity.map((item:any)=><div key={item.id}><strong>{item.type.replaceAll('.',' ')}</strong><span>{new Date(item.timestamp).toLocaleString()} · {item.summary}</span></div>)}</div>:<div className="empty-state">No audience activity yet.</div>}</section></div></section>;
}
