"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { phase1Api } from "../lib/phase1-api";
import { SenderIdentityManager } from "./sender-identity-manager";

export type SettingsSection = "general" | "members" | "sender-identities" | "send-policies" | "api-keys" | "audit-log" | "dangerous-actions";

type Workspace = { id:string; name:string; legalName:string; businessAddress:string; timezone:string; locale:string; status:string; rowVersion:string };
type Member = { id:string; userId:string; role:"owner"|"admin"|"marketer"|"analyst"; status:string; email?:string; displayName?:string|null; invitedBy?:string|null; createdAt?:string };
type Invitation = { id:string; email:string; role:string; createdAt:string; expiresAt:string; acceptedAt?:string|null; revokedAt?:string|null };
type Policy = { version:number; frequencyWindowSeconds:number; frequencyMax:number; quietHours?:{startHour:number;endHour:number}; warmingDailyLimit?:number };
type ApiKey = { id:string; name:string; prefix:string; scopes:string[]; createdAt:string; lastUsedAt?:string|null; expiresAt?:string|null; revokedAt?:string|null };
type Audit = { id:string; actorType:string; actorId?:string|null; action:string; objectType:string; objectId?:string|null; riskLevel:string; before?:unknown; after?:unknown; requestId?:string|null; correlationId?:string|null; occurredAt:string };
type Dangerous = { workspace:Workspace; member:{id:string;role:Member["role"]}; members:Member[]; owners:Member[]; canTransfer:boolean; canDelete:boolean };

const sections:Array<{id:SettingsSection; label:string; description:string}>=[
  {id:"general",label:"General",description:"Identity, address, timezone and locale"},
  {id:"members",label:"Users & roles",description:"Workspace membership and access"},
  {id:"sender-identities",label:"Sender identities",description:"From addresses and domain readiness"},
  {id:"send-policies",label:"Send policies",description:"Frequency, quiet hours and safety limits"},
  {id:"api-keys",label:"API keys",description:"Scoped event-ingestion credentials"},
  {id:"audit-log",label:"Audit log",description:"Inspectable administrative history"},
  {id:"dangerous-actions",label:"Dangerous actions",description:"Ownership and controlled deletion"},
];
const roles:Member["role"][]=["admin","marketer","analyst"];
const scopes=["events.read","events.write"];
const timezones=["UTC","America/New_York","America/Los_Angeles","Europe/London","Europe/Berlin","Asia/Karachi","Asia/Singapore","Australia/Sydney"];
const locales=["en","en-US","en-GB","de-DE","fr-FR","es-ES","ja-JP"];

function requestError(error:unknown){return error instanceof Error?error.message:"Something went wrong. Please try again."}
function formatTime(value?:string|null){return value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—"}
function badge(value:string){const normalized=value.toLowerCase();const tone=normalized.includes("active")||normalized.includes("verified")||normalized.includes("accepted")||normalized.includes("owner")?"pill-success":normalized.includes("revoked")||normalized.includes("delete")||normalized.includes("blocked")?"pill-danger":normalized.includes("pending")||normalized.includes("expire")?"pill-warning":"pill-neutral";return <span className={`pill ${tone}`}>{value.replaceAll("_"," ")}</span>}

export function SettingsConsole({workspaceId,section}:{workspaceId:string;section:SettingsSection}){
  const active=sections.find(item=>item.id===section)!;
  return <section className="settings-page">
    <header className="page-heading"><div><span className="eyebrow">Workspace administration</span><h1>Settings</h1><p>{active.label} · {active.description}</p></div></header>
    <div className="settings-layout">
      <nav className="settings-nav" aria-label="Settings sections">{sections.map(item=><Link key={item.id} href={`/w/${workspaceId}/settings/${item.id}`} aria-current={item.id===section?"page":undefined}><strong>{item.label}</strong><small>{item.description}</small></Link>)}</nav>
      <main className="settings-content">{section==="general"&&<General workspaceId={workspaceId}/>} {section==="members"&&<Members workspaceId={workspaceId}/>} {section==="sender-identities"&&<Senders workspaceId={workspaceId}/>} {section==="send-policies"&&<Policies workspaceId={workspaceId}/>} {section==="api-keys"&&<Keys workspaceId={workspaceId}/>} {section==="audit-log"&&<Audits workspaceId={workspaceId}/>} {section==="dangerous-actions"&&<DangerousActions workspaceId={workspaceId}/>}</main>
    </div>
  </section>;
}

function General({workspaceId}:{workspaceId:string}){
  const [workspace,setWorkspace]=useState<Workspace|null>(null),[saved,setSaved]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  useEffect(()=>{void phase1Api<Workspace>(`/api/v1/workspaces/${workspaceId}`).then(setWorkspace).catch(error=>setError(requestError(error)))},[workspaceId]);
  if(!workspace)return <LoadState error={error}/>;
  const current=workspace;
  const update=(key:keyof Workspace,value:string)=>setWorkspace({...current,[key]:value});
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");setSaved("");try{const result=await phase1Api<Workspace>(`/api/v1/workspaces/${workspaceId}`,{method:"PATCH",body:JSON.stringify({name:current.name.trim(),legalName:current.legalName.trim(),businessAddress:current.businessAddress.trim(),timezone:current.timezone,locale:current.locale,expectedRowVersion:current.rowVersion})});setWorkspace(result);setSaved("Changes saved. Readiness and compliance surfaces now use this canonical workspace identity.")}catch(cause){setError(requestError(cause))}finally{setSaving(false)}}
  return <form className="settings-stack" onSubmit={save}><section className="panel settings-card"><div className="panel-heading"><div><h2>Workspace identity</h2><p className="panel-subtitle">Used by compliance footers and Release 1 production readiness.</p></div>{badge(workspace.status)}</div><div className="form-grid"><label>Workspace name<input value={workspace.name} onChange={event=>update("name",event.target.value)} required maxLength={200}/></label><label>Business / legal name<input value={workspace.legalName} onChange={event=>update("legalName",event.target.value)} required maxLength={500}/></label></div><label>Physical business address<textarea rows={3} value={workspace.businessAddress} onChange={event=>update("businessAddress",event.target.value)} required maxLength={500}/></label><p className="settings-note">This is the canonical business address used by the required compliance footer. Missing identity data blocks readiness.</p></section>
    <section className="panel settings-card"><div className="panel-heading"><div><h2>Regional defaults</h2><p className="panel-subtitle">These change future display and scheduling defaults, never historical UTC facts.</p></div></div><div className="form-grid"><label>Default timezone<select value={workspace.timezone} onChange={event=>update("timezone",event.target.value)}>{timezones.includes(workspace.timezone)?null:<option value={workspace.timezone}>{workspace.timezone}</option>}{timezones.map(zone=><option key={zone}>{zone}</option>)}</select></label><label>Locale and data display<select value={workspace.locale} onChange={event=>update("locale",event.target.value)}>{locales.includes(workspace.locale)?null:<option value={workspace.locale}>{workspace.locale}</option>}{locales.map(locale=><option key={locale}>{locale}</option>)}</select></label></div><div className="settings-callout"><strong>Timezone consequence</strong><p>Changing the workspace timezone changes default display and scheduling behavior. Historical timestamps are not rewritten.</p></div></section>
    <ActionState error={error} success={saved}/><div className="settings-actions"><button className="button-secondary" type="button" onClick={()=>setWorkspace({...workspace})}>Cancel</button><button className="button-primary" disabled={saving}>{saving?"Saving…":"Save changes"}</button></div>
  </form>;
}

function Members({workspaceId}:{workspaceId:string}){
  const [members,setMembers]=useState<Member[]>([]),[invitations,setInvitations]=useState<Invitation[]>([]),[email,setEmail]=useState(""),[role,setRole]=useState<Member["role"]>("marketer"),[error,setError]=useState(""),[success,setSuccess]=useState(""),[loading,setLoading]=useState(true);
  async function load(){setLoading(true);try{const [memberData,invitationData]=await Promise.all([phase1Api<{items:Member[]}>(`/api/v1/workspaces/${workspaceId}/members`),phase1Api<{items:Invitation[]}>(`/api/v1/workspaces/${workspaceId}/invitations`)]);setMembers(memberData.items);setInvitations(invitationData.items);setError("")}catch(cause){setError(requestError(cause))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[workspaceId]);
  async function invite(event:FormEvent){event.preventDefault();setError("");try{await phase1Api(`/api/v1/workspaces/${workspaceId}/invitations`,{method:"POST",body:JSON.stringify({email,role})});setEmail("");setSuccess("Invitation created. The invitee receives the workspace role after accepting their invitation.");await load()}catch(cause){setError(requestError(cause))}}
  async function changeRole(memberId:string,nextRole:Member["role"]){try{await phase1Api(`/api/v1/workspaces/${workspaceId}/members/${memberId}`,{method:"PATCH",body:JSON.stringify({role:nextRole})});setSuccess("Role updated and audited. Server authorization takes effect immediately.");await load()}catch(cause){setError(requestError(cause))}}
  async function revoke(member:Member){if(!window.confirm(`Revoke ${member.email??member.userId}'s workspace access?`))return;try{await phase1Api(`/api/v1/workspaces/${workspaceId}/members/${member.id}`,{method:"DELETE"});setSuccess("Membership revoked and recorded in the audit log.");await load()}catch(cause){setError(requestError(cause))}}
  if(loading)return <LoadState error={error}/>;
  return <div className="settings-stack"><section className="panel settings-card"><div className="panel-heading"><div><h2>Invite a workspace member</h2><p className="panel-subtitle">Roles are server-enforced permission bundles, not browser-only controls.</p></div></div><form className="inline-form" onSubmit={invite}><label>Email address<input type="email" value={email} onChange={event=>setEmail(event.target.value)} required/></label><label>Role<select value={role} onChange={event=>setRole(event.target.value as Member["role"])}>{roles.map(item=><option key={item} value={item}>{item}</option>)}</select></label><button className="button-primary">Send invitation</button></form><div className="settings-note"><strong>Permission summary:</strong> Admins manage most workspace operations; Marketers create content and flows; Analysts are read-only for workspace data and analytics.</div></section><ActionState error={error} success={success}/><section className="panel table-panel"><div className="settings-table-heading"><div><h2>Members</h2><p>Active, invited, and revoked access are retained for accountability.</p></div><span>{members.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Member</th><th>Role</th><th>Status</th><th>Last active</th><th>Actions</th></tr></thead><tbody>{members.map(member=><tr key={member.id}><td><strong>{member.displayName??member.email??member.userId}</strong><br/><small>{member.email??member.userId}</small></td><td>{member.role==="owner"?badge("owner"):<select aria-label={`Role for ${member.email??member.userId}`} value={member.role} onChange={event=>void changeRole(member.id,event.target.value as Member["role"])}>{roles.map(item=><option key={item}>{item}</option>)}</select>}</td><td>{badge(member.status)}</td><td>{formatTime(member.createdAt)}</td><td>{member.status==="active"&&member.role!=="owner"?<button className="button-secondary small-button" onClick={()=>void revoke(member)}>Revoke</button>:"—"}</td></tr>)}</tbody></table></div>{!members.length&&<Empty title="No members yet" text="Invite teammates to share the workspace with server-enforced roles."/>}</section><section className="panel table-panel"><div className="settings-table-heading"><div><h2>Invitation status</h2><p>Expired and used invitations remain visible; create a new invitation to recover.</p></div></div><div className="table-wrap"><table><thead><tr><th>Email</th><th>Role</th><th>Status</th><th>Expires</th></tr></thead><tbody>{invitations.map(invitation=>{const state=invitation.acceptedAt?"accepted":invitation.revokedAt?"revoked":new Date(invitation.expiresAt)<new Date()?"expired":"pending";return <tr key={invitation.id}><td>{invitation.email}</td><td>{invitation.role}</td><td>{badge(state)}</td><td>{formatTime(invitation.expiresAt)}</td></tr>})}</tbody></table></div>{!invitations.length&&<Empty title="No invitations" text="Invitations will appear here with their acceptance or expiry state."/>}</section></div>;
}

function Senders({workspaceId}:{workspaceId:string}){return <div className="settings-stack"><div className="settings-callout"><strong>Settings manages identities; Deliverability manages DNS.</strong><p>Create From names, From addresses, reply-to addresses and their associated verified domains here. SPF, DKIM, DMARC and diagnostics remain in Deliverability.</p></div><SenderIdentityManager workspaceId={workspaceId}/></div>}

function Policies({workspaceId}:{workspaceId:string}){
  const [policy,setPolicy]=useState<Policy|null>(null),[error,setError]=useState(""),[success,setSuccess]=useState(""),[saving,setSaving]=useState(false);
  useEffect(()=>{void phase1Api<Policy>(`/api/v1/workspaces/${workspaceId}/send-policy`).then(setPolicy).catch(cause=>setError(requestError(cause)))},[workspaceId]);
  if(!policy)return <LoadState error={error}/>;
  const current=policy;
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const next=await phase1Api<Policy>(`/api/v1/workspaces/${workspaceId}/send-policy`,{method:"PATCH",body:JSON.stringify({...current,expectedVersion:current.version})});setPolicy(next);setSuccess("Send policy saved. The final message eligibility pipeline now reads this policy version.")}catch(cause){setError(requestError(cause))}finally{setSaving(false)}}
  return <form className="settings-stack" onSubmit={save}><section className="panel settings-card"><div className="panel-heading"><div><h2>Frequency cap</h2><p className="panel-subtitle">Maximum marketing messages per recipient in the rolling policy window.</p></div>{badge(`policy v${policy.version}`)}</div><div className="form-grid"><label>Maximum messages<input type="number" min={0} value={policy.frequencyMax} onChange={event=>setPolicy({...policy,frequencyMax:Number(event.target.value)})}/></label><label>Rolling window (hours)<input type="number" min={1} value={Math.round(policy.frequencyWindowSeconds/3600)} onChange={event=>setPolicy({...policy,frequencyWindowSeconds:Number(event.target.value)*3600})}/></label></div><p className="settings-note">Example: a recipient who has already received {policy.frequencyMax} marketing messages in this window is held by the canonical eligibility policy, not discarded.</p></section><section className="panel settings-card"><div className="panel-heading"><div><h2>Quiet hours and timezone fallback</h2><p className="panel-subtitle">Messages that become eligible during quiet hours are postponed, not discarded.</p></div></div><div className="form-grid"><label>Start hour (0–23)<input type="number" min={0} max={23} value={policy.quietHours?.startHour??""} onChange={event=>setPolicy({...policy,quietHours:{startHour:Number(event.target.value),endHour:policy.quietHours?.endHour??8}})}/></label><label>End hour (0–23)<input type="number" min={0} max={23} value={policy.quietHours?.endHour??""} onChange={event=>setPolicy({...policy,quietHours:{startHour:policy.quietHours?.startHour??20,endHour:Number(event.target.value)}})}/></label></div><div className="settings-callout"><strong>Preferred timezone source: profile timezone when reliable</strong><p>Fallback: workspace timezone. This is the exact same fallback used by final send-time policy evaluation.</p></div></section><section className="panel settings-card"><div className="panel-heading"><div><h2>Warming ceiling</h2><p className="panel-subtitle">A workspace safety ceiling, enforced before provider submission.</p></div></div><label>Maximum messages per day (optional)<input type="number" min={1} value={policy.warmingDailyLimit??""} onChange={event=>setPolicy({...policy,warmingDailyLimit:event.target.value?Number(event.target.value):undefined})}/></label><p className="settings-note">Raising this safety control requires the operations permission and is audited. Detailed domain authentication stays in Deliverability.</p></section><ActionState error={error} success={success}/><div className="settings-actions"><button className="button-primary" disabled={saving}>{saving?"Saving…":"Save send policy"}</button></div></form>;
}

function Keys({workspaceId}:{workspaceId:string}){
  const [items,setItems]=useState<ApiKey[]>([]),[name,setName]=useState(""),[selected,setSelected]=useState<string[]>(["events.write"]),[expiry,setExpiry]=useState(""),[secret,setSecret]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  async function load(){setLoading(true);try{const result=await phase1Api<{items:ApiKey[]}>(`/api/v1/workspaces/${workspaceId}/api-keys`);setItems(result.items);setError("")}catch(cause){setError(requestError(cause))}finally{setLoading(false)}} useEffect(()=>{void load()},[workspaceId]);
  async function create(event:FormEvent){event.preventDefault();setError("");setSecret("");try{const result=await phase1Api<{secret:string}>(`/api/v1/workspaces/${workspaceId}/api-keys`,{method:"POST",body:JSON.stringify({name,scopes:selected,expiresAt:expiry||undefined})});setSecret(result.secret);setName("");await load()}catch(cause){setError(requestError(cause))}}
  async function revoke(item:ApiKey){if(!window.confirm(`Revoke ${item.name}? Requests using this credential will fail immediately.`))return;try{await phase1Api(`/api/v1/workspaces/${workspaceId}/api-keys/${item.id}`,{method:"DELETE"});setSecret("");await load()}catch(cause){setError(requestError(cause))}}
  if(loading)return <LoadState error={error}/>;
  return <div className="settings-stack"><section className="panel settings-card"><div className="panel-heading"><div><h2>Create API key</h2><p className="panel-subtitle">Secrets are generated with high entropy, stored only as keyed hashes, and shown once.</p></div></div><form onSubmit={create}><div className="form-grid"><label>Name<input value={name} onChange={event=>setName(event.target.value)} required maxLength={100}/></label><label>Expiry (optional)<input type="datetime-local" value={expiry} onChange={event=>setExpiry(event.target.value)}/></label></div><fieldset className="settings-fieldset"><legend>Scopes</legend>{scopes.map(scope=><label key={scope} className="check-label"><input type="checkbox" checked={selected.includes(scope)} onChange={event=>setSelected(event.target.checked?[...selected,scope]:selected.filter(item=>item!==scope))}/>{scope}</label>)}</fieldset><button className="button-primary" disabled={!name.trim()||!selected.length}>Create key</button></form>{secret&&<div className="settings-secret" role="status"><strong>Copy this secret now — it will not be shown again.</strong><code>{secret}</code><button className="button-secondary" type="button" onClick={()=>void navigator.clipboard.writeText(secret)}>Copy secret</button></div>}</section><ActionState error={error}/><section className="panel table-panel"><div className="settings-table-heading"><div><h2>API keys</h2><p>Revocation is immediate and audit history never exposes a secret.</p></div></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Prefix</th><th>Scopes</th><th>Creator / created</th><th>Last used</th><th>Expiry</th><th>State</th><th/></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td><code>{item.prefix}…</code></td><td>{item.scopes.join(", ")}</td><td>{formatTime(item.createdAt)}</td><td>{formatTime(item.lastUsedAt)}</td><td>{formatTime(item.expiresAt)}</td><td>{badge(item.revokedAt?"revoked":"active")}</td><td>{!item.revokedAt&&<button className="button-secondary small-button" onClick={()=>void revoke(item)}>Revoke</button>}</td></tr>)}</tbody></table></div>{!items.length&&<Empty title="No API keys" text="Create a scoped credential only for an integration that needs event API access."/>}</section></div>;
}

function Audits({workspaceId}:{workspaceId:string}){
  const [items,setItems]=useState<Audit[]>([]),[error,setError]=useState(""),[action,setAction]=useState(""),[risk,setRisk]=useState(""),[actor,setActor]=useState("");
  async function load(){try{const search=new URLSearchParams();if(action)search.set("action",action);if(risk)search.set("riskLevel",risk);if(actor)search.set("actor",actor);const result=await phase1Api<{items:Audit[]}>(`/api/v1/workspaces/${workspaceId}/audit?${search}`);setItems(result.items);setError("")}catch(cause){setError(requestError(cause))}}useEffect(()=>{void load()},[workspaceId]);
  return <div className="settings-stack"><section className="panel settings-card"><div className="panel-heading"><div><h2>Audit filters</h2><p className="panel-subtitle">Audit records are append-oriented and sensitive fields are redacted.</p></div></div><form className="inline-form" onSubmit={event=>{event.preventDefault();void load()}}><label>Actor ID<input value={actor} onChange={event=>setActor(event.target.value)} placeholder="Any actor"/></label><label>Action<input value={action} onChange={event=>setAction(event.target.value)} placeholder="e.g. api_key.revoked"/></label><label>Risk<select value={risk} onChange={event=>setRisk(event.target.value)}><option value="">Any risk</option><option>low</option><option>medium</option><option>high</option></select></label><button className="button-secondary">Apply</button></form></section><ActionState error={error}/><section className="panel table-panel"><div className="settings-table-heading"><div><h2>Audit events</h2><p>Request and correlation identifiers are available for support investigation.</p></div><span>{items.length} events</span></div><div className="table-wrap"><table><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Object</th><th>Risk</th><th>Correlation</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{formatTime(item.occurredAt)}</td><td>{item.actorId??item.actorType}</td><td><strong>{item.action}</strong></td><td>{item.objectType}{item.objectId?` · ${item.objectId}`:""}</td><td>{badge(item.riskLevel)}</td><td><code>{item.correlationId??"—"}</code></td></tr>)}</tbody></table></div>{!items.length&&<Empty title="No matching audit events" text="Change filters or make an administrative change to create an auditable event."/>}</section></div>;
}

function DangerousActions({workspaceId}:{workspaceId:string}){
  const [data,setData]=useState<Dangerous|null>(null),[target,setTarget]=useState(""),[confirmation,setConfirmation]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState("");
  async function load(){try{const result=await phase1Api<Dangerous>(`/api/v1/workspaces/${workspaceId}/dangerous-actions`);setData(result);setError("")}catch(cause){setError(requestError(cause))}}useEffect(()=>{void load()},[workspaceId]);
  async function transfer(event:FormEvent){event.preventDefault();try{await phase1Api(`/api/v1/workspaces/${workspaceId}/ownership-transfer`,{method:"POST",body:JSON.stringify({targetMemberId:target})});setSuccess("Ownership transferred. The former owner is now an admin; the action is in the audit log.");await load()}catch(cause){setError(requestError(cause))}}
  async function requestDeletion(event:FormEvent){event.preventDefault();try{await phase1Api(`/api/v1/workspaces/${workspaceId}/deletion-request`,{method:"POST",body:JSON.stringify({confirmation})});setSuccess("Controlled deletion requested. Sending has been placed on hold.");await load()}catch(cause){setError(requestError(cause))}}
  if(!data)return <LoadState error={error}/>;
  const candidateOwners=data.members.filter(member=>member.id!==data.member.id);
  return <div className="settings-stack"><div className="settings-danger-banner"><strong>High-risk changes</strong><p>These actions affect workspace governance and production behavior. Every request is server-authorized and audited.</p></div><ActionState error={error} success={success}/><section className="panel settings-card"><div className="panel-heading"><div><h2>Transfer workspace ownership</h2><p className="panel-subtitle">The recipient must be an active workspace member. The workspace is never left without an owner.</p></div>{badge(data.member.role)}</div>{data.canTransfer?<form onSubmit={transfer}><label>New owner<select value={target} onChange={event=>setTarget(event.target.value)} required><option value="">Choose an active member</option>{candidateOwners.map(owner=><option key={owner.id} value={owner.id}>{owner.email??owner.userId} · {owner.role}</option>)}</select></label><button className="button-secondary" disabled={!target}>Transfer ownership</button></form>:<p className="settings-note">Only the current workspace owner can transfer ownership.</p>}</section><section className="panel settings-card danger-card"><div className="panel-heading"><div><h2>Request controlled workspace deletion</h2><p className="panel-subtitle">This does not directly delete records. It begins the governed retention and privacy workflow and stops normal production behavior.</p></div></div>{data.canDelete?<form onSubmit={requestDeletion}><label>Type <strong>{data.workspace.name}</strong> to confirm<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off"/></label><button className="button-danger" disabled={confirmation!==data.workspace.name}>Request controlled deletion</button></form>:<p className="settings-note">Only the owner with workspace deletion authority can request this action.</p>}</section></div>;
}

function ActionState({error,success}:{error?:string;success?:string}){return <>{error&&<div role="alert">{error}</div>}{success&&<p className="settings-success" role="status">{success}</p>}</>}
function LoadState({error}:{error:string}){return error?<div role="alert">{error}</div>:<div className="settings-loading"><span className="skeleton skeleton-title"/><span className="skeleton skeleton-card"/></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><strong>{title}</strong><p>{text}</p></div>}
