import { PrismaClient } from '@prisma/client';
import { PrismaPhase3Repository } from '../../../packages/persistence/src/prisma/phase3-repository.js';
import { Phase3RuntimeService } from '../../../packages/application/src/phase3/phase3-runtime-service.js';
import { PrismaFlowRuleEvaluationPort,PrismaPhase2FlowMessagePort } from '../../../packages/persistence/src/prisma/phase3-runtime-adapters.js';
import { Phase3JobQueue } from '../../../packages/queue/src/bullmq/phase3-job-queue.js';
import { Phase2JobQueue } from '../../../packages/queue/src/bullmq/phase2-job-queue.js';
const redisUrl=process.env.REDIS_URL;if(!redisUrl)throw new Error('REDIS_URL_REQUIRED');const db=new PrismaClient(),repo=new PrismaPhase3Repository(db),runtime=new Phase3RuntimeService(repo,new PrismaPhase2FlowMessagePort(db),new PrismaFlowRuleEvaluationPort(db)),queue=new Phase3JobQueue(redisUrl),phase2Queue=new Phase2JobQueue(redisUrl),once=process.argv.includes('--once');
async function dispatchOutbox(){const rows=await (db as any).outboxEvent.findMany({where:{publishedAt:null,eventType:{in:['phase3.event.accepted','phase3.audience.list.entered','phase3.audience.segment.entered','phase2.message.policy']}},orderBy:{createdAt:'asc'},take:200});let n=0;for(const o of rows){try{const payload=o.payloadJson as any;if(o.eventType==='phase2.message.policy')await phase2Queue.enqueue({type:'phase2.message.policy',workspaceId:o.workspaceId,messageId:String(payload?.messageId??o.aggregateId)});else if(o.eventType==='phase3.event.accepted')await queue.enqueue({type:'phase3.event.route',workspaceId:o.workspaceId,eventId:String(payload?.eventId??o.aggregateId)});else await queue.enqueue({type:'phase3.audience.transition',workspaceId:o.workspaceId,transitionId:String(payload?.transitionId??payload?.membershipId??o.aggregateId),audienceType:o.eventType.includes('.list.')?'list':'segment'});await (db as any).outboxEvent.update({where:{id:o.id},data:{publishedAt:new Date(),attemptCount:{increment:1},lastError:null}});n++}catch(e){await (db as any).outboxEvent.update({where:{id:o.id},data:{attemptCount:{increment:1},lastError:e instanceof Error?e.message:String(e)}})}}return n}
async function claimDueDateSchedules(now:Date){return (db as any).$transaction(async(tx:any)=>{const rows:any[]=await tx.$queryRawUnsafe(`SELECT * FROM "flow_date_trigger_schedule" WHERE "state"='pending' AND "due_at" <= $1 ORDER BY "due_at" ASC FOR UPDATE SKIP LOCKED LIMIT 200`,now);if(!rows.length)return [];const ids=rows.map(row=>row.id);await tx.flowDateTriggerSchedule.updateMany({where:{id:{in:ids}},data:{state:'leased',leaseOwner:`scheduler:${process.pid}`,leaseExpiresAt:new Date(now.getTime()+30000)}});return rows})}
async function releaseExpiredDateScheduleLeases(now:Date){return (db as any).flowDateTriggerSchedule.updateMany({where:{state:'leased',leaseExpiresAt:{lte:now}},data:{state:'pending',leaseOwner:null,leaseExpiresAt:null}})}
async function tick(){const now=new Date();await releaseExpiredDateScheduleLeases(now);const [actions,dateSchedules]=await Promise.all([runtime.dispatchDue({now,leaseOwner:`scheduler:${process.pid}`,leaseMs:30000,limit:200}),claimDueDateSchedules(now)]);for(const a of actions)await queue.enqueue({type:'phase3.flow.execute',workspaceId:a.workspaceId,actionId:a.id});for(const schedule of dateSchedules)await queue.enqueue({type:'phase3.date.route',workspaceId:schedule.workspace_id,scheduleId:schedule.id});const events=await dispatchOutbox();console.log(JSON.stringify({event:'phase3.scheduler.tick',claimedActions:actions.length,claimedDateSchedules:dateSchedules.length,dispatchedEvents:events}))}
if(once){await tick();await queue.close();await phase2Queue.close();await db.$disconnect();process.exit(0)}const timer=setInterval(()=>void tick().catch(e=>console.error(e)),1000);await tick();for(const sig of ['SIGINT','SIGTERM'] as const)process.on(sig,async()=>{clearInterval(timer);await queue.close();await phase2Queue.close();await db.$disconnect();process.exit(0)});
