import test from "node:test";
import assert from "node:assert/strict";
import { Phase1Platform } from "../packages/application/src/phase1/in-memory-platform.js";

function setup(){const p=new Phase1Platform();const w=p.createWorkspace({userId:"owner",email:"owner@example.com"},{name:"Brand",legalName:"Brand Ltd",businessAddress:"1 Street",timezone:"UTC",locale:"en"});return {p,w}}

test("invitation is tokenized, email-bound, expiring, and accepted once",()=>{const {p,w}=setup();const inv=p.invite(w.id,"owner","marketer@example.com","marketer",1);assert.throws(()=>p.acceptInvitation(inv.token,"u1","wrong@example.com"),/INVITATION_EMAIL_MISMATCH/);const m=p.acceptInvitation(inv.token,"u1","marketer@example.com");assert.equal(m.status,"active");assert.throws(()=>p.acceptInvitation(inv.token,"u2","marketer@example.com"),/INVITATION_INVALID/)});
test("last owner cannot be demoted",()=>{const {p,w}=setup();const owner=p.listMembers(w.id,"owner")[0]!;assert.throws(()=>p.updateMemberRole(w.id,"owner",owner.id,"admin"),/LAST_OWNER_PROTECTED/)});
test("workspace updates use optimistic concurrency",()=>{const {p,w}=setup();p.updateWorkspace(w.id,"owner",{name:"One",expectedRowVersion:1});assert.throws(()=>p.updateWorkspace(w.id,"owner",{name:"Two",expectedRowVersion:1}),/CONCURRENCY_CONFLICT/)});
test("profile pagination cursor is bounded and stable",()=>{const {p,w}=setup();for(let i=0;i<6;i++)p.upsertProfile(w.id,"owner",{email:`p${i}@example.com`,source:"test"});const one=p.pageProfiles(w.id,"owner",{limit:2});assert.equal(one.items.length,2);assert.ok(one.nextCursor);const two=p.pageProfiles(w.id,"owner",{limit:2,cursor:one.nextCursor});assert.equal(two.items.length,2);assert.notEqual(two.items[0]!.id,one.items[0]!.id)});
test("profile timeline includes consent and suppression evidence",()=>{const {p,w}=setup();const x=p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"manual"});p.recordConsent(w.id,"owner",x.id,"granted","form");p.suppress(w.id,"owner",x.id,"manual");const kinds=p.profileTimeline(w.id,"owner",x.id).map(x=>x.kind);assert.ok(kinds.includes("consent"));assert.ok(kinds.includes("suppression"))});
test("list remove preserves provenance and archive prevents new membership",()=>{const {p,w}=setup();const x=p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"manual"});const l=p.createList(w.id,"owner","List");const m=p.addToList(w.id,"owner",l.id,x.id,"api","src1");assert.equal(m.source,"api");p.removeFromList(w.id,"owner",l.id,x.id);assert.equal(m.state,"left");p.archiveList(w.id,"owner",l.id);assert.throws(()=>p.addToList(w.id,"owner",l.id,x.id),/LIST_ARCHIVED/)});
test("subscription projection follows latest consent record",()=>{const {p,w}=setup();const x=p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"manual"});p.recordConsent(w.id,"owner",x.id,"granted","form","2026-01-01T00:00:00Z");p.recordConsent(w.id,"owner",x.id,"withdrawn","unsubscribe","2026-02-01T00:00:00Z");assert.equal(p.eligibility(w.id,"owner",x.id).code,"NO_MARKETING_CONSENT")});
test("protected suppression cannot be manually revoked",()=>{const {p,w}=setup();const x=p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"manual"});const s=p.suppress(w.id,"owner",x.id,"complaint","provider");assert.throws(()=>p.revokeSuppression(w.id,"owner",s.id),/PROTECTED_SUPPRESSION/)});
test("temporary manual suppression can expire",()=>{const {p,w}=setup();const x=p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"manual"});p.recordConsent(w.id,"owner",x.id,"granted","form");p.suppress(w.id,"owner",x.id,"manual","manual",new Date(Date.now()-1000).toISOString());assert.equal(p.eligibility(w.id,"owner",x.id).eligible,true)});
test("staged import requires mapping and consent evidence",()=>{const {p,w}=setup();const j=p.createImport(w.id,"owner",{fileName:"a.csv",csv:"email\na@example.com"});assert.throws(()=>p.validateImport(w.id,"owner",j.id),/IMPORT_MAPPING_REQUIRED/);assert.throws(()=>p.setImportMapping(w.id,"owner",j.id,{email:"email"},{source:"crm",upsert:true,blankPolicy:"ignore",consent:{status:"granted",source:"crm"}}),/CONSENT_EVIDENCE_REQUIRED/)});
test("staged import validates, commits, records results, and is idempotent",()=>{const {p,w}=setup();const j=p.createImport(w.id,"owner",{fileName:"a.csv",csv:"email,first_name\na@example.com,Ada\nbad,Bad"});p.setImportMapping(w.id,"owner",j.id,{email:"email",firstName:"first_name"},{source:"crm",upsert:true,blankPolicy:"ignore"});p.validateImport(w.id,"owner",j.id);const done=p.commitStagedImport(w.id,"owner",j.id);assert.equal(done.state,"completed_with_errors");assert.equal(p.listProfiles(w.id,"owner").length,1);assert.equal(p.commitStagedImport(w.id,"owner",j.id).id,j.id)});
test("import rollback never removes consent added by import",()=>{const {p,w}=setup();const j=p.createImport(w.id,"owner",{fileName:"a.csv",csv:"email\na@example.com"});p.setImportMapping(w.id,"owner",j.id,{email:"email"},{source:"crm",upsert:true,blankPolicy:"ignore",consent:{status:"granted",source:"crm",evidenceNote:"CRM opt-in export"}});p.validateImport(w.id,"owner",j.id);p.commitStagedImport(w.id,"owner",j.id);const id=j.rows.find(r=>r.profileId)?.profileId!;p.rollbackImport(w.id,"owner",j.id);assert.equal(p.listConsent(w.id,"owner",id).length,1)});
test("export supports selected scope and arbitrary approved fields",()=>{const {p,w}=setup();const a=p.upsertProfile(w.id,"owner",{email:"a@example.com",firstName:"A",source:"m"});p.upsertProfile(w.id,"owner",{email:"b@example.com",firstName:"B",source:"m"});const e=p.createExport(w.id,"owner",60,["email","first_name"],[a.id]);const csv=p.downloadExport(w.id,e.id,e.token);assert.match(csv,/a@example.com/);assert.doesNotMatch(csv,/b@example.com/)});
test("domain normalization rejects malformed values",()=>{const {p,w}=setup();assert.throws(()=>p.createDomain(w.id,"owner","http://example.com"),/URL_USED_INSTEAD_OF_DOMAIN/);assert.equal(p.createDomain(w.id,"owner","EXAMPLE.COM.").domain,"example.com")});
test("readiness exposes individual blockers rather than one opaque flag",()=>{const {p,w}=setup();const r=p.readiness(w.id,"owner",{feedbackReady:false,unsubscribeReady:false});assert.equal(r.ready,false);assert.ok(r.checks.some(c=>c.key==="feedback"&&!c.passed));assert.ok(r.checks.some(c=>c.key==="unsubscribe"&&!c.passed))});
test("audit log is permission-gated and records high-risk operations",()=>{const {p,w}=setup();const inv=p.invite(w.id,"owner","analyst@example.com","analyst");p.acceptInvitation(inv.token,"analyst","analyst@example.com");const entries=p.listAudit(w.id,"analyst");assert.ok(entries.some(a=>a.action==="member.invite"&&a.riskLevel==="medium"))});
