import test from "node:test";
import assert from "node:assert/strict";
import { Phase1Platform } from "../packages/application/src/phase1/in-memory-platform.js";
import { hasPermission } from "../packages/domain/src/phase1/permissions.js";
import { previewCsv } from "../packages/domain/src/phase1/csv.js";

function setup(){const p=new Phase1Platform();const w=p.createWorkspace({userId:"owner",email:"owner@example.com"},{name:"A",legalName:"A Ltd",businessAddress:"1 Street",timezone:"UTC",locale:"en"});return {p,w}}

test("role permissions keep export and suppression privileged",()=>{assert.equal(hasPermission("marketer","profiles.export"),false);assert.equal(hasPermission("marketer","suppressions.manage"),false);assert.equal(hasPermission("owner","profiles.export"),true)});
test("cross-workspace profile reads fail closed",()=>{const {p,w}=setup();const w2=p.createWorkspace({userId:"other",email:"other@example.com"},{name:"B",legalName:"B Ltd",businessAddress:"2 Street",timezone:"UTC",locale:"en"});p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"manual"});assert.throws(()=>p.listProfiles(w.id,"other"),/WORKSPACE_ACCESS_DENIED/);assert.equal(p.listProfiles(w2.id,"other").length,0)});
test("email normalization preserves local part while normalizing domain",()=>{const {p,w}=setup();const a=p.upsertProfile(w.id,"owner",{email:"A.B+tag@EXAMPLE.COM",source:"manual"});const b=p.upsertProfile(w.id,"owner",{email:"A.B+tag@example.com",source:"manual"});assert.equal(a.id,b.id)});
test("upsert restores a soft-deleted profile instead of failing on duplicate email",()=>{const {p,w}=setup();const original=p.upsertProfile(w.id,"owner",{email:"deleted@example.com",source:"manual",firstName:"Before"});original.deletedAt=new Date().toISOString();const restored=p.upsertProfile(w.id,"owner",{email:"deleted@example.com",source:"manual",firstName:"After"});assert.equal(restored.id,original.id);assert.equal(restored.firstName,"After");assert.equal(restored.deletedAt,undefined);assert.equal(p.listProfiles(w.id,"owner").length,1)});
test("typed custom properties reject type conflicts",()=>{const {p,w}=setup();p.defineProperty(w.id,"owner","score","Score","number");assert.throws(()=>p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"manual",properties:{score:"high"}}),/PROPERTY_TYPE_CONFLICT/)});
test("list membership never creates consent",()=>{const {p,w}=setup();const profile=p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"manual"});const list=p.createList(w.id,"owner","Newsletter");p.addToList(w.id,"owner",list.id,profile.id);assert.equal(p.eligibility(w.id,"owner",profile.id).code,"NO_MARKETING_CONSENT")});
test("granted consent permits eligibility until a protected suppression exists",()=>{const {p,w}=setup();const profile=p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"manual"});p.recordConsent(w.id,"owner",profile.id,"granted","signup_form");assert.equal(p.eligibility(w.id,"owner",profile.id).eligible,true);p.suppress(w.id,"owner",profile.id,"complaint","provider");assert.equal(p.eligibility(w.id,"owner",profile.id).code,"SUPPRESSED_COMPLAINT")});
test("CSV preview rejects duplicate headings and flags duplicate rows",()=>{assert.throws(()=>previewCsv("email,email\na@example.com,a@example.com"),/DUPLICATE_HEADERS/);const p=previewCsv("email\na@example.com\na@example.com");assert.equal(p.totals.duplicateInFile,1)});
test("re-import with identical mutation policy is idempotent",()=>{const {p,w}=setup();const csv="email,first_name\na@example.com,Ada\nb@example.com,Bob";const one=p.commitImport(w.id,"owner",csv,{source:"source1"});const two=p.commitImport(w.id,"owner",csv,{source:"source1"});assert.equal(one.id,two.id);assert.equal(p.listProfiles(w.id,"owner").length,2)});
test("profile merge preserves consent suppression and list provenance",()=>{const {p,w}=setup();const a=p.upsertProfile(w.id,"owner",{email:"a@example.com",source:"one"});const b=p.upsertProfile(w.id,"owner",{email:"b@example.com",source:"two"});const l=p.createList(w.id,"owner","VIP");p.addToList(w.id,"owner",l.id,b.id,"import:test");p.recordConsent(w.id,"owner",b.id,"granted","form");p.suppress(w.id,"owner",b.id,"hard_bounce","provider");p.mergeProfiles(w.id,"owner",a.id,b.id);assert.equal(p.eligibility(w.id,"owner",a.id).code,"SUPPRESSED_HARD_BOUNCE");assert.ok(p.memberships.some(m=>m.profileId===a.id&&m.listId===l.id&&m.source==="import:test"))});
test("export is workspace scoped, formula-safe, permission protected and expires",()=>{const {p,w}=setup();p.upsertProfile(w.id,"owner",{email:"=cmd@example.com",firstName:"+Formula",source:"manual"});const j=p.createExport(w.id,"owner",1);assert.match(p.downloadExport(w.id,j.id,j.token),/'\+Formula/);assert.throws(()=>p.downloadExport("00000000-0000-0000-0000-000000000000",j.id,j.token),/EXPORT_NOT_FOUND/);assert.throws(()=>p.downloadExport(w.id,j.id,j.token,new Date(Date.now()+2000)),/EXPORT_EXPIRED/)});
test("sender identity requires a verified matching domain",()=>{const {p,w}=setup();const d=p.createDomain(w.id,"owner","example.com");assert.throws(()=>p.createSenderIdentity(w.id,"owner",{domainId:d.id,fromName:"Brand",fromEmail:"hello@example.com",replyTo:"reply@example.com"}),/DOMAIN_NOT_VERIFIED/);p.markDomainVerified(w.id,"owner",d.id,{dkim:"ok"});const i=p.createSenderIdentity(w.id,"owner",{domainId:d.id,fromName:"Brand",fromEmail:"hello@example.com",replyTo:"reply@example.com"});assert.equal(i.fromEmail,"hello@example.com")});
test("a workspace keeps one current sending domain",()=>{const {p,w}=setup();const first=p.createDomain(w.id,"owner","example.com");assert.equal(p.createDomain(w.id,"owner","example.com").id,first.id);assert.throws(()=>p.createDomain(w.id,"owner","second-example.com"),/WORKSPACE_SENDING_DOMAIN_EXISTS/)});
test("CSV validation honors the selected Email Address mapping",()=>{const preview=previewCsv("Email Address,Country\na@example.com,GB","Email Address");assert.equal(preview.totals.valid,1);assert.equal(preview.rows[0]?.email,"a@example.com")});
test("readiness requires operational evidence beyond sender foundation",()=>{const {p,w}=setup();assert.equal(p.readiness(w.id,"owner").ready,false);const d=p.createDomain(w.id,"owner","example.com");p.markDomainVerified(w.id,"owner",d.id,{dkim:"ok"});p.createSenderIdentity(w.id,"owner",{domainId:d.id,fromName:"Brand",fromEmail:"hello@example.com",replyTo:"reply@example.com"});assert.equal(p.readiness(w.id,"owner").ready,false);assert.equal(p.readiness(w.id,"owner",{feedbackReady:true,unsubscribeReady:true,profilesReady:true,emailReady:true,testSendReady:true,flowReady:true}).ready,true)});
