import test from "node:test";
import assert from "node:assert/strict";
import { Phase2ContentService } from "../packages/application/src/phase2/content-service.js";
import { ensureComplianceFooter, validateStructuredDocument, type EmailDraft, type StructuredEmailDocument } from "../packages/domain/src/phase2/content.js";
import { runPreflight } from "../packages/domain/src/phase2/preflight.js";
import { compileStructuredDraft, resolveTemplate } from "../packages/email-renderer/src/phase2-structured.js";
import { buildImportedHtmlDocument } from "../frontend/src/lib/template-document-utils.js";

const actor={userId:"owner",workspaceId:"ws1"};
const ctx={senderDomainReady:true,workspaceBusinessAddress:"1 Street",allowHtmlMode:false};
const renderCtx={profile:{first_name:"Ada"},workspace:{business_name:"Brand",business_address:"1 Street"},system:{unsubscribe_url:"https://example.com/u",preferences_url:"https://example.com/p"}};
function ready(){const s=new Phase2ContentService();const d=s.createEmail(actor,{internalName:"Welcome"});return {s,d:s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,subject:"Welcome {{ profile.first_name | default: \"there\" }}",preheader:"A quick hello",senderIdentityId:"sender1",replyTo:"reply@example.com",plainText:"A message for you."})}}

test("structured documents always retain one locked compliance footer",()=>{const doc=ensureComplianceFooter({schemaVersion:1,blocks:[{id:"x",type:"text",text:"Hi"}]});assert.equal(doc.blocks.filter(b=>b.type==="compliance_footer").length,1);assert.equal((doc.blocks.find(b=>b.type==="compliance_footer") as any).locked,true)});
test("compliance footer stays last and retains its design when a document is normalized",()=>{const doc=ensureComplianceFooter({schemaVersion:1,blocks:[{id:"compliance",type:"compliance_footer",locked:true,logoWidth:96},{id:"text",type:"text",text:"Hello"},{id:"duplicate",type:"compliance_footer",locked:true}]});assert.equal(doc.blocks.length,2);assert.equal(doc.blocks.at(-1)?.type,"compliance_footer");assert.equal((doc.blocks.at(-1) as any).logoWidth,96)});
test("branded footer renders logo, socials, address and signed unsubscribe without leaking HTML",()=>{const {d}=ready();const document:StructuredEmailDocument={schemaVersion:1,blocks:[{id:"body",type:"text",text:"Hello"},{id:"compliance",type:"compliance_footer",locked:true,logoUrl:"https://media.example.com/logo.png",logoWidth:92,logoAlign:"left",socialLinks:[{platform:"Instagram",url:"https://instagram.com/example"}],addressMode:"custom",customAddress:"12 Main St <Suite>"}]};const compiled=compileStructuredDraft({...d,structuredDocument:document,plainTextMode:"manual",plainText:"Hello"});const html=resolveTemplate(compiled.htmlTemplate,renderCtx,true);const text=resolveTemplate(compiled.textTemplate,renderCtx,false);assert.match(html,/logo\.png/);assert.match(html,/width="92"/);assert.match(html,/instagram\.com\/example/);assert.match(html,/12 Main St &lt;Suite&gt;/);assert.match(html,/href="https:\/\/example\.com\/u"/);assert.match(text,/Unsubscribe: https:\/\/example\.com\/u/);assert.equal((html.match(/>Unsubscribe</g)??[]).length,1)});
test("footer rejects unsafe image and social URLs",()=>{const document:StructuredEmailDocument={schemaVersion:1,blocks:[{id:"compliance",type:"compliance_footer",locked:true,logoUrl:"javascript:alert(1)",socialLinks:[{platform:"X",url:"http://example.com"}]}]};const codes=validateStructuredDocument(document).map(issue=>issue.code);assert.ok(codes.includes("FOOTER_LOGO_URL_INVALID"));assert.ok(codes.includes("FOOTER_SOCIAL_LINK_INVALID"))});
test("footer supports hosted social icon images and rejects unsafe sources",()=>{const {d}=ready();const document:StructuredEmailDocument={schemaVersion:1,blocks:[{id:"body",type:"text",text:"Hello"},{id:"footer",type:"compliance_footer",locked:true,socialLinks:[{platform:"Instagram",url:"https://example.com/social",iconUrl:"https://example.com/instagram.png"}]}]};assert.match(compileStructuredDraft({...d,structuredDocument:document}).htmlTemplate,/instagram\.png/);const unsafe=structuredClone(document);const footer=unsafe.blocks[1];if(footer?.type==="compliance_footer")footer.socialLinks![0]!.iconUrl="data:image/svg+xml,bad";assert.ok(validateStructuredDocument(unsafe).some(issue=>issue.code==="FOOTER_SOCIAL_LINK_INVALID"));});
test("editing imported HTML keeps the configured footer",()=>{const original:StructuredEmailDocument={schemaVersion:1,blocks:[{id:"old",type:"custom_html",html:"<p>Old</p>"},{id:"footer",type:"compliance_footer",locked:true,logoUrl:"https://example.com/logo.png",addressMode:"custom",customAddress:"12 Main Street",socialLinks:[{platform:"X",url:"https://example.com/social"}]}]};const updated=buildImportedHtmlDocument("<p>New</p>",original);assert.equal(updated.blocks[0]?.type,"custom_html");assert.equal(updated.blocks[1]?.type,"compliance_footer");assert.deepEqual(updated.blocks[1],original.blocks[1]);});
test("full imported HTML keeps its document shape and places the footer inside body",()=>{const {d}=ready();const html="<!doctype html><html><body><main><p>Original</p></main></body></html>";const draft={...d,structuredDocument:buildImportedHtmlDocument(html)};const rendered=compileStructuredDraft(draft).htmlTemplate;assert.match(rendered,/<main><p>Original<\/p><\/main>/);assert.ok(rendered.indexOf("Unsubscribe")<rendered.indexOf("</body>"));assert.equal((rendered.match(/<html>/g)??[]).length,1);assert.doesNotMatch(rendered,/<div data-custom-html=/);});
test("manual plain text always contains the legal footer even when unsubscribe was typed already",()=>{const {d}=ready();const draft={...d,structuredDocument:{schemaVersion:1 as const,blocks:[{id:"body",type:"text" as const,text:"Hello"},{id:"footer",type:"compliance_footer" as const,locked:true as const,customAddress:"12 Main Street",addressMode:"custom" as const}]},plainTextMode:"manual" as const,plainText:"Hello\nUnsubscribe: {{ system.unsubscribe_url }}"};const text=resolveTemplate(compileStructuredDraft(draft).textTemplate,renderCtx,false);assert.match(text,/Brand · 12 Main Street/);assert.equal((text.match(/Unsubscribe:/g)??[]).length,1);});
test("preflight blocks profile variables without a fallback",()=>{const {s,d}=ready();const bad=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,subject:"Hi {{ profile.first_name }}"});const pf=s.preflight(actor,bad.id,ctx);assert.equal(pf.ok,false);assert.ok(pf.issues.some(x=>x.code==="VARIABLE_FALLBACK_REQUIRED"))});
test("preflight blocks unsafe image URLs",()=>{const {s,d}=ready();const blocks=[...d.structuredDocument.blocks];blocks.splice(1,0,{id:"img",type:"image",src:"http://example.com/a.png",alt:"A"} as any);const next=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,structuredDocument:{schemaVersion:1,blocks}});assert.ok(s.preflight(actor,next.id,ctx).issues.some(x=>x.code==="IMAGE_URL_UNSAFE"))});
test("structured compiler escapes author content",()=>{const {s,d}=ready();const blocks=[{id:"t",type:"text",text:"<script>alert(1)</script>"},{id:"compliance",type:"compliance_footer",locked:true}] as any;const next=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,structuredDocument:{schemaVersion:1,blocks}});const c=compileStructuredDraft(next);assert.doesNotMatch(c.htmlTemplate,/<script>/);assert.match(c.htmlTemplate,/&lt;script&gt;/)});
test("structured compiler renders header, footer, and responsive-safe columns",()=>{const {s,d}=ready();const document:StructuredEmailDocument={schemaVersion:1,blocks:[{id:"header",type:"header",text:"Vela",align:"center"},{id:"columns",type:"columns",columns:[{id:"left",blocks:[{id:"left-text",type:"text",text:"Left column"}]},{id:"right",blocks:[{id:"right-text",type:"text",text:"Right column"}]}]},{id:"footer",type:"footer",text:"See you soon"},{id:"compliance",type:"compliance_footer",locked:true}]};const next=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,structuredDocument:document,plainTextMode:"auto"});const compiled=compileStructuredDraft(next);assert.match(compiled.htmlTemplate,/role="presentation"/);assert.match(compiled.htmlTemplate,/Left column/);assert.match(compiled.htmlTemplate,/See you soon/);assert.match(compiled.textTemplate,/Right column/)});
test("preview resolves safe variables and labels its sample source",()=>{const {s,d}=ready();const p=s.preview(actor,d.id,ctx,renderCtx,"profile:ada");assert.match(p.subject,/Ada/);assert.equal(p.sampleSource,"profile:ada");assert.match(p.html,/Unsubscribe/)});
test("publishing creates immutable increasing versions",()=>{const {s,d}=ready();const v1=s.publish(actor,d.id,ctx);const changed=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,subject:"Second"});const v2=s.publish(actor,changed.id,ctx);assert.equal(v1.versionNumber,1);assert.equal(v2.versionNumber,2);assert.notEqual(v1.contentHash,v2.contentHash);assert.equal(s.listVersions(actor,d.id)[0]!.subjectTemplate,v1.subjectTemplate)});
test("restore creates a new mutable draft without mutating version history",()=>{const {s,d}=ready();const v=s.publish(actor,d.id,ctx);const changed=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,subject:"Changed"});const restored=s.restoreVersion(actor,changed.id,v.versionNumber);assert.equal(restored.subject,v.subjectTemplate);assert.equal(s.listVersions(actor,d.id)[0]!.subjectTemplate,v.subjectTemplate)});
test("test sends are explicitly excluded from production analytics",()=>{const {s,d}=ready();const t=s.createTestSend(actor,d.id,"seed@example.com",ctx,renderCtx);assert.equal(t.kind,"test");assert.equal(t.excludedFromProductionAnalytics,true);assert.match(t.subject,/^\[TEST\]/)});
test("html/source mode remains blocked until owner decision enables it",()=>{const s=new Phase2ContentService();const d=s.createEmail(actor,{internalName:"HTML",authoringMode:"html"});const p=runPreflight(d,ctx);assert.ok(p.issues.some(i=>i.code==="HTML_MODE_DISABLED"))});
test("preflight does not claim the domain is unready before a sender is selected",()=>{const draft={id:"email-1",workspaceId:"ws1",internalName:"Welcome",subject:"Hello",preheader:"",senderIdentityId:null,replyTo:"",plainText:"Body",plainTextMode:"manual" as const,plainTextStale:false,authoringMode:"structured" as const,structuredDocument:ensureComplianceFooter({schemaVersion:1,blocks:[{id:"text",type:"text",text:"Hi"},{id:"compliance",type:"compliance_footer",locked:true}]}),htmlSource:null,trackingEnabled:true,openTrackingEnabled:false,rowVersion:1,state:"draft" as const,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null} satisfies EmailDraft;const pf=runPreflight(draft,{senderDomainReady:false,workspaceBusinessAddress:"1 Street",allowHtmlMode:false});assert.ok(pf.issues.some(i=>i.code==="MISSING_SENDER"));assert.equal(pf.issues.some(i=>i.code==="SENDER_DOMAIN_NOT_READY"),false)});
test("preflight blocks publish when the selected domain is not authenticated",()=>{const draft={id:"email-1",workspaceId:"ws1",internalName:"Welcome",subject:"Hello",preheader:"",senderIdentityId:"sender1",replyTo:"reply@example.com",plainText:"Body",plainTextMode:"manual" as const,plainTextStale:false,authoringMode:"structured" as const,structuredDocument:ensureComplianceFooter({schemaVersion:1,blocks:[{id:"text",type:"text",text:"Hi"},{id:"compliance",type:"compliance_footer",locked:true}]}),htmlSource:null,trackingEnabled:true,openTrackingEnabled:false,rowVersion:1,state:"draft" as const,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null} satisfies EmailDraft;const pf=runPreflight(draft,{senderDomainReady:false,workspaceBusinessAddress:"1 Street",allowHtmlMode:false});assert.ok(pf.issues.some(i=>i.code==="SENDER_DOMAIN_NOT_READY"))});
