import test from "node:test";
import assert from "node:assert/strict";
import { Phase2ContentService } from "../packages/application/src/phase2/content-service.js";
import { ensureComplianceFooter, type EmailDraft, type StructuredEmailDocument } from "../packages/domain/src/phase2/content.js";
import { runPreflight } from "../packages/domain/src/phase2/preflight.js";
import { compileStructuredDraft } from "../packages/email-renderer/src/phase2-structured.js";

const actor={userId:"owner",workspaceId:"ws1"};
const ctx={senderDomainReady:true,workspaceBusinessAddress:"1 Street",allowHtmlMode:false};
const renderCtx={profile:{first_name:"Ada"},workspace:{business_name:"Brand",business_address:"1 Street"},system:{unsubscribe_url:"https://example.com/u",preferences_url:"https://example.com/p"}};
function ready(){const s=new Phase2ContentService();const d=s.createEmail(actor,{internalName:"Welcome"});return {s,d:s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,subject:"Welcome {{ profile.first_name | default: \"there\" }}",preheader:"A quick hello",senderIdentityId:"sender1",replyTo:"reply@example.com",plainText:"A message for you."})}}

test("structured documents always retain one locked compliance footer",()=>{const doc=ensureComplianceFooter({schemaVersion:1,blocks:[{id:"x",type:"text",text:"Hi"}]});assert.equal(doc.blocks.filter(b=>b.type==="compliance_footer").length,1);assert.equal((doc.blocks.find(b=>b.type==="compliance_footer") as any).locked,true)});
test("preflight blocks profile variables without a fallback",()=>{const {s,d}=ready();const bad=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,subject:"Hi {{ profile.first_name }}"});const pf=s.preflight(actor,bad.id,ctx);assert.equal(pf.ok,false);assert.ok(pf.issues.some(x=>x.code==="VARIABLE_FALLBACK_REQUIRED"))});
test("preflight blocks unsafe image URLs",()=>{const {s,d}=ready();const blocks=[...d.structuredDocument.blocks];blocks.splice(1,0,{id:"img",type:"image",src:"http://example.com/a.png",alt:"A"} as any);const next=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,structuredDocument:{schemaVersion:1,blocks}});assert.ok(s.preflight(actor,next.id,ctx).issues.some(x=>x.code==="IMAGE_URL_UNSAFE"))});
test("structured compiler escapes author content",()=>{const {s,d}=ready();const blocks=[{id:"t",type:"text",text:"<script>alert(1)</script>"},{id:"compliance",type:"compliance_footer",locked:true}] as any;const next=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,structuredDocument:{schemaVersion:1,blocks}});const c=compileStructuredDraft(next);assert.doesNotMatch(c.htmlTemplate,/<script>/);assert.match(c.htmlTemplate,/&lt;script&gt;/)});
test("structured compiler renders header, footer, and responsive-safe columns",()=>{const {s,d}=ready();const document:StructuredEmailDocument={schemaVersion:1,blocks:[{id:"header",type:"header",text:"Vela",align:"center"},{id:"columns",type:"columns",columns:[{id:"left",blocks:[{id:"left-text",type:"text",text:"Left column"}]},{id:"right",blocks:[{id:"right-text",type:"text",text:"Right column"}]}]},{id:"footer",type:"footer",text:"See you soon"},{id:"compliance",type:"compliance_footer",locked:true}]};const next=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,structuredDocument:document,plainTextMode:"auto"});const compiled=compileStructuredDraft(next);assert.match(compiled.htmlTemplate,/role="presentation"/);assert.match(compiled.htmlTemplate,/Left column/);assert.match(compiled.htmlTemplate,/See you soon/);assert.match(compiled.textTemplate,/Right column/)});
test("preview resolves safe variables and labels its sample source",()=>{const {s,d}=ready();const p=s.preview(actor,d.id,ctx,renderCtx,"profile:ada");assert.match(p.subject,/Ada/);assert.equal(p.sampleSource,"profile:ada");assert.match(p.html,/Unsubscribe/)});
test("publishing creates immutable increasing versions",()=>{const {s,d}=ready();const v1=s.publish(actor,d.id,ctx);const changed=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,subject:"Second"});const v2=s.publish(actor,changed.id,ctx);assert.equal(v1.versionNumber,1);assert.equal(v2.versionNumber,2);assert.notEqual(v1.contentHash,v2.contentHash);assert.equal(s.listVersions(actor,d.id)[0]!.subjectTemplate,v1.subjectTemplate)});
test("restore creates a new mutable draft without mutating version history",()=>{const {s,d}=ready();const v=s.publish(actor,d.id,ctx);const changed=s.updateDraft(actor,d.id,{expectedRowVersion:d.rowVersion,subject:"Changed"});const restored=s.restoreVersion(actor,changed.id,v.versionNumber);assert.equal(restored.subject,v.subjectTemplate);assert.equal(s.listVersions(actor,d.id)[0]!.subjectTemplate,v.subjectTemplate)});
test("test sends are explicitly excluded from production analytics",()=>{const {s,d}=ready();const t=s.createTestSend(actor,d.id,"seed@example.com",ctx,renderCtx);assert.equal(t.kind,"test");assert.equal(t.excludedFromProductionAnalytics,true);assert.match(t.subject,/^\[TEST\]/)});
test("html/source mode remains blocked until owner decision enables it",()=>{const s=new Phase2ContentService();const d=s.createEmail(actor,{internalName:"HTML",authoringMode:"html"});const p=runPreflight(d,ctx);assert.ok(p.issues.some(i=>i.code==="HTML_MODE_DISABLED"))});
test("preflight does not claim the domain is unready before a sender is selected",()=>{const draft={id:"email-1",workspaceId:"ws1",internalName:"Welcome",subject:"Hello",preheader:"",senderIdentityId:null,replyTo:"",plainText:"Body",plainTextMode:"manual" as const,plainTextStale:false,authoringMode:"structured" as const,structuredDocument:ensureComplianceFooter({schemaVersion:1,blocks:[{id:"text",type:"text",text:"Hi"},{id:"compliance",type:"compliance_footer",locked:true}]}),htmlSource:null,trackingEnabled:true,openTrackingEnabled:false,rowVersion:1,state:"draft" as const,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null} satisfies EmailDraft;const pf=runPreflight(draft,{senderDomainReady:false,workspaceBusinessAddress:"1 Street",allowHtmlMode:false});assert.ok(pf.issues.some(i=>i.code==="MISSING_SENDER"));assert.equal(pf.issues.some(i=>i.code==="SENDER_DOMAIN_NOT_READY"),false)});
test("preflight blocks publish when the selected domain is not authenticated",()=>{const draft={id:"email-1",workspaceId:"ws1",internalName:"Welcome",subject:"Hello",preheader:"",senderIdentityId:"sender1",replyTo:"reply@example.com",plainText:"Body",plainTextMode:"manual" as const,plainTextStale:false,authoringMode:"structured" as const,structuredDocument:ensureComplianceFooter({schemaVersion:1,blocks:[{id:"text",type:"text",text:"Hi"},{id:"compliance",type:"compliance_footer",locked:true}]}),htmlSource:null,trackingEnabled:true,openTrackingEnabled:false,rowVersion:1,state:"draft" as const,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",archivedAt:null} satisfies EmailDraft;const pf=runPreflight(draft,{senderDomainReady:false,workspaceBusinessAddress:"1 Street",allowHtmlMode:false});assert.ok(pf.issues.some(i=>i.code==="SENDER_DOMAIN_NOT_READY"))});
