import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { InMemoryPhase2Repository } from "../packages/persistence/src/proof/in-memory-phase2-repository.js";
import { LocalObjectStore } from "../packages/object-store/src/local-object-store.js";
import { FakeEmailProvider } from "../packages/provider-email/src/proof/fake-email-provider.js";
import { Phase2Service } from "../packages/application/src/phase2/phase2-service.js";
import { defaultStructuredDocument } from "../packages/domain/src/phase2/content.js";
import { createTrackingToken, verifyTrackingToken, assertSafeTrackingDestination, classifyClick } from "../packages/domain/src/phase2/tracking.js";
import { buildMime } from "../packages/email-renderer/src/mime-builder.js";
import type { FlowGraph3 } from "../packages/domain/src/phase3/flow.js";
import { Phase3Service } from "../packages/application/src/phase3/phase3-service.js";
import { Phase3RuntimeService } from "../packages/application/src/phase3/phase3-runtime-service.js";
import { InMemoryPhase3Repository } from "../packages/persistence/src/proof/in-memory-phase3-repository.js";
import { InMemoryPhase3RuntimeRepository } from "../packages/persistence/src/proof/in-memory-phase3-runtime-repository.js";
import { StaticRuleEvaluationPort } from "../packages/testkit/src/phase3-runtime-fakes.js";

const WS="11111111-1111-4111-8111-111111111111";
const USER="22222222-2222-4222-8222-222222222222";
const PROFILE="33333333-3333-4333-8333-333333333333";
const DOMAIN="44444444-4444-4444-8444-444444444444";
const SENDER="55555555-5555-4555-8555-555555555555";

async function setup(consent="granted"){
  const root=await mkdtemp(join(tmpdir(),"phase2-"));
  const repo=new InMemoryPhase2Repository();
  repo.seedWorkspace({id:WS,businessAddress:"123 Test Street",timezone:"UTC",legalName:"Test Brand"},USER,"owner");
  repo.seedProfile({id:PROFILE,workspaceId:WS,normalizedEmail:"ada@example.com",originalEmail:"ada@example.com",firstName:"Ada",timezone:"UTC"},consent);
  repo.seedSender({id:DOMAIN,workspaceId:WS,domain:"brand.test",status:"verified"},{id:SENDER,workspaceId:WS,domainId:DOMAIN,fromName:"Test Brand",fromEmail:"hello@brand.test",replyTo:"support@brand.test",status:"active"});
  const objects=new LocalObjectStore(root),provider=new FakeEmailProvider();
  const service=new Phase2Service(repo,objects,provider,{publicBaseUrl:"https://mail.brand.test",unsubscribeSecret:"u".repeat(32),trackingSecret:"t".repeat(32),maxMessageBytes:500_000,providerReady:true});
  const actor={userId:USER,workspaceId:WS};
  const draft=await service.createEmail(actor,{internalName:"Welcome"});
  await service.updateEmail(actor,draft.id,{expectedRowVersion:draft.rowVersion,patch:{subject:'Welcome {{ profile.first_name | default: "there" }}',preheader:"A friendly hello",senderIdentityId:SENDER,replyTo:"support@brand.test",structuredDocument:{schemaVersion:1,blocks:[{id:"h",type:"heading",level:2,text:'Hello {{ profile.first_name | default: "there" }}'},{id:"b",type:"button",label:"Visit",url:"https://example.com/welcome"},{id:"compliance",type:"compliance_footer",locked:true}]},plainText:'Hello {{ profile.first_name | default: "there" }}\nVisit https://example.com/welcome\nUnsubscribe: {{ system.unsubscribe_url }}'}});
  const version=await service.publish(actor,draft.id);
  return {root,repo,objects,provider,service,actor,draftId:draft.id,version};
}

async function cleanup(root:string){await rm(root,{recursive:true,force:true})}

test("Phase 2 content persists immutable published versions and restores only draft",async()=>{const x=await setup();try{const v1=x.version;const draft=await x.service.getEmail(x.actor,x.draftId);const changed=await x.service.updateEmail(x.actor,x.draftId,{expectedRowVersion:draft.rowVersion,patch:{subject:"Changed"}});assert.equal(v1.subjectTemplate.includes("Welcome"),true);await x.service.restore(x.actor,x.draftId,v1.id);const restored=await x.service.getEmail(x.actor,x.draftId);assert.equal(restored.subject,v1.subjectTemplate);assert.equal((await x.repo.listEmailVersions(WS,x.draftId)).length,1);assert.ok(changed.rowVersion>draft.rowVersion)}finally{await cleanup(x.root)}});

test("saved templates and starting points clone into independent mutable drafts",async()=>{const x=await setup();try{const source=await x.service.getEmail(x.actor,x.draftId);const template=await x.service.saveAsTemplate(x.actor,x.draftId,{name:"Welcome reusable"});const fromTemplate=await x.service.createEmail(x.actor,{internalName:"Template copy",templateId:template.id});const fromStartingPoint=await x.service.createEmail(x.actor,{internalName:"Writing copy",startingPointId:"text-only"});assert.equal(fromTemplate.subject,source.subject);assert.ok(fromStartingPoint.structuredDocument.blocks.some(block=>block.type==="text"));const changed=await x.service.updateEmail(x.actor,x.draftId,{expectedRowVersion:source.rowVersion,patch:{subject:"Changed source"}});assert.equal(changed.subject,"Changed source");assert.equal((await x.service.getEmail(x.actor,fromTemplate.id)).subject,source.subject);assert.equal((await x.service.templates(x.actor)).items[0]?.name,"Welcome reusable")}finally{await cleanup(x.root)}});

test("template library CRUD is tenant-scoped, audited, and preserves independent copies",async()=>{const x=await setup();try{const created=await x.service.createTemplate(x.actor,{name:"Lifecycle base",category:"Lifecycle"});assert.equal(created.category,"Lifecycle");assert.equal(created.document.blocks.at(-1)?.type,"compliance_footer");const updated=await x.service.updateTemplate(x.actor,created.id,{name:"Lifecycle foundation",category:null});assert.equal(updated.category,null);const duplicate=await x.service.duplicateTemplate(x.actor,created.id,{name:"Lifecycle foundation copy"});duplicate.document.blocks.push({id:"local-only",type:"text",text:"Local mutation"});const active=await x.service.templates(x.actor);const storedCopy=active.items.find(template=>template.id===duplicate.id);assert.equal(storedCopy?.document.blocks.some(block=>block.id==="local-only"),false);assert.equal(active.items.length,2);await x.service.archiveTemplate(x.actor,created.id);assert.equal((await x.service.templates(x.actor)).items.some(template=>template.id===created.id),false);assert.equal((await x.service.templates(x.actor,{archived:true})).items.some(template=>template.id===created.id),true);await x.service.archiveTemplate(x.actor,created.id,false);assert.equal((await x.service.templates(x.actor)).items.some(template=>template.id===created.id),true);assert.ok(x.repo.audits.some(event=>event.action==="content.template.created"&&event.objectId===created.id));assert.ok(x.repo.audits.some(event=>event.action==="content.template.duplicated"&&event.objectId===duplicate.id));await assert.rejects(()=>x.service.createTemplate({...x.actor,userId:"not-a-member"},{name:"Denied"}),/WORKSPACE_ACCESS_DENIED/);const otherWorkspace="66666666-6666-4666-8666-666666666666",otherUser="77777777-7777-4777-8777-777777777777";x.repo.seedWorkspace({id:otherWorkspace,businessAddress:"456 Other Street",timezone:"UTC",legalName:"Other Brand"},otherUser,"owner");await assert.rejects(()=>x.service.updateTemplate({workspaceId:otherWorkspace,userId:otherUser},created.id,{name:"Cross tenant"}),/TEMPLATE_NOT_FOUND/);await assert.rejects(()=>x.service.createTemplate(x.actor,{name:"x".repeat(161)}),/TEMPLATE_NAME_INVALID/)}finally{await cleanup(x.root)}});

test("draft test snapshots use the same render pipeline and honor pinned tracking settings",async()=>{const x=await setup();try{const draft=await x.service.getEmail(x.actor,x.draftId);const updated=await x.service.updateEmail(x.actor,x.draftId,{expectedRowVersion:draft.rowVersion,patch:{trackingEnabled:false}});const testSend=await x.service.testSend(x.actor,x.draftId,{profileId:PROFILE,expectedRowVersion:updated.rowVersion});await x.service.evaluatePolicy(WS,testSend.messageId);await x.service.renderMessage(WS,testSend.messageId);await x.service.submitMessage(WS,testSend.messageId);const artifact=await x.repo.artifact(WS,testSend.messageId);const mime=(await x.objects.get(artifact!.objectKey)).toString("utf8");assert.match(mime,/\[TEST\]/);assert.doesNotMatch(mime,/\/t\/c\//);assert.equal((await x.repo.message(WS,testSend.messageId))?.emailTestSnapshotId,testSend.snapshotId)}finally{await cleanup(x.root)}});

test("Content v2 never rewrites a published Flow v1; existing Runs use v1 and new Runs use explicitly published Flow v2",async()=>{const x=await setup();try{const graph=(emailVersionId:string):FlowGraph3=>({schemaVersion:1,trigger:{type:"generic_event",eventName:"content.ready",schemaVersion:1},nodes:[{id:"email",type:"email",emailVersionId,mode:"live"},{id:"end",type:"end"}],edges:[{from:"trigger",to:"email"},{from:"email",to:"end"}],entryPolicy:{mode:"once_per_event"},entryFilters:[],exitRules:[]});const definitionsRepo=new InMemoryPhase3Repository(true),definitions=new Phase3Service(definitionsRepo),flow=await definitions.createFlow(WS,"Welcome flow",graph(x.version.id)),flowV1=await definitions.publishFlow(WS,flow.id,flow.rowVersion);await definitions.activateFlow(WS,flow.id,flowV1.id,"production",true);
  const runtimeRepo=new InMemoryPhase3RuntimeRepository(),messagePort={async createFlowMessage(input:any){const message=await x.service.createMessageIntent(x.actor,{sourceType:"flow",sourceId:input.flowRunId,profileId:input.profileId,emailVersionId:input.emailVersionId,sequence:input.sequence});return {messageId:message.id,duplicate:false}},async cancelPendingForRuns(){return 0}},runtime=new Phase3RuntimeService(runtimeRepo,messagePort,new StaticRuleEvaluationPort(true)),now=new Date("2026-08-24T10:00:00.000Z");runtimeRepo.seedFlow({id:flow.id,workspaceId:WS,status:"active",activeVersionId:flowV1.id,entryState:"open",executionState:"running",pausedAt:null},{id:flowV1.id,workspaceId:WS,flowId:flow.id,versionNumber:flowV1.versionNumber,graph:flowV1.graph,graphHash:flowV1.graphHash});runtimeRepo.seedProfile({id:PROFILE,workspaceId:WS,timezone:"UTC",workspaceTimezone:"UTC"});
  const existing=await runtime.enter({workspaceId:WS,flowId:flow.id,profileId:PROFILE,triggerEventId:"evt-v1",triggerKey:"evt-v1",now});assert.equal(existing.run?.flowVersionId,flowV1.id);
  const draft=await x.service.getEmail(x.actor,x.draftId),changed=await x.service.updateEmail(x.actor,x.draftId,{expectedRowVersion:draft.rowVersion,patch:{subject:"Welcome v2"}}),emailV2=await x.service.publish(x.actor,x.draftId,{expectedRowVersion:changed.rowVersion});assert.equal(flowV1.graph.nodes.find(node=>node.type==="email")?.emailVersionId,x.version.id);assert.notEqual(emailV2.id,x.version.id);
  const flowDraft=await definitionsRepo.flow(WS,flow.id),updated=await definitionsRepo.updateFlow({workspaceId:WS,flowId:flow.id,graph:graph(emailV2.id),rowVersion:flowDraft!.rowVersion}),flowV2=await definitions.publishFlow(WS,flow.id,updated.rowVersion);await definitions.activateFlow(WS,flow.id,flowV2.id,"production",true);assert.equal(flowV2.graph.nodes.find(node=>node.type==="email")?.emailVersionId,emailV2.id);runtimeRepo.versions.set(flowV2.id,{id:flowV2.id,workspaceId:WS,flowId:flow.id,versionNumber:flowV2.versionNumber,graph:flowV2.graph,graphHash:flowV2.graphHash});runtimeRepo.flows.set(flow.id,{...runtimeRepo.flows.get(flow.id)!,activeVersionId:flowV2.id});
  const existingAction=(await runtime.dispatchDue({now,leaseOwner:"worker-v1"}))[0]!;await runtime.executeAction(existingAction,now);const existingMessage=[...x.repo.messages.values()].find(message=>message.sourceId===existing.run!.id)!;assert.equal(existingMessage.emailVersionId,x.version.id);await x.service.evaluatePolicy(WS,existingMessage.id);await x.service.renderMessage(WS,existingMessage.id);await x.service.submitMessage(WS,existingMessage.id);
  const fresh=await runtime.enter({workspaceId:WS,flowId:flow.id,profileId:PROFILE,triggerEventId:"evt-v2",triggerKey:"evt-v2",now:new Date(now.getTime()+1000)});assert.equal(fresh.run?.flowVersionId,flowV2.id);const freshAction=(await runtime.dispatchDue({now:new Date(now.getTime()+1000),leaseOwner:"worker-v2"})).find(action=>action.flowRunId===fresh.run?.id)!;await runtime.executeAction(freshAction,new Date(now.getTime()+1000));const freshMessage=[...x.repo.messages.values()].find(message=>message.sourceId===fresh.run!.id)!;assert.equal(freshMessage.emailVersionId,emailV2.id);await x.service.evaluatePolicy(WS,freshMessage.id);await x.service.renderMessage(WS,freshMessage.id);await x.service.submitMessage(WS,freshMessage.id);assert.equal(x.provider.submitCalls,2)}finally{await cleanup(x.root)}});

test("controlled send re-evaluates policy, renders compliant MIME, and submits once under duplicate execution",async()=>{const x=await setup();try{const msg=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666666",profileId:PROFILE,emailVersionId:x.version.id});assert.equal((await x.service.evaluatePolicy(WS,msg.id)).outcome,"allow");await x.service.renderMessage(WS,msg.id);await Promise.all([x.service.submitMessage(WS,msg.id),x.service.submitMessage(WS,msg.id)]);assert.equal(x.provider.submitCalls,1);const stored=await x.repo.message(WS,msg.id);assert.equal(stored?.state,"submitted");const artifact=await x.repo.artifact(WS,msg.id);assert.ok(artifact);const mime=(await x.objects.get(artifact!.objectKey)).toString("utf8");assert.match(mime,/List-Unsubscribe:/);assert.match(mime,/List-Unsubscribe-Post: List-Unsubscribe=One-Click/);assert.match(mime,/~?\/t\/c\//)}finally{await cleanup(x.root)}});

test("V3 render submits unsigned MIME and leaves Easy DKIM to SES",async()=>{const x=await setup();try{const current=await x.repo.senderDomain(WS,DOMAIN);x.repo.domains.set(`${WS}:${DOMAIN}`,{...current!,rootDomain:"brand.test",delegatedSubdomain:"send.brand.test",provisioningMode:"branded_delegation",provisioningVersion:"V3_ROOT_SENDER_DELEGATED_EASY_DKIM",authenticationStatus:"verified",readinessStatus:"ready",workspacePrimary:true});(x.repo as any).deliveryRoute=async()=>({id:"route-v3",workspaceId:WS,senderDomainId:DOMAIN,provider:"ses",providerRegion:"us-east-1",providerIdentityReference:"brand.test",configurationSetName:"workspace-test",mailFromDomain:"bounce.send.brand.test",trackingMode:"platform",status:"active"});const msg=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666690",profileId:PROFILE,emailVersionId:x.version.id});assert.equal((await x.service.evaluatePolicy(WS,msg.id)).outcome,"allow");await x.service.renderMessage(WS,msg.id);const artifact=await x.repo.artifact(WS,msg.id),mime=(await x.objects.get(artifact!.objectKey)).toString("utf8");assert.doesNotMatch(mime,/^DKIM-Signature:/);await x.service.submitMessage(WS,msg.id);assert.equal(x.provider.submitCalls,1)}finally{await cleanup(x.root)}});

test("a historical sender domain cannot submit a new message",async()=>{const x=await setup();try{const domain=await x.repo.senderDomain(WS,DOMAIN);x.repo.domains.set(`${WS}:${DOMAIN}`,{...domain!,workspacePrimary:false});const msg=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666683",profileId:PROFILE,emailVersionId:x.version.id});const decision=await x.service.evaluatePolicy(WS,msg.id);assert.equal(decision.outcome,"hold");assert.equal(decision.reason,"SENDER_NOT_READY");assert.equal(x.provider.submitCalls,0)}finally{await cleanup(x.root)}});

test("unsubscribe or protected suppression immediately blocks a later production message",async()=>{const x=await setup();try{x.repo.setProtectedSuppression(WS,PROFILE,true);const msg=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666667",profileId:PROFILE,emailVersionId:x.version.id});const decision=await x.service.evaluatePolicy(WS,msg.id);assert.equal(decision.outcome,"skip");assert.equal(decision.reason,"PROTECTED_SUPPRESSION");assert.equal(x.provider.submitCalls,0)}finally{await cleanup(x.root)}});

test("workspace operational hold prevents new submissions and can be released",async()=>{const x=await setup();try{const hold=await x.service.createHold(x.actor,{scopeType:"workspace",reason:"operator emergency stop"});const m1=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666668",profileId:PROFILE,emailVersionId:x.version.id});assert.equal((await x.service.evaluatePolicy(WS,m1.id)).reason,"OPERATIONAL_HOLD");await x.service.releaseHold(x.actor,hold.id,"resolved");const m2=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666669",profileId:PROFILE,emailVersionId:x.version.id});assert.equal((await x.service.evaluatePolicy(WS,m2.id)).outcome,"allow")}finally{await cleanup(x.root)}});

test("frequency reservation prevents concurrent messages from exceeding cap",async()=>{const x=await setup();try{await x.service.setSendPolicy(x.actor,{version:2,frequencyWindowSeconds:86400,frequencyMax:1});const a=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666670",profileId:PROFILE,emailVersionId:x.version.id});const b=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666671",profileId:PROFILE,emailVersionId:x.version.id});assert.equal((await x.service.evaluatePolicy(WS,a.id)).outcome,"allow");const d=await x.service.evaluatePolicy(WS,b.id);assert.equal(d.outcome,"hold");assert.equal(d.reason,"FREQUENCY_CAP")}finally{await cleanup(x.root)}});

test("unknown provider outcome reconciles without blind second submission",async()=>{const x=await setup();try{x.provider.mode="accept-then-unknown";const msg=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666672",profileId:PROFILE,emailVersionId:x.version.id});await x.service.evaluatePolicy(WS,msg.id);await x.service.renderMessage(WS,msg.id);await x.service.submitMessage(WS,msg.id);assert.equal((await x.repo.message(WS,msg.id))?.state,"unknown");assert.equal(x.provider.submitCalls,1);await x.service.submitMessage(WS,msg.id);assert.equal(x.provider.submitCalls,1);await x.service.reconcileUnknown(WS,msg.id);assert.equal((await x.repo.message(WS,msg.id))?.state,"submitted");assert.equal(x.provider.submitCalls,1)}finally{await cleanup(x.root)}});

test("duplicate and out-of-order provider feedback is idempotent and complaint wins",async()=>{const x=await setup();try{const msg=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666673",profileId:PROFILE,emailVersionId:x.version.id});await x.service.evaluatePolicy(WS,msg.id);await x.service.renderMessage(WS,msg.id);await x.service.submitMessage(WS,msg.id);const attempt=[...x.repo.attempts.values()][0]!;const complaint={providerEventId:"evt-c",provider:"ses",providerMessageId:attempt.providerMessageId!,eventType:"complaint" as const,occurredAt:new Date().toISOString(),rawType:"complaint",metadata:{}};assert.equal((await x.service.applyFeedback(complaint)).applied,true);assert.equal((await x.service.applyFeedback(complaint)).reason,"DUPLICATE");const delivery={...complaint,providerEventId:"evt-d",eventType:"delivery" as const,rawType:"delivery"};await x.service.applyFeedback(delivery);assert.equal((await x.repo.message(WS,msg.id))?.state,"complained");assert.equal(await x.repo.activeProtectedSuppression(WS,PROFILE),true)}finally{await cleanup(x.root)}});

test("hard bounce creates protected suppression and blocks the next marketing message",async()=>{const x=await setup();try{const msg=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666674",profileId:PROFILE,emailVersionId:x.version.id});await x.service.evaluatePolicy(WS,msg.id);await x.service.renderMessage(WS,msg.id);await x.service.submitMessage(WS,msg.id);const attempt=[...x.repo.attempts.values()][0]!;await x.service.applyFeedback({providerEventId:"evt-b",provider:"ses",providerMessageId:attempt.providerMessageId!,eventType:"bounce",occurredAt:new Date().toISOString(),rawType:"bounce",metadata:{bounceType:"Permanent"}});const next=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666675",profileId:PROFILE,emailVersionId:x.version.id});assert.equal((await x.service.evaluatePolicy(WS,next.id)).reason,"PROTECTED_SUPPRESSION")}finally{await cleanup(x.root)}});

test("final submission re-evaluates the canonical policy after rendering",async()=>{const x=await setup();try{const msg=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666680",profileId:PROFILE,emailVersionId:x.version.id});await x.service.evaluatePolicy(WS,msg.id);await x.service.renderMessage(WS,msg.id);await x.service.createHold(x.actor,{scopeType:"workspace",reason:"Investigating feedback path"});const result=await x.service.submitMessage(WS,msg.id);const trace=await x.service.messageTrace(x.actor,msg.id);assert.equal(result?.state,"held");assert.equal((trace.events.at(-1)?.detail as {reason:string}).reason,"OPERATIONAL_HOLD");assert.equal(x.provider.submitCalls,0)}finally{await cleanup(x.root)}});

test("configured stale-feedback safety is a stable final policy hold",async()=>{const x=await setup();try{const first=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666681",profileId:PROFILE,emailVersionId:x.version.id});await x.service.evaluatePolicy(WS,first.id);await x.service.renderMessage(WS,first.id);await x.service.submitMessage(WS,first.id);await x.service.setSendPolicy(x.actor,{version:2,frequencyWindowSeconds:86400,frequencyMax:3,feedbackStaleAfterSeconds:60});const next=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666682",profileId:PROFILE,emailVersionId:x.version.id});const decision=await x.service.evaluatePolicy(WS,next.id);assert.equal(decision.outcome,"hold");assert.equal(decision.reason,"FEEDBACK_STALE");assert.equal((await x.repo.message(WS,next.id))?.state,"held")}finally{await cleanup(x.root)}});

test("test messages bypass marketing consent but remain excluded from production analytics",async()=>{const x=await setup("unknown");try{const msg=await x.service.createMessageIntent(x.actor,{sourceType:"test",sourceId:"66666666-6666-4666-8666-666666666676",profileId:PROFILE,emailVersionId:x.version.id});assert.equal((await x.service.evaluatePolicy(WS,msg.id)).outcome,"allow");await x.service.renderMessage(WS,msg.id);await x.service.submitMessage(WS,msg.id);const summary=await x.service.analytics(x.actor);assert.equal(summary.intents,0);assert.equal(summary.submitted,0)}finally{await cleanup(x.root)}});

test("analytics facts keep submitted separate, exclude tests, and count late feedback once",async()=>{const x=await setup();try{const live=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666678",profileId:PROFILE,emailVersionId:x.version.id}),testMessage=await x.service.createMessageIntent(x.actor,{sourceType:"test",sourceId:"66666666-6666-4666-8666-666666666679",profileId:PROFILE,emailVersionId:x.version.id});for(const message of [live,testMessage]){await x.service.evaluatePolicy(WS,message.id);await x.service.renderMessage(WS,message.id);await x.service.submitMessage(WS,message.id)}const attempt=[...x.repo.attempts.values()].find(item=>item.messageId===live.id)!;const delivery={providerEventId:"analytics-delivery",provider:"ses",providerMessageId:attempt.providerMessageId!,eventType:"delivery" as const,occurredAt:new Date().toISOString(),rawType:"delivery",metadata:{}};assert.equal((await x.service.applyFeedback(delivery)).applied,true);const from=new Date(Date.now()-60_000),to=new Date(Date.now()+60_000),beforeLate=await x.service.analyticsPeriod(x.actor,{from,to});assert.equal(beforeLate.submitted,1);assert.equal(beforeLate.delivered,1);assert.equal(beforeLate.complaints,0);const complaint={...delivery,providerEventId:"analytics-complaint",eventType:"complaint" as const,rawType:"complaint"};assert.equal((await x.service.applyFeedback(complaint)).applied,true);assert.equal((await x.service.applyFeedback(complaint)).reason,"DUPLICATE");const afterLate=await x.service.analyticsPeriod(x.actor,{from,to});assert.equal(afterLate.complaints,1)}finally{await cleanup(x.root)}});

test("tracking tokens are opaque, expiring and HTTPS destination validation rejects unsafe links",()=>{const secret="s".repeat(32),token=createTrackingToken({v:1,purpose:"click",messageId:PROFILE,trackingLinkId:DOMAIN,exp:Math.floor(Date.now()/1000)+30},secret);const parsed=verifyTrackingToken(token,secret);assert.equal(parsed.messageId,PROFILE);assert.throws(()=>assertSafeTrackingDestination("javascript:alert(1)"),/UNSAFE/);assert.equal(classifyClick("Proofpoint URL Defense"),"scanner")});

test("MIME rejects header injection",()=>{assert.throws(()=>buildMime({fromName:"Brand",fromEmail:"hello@brand.test",replyTo:"support@brand.test",to:"ada@example.com",subject:"Good\r\nBcc: bad@example.com",html:"<p>x</p>",text:"x",unsubscribeUrl:"https://brand.test/u/1"}),/HEADER_INJECTION/)});

test("message trace connects policy, render and provider submission",async()=>{const x=await setup();try{const msg=await x.service.createMessageIntent(x.actor,{sourceType:"manual",sourceId:"66666666-6666-4666-8666-666666666677",profileId:PROFILE,emailVersionId:x.version.id});await x.service.evaluatePolicy(WS,msg.id);await x.service.renderMessage(WS,msg.id);await x.service.submitMessage(WS,msg.id);const trace=await x.service.messageTrace(x.actor,msg.id);const kinds=trace.events.map(e=>e.kind);assert.ok(kinds.includes("message.intent_created"));assert.ok(kinds.includes("policy.evaluated"));assert.ok(kinds.includes("message.rendered"));assert.ok(kinds.includes("provider.submitted"))}finally{await cleanup(x.root)}});
