import test from 'node:test';import assert from 'node:assert/strict';
import {Phase4Service} from '../packages/application/src/phase4/phase4-service.js';
import {InMemoryPhase4Repository} from '../packages/persistence/src/proof/in-memory-phase4-repository.js';
import {requiredHardeningChecks4} from '../packages/domain/src/phase4/hardening.js';
import {requiredCapacityScenarios4} from '../packages/domain/src/phase4/capacity.js';
import {requiredRecoveryScenarios4} from '../packages/domain/src/phase4/recovery.js';
import {requiredSloIndicators4} from '../packages/domain/src/phase4/operations.js';

async function fillHardening(s:Phase4Service){
 for(const checkKey of requiredHardeningChecks4){if(checkKey==='migration.rehearsal')continue;await s.recordHardeningEvidence({checkKey,status:'passed',summary:'proof',owner:'owner'})}
 const now=new Date();for(const scenario of requiredCapacityScenarios4)await s.recordCapacity({scenario,startedAt:now,finishedAt:new Date(now.getTime()+1000),target:100,achieved:100,errorRate:0,safeCeiling:90,passed:true});
 for(const scenario of requiredRecoveryScenarios4)await s.recordRecovery({scenario,status:'passed',rpoMinutes:scenario==='backup_restore'?10:undefined,rtoMinutes:scenario==='backup_restore'?90:undefined,evidence:{proof:true}});
 for(const indicator of requiredSloIndicators4)await s.recordSloObservation({indicator,windowStart:now,windowEnd:new Date(now.getTime()+1000),observed:indicator==='segment_freshness_visible'?true:0,objective:'source objective',passed:true});
 await s.recordMigrationRehearsal({sourceLabel:'representative',sourceRows:10,acceptedRows:9,rejectedRows:1,duplicateRows:1,invalidRows:1,missingConsentRows:0,suppressedRows:1,acceptedProfiles:8,listMemberships:8,consentGranted:7,exclusions:2,reconciled:true,sourceOfTruthPlan:'source frozen during pilot',evidence:{proof:true},startedAt:now,finishedAt:new Date(now.getTime()+1000),owner:'data-owner'});
}

test('Phase4 pilot entry stays locked until prior external gates and hardening evidence pass',async()=>{const r=new InMemoryPhase4Repository(false,false),s=new Phase4Service(r);await fillHardening(s);let st=await s.launchStatus();assert.equal(st.pilotGate.allowed,false);assert(st.pilotGate.reasons.includes('PHASE2_EXTERNAL_GATE'));r.p2=true;r.p3=true;st=await s.launchStatus();assert.equal(st.pilotGate.allowed,true)});
test('Phase4 S0/S1 open security findings block pilot',async()=>{const r=new InMemoryPhase4Repository(true,true),s=new Phase4Service(r);await fillHardening(s);const f=await s.recordSecurityFinding({title:'tenant escape',severity:'S0',owner:'security'});assert.equal((await s.launchStatus()).pilotGate.allowed,false);await s.closeSecurityFinding(f.id);assert.equal((await s.launchStatus()).pilotGate.allowed,true)});
test('Phase4 passed launch evidence requires named approver',async()=>{const s=new Phase4Service(new InMemoryPhase4Repository());await assert.rejects(()=>s.recordLaunchEvidence({area:'security',status:'passed',summary:'ok'}),/APPROVER/)});
test('Phase4 active stop signal immediately holds a running pilot',async()=>{const r=new InMemoryPhase4Repository(true,true),s=new Phase4Service(r);await fillHardening(s);await s.startPilot();const sig=await s.recordStopSignal({code:'feedback_unhealthy',detail:'feedback lag exceeded safe limit'});assert.equal((await r.pilot()).state,'held');assert.equal((await s.launchStatus()).pilotGate.allowed,false);await s.clearStopSignal(sig.id);assert.equal((await s.launchStatus()).pilotGate.allowed,true)});
test('Phase4 capacity evidence records measured safe ceiling and rejects invented ceiling above observed',async()=>{const s=new Phase4Service(new InMemoryPhase4Repository());await assert.rejects(()=>s.recordCapacity({scenario:'event_burst',startedAt:new Date(),finishedAt:new Date(),target:1000,achieved:900,errorRate:.01,safeCeiling:1000,passed:false}),/SAFE_CEILING/);const x=await s.recordCapacity({scenario:'event_burst',startedAt:new Date(),finishedAt:new Date(),target:1000,achieved:900,errorRate:.01,safeCeiling:800,passed:true});assert.equal(x.safeCeiling,800)});
test('Phase4 privacy deletion places hold before deletion and enforces sequential tombstone workflow',async()=>{const r=new InMemoryPhase4Repository(),s=new Phase4Service(r);let j=await s.requestDeletion('w','p');assert(r.holds.has('w:p'));assert.equal(r.cancelled,1);for(const state of ['held','discovering','deleting','anonymizing','tombstoned','completed'] as const)j=await s.advanceDeletion('w','p',state);assert.equal(j.state,'completed');assert.ok(j.tombstoneHash)});
test('Phase4 deletion cannot skip required states',async()=>{const s=new Phase4Service(new InMemoryPhase4Repository());await s.requestDeletion('w','p');await assert.rejects(()=>s.advanceDeletion('w','p','deleting'),/TRANSITION_INVALID/)});
test('Phase4 recovery evidence captures explicit RPO/RTO instead of assuming recovery',async()=>{const r=new InMemoryPhase4Repository(),s=new Phase4Service(r);const x=await s.recordRecovery({scenario:'backup_restore',status:'passed',rpoMinutes:10,rtoMinutes:90,evidence:{restoreId:'proof'}});assert.equal(x.rpoMinutes,10);assert.equal((await r.recoveryExercises()).length,1)});
