import test from 'node:test';import assert from 'node:assert/strict';
import {Phase4Service} from '../packages/application/src/phase4/phase4-service.js';
import {InMemoryPhase4Repository} from '../packages/persistence/src/proof/in-memory-phase4-repository.js';
import {requiredCapacityScenarios4} from '../packages/domain/src/phase4/capacity.js';
import {requiredHardeningChecks4} from '../packages/domain/src/phase4/hardening.js';
import {launchAreas4} from '../packages/domain/src/phase4/launch.js';
import {requiredSloIndicators4} from '../packages/domain/src/phase4/operations.js';
import {requiredRecoveryScenarios4} from '../packages/domain/src/phase4/recovery.js';

async function completeHardening(s:Phase4Service){const now=new Date('2026-08-19T00:00:00Z');
 for(const checkKey of requiredHardeningChecks4){if(checkKey==='migration.rehearsal')continue;await s.recordHardeningEvidence({checkKey,status:'passed',summary:`passed ${checkKey}`,owner:'assigned-owner',evidence:{artifact:`evidence/${checkKey}`}})}
 for(const scenario of requiredCapacityScenarios4)await s.recordCapacity({scenario,startedAt:now,finishedAt:new Date(now.getTime()+60_000),target:1000,achieved:1000,errorRate:0,safeCeiling:800,passed:true,notes:'measured'});
 for(const scenario of requiredRecoveryScenarios4)await s.recordRecovery({scenario,status:'passed',rpoMinutes:scenario==='backup_restore'?10:undefined,rtoMinutes:scenario==='backup_restore'?180:undefined,evidence:{drill:true}});
 for(const indicator of requiredSloIndicators4)await s.recordSloObservation({indicator,windowStart:now,windowEnd:new Date(now.getTime()+60_000),observed:indicator==='segment_freshness_visible'?true:0,objective:'approved initial SLO',passed:true,evidence:{dashboard:'local'}});
 await s.recordMigrationRehearsal({sourceLabel:'representative audience',sourceRows:100,acceptedRows:95,rejectedRows:5,duplicateRows:10,invalidRows:3,missingConsentRows:2,suppressedRows:4,acceptedProfiles:85,listMemberships:90,consentGranted:80,exclusions:15,reconciled:true,sourceOfTruthPlan:'source frozen for controlled cohort; platform authoritative for pilot actions',evidence:{report:'migration-reconciliation'},startedAt:now,finishedAt:new Date(now.getTime()+3_600_000),owner:'data-integrity-owner'});
}

async function completePilot(s:Phase4Service){const base=new Date('2026-08-19T00:00:00Z');for(let stage=0;stage<=4;stage++){await s.startPilot();const start=new Date(base.getTime()+stage*72*3_600_000);const finish=new Date(start.getTime()+(stage===1?48:2)*3_600_000);await s.recordPilotObservation({stage:stage as 0|1|2|3|4,audience:`stage ${stage}`,startedAt:start,finishedAt:finish,healthPassed:true,unresolvedAlerts:0,expectedEventsReceived:stage===0?true:undefined,enoughFeedback:stage===1?true:undefined,withinWarmingCeiling:stage===2?true:undefined,completeFlowCycle:stage===3?true:undefined,approvedBy:'pilot-owner',evidence:{stage}});await s.completePilotStage()}}

test('Phase4 hardening gate requires every source-defined hardening family',async()=>{const r=new InMemoryPhase4Repository(true,true),s=new Phase4Service(r);let st=await s.hardeningStatus();assert.equal(st.passed,false);await completeHardening(s);st=await s.hardeningStatus();assert.equal(st.passed,true);assert.deepEqual(st.reasons,[])});
test('Phase4 backup restore must meet the initial RPO/RTO objective',async()=>{const r=new InMemoryPhase4Repository(true,true),s=new Phase4Service(r);await completeHardening(s);await s.recordRecovery({scenario:'backup_restore',status:'passed',rpoMinutes:30,rtoMinutes:300,evidence:{slow:true}});const st=await s.hardeningStatus();assert.equal(st.passed,false);assert(st.reasons.includes('RECOVERY_RPO_RTO_OBJECTIVE'))});
test('Phase4 hardening waiver requires owner and review date',async()=>{const s=new Phase4Service(new InMemoryPhase4Repository());await assert.rejects(()=>s.recordHardeningEvidence({checkKey:'security.penetration_test',status:'waived',summary:'temporary'}),/OWNER/);await assert.rejects(()=>s.recordHardeningEvidence({checkKey:'security.penetration_test',status:'waived',summary:'temporary',owner:'security'}),/REVIEW/);const x=await s.recordHardeningEvidence({checkKey:'security.penetration_test',status:'waived',summary:'accepted residual risk',owner:'security',reviewAt:new Date('2026-09-01')});assert.equal(x.status,'waived')});
test('Phase4 migration rehearsal must reconcile source rows and source-of-truth ownership',async()=>{const s=new Phase4Service(new InMemoryPhase4Repository());const now=new Date();await assert.rejects(()=>s.recordMigrationRehearsal({sourceLabel:'x',sourceRows:10,acceptedRows:8,rejectedRows:1,duplicateRows:0,invalidRows:1,missingConsentRows:0,suppressedRows:0,acceptedProfiles:8,listMemberships:8,consentGranted:8,exclusions:1,reconciled:true,sourceOfTruthPlan:'plan',evidence:{},startedAt:now,finishedAt:now,owner:'owner'}),/ROW_RECONCILIATION/)});
test('Phase4 pilot stage completion requires recorded stage-specific observation evidence',async()=>{const r=new InMemoryPhase4Repository(true,true),s=new Phase4Service(r);await completeHardening(s);await s.startPilot();await assert.rejects(()=>s.completePilotStage(),/OBSERVATION_REQUIRED/);const now=new Date();await s.recordPilotObservation({stage:0,audience:'seed',startedAt:now,finishedAt:new Date(now.getTime()+3_600_000),healthPassed:true,unresolvedAlerts:0,expectedEventsReceived:true,approvedBy:'pilot-owner',evidence:{}});const next=await s.completePilotStage();assert.equal(next.stage,1);assert.equal(next.state,'ready')});
test('Phase4 Stage 1 enforces at least 48 hours or enough feedback',async()=>{const r=new InMemoryPhase4Repository(true,true),s=new Phase4Service(r);await completeHardening(s);await s.startPilot();let now=new Date();await s.recordPilotObservation({stage:0,audience:'seed',startedAt:now,finishedAt:new Date(now.getTime()+3_600_000),healthPassed:true,unresolvedAlerts:0,expectedEventsReceived:true,approvedBy:'pilot-owner',evidence:{}});await s.completePilotStage();await s.startPilot();now=new Date();await assert.rejects(()=>s.recordPilotObservation({stage:1,audience:'engaged',startedAt:now,finishedAt:new Date(now.getTime()+2*3_600_000),healthPassed:true,unresolvedAlerts:0,approvedBy:'pilot-owner',evidence:{}}),/OBSERVATION_INSUFFICIENT/)});
test('Phase4 release approval is impossible before completed pilot and eight-area launch review',async()=>{const r=new InMemoryPhase4Repository(true,true),s=new Phase4Service(r);await completeHardening(s);await assert.rejects(()=>s.approveRelease1({approvedBy:'release-owner'}),/CONTROLLED_PILOT_INCOMPLETE/);await completePilot(s);let status=await s.launchStatus();assert.equal(status.releaseGate.allowed,false);for(const area of launchAreas4)await s.recordLaunchEvidence({area,status:'passed',summary:`approved ${area}`,approver:`${area}-owner`});status=await s.launchStatus();assert.equal(status.releaseGate.allowed,true);const release=await s.approveRelease1({approvedBy:'release-owner',notes:'Release 1 internal production'});assert.equal(release.status,'approved')});
test('Phase4 final approval becomes blocked again if a severe finding is reopened before approval',async()=>{const r=new InMemoryPhase4Repository(true,true),s=new Phase4Service(r);await completeHardening(s);await completePilot(s);for(const area of launchAreas4)await s.recordLaunchEvidence({area,status:'passed',summary:'approved',approver:'owner'});await s.recordSecurityFinding({title:'late tenant escape',severity:'S1',owner:'security'});const status=await s.launchStatus();assert.equal(status.releaseGate.allowed,false);assert(status.releaseGate.reasons.includes('SEVERE_SECURITY_FINDING'))});
