import { randomUUID } from "node:crypto";
import { compileStructuredDraft, resolveTemplate, type RenderContext } from "../../../email-renderer/src/phase2-structured.js";
import { defaultStructuredDocument, ensureComplianceFooter, PHASE2_SANITIZER_VERSION, type AuthoringMode, type EmailDraft, type PreflightResult, type PublishedEmailVersion, type StructuredEmailDocument } from "../../../domain/src/phase2/content.js";
import { runPreflight, type PreflightContext } from "../../../domain/src/phase2/preflight.js";

export interface Phase2Actor {userId:string;workspaceId:string}
export interface PreviewResult {subject:string;preheader:string;html:string;text:string;sampleSource:string;preflight:PreflightResult}
export interface TestSendIntent {id:string;workspaceId:string;emailDefinitionId:string;recipient:string;kind:"test";subject:string;createdAt:string;excludedFromProductionAnalytics:true}

export class Phase2ContentService{
  #drafts=new Map<string,EmailDraft>();#versions=new Map<string,PublishedEmailVersion[]>();#tests:TestSendIntent[]=[];
  createEmail(actor:Phase2Actor,input:{internalName:string;authoringMode?:AuthoringMode}):EmailDraft{const now=new Date().toISOString();const mode=input.authoringMode??"structured";const draft:EmailDraft={id:randomUUID(),workspaceId:actor.workspaceId,internalName:input.internalName,authoringMode:mode,subject:"",preheader:"",senderIdentityId:null,replyTo:"",structuredDocument:defaultStructuredDocument(),htmlSource:null,plainText:"",trackingEnabled:true,openTrackingEnabled:false,rowVersion:1,state:"draft",createdAt:now,updatedAt:now};this.#drafts.set(draft.id,draft);return structuredClone(draft)}
  listEmails(actor:Phase2Actor){return [...this.#drafts.values()].filter(x=>x.workspaceId===actor.workspaceId).map(d=>({...structuredClone(d),versions:this.listVersions(actor,d.id)}))}
  getDraft(actor:Phase2Actor,id:string){const d=this.#drafts.get(id);if(!d||d.workspaceId!==actor.workspaceId)throw new Error("EMAIL_NOT_FOUND");return structuredClone(d)}
  updateDraft(actor:Phase2Actor,id:string,input:Partial<Omit<EmailDraft,"id"|"workspaceId"|"createdAt"|"updatedAt"|"rowVersion">>&{expectedRowVersion:number}){const d=this.#drafts.get(id);if(!d||d.workspaceId!==actor.workspaceId)throw new Error("EMAIL_NOT_FOUND");if(d.rowVersion!==input.expectedRowVersion)throw new Error("CONCURRENCY_CONFLICT");const next={...d,...input,rowVersion:d.rowVersion+1,updatedAt:new Date().toISOString()};delete (next as any).expectedRowVersion;if(next.authoringMode==="structured")next.structuredDocument=ensureComplianceFooter(next.structuredDocument);this.#drafts.set(id,next);return structuredClone(next)}
  preflight(actor:Phase2Actor,id:string,ctx:PreflightContext){return runPreflight(this.getDraft(actor,id),ctx)}
  preview(actor:Phase2Actor,id:string,ctx:PreflightContext,renderContext:RenderContext,sampleSource="mock"):PreviewResult{const d=this.getDraft(actor,id),pf=runPreflight(d,ctx),compiled=compileStructuredDraft(d);const footer=`<hr><p>${String(renderContext.workspace.business_name??"")} · ${String(renderContext.workspace.business_address??"")} · <a href="${renderContext.system.unsubscribe_url}">Unsubscribe</a></p>`;const withFooter={...renderContext,system:{...renderContext.system,compliance_footer:footer}};return {subject:resolveTemplate(d.subject,withFooter,false).replace(/[\r\n]/g," "),preheader:resolveTemplate(d.preheader,withFooter,false),html:resolveTemplate(compiled.htmlTemplate,withFooter,true),text:resolveTemplate(compiled.textTemplate,withFooter,false),sampleSource,preflight:pf}}
  publish(actor:Phase2Actor,id:string,ctx:PreflightContext){const d=this.getDraft(actor,id),pf=runPreflight(d,ctx);if(!pf.ok)throw new Error("EMAIL_PREFLIGHT_BLOCKED");if(d.authoringMode!=="structured")throw new Error("HTML_MODE_NOT_IMPLEMENTED");if(!d.senderIdentityId)throw new Error("MISSING_SENDER");const c=compileStructuredDraft(d),versions=this.#versions.get(id)??[];const v:PublishedEmailVersion={id:randomUUID(),workspaceId:actor.workspaceId,emailDefinitionId:id,versionNumber:versions.length+1,authoringMode:d.authoringMode,authoringSchemaVersion:1,sourceDocument:structuredClone(d.structuredDocument),sanitizedSource:null,compiledHtml:c.htmlTemplate,compiledText:c.textTemplate,subjectTemplate:d.subject,preheaderTemplate:d.preheader,senderIdentityId:d.senderIdentityId,replyTo:d.replyTo,contentHash:c.contentHash,compilerVersion:c.compilerVersion,sanitizerVersion:PHASE2_SANITIZER_VERSION,preflight:pf,publishedAt:new Date().toISOString(),publishedBy:actor.userId};versions.push(v);this.#versions.set(id,versions);return structuredClone(v)}
  listVersions(actor:Phase2Actor,id:string){this.getDraft(actor,id);return structuredClone(this.#versions.get(id)??[])}
  restoreVersion(actor:Phase2Actor,id:string,versionNumber:number){const version=this.listVersions(actor,id).find(v=>v.versionNumber===versionNumber);if(!version||!version.sourceDocument)throw new Error("EMAIL_VERSION_NOT_FOUND");const d=this.#drafts.get(id)!;const next={...d,structuredDocument:structuredClone(version.sourceDocument),subject:version.subjectTemplate,preheader:version.preheaderTemplate,plainText:version.compiledText,senderIdentityId:version.senderIdentityId,replyTo:version.replyTo,rowVersion:d.rowVersion+1,updatedAt:new Date().toISOString(),state:"draft" as const};this.#drafts.set(id,next);return structuredClone(next)}
  createTestSend(actor:Phase2Actor,id:string,recipient:string,ctx:PreflightContext,renderContext:RenderContext){const preview=this.preview(actor,id,ctx,renderContext,"test-send");if(!preview.preflight.ok)throw new Error("EMAIL_PREFLIGHT_BLOCKED");const item:TestSendIntent={id:randomUUID(),workspaceId:actor.workspaceId,emailDefinitionId:id,recipient,kind:"test",subject:`[TEST] ${preview.subject}`,createdAt:new Date().toISOString(),excludedFromProductionAnalytics:true};this.#tests.push(item);return structuredClone(item)}
}
