"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { phase1Api } from "../lib/phase1-api";

const format = (value: unknown) => value ? new Date(String(value)).toLocaleString() : "Not available";
const count = (value: unknown) => new Intl.NumberFormat().format(Number(value ?? 0));
const percent = (value: unknown) => typeof value === "number" ? `${(value * 100).toFixed(value * 100 >= 10 ? 1 : 2)}%` : "—";
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const tone = (value: string) => value === "current" ? "success" : value === "delayed" || value === "refreshing" ? "warning" : "danger";
type Filter = { range: string; from: string; to: string; timezone: string; flowId: string; emailVersionId: string; messageStatus: string };

export function AnalyticsConsole({ workspaceId }: { workspaceId: string }) {
  const [data, setData] = useState<any>();
  const [filters, setFilters] = useState<Filter>({ range: "30", from: "", to: "", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", flowId: "", emailVersionId: "", messageStatus: "all" });
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const query = useMemo(() => { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, value); }); return params.toString(); }, [filters]);
  useEffect(() => { let active = true; setLoading(true); phase1Api<any>(`/api/v1/workspaces/${workspaceId}/analytics/dashboard?${query}`).then(result => { if (active) { setData(result); setError(""); window.history.replaceState(null, "", `?${query}`); } }).catch(caught => active && setError(caught instanceof Error ? caught.message : "Unable to load analytics.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [workspaceId, query]);
  const set = (key: keyof Filter, value: string) => setFilters(current => { if (key === "range" && value === "custom" && (!current.from || !current.to)) { const to = new Date(), from = new Date(to.getTime() - 7 * 86_400_000); return { ...current, range: value, from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) }; } return { ...current, [key]: value }; });
  const download = async () => { try { const base = process.env.NEXT_PUBLIC_EMAIL_PLATFORM_API_URL ?? "http://localhost:4000"; const token = window.localStorage.getItem("emailPlatformAccessToken"), devUser = process.env.NEXT_PUBLIC_EMAIL_PLATFORM_DEV_USER ?? "dev-owner"; const response = await fetch(`${base}/api/v1/workspaces/${workspaceId}/analytics/export?${query}`, { credentials: "include", headers: token ? { authorization: `Bearer ${token}` } : { "x-dev-user": devUser } }); if (!response.ok) throw new Error("Export unavailable."); const url = URL.createObjectURL(await response.blob()), anchor = document.createElement("a"); anchor.href = url; anchor.download = "analytics-export.csv"; anchor.click(); URL.revokeObjectURL(url); } catch (caught) { setError(caught instanceof Error ? caught.message : "Export unavailable."); } };
  if (loading && !data) return <AnalyticsSkeleton/>;
  if (!data) return <div role="alert">{error}</div>;
  const metricByKey = new Map(data.metrics.map((metric: any) => [metric.key, metric]));
  return <section className="analytics-console"><header className="analytics-header"><div><h1>Analytics</h1><p>Real production messaging, delivery, and Flow performance. Submitted is not delivered.</p></div><div className="analytics-actions"><button className="button-secondary" onClick={download}>Export filtered CSV</button></div></header><Filters data={data} filters={filters} set={set}/>{error && <div role="alert">{error}</div>}<section className="analytics-freshness"><div><strong>Data freshness: {label(data.freshness.state)}</strong><span>{data.freshness.detail}</span></div><span className={`pill pill-${tone(data.freshness.state)}`}>{label(data.freshness.state)}</span><small>Refreshed {format(data.freshness.refreshedAt)} · latest source fact {format(data.freshness.sourceLatestAt)} · projection lag {data.freshness.projectionLagSeconds}s</small></section><MetricGrid metrics={data.metrics}/><div className="dashboard-grid"><Trend trend={data.trend}/><Delivery outcomes={data.deliveryOutcomes} metricByKey={metricByKey}/></div><FlowComparison data={data} workspaceId={workspaceId}/>{data.flowDetail ? <FlowDetail detail={data.flowDetail}/> : <section className="analytics-callout"><strong>Choose a Flow filter to open version-aware Flow Analytics.</strong><span>Each Flow Version remains separate across run states, node execution, branches, exits, and policy reasons.</span></section>}<section className="analytics-bottom"><Definitions data={data}/><MessageDrilldown data={data} workspaceId={workspaceId}/></section></section>;
}

function Filters({ data, filters, set }: any) { return <section className="analytics-filters" aria-label="Analytics filters"><label>Date range<select value={filters.range} onChange={event => set("range", event.target.value)}><option value="today">Today</option><option value="7">Last 7 days</option><option value="14">Last 14 days</option><option value="30">Last 30 days</option><option value="custom">Custom</option></select></label>{filters.range === "custom" && <><label>From<input type="date" required value={filters.from} onChange={event => set("from", event.target.value)}/></label><label>To<input type="date" required value={filters.to} onChange={event => set("to", event.target.value)}/></label></>}<label>Timezone<select value={filters.timezone} onChange={event => set("timezone", event.target.value)}>{[filters.timezone, "UTC", "America/New_York", "Europe/London", "Asia/Karachi", "Asia/Tokyo"].filter((value, index, values) => values.indexOf(value) === index).map(value => <option key={value} value={value}>{value}</option>)}</select></label>{data.filters.domain&&<div className="filter-summary"><small>Sending domain</small><strong>{data.filters.domain.domain}</strong></div>}<label>Flow<select value={filters.flowId} onChange={event => set("flowId", event.target.value)}><option value="">All Flows</option>{data.filters.flows.map((flow: any) => <option value={flow.id} key={flow.id}>{flow.name}</option>)}</select></label><label>Email Version<select value={filters.emailVersionId} onChange={event => set("emailVersionId", event.target.value)}><option value="">All content</option>{data.filters.emailVersions.map((version: any) => <option value={version.id} key={version.id}>{version.label}</option>)}</select></label><label>Message status<select value={filters.messageStatus} onChange={event => set("messageStatus", event.target.value)}>{["all", "created", "held", "skipped", "submitted", "delivered", "bounced", "complained", "failed", "cancelled"].map(state => <option value={state} key={state}>{label(state)}</option>)}</select></label></section>; }
function MetricGrid({ metrics }: { metrics: any[] }) { return <section className="analytics-metric-grid">{metrics.map((metric, index) => <article className={`analytics-metric metric-${index % 5}`} key={metric.key}><span>{metric.label}</span><strong>{count(metric.value)}</strong>{metric.numerator !== null && <small>{percent(metric.rate)} · {count(metric.numerator)} / {count(metric.denominator)}</small>}<em>{metric.definitionVersion}</em></article>)}</section>; }
function Trend({ trend }: { trend: any[] }) { const points = (key: string) => { const max = Math.max(1, ...trend.flatMap(row => [row.submitted, row.delivered, row.uniqueClicks])); return trend.map((row, index) => `${trend.length < 2 ? 0 : index / (trend.length - 1) * 100},${100 - Number(row[key] ?? 0) / max * 88}`).join(" "); }; const total = trend.reduce((sum, row) => sum + row.submitted + row.delivered + row.uniqueClicks, 0); return <section className="panel analytics-chart"><div className="panel-heading"><div><h2>Message performance trend</h2><p className="panel-subtitle">Daily production facts in the selected timezone.</p></div></div>{total ? <><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Submitted, delivered, and unique click trends"><polyline className="analytics-line submitted" points={points("submitted")}/><polyline className="analytics-line delivered" points={points("delivered")}/><polyline className="analytics-line clicks" points={points("uniqueClicks")}/></svg><div className="analytics-legend"><span><i className="submitted"/>Submitted</span><span><i className="delivered"/>Delivered</span><span><i className="clicks"/>Unique clicks</span></div></> : <div className="empty-state"><strong>No production activity in this window.</strong><p>Test sends are intentionally excluded from every metric and trend.</p></div>}</section>; }
function Delivery({ outcomes, metricByKey }: any) { const rows = ["delivered", "hard_bounces", "soft_bounces", "complaints", "unsubscribes"].map(key => metricByKey.get(key)).filter(Boolean); return <section className="panel analytics-outcomes"><div className="panel-heading"><div><h2>Delivery outcomes</h2><p className="panel-subtitle">Provider feedback and production message states remain distinct.</p></div></div>{rows.map((row: any) => <div className="outcome-row" key={row.key}><span>{row.label}</span><strong>{count(row.value)}</strong><small>{row.numerator === null ? "Count" : `${percent(row.rate)} · ${count(row.numerator)} / ${count(row.denominator)}`}</small></div>)}<div className="outcome-states">{Object.entries(outcomes).map(([key, value]) => <span key={key}><b>{count(value)}</b> {label(key)}</span>)}</div></section>; }
function FlowComparison({ data, workspaceId }: any) { return <section className="panel analytics-table-panel"><div className="panel-heading"><div><h2>Flow comparison</h2><p className="panel-subtitle">Results are grouped by exact Flow and immutable Flow Version; versions are never silently combined.</p></div></div><div className="table-wrap"><table><thead><tr><th>Flow / Version</th><th>Entries</th><th>Intents</th><th>Submitted</th><th>Delivered</th><th>Unique clicks</th><th>Complaints</th><th>Drill-down</th></tr></thead><tbody>{data.flowComparison.map((flow: any) => <tr key={flow.flowVersionId}><td><strong>{flow.flowName}</strong><br/><small>Version {flow.versionNumber}</small></td><td>{count(flow.entries)}</td><td>{count(flow.intents)}</td><td>{count(flow.submitted)}</td><td>{count(flow.delivered)}</td><td>{count(flow.uniqueClicks)}</td><td>{count(flow.complaints)}</td><td><Link href={`/w/${workspaceId}/flows/${flow.flowId}/runs`}>Runs</Link></td></tr>)}</tbody></table></div>{!data.flowComparison.length && <div className="empty-state"><strong>No Flow Version facts match these filters.</strong><p>Activate a Flow and process production events to populate the comparison.</p></div>}</section>; }
function FlowDetail({ detail }: { detail: any }) { const group = (title: string, rows: any[], render: (row: any) => string) => <section className="analytics-detail-group"><h3>{title}</h3>{rows.length ? <div>{rows.map((row, index) => <p key={`${row.flowVersionId}-${index}`}><strong>v{detail.versions.find((version: any) => version.id === row.flowVersionId)?.versionNumber ?? "?"}</strong> · {render(row)} <b>{count(row.value)}</b></p>)}</div> : <p className="muted">No supported facts in this period.</p>}</section>; return <section className="panel analytics-flow-detail"><div className="panel-heading"><div><h2>Flow Analytics</h2><p className="panel-subtitle">Version-aware run lifecycle, execution, branch, exit, and policy evidence for the selected Flow.</p></div></div><div className="analytics-detail-grid">{group("Run states", detail.runStates, row => label(row.state))}{group("Node performance", detail.nodePerformance, row => `${row.nodeLabel} · ${label(row.state)}`)}{group("Branch outcomes", detail.branchOutcomes, row => `${row.nodeLabel} → ${row.nextNodeLabel ?? "unresolved"}`)}{group("Exit reasons", detail.exitReasons, row => label(row.reason))}{group("Policy reasons", detail.policyReasons, row => label(row.reason))}</div></section>; }
function Definitions({ data }: { data: any }) { return <section className="panel analytics-definitions"><h2>Definitions & limitations</h2><p><strong>Definition version:</strong> {data.definitions.version}</p><p>{data.definitions.opens}</p><p>{data.definitions.exclusion}</p><p>{data.definitions.lateFeedback}</p><p>{data.definitions.attribution}</p></section>; }
function MessageDrilldown({ data, workspaceId }: any) { return <section className="panel analytics-messages"><div className="panel-heading"><div><h2>Message drill-down</h2><p className="panel-subtitle">Recent production Message intents matching the selected scope.</p></div></div><div className="table-wrap"><table><thead><tr><th>Message</th><th>Email Version</th><th>State</th><th>Intent</th><th>Submitted</th><th>Policy reason</th><th>Flow Run</th></tr></thead><tbody>{data.recentMessages.map((message: any) => <tr key={message.id}><td><Link href={`/w/${workspaceId}/messages/${message.id}`}>{message.id.slice(0, 8)}…</Link></td><td>{message.emailVersionLabel ?? "—"}</td><td>{label(message.state)}</td><td>{format(message.createdAt)}</td><td>{format(message.submittedAt)}</td><td>{message.policyReason ? label(message.policyReason) : "—"}</td><td>{message.flowId ? <Link href={`/w/${workspaceId}/flows/${message.flowId}/runs`}>Open Run</Link> : "—"}</td></tr>)}</tbody></table></div>{!data.recentMessages.length && <div className="empty-state"><strong>No matching production Message intents.</strong><p>Try a wider time range or remove a filter.</p></div>}</section>; }
function AnalyticsSkeleton() { return <div className="deliverability-loading"><div className="skeleton skeleton-title"/><div className="skeleton skeleton-subtitle"/><div className="analytics-metric-grid">{Array.from({ length: 5 }, (_, index) => <div className="skeleton skeleton-card" key={index}/>)}</div></div>; }
