"use client";
import {useCallback,useDeferredValue,useEffect,useState} from "react";
import {phase1Api} from "../lib/phase1-api";
import {ConfirmationDialog} from "./confirmation-dialog";
const date=(v?:string)=>v?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(v)):"—";
export function ListManager({workspaceId}:{workspaceId:string}){
  const [items,setItems]=useState<any[]>([]),[q,setQ]=useState(""),dq=useDeferredValue(q),[status,setStatus]=useState("active"),[sort,setSort]=useState("updated_desc"),[error,setError]=useState(""),[loading,setLoading]=useState(true),[create,setCreate]=useState(false),[deleteTarget,setDeleteTarget]=useState<any>(null),[deleteError,setDeleteError]=useState(""),[deleting,setDeleting]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const p=new URLSearchParams({q:dq,status,sort});setItems((await phase1Api<any>(`/api/v1/workspaces/${workspaceId}/lists/overview?${p}`)).items);setError("")}catch(e:any){setError(e.message)}finally{setLoading(false)}},[workspaceId,dq,status,sort]);
  useEffect(()=>{void load()},[load]);
  const remove=async()=>{if(!deleteTarget)return;setDeleting(true);setDeleteError("");try{await phase1Api(`/api/v1/workspaces/${workspaceId}/lists/${deleteTarget.id}`,{method:"DELETE"});setDeleteTarget(null);await load()}catch(e:any){setDeleteError(e.message==="LIST_ACTIVE_FLOW_DEPENDENCY"?"This list is connected to a live or paused flow. Delete or disconnect that flow first, then try again.":e.message)}finally{setDeleting(false)}};
  let table:React.ReactNode;
  if(loading)table=<div className="empty-state">Loading lists…</div>;
  else if(!items.length)table=<div className="empty-state"><strong>No lists yet.</strong><p>Create a list to organize explicit static membership.</p><button className="button-primary" onClick={()=>setCreate(true)}>Create list</button></div>;
  else table=<div className="table-wrap"><table><thead><tr><th>List</th><th>Members</th><th>Reachable</th><th>Source</th><th>Connected flows</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><a className="list-link" href={`/w/${workspaceId}/audiences/lists/${x.id}`}><strong>{x.name}</strong><small>{x.description||"No description"}</small></a></td><td>{x.members}</td><td>{x.reachable}</td><td>{x.source}</td><td>{x.connectedFlows}</td><td>{date(x.updatedAt)}</td><td><button type="button" className="button-danger" onClick={()=>{setDeleteError("");setDeleteTarget(x)}}>Delete</button></td></tr>)}</tbody></table></div>;
  return <><div className="page-heading"><div><h1>Lists</h1><p>Static audience membership with provenance and clear separation from marketing consent.</p></div><button className="button-primary" onClick={()=>setCreate(true)}>＋ Create list</button></div><section className="profiles-toolbar panel"><input placeholder="⌕ Search lists" aria-label="Search lists" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button className="button-secondary" onClick={()=>setQ("")}>Clear</button>}<select aria-label="List status" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="archived">Archived</option><option value="all">All statuses</option></select><select aria-label="List sort" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated_desc">Last updated</option><option value="updated_asc">Oldest updated</option></select></section>{error?<section className="panel profile-error"><strong>Unable to load lists.</strong><p>{error}</p><button className="button-secondary" onClick={load}>Retry</button></section>:<section className="panel table-panel">{table}</section>}<section className="audience-note"><strong>Lists organize profiles. They do not grant permission.</strong><span>Eligible counts are calculated separately from membership and can change as consent or suppressions change.</span></section>{create&&<CreateList workspaceId={workspaceId} onClose={()=>setCreate(false)}/>}<ConfirmationDialog open={Boolean(deleteTarget)} title={`Delete ${deleteTarget?.name??'list'}?`} consequence={`${deleteTarget?.members??0} membership record${deleteTarget?.members===1?'':'s'} and historical references will be retained for audit. The list will disappear from your workspace and can no longer receive members.`} confirmLabel="Delete list" pendingLabel="Deleting…" pending={deleting} error={deleteError} tone="danger" onCancel={()=>{setDeleteTarget(null);setDeleteError('')}} onConfirm={()=>void remove()}/></>;
}
function CreateList({workspaceId,onClose}:{workspaceId:string;onClose:()=>void}){
  const [name,setName]=useState(""),[description,setDescription]=useState(""),[initialMembers,setInitialMembers]=useState<"empty"|"select"|"csv">("empty"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[createdList,setCreatedList]=useState<any>(null);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const list=createdList?await phase1Api<any>(`/api/v1/workspaces/${workspaceId}/lists/${createdList.id}`,{method:"PATCH",body:JSON.stringify({name,description})}):await phase1Api<any>(`/api/v1/workspaces/${workspaceId}/lists`,{method:"POST",body:JSON.stringify({name,description})});setCreatedList(list);setError("");if(initialMembers==="empty")window.location.href=`/w/${workspaceId}/audiences/lists/${list.id}`;else if(initialMembers==="csv")window.location.href=`/w/${workspaceId}/imports?targetListId=${encodeURIComponent(list.id)}`;}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  if(createdList&&initialMembers==="select")return <ProfileSelection workspaceId={workspaceId} listId={createdList.id} onBack={()=>setCreatedList(null)} onClose={()=>window.location.href=`/w/${workspaceId}/audiences/lists/${createdList.id}`}/>;
  return <div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><div className="modal-head"><h2>Create list</h2><button type="button" onClick={onClose}>×</button></div><label>List name *<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><fieldset className="initial-members"><legend>Initial members</legend><label><input type="radio" name="initial-members" checked={initialMembers==="empty"} onChange={()=>setInitialMembers("empty")}/> Start empty</label><label><input type="radio" name="initial-members" checked={initialMembers==="select"} onChange={()=>setInitialMembers("select")}/> Select existing profiles</label><label><input type="radio" name="initial-members" checked={initialMembers==="csv"} onChange={()=>setInitialMembers("csv")}/> Import CSV</label></fieldset><p className="consent-safety-note">Creating a list or adding profiles to a list does not grant marketing consent.</p>{error&&<div role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="button-secondary" onClick={onClose}>Cancel</button><button className="button-primary" disabled={busy}>{busy?"Creating…":"Create list"}</button></div></form></div>;
}
function ProfileSelection({workspaceId,listId,onBack,onClose}:{workspaceId:string;listId:string;onBack:()=>void;onClose:()=>void}){
  const [data,setData]=useState<{items:any[];sources:string[];nextCursor?:string|null}>({items:[],sources:[]}),[q,setQ]=useState(""),[eligibility,setEligibility]=useState(""),[source,setSource]=useState(""),[cursor,setCursor]=useState<string|null>(null),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const p=new URLSearchParams({limit:"100"});if(cursor)p.set("cursor",cursor);if(q.trim())p.set("q",q.trim());if(eligibility)p.set("eligibility",eligibility);if(source)p.set("source",source);setData(await phase1Api<any>(`/api/v1/workspaces/${workspaceId}/profiles/overview?${p}`));setError("")}catch(e:any){setError(e.message)}},[workspaceId,q,eligibility,source,cursor]);
  useEffect(()=>{void load()},[load]);
  const pageIds=data.items.map(x=>x.id),pageSelected=pageIds.length>0&&pageIds.every(id=>selected.includes(id));
  const togglePage=()=>setSelected(current=>pageSelected?current.filter(id=>!pageIds.includes(id)):[...new Set([...current,...pageIds])]);
  const add=async()=>{setBusy(true);try{await phase1Api(`/api/v1/workspaces/${workspaceId}/lists/${listId}/memberships:batch`,{method:"POST",body:JSON.stringify({profileIds:selected,action:"add",sourceType:"manual"})});window.location.href=`/w/${workspaceId}/audiences/lists/${listId}`}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  return <div className="modal-backdrop"><div className="modal-card modal-card-wide"><div className="modal-head"><h2>Select existing profiles</h2><button onClick={onClose}>×</button></div><p>Selected profiles are added with Manual provenance. This does not grant consent.</p><section className="profiles-toolbar selector-toolbar"><input aria-label="Search profiles" placeholder="Search profiles" value={q} onChange={e=>{setCursor(null);setQ(e.target.value)}}/><select aria-label="Eligibility filter" value={eligibility} onChange={e=>{setCursor(null);setEligibility(e.target.value)}}><option value="">Eligibility</option><option value="eligible">Eligible</option><option value="suppressed">Suppressed</option><option value="no_marketing_consent">No consent</option></select><select aria-label="Source filter" value={source} onChange={e=>{setCursor(null);setSource(e.target.value)}}><option value="">Source</option>{data.sources.map(x=><option key={x}>{x}</option>)}</select><button type="button" onClick={togglePage}>{pageSelected?"Clear page":"Select page"}</button><button type="button" onClick={()=>setSelected([])}>Clear selection</button></section><div className="table-wrap selection-profile-table"><table><thead><tr><th><input type="checkbox" aria-label="Select page" checked={pageSelected} onChange={togglePage}/></th><th>Name</th><th>Email</th><th>Eligibility</th><th>Source</th></tr></thead><tbody>{data.items.length?data.items.map(x=><tr key={x.id}><td><input type="checkbox" aria-label={`Select ${x.originalEmail}`} checked={selected.includes(x.id)} onChange={()=>setSelected(current=>current.includes(x.id)?current.filter(id=>id!==x.id):[...current,x.id])}/></td><td>{x.name}</td><td>{x.originalEmail}</td><td><span className={`pill ${x.eligibility?.eligible?"pill-success":"pill-warning"}`}>{x.eligibility?.eligible?"Eligible":String(x.eligibility?.code??"Ineligible").replaceAll("_"," ")}</span></td><td>{x.source}</td></tr>):<tr><td colSpan={5}><div className="empty-state">No profiles match these filters.</div></td></tr>}</tbody></table></div>{data.nextCursor&&<div className="modal-actions"><button className="button-secondary" onClick={()=>setCursor(data.nextCursor??null)}>Next page</button></div>}{error&&<div role="alert">{error}</div>}<div className="modal-actions"><span>{selected.length} profile{selected.length===1?"":"s"} selected</span><button className="button-secondary" onClick={onBack}>Back</button><button className="button-primary" disabled={!selected.length||busy} onClick={add}>{busy?"Adding…":"Add profiles"}</button></div></div></div>;
}
