import type { GenericEventInput,GenericEventSchema } from '../../../domain/src/phase3/generic-events.js';import type { SegmentRule } from '../../../domain/src/phase3/segment-rules.js';import type { FlowGraph3 } from '../../../domain/src/phase3/flow.js';
export interface Segment3 {id:string;workspaceId:string;name:string;description:string;status:'draft'|'active'|'archived';draftRule:SegmentRule;createdAt:Date;updatedAt:Date}
export interface SegmentVersion3 {id:string;workspaceId:string;segmentId:string;versionNumber:number;rule:SegmentRule;publishedAt:Date}
export interface SegmentEstimate3 {segmentId:string;count:number;eligibleCount:number;sampleProfileIds:string[];evaluatedAt:Date;status:'current'|'stale'|'refreshing'|'failed';exact:boolean;lowerBound?:number}
export interface StoredEvent3 extends GenericEventInput {id:string;workspaceId:string;receivedAt:string}
export interface Flow3 {id:string;workspaceId:string;name:string;status:'draft'|'testing'|'active'|'paused'|'archived';draftGraph:FlowGraph3;activeVersionId?:string;activeVersionActivatedAt?:Date|null;rowVersion:number;updatedAt:Date}
export interface FlowVersion3 {id:string;workspaceId:string;flowId:string;versionNumber:number;graph:FlowGraph3;graphHash:string;publishedAt:Date}
export interface Phase3Repository {
 createSegment(input:{workspaceId:string;name:string;description?:string;rule:SegmentRule}):Promise<Segment3>;updateSegment(input:{workspaceId:string;segmentId:string;name?:string;description?:string;rule?:SegmentRule}):Promise<Segment3>;listSegments(workspaceId:string):Promise<Segment3[]>;segment(workspaceId:string,id:string):Promise<Segment3|null>;publishSegment(workspaceId:string,id:string):Promise<SegmentVersion3>;estimateSegment(workspaceId:string,id:string):Promise<SegmentEstimate3>;
 saveEventSchema(workspaceId:string,schema:GenericEventSchema):Promise<void>;eventSchema(workspaceId:string,name:string,version:number):Promise<GenericEventSchema|null>;insertEvent(workspaceId:string,input:GenericEventInput):Promise<{event:StoredEvent3;duplicate:boolean}>;eventById(workspaceId:string,eventId:string):Promise<StoredEvent3|null>;listEvents(workspaceId:string):Promise<StoredEvent3[]>;
 createFlow(input:{workspaceId:string;name:string;graph:FlowGraph3}):Promise<Flow3>;updateFlow(input:{workspaceId:string;flowId:string;graph:FlowGraph3;rowVersion:number;name?:string}):Promise<Flow3>;flow(workspaceId:string,id:string):Promise<Flow3|null>;listFlows(workspaceId:string):Promise<Flow3[]>;publishFlow(workspaceId:string,id:string,expectedRowVersion?:number):Promise<FlowVersion3>;publishedFlowVersion(workspaceId:string,versionId:string):Promise<FlowVersion3|null>;activateFlow(workspaceId:string,id:string,versionId:string,status:'testing'|'active'):Promise<Flow3>;scheduleProfileDateEntries(input:{workspaceId:string;flowId:string;flowVersionId:string;activatedAt:Date}):Promise<{scheduled:number;skipped:number}>;
 phase2ExternalGatePassed():Promise<boolean>;
}
