'use client';
import {FormEvent,useEffect,useState} from 'react';
import {phase4Api} from '../../lib/phase4-api';
const hardeningChecks=['security.threat_model','security.tenant_isolation','security.dependency_scan','security.container_scan','security.secret_scan','security.static_analysis','security.iac_scan','security.penetration_test','security.secret_rotation','security.least_privilege','resilience.backpressure_fairness','privacy.deletion_all_stores','privacy.artifact_expiry','privacy.audit_access_review','privacy.support_access_expiry','operations.dashboards','operations.alerts','operations.runbooks','operations.on_call','operations.kill_switch_drill','operations.hold_drill','operations.safe_replay_drill','operations.reconciliation_drill','operations.slo_baseline','migration.rehearsal'];
const launchAreas=['product','data_integrity','security','deliverability','compliance_privacy','reliability','operations','ux'];
export function LaunchReadiness({workspaceId}:{workspaceId:string}){
 const [data,setData]=useState<any>(null),[msg,setMsg]=useState('');
 async function load(){try{setData(await phase4Api(`/api/v1/workspaces/${workspaceId}/phase4/status`));setMsg('')}catch(e){setMsg(String(e))}}
 useEffect(()=>{void load()},[workspaceId]);
 async function post(path:string,payload:any){try{await phase4Api(`/api/v1/workspaces/${workspaceId}/phase4${path}`,{method:'POST',body:JSON.stringify(payload)});await load()}catch(e){setMsg(String(e))}}
 async function hardening(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await post('/hardening-evidence',{checkKey:f.get('checkKey'),status:'passed',summary:f.get('summary'),owner:f.get('owner'),evidence:{recordedFrom:'phase4-ui'}});e.currentTarget.reset()}
 async function launchEvidence(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await post('/launch-evidence',{area:f.get('area'),status:'passed',summary:f.get('summary'),approver:f.get('approver')});e.currentTarget.reset()}
 async function observation(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),stage=Number(data?.pilot?.stage??0);await post('/pilot/observations',{stage,audience:String(f.get('audience')),startedAt:String(f.get('startedAt')),finishedAt:String(f.get('finishedAt')),healthPassed:f.get('healthPassed')==='on',unresolvedAlerts:Number(f.get('unresolvedAlerts')),expectedEventsReceived:f.get('expectedEventsReceived')==='on',enoughFeedback:f.get('enoughFeedback')==='on',withinWarmingCeiling:f.get('withinWarmingCeiling')==='on',completeFlowCycle:f.get('completeFlowCycle')==='on',approvedBy:String(f.get('approvedBy')),evidence:{recordedFrom:'phase4-ui'}});e.currentTarget.reset()}
 async function approveRelease(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await post('/release/approve',{approvedBy:String(f.get('approvedBy')),notes:String(f.get('notes'))});e.currentTarget.reset()}
 return <main><h1>Release 1 hardening, pilot & approval</h1><p>Internal owner-only control surface. Hardening evidence unlocks the controlled pilot. Final eight-area sign-off happens only after the pilot is complete.</p>
 {data&&<>
  <section className="panel"><h2>Hardening / pilot gate</h2><p><strong>{data.pilotGate.allowed?'READY':'BLOCKED'}</strong></p>{!data.pilotGate.allowed&&<ul>{data.pilotGate.reasons.map((r:string)=><li key={r}>{r}</li>)}</ul>}<p>Stage {data.pilot.stage} · {data.pilot.state}</p><p>Release: {data.release.status}</p><button type="button" disabled={!data.pilotGate.allowed||data.pilot.state==='running'||data.pilot.state==='completed'} onClick={()=>void post('/pilot/start',{})}>Start current pilot stage</button> <button type="button" disabled={data.pilot.state!=='running'} onClick={()=>void post('/pilot/complete-stage',{})}>Complete observed stage</button></section>
  <section className="panel"><h2>Hardening evidence</h2><p>{data.hardening.passed?'All required hardening evidence is present.':`${data.hardening.reasons.length} blocker(s) remain.`}</p><form onSubmit={hardening}><label>Check <select name="checkKey">{hardeningChecks.map(x=><option key={x}>{x}</option>)}</select></label><label>Summary <input name="summary" required/></label><label>Owner <input name="owner" required/></label><button>Record passed evidence</button></form></section>
  <section className="panel"><h2>Pilot observation</h2><p>Record only after the stage has actually been observed. Stage-specific safety rules are enforced by the server.</p><form onSubmit={observation}><label>Audience <input name="audience" required/></label><label>Started at <input type="datetime-local" name="startedAt" required/></label><label>Finished at <input type="datetime-local" name="finishedAt" required/></label><label>Approved by <input name="approvedBy" required/></label><label>Unresolved alerts <input type="number" name="unresolvedAlerts" min="0" defaultValue="0" required/></label><label><input type="checkbox" name="healthPassed" required/> Health checks passed</label><label><input type="checkbox" name="expectedEventsReceived"/> Expected events received</label><label><input type="checkbox" name="enoughFeedback"/> Enough feedback</label><label><input type="checkbox" name="withinWarmingCeiling"/> Within warming ceiling</label><label><input type="checkbox" name="completeFlowCycle"/> Complete flow cycle</label><button disabled={data.pilot.state!=='running'}>Record current-stage observation</button></form></section>
  <section className="panel"><h2>Final launch review</h2><p><strong>{data.releaseGate.allowed?'READY FOR RELEASE APPROVAL':'BLOCKED'}</strong></p>{!data.releaseGate.allowed&&<ul>{data.releaseGate.reasons.map((r:string)=><li key={r}>{r}</li>)}</ul>}<form onSubmit={launchEvidence}><label>Area <select name="area">{launchAreas.map(x=><option key={x}>{x}</option>)}</select></label><label>Summary <input name="summary" required/></label><label>Approver <input name="approver" required/></label><button>Record sign-off</button></form><form onSubmit={approveRelease}><label>Release approver <input name="approvedBy" required/></label><label>Approval notes <input name="notes" required/></label><button disabled={!data.releaseGate.allowed||data.release.status==='approved'}>Approve Release 1</button></form></section>
  <section className="panel"><h2>Open security findings</h2><pre>{JSON.stringify(data.findings.filter((x:any)=>x.status==='open'),null,2)}</pre></section>
  <section className="panel"><h2>Active stop signals</h2><pre>{JSON.stringify(data.signals.filter((x:any)=>x.active),null,2)}</pre></section>
 </>}{msg&&<pre role="alert">{msg}</pre>}</main>
}
