'use client';
import type { Rule, RuleOptions, RuleValueType, ProfileOperator } from './flow-types';
import s from './flows.module.css';
export const eligibleRule: Rule = { type: 'eligibility', operator: 'is', value: 'eligible' };
const initialRule = (type: string): Rule => {
  switch (type) {
    case 'profile': return { type, field: 'email', operator: 'contains', value: '', valueType: 'text' };
    case 'list': return { type, listId: '', operator: 'is_member' };
    case 'segment': return { type, segmentId: '', operator: 'is_member' };
    case 'consent': return { type, channel: 'email', purpose: 'marketing', operator: 'is', value: 'granted' };
    case 'suppression': return { type, operator: 'is_not_suppressed' };
    case 'email_activity': return { type, event: 'clicked', operator: 'at_least', count: 1, withinDays: 30 };
    case 'event': return { type, name: '', operator: 'at_least', count: 1, withinDays: 30 };
    case 'group': return { type, operator: 'and', children: [structuredClone(eligibleRule)] };
    default: return structuredClone(eligibleRule);
  }
};
const valueType = (type?: string): RuleValueType => type === 'number' || type === 'boolean' ? type : type === 'date' || type === 'datetime' ? 'datetime' : 'text';
function typedValue(text: string, type?: RuleValueType): string | number | boolean { return type === 'number' ? Number(text) : type === 'boolean' ? text === 'true' : text; }

export function FlowRules({ title, rules, options, onChange }: { title: string; rules: Rule[]; options: RuleOptions; onChange: (rules: Rule[]) => void }) {
  return <section className={s.ruleSection}><div className={s.sectionHeading}><h3>{title}</h3><span>{rules.length}</span></div><p className={s.hint}>{title.startsWith('Exit') ? 'A match to any exit rule ends a run before its next action.' : 'All of these rules must match to allow entry.'}</p>{rules.map((rule, index) => <div className={s.ruleCard} key={index}><RuleEditor rule={rule} options={options} onChange={value => onChange(rules.map((item, i) => i === index ? value : item))}/><button className={s.textDanger} onClick={() => onChange(rules.filter((_, i) => i !== index))}>Remove rule</button></div>)}<button className={s.secondary} onClick={() => onChange([...rules, structuredClone(eligibleRule)])}>+ Add rule</button></section>;
}

export function RuleEditor({ rule, options, onChange, depth = 1 }: { rule: Rule; options: RuleOptions; onChange: (rule: Rule) => void; depth?: number }) {
  const fieldChoices = [...options.nativeProfileFields.map(f => ({ key: f.key, label: f.label, type: valueType(f.type) })), ...options.profileProperties.map(f => ({ key: `property:${f.key}`, label: f.displayName, type: valueType(f.dataType) }))];
  return <div className={s.formStack}>
    <label>Condition<select value={rule.type} onChange={event => onChange(initialRule(event.target.value))}><option value="eligibility">Marketing eligibility</option><option value="profile">Profile property</option><option value="list">List membership</option><option value="segment">Segment membership</option><option value="consent">Email consent</option><option value="suppression">Suppression</option><option value="email_activity">Email engagement</option><option value="event">Customer event</option>{depth < 4 && <option value="group">Condition group</option>}</select></label>
    {rule.type === 'group' && <><label>Match<select value={rule.operator} onChange={e => onChange({ ...rule, operator: e.target.value === 'or' ? 'or' : 'and' })}><option value="and">All conditions (AND)</option><option value="or">Any condition (OR)</option></select></label>{rule.children.map((child, i) => <div className={s.ruleCard} key={i}><RuleEditor rule={child} options={options} depth={depth + 1} onChange={value => onChange({ ...rule, children: rule.children.map((item, index) => i === index ? value : item) })}/><button className={s.textDanger} disabled={rule.children.length === 1} onClick={() => onChange({ ...rule, children: rule.children.filter((_, index) => i !== index) })}>Remove condition</button></div>)}<button className={s.secondary} disabled={rule.children.length >= 10} onClick={() => onChange({ ...rule, children: [...rule.children, structuredClone(eligibleRule)] })}>+ Add condition</button></>}
    {rule.type === 'eligibility' && <label>Profile is<select value={rule.value} onChange={e => onChange({ ...rule, value: e.target.value === 'eligible' ? 'eligible' : 'not_eligible' })}><option value="eligible">Subscribed and not suppressed</option><option value="not_eligible">Not eligible for marketing</option></select></label>}
    {rule.type === 'consent' && <label>Marketing subscription<select value={rule.value} onChange={e => onChange({ ...rule, value: e.target.value as typeof rule.value })}><option value="granted">Subscribed</option><option value="withdrawn">Unsubscribed</option><option value="unknown">Unknown</option></select></label>}
    {rule.type === 'suppression' && <><label>Profile<select value={rule.operator} onChange={e => onChange({ ...rule, operator: e.target.value === 'is_suppressed' ? 'is_suppressed' : 'is_not_suppressed' })}><option value="is_not_suppressed">Is not suppressed</option><option value="is_suppressed">Is suppressed</option></select></label><label>Reason<select value={rule.reason ?? ''} onChange={e => onChange({ ...rule, reason: e.target.value ? e.target.value as typeof rule.reason : undefined })}><option value="">Any reason</option>{['complaint', 'global_unsubscribe', 'hard_bounce', 'category_unsubscribe', 'manual', 'administrative', 'legal'].map(reason => <option key={reason} value={reason}>{reason.replaceAll('_', ' ')}</option>)}</select></label></>}
    {(rule.type === 'list' || rule.type === 'segment') && <><label>{rule.type === 'list' ? 'List' : 'Segment'}<select value={rule.type === 'list' ? rule.listId : rule.segmentId} onChange={e => onChange(rule.type === 'list' ? { ...rule, listId: e.target.value } : { ...rule, segmentId: e.target.value })}><option value="">Choose a {rule.type}</option>{(rule.type === 'list' ? options.lists : options.segments).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Membership<select value={rule.operator} onChange={e => onChange({ ...rule, operator: e.target.value === 'is_member' ? 'is_member' : 'is_not_member' })}><option value="is_member">Is a member</option><option value="is_not_member">Is not a member</option></select></label></>}
    {rule.type === 'profile' && <><label>Property<select value={rule.field} onChange={e => { const field = fieldChoices.find(f => f.key === e.target.value); onChange({ ...rule, field: e.target.value as typeof rule.field, valueType: field?.type, operator: 'eq', value: field?.type === 'boolean' ? true : field?.type === 'number' ? 0 : '', valueTo: undefined }); }}><option value="">Choose property</option>{fieldChoices.map(f => <option key={f.key} value={f.key}>{f.label}</option>)}</select></label><Comparison type={rule.valueType} operator={rule.operator} value={rule.value} valueTo={rule.valueTo} withinDays={rule.withinDays} onChange={patch => onChange({ ...rule, ...patch })}/></>}
    {rule.type === 'email_activity' && <><label>Event<select value={rule.event} onChange={e => onChange({ ...rule, event: e.target.value as typeof rule.event, emailVersionId: e.target.value === 'unsubscribed' ? undefined : rule.emailVersionId })}>{['sent', 'delivered', 'clicked', 'opened', 'bounced', 'complained', 'unsubscribed'].map(item => <option key={item}>{item}</option>)}</select></label>{rule.event !== 'unsubscribed' && <label>Email<select value={rule.emailVersionId ?? ''} onChange={e => onChange({ ...rule, emailVersionId: e.target.value || undefined })}><option value="">Any email</option>{options.emails.map(email => <option key={email.id} value={email.id}>{email.name} · v{email.versionNumber}</option>)}</select></label>}</>}
    {rule.type === 'event' && <><label>Registered event<select value={`${rule.name}|${rule.schemaVersion ?? ''}`} onChange={e => { const [name, version] = e.target.value.split('|'); onChange({ ...rule, name, schemaVersion: Number(version), property: undefined }); }}><option value="|">Choose event</option>{options.events.map(event => <option key={`${event.name}|${event.schemaVersion}`} value={`${event.name}|${event.schemaVersion}`}>{event.name} · v{event.schemaVersion}</option>)}</select></label><label>Event property (optional)<select value={rule.property?.key ?? ''} onChange={e => { const event = options.events.find(item => item.name === rule.name && item.schemaVersion === rule.schemaVersion); const type = valueType(event?.properties?.[e.target.value]?.type); onChange({ ...rule, property: e.target.value ? { key: e.target.value, valueType: type, operator: 'exists' } : undefined }); }}><option value="">No property filter</option>{Object.keys(options.events.find(item => item.name === rule.name && item.schemaVersion === rule.schemaVersion)?.properties ?? {}).map(key => <option key={key}>{key}</option>)}</select></label>{rule.property && <Comparison type={rule.property.valueType} {...rule.property} onChange={patch => onChange({ ...rule, property: { ...rule.property!, ...patch } })}/>}</>}
    {(rule.type === 'email_activity' || rule.type === 'event') && <><div className={s.twoFields}><label>Happened<select value={rule.operator} onChange={e => onChange({ ...rule, operator: e.target.value as typeof rule.operator })}><option value="at_least">At least</option><option value="exactly">Exactly</option><option value="at_most">At most</option></select></label><label>Times<input type="number" min={0} max={1000} value={rule.count} onChange={e => onChange({ ...rule, count: Number(e.target.value) })}/></label></div><label>Within the last (days)<input type="number" min={1} max={365} value={rule.withinDays} onChange={e => onChange({ ...rule, withinDays: Number(e.target.value) })}/></label></>}
  </div>;
}
type ComparisonPatch = { operator?: ProfileOperator; value?: string | number | boolean; valueTo?: string | number; withinDays?: number };
function Comparison({ type, operator, value, valueTo, withinDays, onChange }: { type?: RuleValueType; operator: ProfileOperator; value?: string | number | boolean; valueTo?: string | number; withinDays?: number; onChange: (patch: ComparisonPatch) => void }) {
  const operators: ProfileOperator[] = type === 'boolean' ? ['eq', 'neq', 'exists', 'not_exists'] : type === 'number' ? ['eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'between', 'exists', 'not_exists'] : type === 'datetime' ? ['before', 'after', 'between', 'within_last', 'exists', 'not_exists', 'eq'] : ['eq', 'neq', 'contains', 'does_not_contain', 'starts_with', 'ends_with', 'exists', 'not_exists'];
  const labels: Record<ProfileOperator, string> = { eq: 'Equals', neq: 'Does not equal', contains: 'Contains', does_not_contain: 'Does not contain', starts_with: 'Starts with', ends_with: 'Ends with', exists: 'Is set', not_exists: 'Is not set', gt: 'Greater than', gte: 'Greater than or equal', lt: 'Less than', lte: 'Less than or equal', between: 'Is between', before: 'Is before', after: 'Is after', within_last: 'Is within the last' };
  const needsValue = operator !== 'exists' && operator !== 'not_exists' && operator !== 'within_last';
  return <><label>Comparison<select value={operator} onChange={e => onChange({ operator: e.target.value as ProfileOperator })}>{[...new Set([operator, ...operators])].map(op => <option value={op} key={op}>{labels[op]}</option>)}</select></label>{operator === 'within_last' ? <label>Days<input type="number" min={1} max={365} value={withinDays ?? 30} onChange={e => onChange({ withinDays: Number(e.target.value) })}/></label> : needsValue && <label>Value{type === 'boolean' ? <select value={String(value ?? true)} onChange={e => onChange({ value: e.target.value === 'true' })}><option>true</option><option>false</option></select> : <input type={type === 'number' ? 'number' : type === 'datetime' ? 'datetime-local' : 'text'} placeholder={type === 'datetime' ? 'Choose date and time' : 'Enter value'} value={String(value ?? '')} onChange={e => onChange({ value: typedValue(e.target.value, type) })}/>}</label>}{operator === 'between' && <label>Upper value<input type={type === 'number' ? 'number' : type === 'datetime' ? 'datetime-local' : 'text'} value={String(valueTo ?? '')} onChange={e => onChange({ valueTo: type === 'number' ? Number(e.target.value) : e.target.value })}/></label>}</>;
}
