'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { phase3Api } from '../../lib/phase3-api';
import type { FlowDetail, Profile } from './flow-types';
import { profileName } from './flow-types';
import { FlowIcon, Status } from './flow-ui';
import s from './flow-activity.module.css';

type Tab = 'runs' | 'messages' | 'performance' | 'versions' | 'changes';
type Run = { id: string; profileId: string; profile?: Profile | null; flowVersionId: string; versionNumber?: number | null; state: string; currentNodeId: string; enteredAt: string; nextActionAt?: string | null; endedAt?: string | null; exitReason?: string | null };
type RunResponse = { items: Run[]; nextCursor: string | null; report: Record<string, number> };
type DeliveryMessage = { id: string; profileId: string; profile?: Profile | null; nodeId?: string | null; state: string; createdAt: string; scheduledFor: string; submittedAt?: string | null; emailVersion?: { versionNumber: number; emailDefinitionId: string } | null; delivery?: { eventType: string; occurredAt?: string } | null; policyHold?: { explanation?: string } | null; attempt?: { explanation?: string; errorCode?: string } | null };
type Metrics = { period: { days: number; from: string; to: string }; freshness: string; entries: number; runStates: Record<string, number>; messages: { created: number; submitted: number; delivered: number; bounced: number; complained: number }; rates: { bounce: number; complaint: number } };
type Version = { id: string; versionNumber: number; publishedAt: string; graphHash: string };
type Audit = { id: string; action: string; actorId?: string | null; riskLevel: string; occurredAt: string; objectId?: string | null };
type DeadLetter = { id: string; jobType: string; resourceId: string; state: string; failureCode?: string; createdAt?: string };
type Trace = { run: Run; events: { kind: string; occurredAt: string; detail?: Record<string, unknown> }[]; executions: { id: string; nodeId: string; state: string; startedAt?: string; completedAt?: string; scheduledAt?: string; errorJson?: unknown }[]; messages: { id: string; nodeId?: string; state: string }[] };
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const stateHelp: Record<string, string> = { active: 'Moving through the journey', waiting: 'Scheduled for a future step', held: 'Stopped by a delivery or policy check', completed: 'Reached the end of the journey', exited: 'Ended because an exit rule matched', failed: 'A step could not finish', cancelled: 'Stopped when the flow was paused' };

export function FlowActivityV2({ workspaceId, flowId }: { workspaceId: string; flowId: string }) {
  const [flow, setFlow] = useState<FlowDetail | null>(null), [runs, setRuns] = useState<RunResponse | null>(null), [messages, setMessages] = useState<DeliveryMessage[]>([]), [metrics, setMetrics] = useState<Metrics | null>(null), [versions, setVersions] = useState<Version[]>([]), [changes, setChanges] = useState<Audit[]>([]), [dead, setDead] = useState<DeadLetter[]>([]);
  const [tab, setTab] = useState<Tab>('runs'), [state, setState] = useState('all'), [query, setQuery] = useState(''), [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [autoRefresh, setAutoRefresh] = useState(true), [message, setMessage] = useState(''), [trace, setTrace] = useState<Trace | null>(null);
  const load = useCallback(async (quiet = false) => {
    quiet ? setRefreshing(true) : setLoading(true);
    try {
      const stateQuery = state === 'all' ? '' : `?state=${encodeURIComponent(state)}`;
      const [detail, runRows, messageRows, metricRows, versionRows, auditRows, deadRows] = await Promise.all([
        phase3Api<FlowDetail>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}`),
        phase3Api<RunResponse>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/runs${stateQuery}`),
        phase3Api<{ items: DeliveryMessage[] }>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/messages`),
        phase3Api<Metrics>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/analytics?days=7`).catch(() => null),
        phase3Api<{ items: Version[] }>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/versions`),
        phase3Api<{ items: Audit[] }>(`/api/v1/workspaces/${workspaceId}/audit?objectType=flow`),
        phase3Api<{ items: DeadLetter[] }>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/dead-letters`),
      ]);
      setFlow(detail); setRuns(runRows); setMessages(messageRows.items); setMetrics(metricRows); setVersions(versionRows.items); setChanges(auditRows.items.filter(item => item.objectId === flowId)); setDead(deadRows.items); setMessage('');
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load flow activity.'); }
    finally { setLoading(false); setRefreshing(false); }
  }, [workspaceId, flowId, state]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!autoRefresh) return; const timer = setInterval(() => void load(true), 15000); return () => clearInterval(timer); }, [autoRefresh, load]);
  async function openRun(id: string) { try { setTrace(await phase3Api<Trace>(`/api/v1/workspaces/${workspaceId}/flow-runs/${id}`)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to open this run.'); } }
  async function replay(id: string) { try { await phase3Api(`/api/v1/workspaces/${workspaceId}/dead-letters/${id}/replay`, { method: 'POST', body: '{}' }); setMessage('Recovery was queued with the original business identity.'); await load(true); } catch (error) { setMessage(error instanceof Error ? error.message : 'Recovery is not available.'); } }
  const visibleRuns = useMemo(() => (runs?.items ?? []).filter(run => !query.trim() || profileName(run.profile ?? { id: run.profileId }).toLowerCase().includes(query.toLowerCase()) || run.id.includes(query)), [runs, query]);
  const report = runs?.report ?? {};
  if (loading && !flow) return <div className={s.loading}><span/><p>Loading flow activity…</p></div>;
  return <div className={s.shell}>
    <header className={s.header}><a className={s.iconButton} href={`/w/${workspaceId}/flows`} aria-label="Back to flows"><FlowIcon name="back"/></a><div className={s.heading}><small>FLOW ACTIVITY</small><h1>{flow?.name ?? 'Flow'}</h1></div><nav><a href={`/w/${workspaceId}/flows/${flowId}/builder`}>Builder</a><a className={s.active} href={`/w/${workspaceId}/flows/${flowId}/runs`}>Activity</a></nav><div className={s.headerActions}>{flow && <Status value={flow.status}/>}<label className={s.liveToggle}><input type="checkbox" checked={autoRefresh} onChange={e => setAutoRefresh(e.target.checked)}/><span/>Live updates</label><button className={s.secondary} disabled={refreshing} onClick={() => void load(true)}><FlowIcon name="refresh"/>{refreshing ? 'Refreshing…' : 'Refresh'}</button></div></header>
    <main className={s.content}>
      <section className={s.summary}><Metric label="Entered" value={metrics?.entries ?? report.entered ?? 0} detail="last 7 days"/><Metric label="Active now" value={report.active ?? 0} detail="in progress"/><Metric label="Waiting" value={report.waiting ?? 0} detail="scheduled"/><Metric label="Completed" value={report.completed ?? 0} detail="finished"/><Metric label="Delivered" value={metrics?.messages.delivered ?? 0} detail={`${metrics?.messages.submitted ?? 0} submitted`}/><Metric label="Needs attention" value={(report.held ?? 0) + (report.failed ?? 0) + dead.length} detail="held, failed, recovery" danger={(report.held ?? 0) + (report.failed ?? 0) + dead.length > 0}/></section>
      {dead.length > 0 && <section className={s.alert}><span><FlowIcon name="activity"/></span><div><strong>{dead.length} operational failure{dead.length === 1 ? '' : 's'} need attention</strong><p>These are platform execution failures, separate from contacts who simply did not match entry rules.</p></div><button className={s.secondary} onClick={() => setTab('runs')}>Review recovery</button></section>}
      <nav className={s.tabs}>{([['runs', 'Runs'], ['messages', 'Messages'], ['performance', 'Performance'], ['versions', 'Versions'], ['changes', 'Change log']] as [Tab, string][]).map(([key, label]) => <button key={key} data-active={tab === key} onClick={() => setTab(key)}>{label}{key === 'runs' && <span>{runs?.items.length ?? 0}</span>}{key === 'messages' && <span>{messages.length}</span>}</button>)}</nav>
      <section className={s.panel}>{tab === 'runs' && <RunsView runs={visibleRuns} state={state} query={query} report={report} dead={dead} setState={setState} setQuery={setQuery} openRun={openRun} replay={replay}/>} {tab === 'messages' && <MessagesView messages={messages}/>} {tab === 'performance' && <PerformanceView metrics={metrics}/>} {tab === 'versions' && <VersionsView versions={versions} activeId={flow?.activeVersionId}/>} {tab === 'changes' && <ChangesView changes={changes}/>}</section>
    </main>
    {trace && <TraceDrawer trace={trace} close={() => setTrace(null)}/>} {message && <div className={s.toast} role="status">{message}<button onClick={() => setMessage('')}><FlowIcon name="close"/></button></div>}
  </div>;
}

function Metric({ label, value, detail, danger = false }: { label: string; value: number; detail: string; danger?: boolean }) { return <article className={s.metric} data-danger={danger}><span>{label}</span><strong>{value.toLocaleString()}</strong><small>{detail}</small></article>; }
function RunsView({ runs, state, query, report, dead, setState, setQuery, openRun, replay }: { runs: Run[]; state: string; query: string; report: Record<string, number>; dead: DeadLetter[]; setState: (value: string) => void; setQuery: (value: string) => void; openRun: (id: string) => Promise<void>; replay: (id: string) => Promise<void> }) { return <><div className={s.panelToolbar}><div><h2>Contact journeys</h2><p>Every entry is pinned to the version that was live at the time.</p></div><label className={s.search}><FlowIcon name="search"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search profile or run ID"/></label><select value={state} onChange={e => setState(e.target.value)}><option value="all">All states</option>{['active', 'waiting', 'held', 'completed', 'exited', 'failed', 'cancelled'].map(item => <option key={item} value={item}>{item} ({report[item] ?? 0})</option>)}</select></div><div className={s.tableWrap}><table><thead><tr><th>Profile</th><th>Status</th><th>Current step</th><th>Entered</th><th>Next action</th><th>Version</th></tr></thead><tbody>{runs.map(run => <tr key={run.id} onClick={() => void openRun(run.id)}><td><strong>{profileName(run.profile ?? { id: run.profileId })}</strong><small>{run.id.slice(0, 8)}</small></td><td><Status value={run.state}/><small>{stateHelp[run.state]}</small></td><td>{run.currentNodeId}</td><td>{formatDate(run.enteredAt)}</td><td>{run.exitReason ?? formatDate(run.nextActionAt)}</td><td>v{run.versionNumber ?? '—'}</td></tr>)}</tbody></table>{!runs.length && <Empty title="No runs found" text="New qualifying contacts will appear here after the flow is activated."/>}</div>{dead.length > 0 && <section className={s.recovery}><h3>Recovery queue</h3>{dead.map(item => <article key={item.id}><div><strong>{item.jobType}</strong><span>{item.failureCode ?? 'Execution stopped after repeated attempts'}</span></div><Status value={item.state}/><button className={s.secondary} disabled={item.state !== 'open'} onClick={() => void replay(item.id)}>Retry safely</button></article>)}</section>}</>; }
function MessagesView({ messages }: { messages: DeliveryMessage[] }) { return <><div className={s.panelToolbar}><div><h2>Email delivery</h2><p>Submitted means the provider accepted the email. Delivered means a provider event confirmed it.</p></div></div><div className={s.tableWrap}><table><thead><tr><th>Recipient</th><th>Message state</th><th>Email</th><th>Created</th><th>Latest delivery detail</th></tr></thead><tbody>{messages.map(row => <tr key={row.id}><td><strong>{profileName(row.profile ?? { id: row.profileId })}</strong><small>{row.profile?.originalEmail}</small></td><td><Status value={row.state}/><small>{row.submittedAt ? `Submitted ${formatDate(row.submittedAt)}` : 'Not submitted to provider'}</small></td><td>Version {row.emailVersion?.versionNumber ?? '—'}<small>{row.nodeId}</small></td><td>{formatDate(row.createdAt)}</td><td>{row.delivery?.eventType ?? row.policyHold?.explanation ?? row.attempt?.explanation ?? (row.state === 'held' ? 'Waiting for delivery policy' : 'No provider event yet')}</td></tr>)}</tbody></table>{!messages.length && <Empty title="No messages yet" text="A message appears only after a contact reaches a configured Email step."/>}</div></>; }
function PerformanceView({ metrics }: { metrics: Metrics | null }) { if (!metrics) return <Empty title="Performance unavailable" text="This role cannot read analytics, or the flow has no reportable activity yet."/>; const submitted = metrics.messages.submitted || 1; return <div className={s.performance}><header><div><h2>Last {metrics.period.days} days</h2><p>Updated {formatDate(metrics.freshness)}</p></div></header><div className={s.performanceGrid}><Metric label="Entries" value={metrics.entries} detail="contacts entering"/><Metric label="Messages created" value={metrics.messages.created} detail="email steps reached"/><Metric label="Submit rate" value={Math.round(metrics.messages.submitted / Math.max(metrics.messages.created, 1) * 100)} detail={`${metrics.messages.submitted} submitted`}/><Metric label="Delivery rate" value={Math.round(metrics.messages.delivered / submitted * 100)} detail={`${metrics.messages.delivered} delivered`}/><Metric label="Bounces" value={metrics.messages.bounced} detail={`${(metrics.rates.bounce * 100).toFixed(2)}% rate`} danger={metrics.messages.bounced > 0}/><Metric label="Complaints" value={metrics.messages.complained} detail={`${(metrics.rates.complaint * 100).toFixed(3)}% rate`} danger={metrics.messages.complained > 0}/></div></div>; }
function VersionsView({ versions, activeId }: { versions: Version[]; activeId?: string | null }) { return <><div className={s.panelToolbar}><div><h2>Published versions</h2><p>Existing runs never change when you publish a new draft.</p></div></div><div className={s.versionList}>{versions.map(version => <article key={version.id}><span>v{version.versionNumber}</span><div><strong>{version.id === activeId ? 'Current active version' : 'Immutable snapshot'}</strong><small>Published {formatDate(version.publishedAt)} · {version.graphHash.slice(0, 14)}…</small></div>{version.id === activeId && <Status value="active"/>}</article>)}{!versions.length && <Empty title="No versions published" text="Review and turn on the flow to create its first immutable version."/>}</div></>; }
function ChangesView({ changes }: { changes: Audit[] }) { return <><div className={s.panelToolbar}><div><h2>Change log</h2><p>Workspace-scoped audit history for this flow.</p></div></div><div className={s.timeline}>{changes.map(change => <article key={change.id}><span><FlowIcon name="activity"/></span><div><strong>{change.action.replaceAll('.', ' ')}</strong><small>{formatDate(change.occurredAt)} · {change.actorId ? `Actor ${change.actorId.slice(0, 8)}` : 'System'} · {change.riskLevel} risk</small></div></article>)}{!changes.length && <Empty title="No changes recorded" text="Saved edits, publishing, activation, and operational actions appear here."/>}</div></>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className={s.empty}><span><FlowIcon name="flow" size={25}/></span><strong>{title}</strong><p>{text}</p></div>; }
function TraceDrawer({ trace, close }: { trace: Trace; close: () => void }) { return <aside className={s.drawer}><header><div><small>RUN TRACE</small><h2>{profileName(trace.run.profile ?? { id: trace.run.profileId })}</h2><p>Entered {formatDate(trace.run.enteredAt)} · version {trace.run.versionNumber ?? '—'}</p></div><button className={s.iconButton} onClick={close}><FlowIcon name="close"/></button></header><section className={s.traceSummary}><Status value={trace.run.state}/><span>{stateHelp[trace.run.state] ?? trace.run.exitReason ?? 'Run activity'}</span></section><ol>{trace.events.map((event, index) => <li key={`${event.kind}-${index}`}><span>{index + 1}</span><div><strong>{event.kind.replaceAll('.', ' ')}</strong><small>{formatDate(event.occurredAt)}</small>{event.detail && <code>{JSON.stringify(event.detail)}</code>}</div></li>)}</ol>{!trace.events.length && <Empty title="No trace events" text="This run has not recorded a node transition yet."/>}</aside>; }
