import { Prisma, type PrismaClient } from "@prisma/client";
import type { Phase1Repository, DbWorkspace, DbMember, DbProfile, DbPropertyDefinition, DbAudienceList, DbSenderDomain, DbSenderIdentity, DbImportJob, DbExportJob, DbWorkspaceProviderConfig } from "../../../application/src/ports/phase1-repository.js";
import type { Role } from "../../../domain/src/phase1/permissions.js";
import type { ConsentStatus, SuppressionReason } from "../../../domain/src/phase1/consent.js";
import type { PropertyType } from "../../../domain/src/phase1/profile.js";
import type { ImportMapping, ImportPolicy } from "../../../domain/src/phase1/import-policy.js";

function workspace(x:any):DbWorkspace{return {id:x.id,name:x.name,legalName:x.legalName,businessAddress:x.businessAddress,timezone:x.timezone,locale:x.locale,status:x.status,rowVersion:x.rowVersion}}
function member(x:any):DbMember{return {id:x.id,workspaceId:x.workspaceId,userId:x.userId,role:x.role as Role,status:x.status,email:x.user?.email,displayName:x.user?.displayName,invitedBy:x.invitedBy,createdAt:x.createdAt,updatedAt:x.updatedAt}}
function profile(x:any):DbProfile{return {id:x.id,workspaceId:x.workspaceId,normalizedEmail:x.normalizedEmail,originalEmail:x.originalEmail,firstName:x.firstName,lastName:x.lastName,locale:x.locale,timezone:x.timezone,countryCode:x.countryCode,region:x.region,city:x.city,source:x.source,rowVersion:x.rowVersion,deletedAt:x.deletedAt}}
function list(x:any):DbAudienceList{return {id:x.id,workspaceId:x.workspaceId,name:x.name,description:x.description,status:x.status,archivedAt:x.archivedAt}}
function domain(x:any):DbSenderDomain{return {id:x.id,workspaceId:x.workspaceId,workspacePrimary:x.workspacePrimary,domain:x.domain,sendingPurpose:x.sendingPurpose,status:x.status,expectedRecords:x.expectedRecords,observedRecords:x.observedRecords,providerReference:x.providerReference,providerRegion:x.providerRegion,providerStatus:x.providerStatus,providerEvidence:x.providerEvidence,dkimStatus:x.dkimStatus,mailFromStatus:x.mailFromStatus,dmarcStatus:x.dmarcStatus,lastCheckedAt:x.lastCheckedAt,verifiedAt:x.verifiedAt,rootDomain:x.rootDomain,delegatedSubdomain:x.delegatedSubdomain,provisioningMode:x.provisioningMode??"legacy_ses_records",provisioningVersion:x.provisioningVersion??"V1_LEGACY_SEND_SUBDOMAIN",provisioningCallerReference:x.provisioningCallerReference,dkimTokens:x.dkimTokens,dkimSigningHostedZone:x.dkimSigningHostedZone,ownershipVerificationToken:x.ownershipVerificationToken,ownershipVerificationTokenHash:x.ownershipVerificationTokenHash,ownershipVerificationStatus:x.ownershipVerificationStatus,ownershipVerifiedAt:x.ownershipVerifiedAt,dkimSigningMode:x.dkimSigningMode,dkimSigningDomain:x.dkimSigningDomain,dkimSelector:x.dkimSelector,dkimPublicKey:x.dkimPublicKey,dkimPrivateKeySecretRef:x.dkimPrivateKeySecretRef,dkimStandbySelector:x.dkimStandbySelector,dkimStandbyPublicKey:x.dkimStandbyPublicKey,dkimStandbyPrivateKeySecretRef:x.dkimStandbyPrivateKeySecretRef,dkimRotationState:x.dkimRotationState,dkimRotationGraceUntil:x.dkimRotationGraceUntil,setupMode:x.setupMode,routingId:x.routingId,dnsStatus:x.dnsStatus,verificationStatus:x.verificationStatus,delegationStatus:x.delegationStatus,soaStatus:x.soaStatus,dmarcObservation:x.dmarcObservation,lifecycleState:x.lifecycleState??"created",authenticationStatus:x.authenticationStatus??"pending",readinessStatus:x.readinessStatus??"not_ready",readinessReasons:x.readinessReasons,dnsProvider:x.dnsProvider,hostedZoneReference:x.hostedZoneReference,delegationSetReference:x.delegationSetReference,mailFromDomain:x.mailFromDomain,trackingDomain:x.trackingDomain,trackingProvider:x.trackingProvider,trackingTenantReference:x.trackingTenantReference,trackingConnectionGroupReference:x.trackingConnectionGroupReference,trackingRoutingEndpoint:x.trackingRoutingEndpoint,trackingCertificateReference:x.trackingCertificateReference,trackingCertificateStatus:x.trackingCertificateStatus,trackingHttpsStatus:x.trackingHttpsStatus,trackingValidationMethod:x.trackingValidationMethod,lastErrorCode:x.lastErrorCode,lastErrorMessage:x.lastErrorMessage,archivedAt:x.archivedAt} as DbSenderDomain}
function providerConfig(x:any):DbWorkspaceProviderConfig{return {workspaceId:x.workspaceId,provider:x.provider,region:x.region,sesTenantName:x.sesTenantName,configurationSetName:x.configurationSetName,providerStatus:x.providerStatus}}
function identity(x:any):DbSenderIdentity{return {id:x.id,workspaceId:x.workspaceId,domainId:x.domainId,fromName:x.fromName,fromEmail:x.fromEmail,replyTo:x.replyTo,purpose:x.purpose as "marketing"|"transactional",status:x.status}}
function importJob(x:any):DbImportJob{return {id:x.id,workspaceId:x.workspaceId,state:x.state,objectKey:x.objectKey,originalName:x.originalName,contentHash:x.contentHash,mapping:x.mappingJson as ImportMapping|null,policy:x.policyJson as ImportPolicy|null,totals:x.totalsJson,createdBy:x.createdBy,createdAt:x.createdAt,completedAt:x.completedAt}}
function exportJob(x:any):DbExportJob{return {id:x.id,workspaceId:x.workspaceId,state:x.state,scope:x.scopeJson,fields:Array.isArray(x.fieldsJson)?x.fieldsJson:[],purpose:x.purpose,objectKey:x.objectKey,tokenHash:x.tokenHash,expiresAt:x.expiresAt,recordCount:x.recordCount,createdBy:x.createdBy}}

export class PrismaPhase1Repository implements Phase1Repository {
  constructor(private readonly db:PrismaClient|Prisma.TransactionClient){}
  async transaction<T>(fn:(tx:Phase1Repository)=>Promise<T>):Promise<T>{
    if (!("$transaction" in this.db)) return fn(this);
    return (this.db as PrismaClient).$transaction(async tx=>fn(new PrismaPhase1Repository(tx)),{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
  }
  async ensureUser(input:{provider:string;subject:string;email:string;displayName?:string}){const row=await (this.db as any).userIdentity.upsert({where:{provider_providerSubject:{provider:input.provider,providerSubject:input.subject}},create:{provider:input.provider,providerSubject:input.subject,email:input.email,displayName:input.displayName,status:"active"},update:{email:input.email,displayName:input.displayName,status:"active"}});return {id:row.id,email:row.email}}
  async createWorkspace(input:{userId:string;name:string;legalName:string;businessAddress:string;timezone:string;locale:string}){const row=await (this.db as any).workspace.create({data:{name:input.name,legalName:input.legalName,businessAddress:input.businessAddress,timezone:input.timezone,locale:input.locale,status:"setup"}});await (this.db as any).workspaceMember.create({data:{workspaceId:row.id,userId:input.userId,role:"owner",status:"active"}});return workspace(row)}
  async listWorkspacesForUser(userId:string){const memberships=await (this.db as any).workspaceMember.findMany({where:{userId,status:"active"},select:{workspaceId:true}});const ids=memberships.map((m:any)=>m.workspaceId);if(!ids.length)return [];return (await (this.db as any).workspace.findMany({where:{id:{in:ids}},orderBy:{createdAt:"asc"}})).map(workspace)}
  async findWorkspace(id:string){const x=await (this.db as any).workspace.findUnique({where:{id}});return x?workspace(x):null}
  async updateWorkspace(id:string,expected:bigint,patch:any){const result=await (this.db as any).workspace.updateMany({where:{id,rowVersion:expected},data:{...patch,rowVersion:{increment:1}}});if(result.count!==1)throw new Error("CONCURRENCY_CONFLICT");const x=await (this.db as any).workspace.findUniqueOrThrow({where:{id}});return workspace(x)}
  async findMember(workspaceId:string,userId:string){const x=await (this.db as any).workspaceMember.findUnique({where:{workspaceId_userId:{workspaceId,userId}}});return x&&x.status==="active"?member(x):null}
  async listMembers(workspaceId:string){const db=this.db as any,rows=await db.workspaceMember.findMany({where:{workspaceId},orderBy:{createdAt:"asc"}}),users=rows.length?await db.userIdentity.findMany({where:{id:{in:rows.map((row:{userId:string})=>row.userId)}},select:{id:true,email:true,displayName:true}}):[],byId=new Map(users.map((user:{id:string;email:string;displayName:string|null})=>[user.id,user]));return rows.map((row:{userId:string})=>member({...row,user:byId.get(row.userId)}))}
  async createInvitation(input:{workspaceId:string;email:string;role:Role;tokenHash:string;invitedBy:string;expiresAt:Date}){const x=await (this.db as any).workspaceInvitation.create({data:input});return {id:x.id}}
  async acceptInvitation(tokenHash:string,email:string,userId:string){const inv=await (this.db as any).workspaceInvitation.findFirst({where:{tokenHash,email,acceptedAt:null,revokedAt:null,expiresAt:{gt:new Date()}}});if(!inv)throw new Error("INVITATION_INVALID");const result=await (this.db as any).workspaceMember.upsert({where:{workspaceId_userId:{workspaceId:inv.workspaceId,userId}},create:{workspaceId:inv.workspaceId,userId,role:inv.role,status:"active",invitedBy:inv.invitedBy},update:{role:inv.role,status:"active"}});await (this.db as any).workspaceInvitation.update({where:{id:inv.id},data:{acceptedAt:new Date()}});return member(result)}
  async updateMemberRole(workspaceId:string,memberId:string,role:Role){const x=await (this.db as any).workspaceMember.findFirst({where:{id:memberId,workspaceId}});if(!x)throw new Error("NOT_FOUND");if(x.role==="owner"&&role!=="owner"){const owners=await (this.db as any).workspaceMember.count({where:{workspaceId,role:"owner",status:"active"}});if(owners<=1)throw new Error("LAST_OWNER_PROTECTED")}return member(await (this.db as any).workspaceMember.update({where:{id:memberId},data:{role}}))}
  async revokeMember(workspaceId:string,memberId:string){return this.transaction(async tx=>{const db=(tx as PrismaPhase1Repository).db as any,current=await db.workspaceMember.findFirst({where:{id:memberId,workspaceId}});if(!current)throw new Error("NOT_FOUND");if(current.role==="owner"&&current.status==="active"){const owners=await db.workspaceMember.count({where:{workspaceId,role:"owner",status:"active"}});if(owners<=1)throw new Error("LAST_OWNER_PROTECTED")}return member(await db.workspaceMember.update({where:{id:memberId},data:{status:"revoked"}}))})}
  async transferOwnership(workspaceId:string,fromMemberId:string,toMemberId:string){return this.transaction(async tx=>{const db=(tx as PrismaPhase1Repository).db as any,[from,to]=await Promise.all([db.workspaceMember.findFirst({where:{id:fromMemberId,workspaceId,status:"active"}}),db.workspaceMember.findFirst({where:{id:toMemberId,workspaceId,status:"active"}})]);if(!from||!to)throw new Error("MEMBER_NOT_FOUND");if(from.role!=="owner")throw new Error("OWNER_REQUIRED");if(from.id===to.id)throw new Error("OWNERSHIP_TARGET_INVALID");const nextTo=await db.workspaceMember.update({where:{id:to.id},data:{role:"owner"}}),nextFrom=await db.workspaceMember.update({where:{id:from.id},data:{role:"admin"}});return {from:member(nextFrom),to:member(nextTo)}})}

  async upsertProfile(input:{workspaceId:string;email:string;normalizedEmail:string;firstName?:string;lastName?:string;locale?:string;timezone?:string;countryCode?:string;region?:string;city?:string;source:string;expectedRowVersion?:bigint}){return this.transaction(async tx=>{const repo=tx as PrismaPhase1Repository;const db=repo.db as any;const old=await repo.findProfileByEmail(input.workspaceId,input.normalizedEmail);const patch:any={lastSeenAt:new Date(),rowVersion:{increment:1}};for(const key of ["firstName","lastName","locale","timezone","countryCode","region","city"] as const)if(input[key]!==undefined)patch[key]=input[key]||null;if(!old){const deleted=await db.profile.findFirst({where:{workspaceId:input.workspaceId,normalizedEmail:input.normalizedEmail,deletedAt:{not:null}}});if(deleted){const restore:any={deletedAt:null,originalEmail:input.email,source:input.source,...patch};const x=await db.profile.update({where:{id:deleted.id},data:restore});return {profile:profile(x),created:true,before:profile(deleted)}}try{const x=await db.profile.create({data:{workspaceId:input.workspaceId,normalizedEmail:input.normalizedEmail,originalEmail:input.email,firstName:input.firstName||null,lastName:input.lastName||null,locale:input.locale||null,timezone:input.timezone||null,countryCode:input.countryCode||null,region:input.region||null,city:input.city||null,source:input.source}});await db.profileIdentifier.create({data:{workspaceId:input.workspaceId,profileId:x.id,kind:"email",normalizedValue:input.normalizedEmail,originalValue:input.email,source:input.source,isPrimary:true}});return {profile:profile(x),created:true}}catch(error:any){if(error?.code!=="P2002")throw error;const existing=await db.profile.findFirst({where:{workspaceId:input.workspaceId,normalizedEmail:input.normalizedEmail}});if(!existing)throw error;const res=await db.profile.updateMany({where:{id:existing.id,workspaceId:input.workspaceId,rowVersion:existing.rowVersion},data:{...patch,deletedAt:null,originalEmail:input.email,source:input.source}});if(res.count!==1)throw new Error("CONCURRENCY_CONFLICT");const x=await db.profile.findUniqueOrThrow({where:{id:existing.id}});return {profile:profile(x),created:false,before:profile(existing)}}}if(input.expectedRowVersion!==undefined&&old.rowVersion!==input.expectedRowVersion)throw new Error("CONCURRENCY_CONFLICT");const res=await db.profile.updateMany({where:{id:old.id,workspaceId:input.workspaceId,rowVersion:old.rowVersion,deletedAt:null},data:patch});if(res.count!==1)throw new Error("CONCURRENCY_CONFLICT");const x=await db.profile.findUniqueOrThrow({where:{id:old.id}});return {profile:profile(x),created:false,before:old}})}
  async findProfile(workspaceId:string,id:string){const x=await (this.db as any).profile.findFirst({where:{id,workspaceId,deletedAt:null}});return x?profile(x):null}
  async findProfileByEmail(workspaceId:string,normalizedEmail:string){const x=await (this.db as any).profile.findFirst({where:{workspaceId,normalizedEmail,deletedAt:null}});return x?profile(x):null}
  async listProfiles(input:{workspaceId:string;q?:string;limit:number;cursorId?:string|null}){const where:any={workspaceId:input.workspaceId,deletedAt:null};if(input.q)where.OR=[{normalizedEmail:{contains:input.q,mode:"insensitive"}},{firstName:{contains:input.q,mode:"insensitive"}},{lastName:{contains:input.q,mode:"insensitive"}}];return (await (this.db as any).profile.findMany({where,orderBy:{id:"asc"},take:Math.min(Math.max(input.limit,1),201),...(input.cursorId?{cursor:{id:input.cursorId},skip:1}:{})})).map(profile)}
  async profileTimeline(workspaceId:string,profileId:string){const [audit,consent,suppressions,memberships]=await Promise.all([(this.db as any).auditEvent.findMany({where:{workspaceId,OR:[{objectId:profileId},{afterJson:{path:["profileId"],equals:profileId}}]},orderBy:{occurredAt:"asc"}}),(this.db as any).consentRecord.findMany({where:{workspaceId,profileId},orderBy:{occurredAt:"asc"}}),(this.db as any).suppression.findMany({where:{workspaceId,profileId},orderBy:{createdAt:"asc"}}),(this.db as any).listMembership.findMany({where:{workspaceId,profileId},orderBy:{joinedAt:"asc"}})]);const out:any[]=[];for(const x of audit)out.push({id:x.id,kind:x.action,occurredAt:x.occurredAt,detail:{objectType:x.objectType,objectId:x.objectId,riskLevel:x.riskLevel}});for(const x of consent)out.push({id:x.id,kind:"consent",occurredAt:x.occurredAt,detail:{status:x.status,source:x.source}});for(const x of suppressions)out.push({id:x.id,kind:"suppression",occurredAt:x.createdAt,detail:{reason:x.reason,source:x.source,revokedAt:x.revokedAt}});for(const x of memberships)out.push({id:x.id,kind:x.state==="active"?"list.joined":"list.left",occurredAt:x.state==="active"?x.joinedAt:(x.leftAt??x.joinedAt),detail:{listId:x.listId,sourceType:x.sourceType,sourceId:x.sourceId}});return out.sort((a,b)=>a.occurredAt.getTime()-b.occurredAt.getTime())}
  async defineProperty(input:{workspaceId:string;key:string;displayName:string;dataType:PropertyType;isArray:boolean}){const x=await (this.db as any).profilePropertyDefinition.upsert({where:{workspaceId_key:{workspaceId:input.workspaceId,key:input.key}},create:{...input,status:"active"},update:{displayName:input.displayName,status:"active"}});if(x.dataType!==input.dataType||x.isArray!==input.isArray)throw new Error("PROPERTY_DEFINITION_CONFLICT");return {id:x.id,workspaceId:x.workspaceId,key:x.key,displayName:x.displayName,dataType:x.dataType as PropertyType,isArray:x.isArray,status:x.status}}
  async listPropertyDefinitions(workspaceId:string){return (await (this.db as any).profilePropertyDefinition.findMany({where:{workspaceId,status:"active"}})).map((x:any)=>({id:x.id,workspaceId:x.workspaceId,key:x.key,displayName:x.displayName,dataType:x.dataType as PropertyType,isArray:x.isArray,status:x.status}))}
  async setPropertyValue(input:{workspaceId:string;profileId:string;definition:DbPropertyDefinition;value:unknown;source:string}){const data:any={textValue:null,numberValue:null,booleanValue:null,datetimeValue:null,jsonValue:null,source:input.source,rowVersion:{increment:1}};if(input.definition.dataType==="text")data.textValue=input.value;else if(input.definition.dataType==="number")data.numberValue=input.value;else if(input.definition.dataType==="boolean")data.booleanValue=input.value;else if(input.definition.dataType==="datetime")data.datetimeValue=new Date(String(input.value));else data.jsonValue=input.value;const existing=await (this.db as any).profilePropertyValue.findUnique({where:{workspaceId_profileId_definitionId:{workspaceId:input.workspaceId,profileId:input.profileId,definitionId:input.definition.id}}});if(existing)await (this.db as any).profilePropertyValue.update({where:{id:existing.id},data});else {delete data.rowVersion;await (this.db as any).profilePropertyValue.create({data:{workspaceId:input.workspaceId,profileId:input.profileId,definitionId:input.definition.id,...data}})}}
  async mergeProfiles(input:{workspaceId:string;canonicalId:string;sourceId:string;actorId:string}){return this.transaction(async tx=>{const repo=tx as PrismaPhase1Repository,db=repo.db as any,ids=[input.canonicalId,input.sourceId].sort();await db.$queryRaw(Prisma.sql`SELECT id FROM "profile" WHERE workspace_id=${input.workspaceId}::uuid AND id IN (${Prisma.join(ids.map(id=>Prisma.sql`${id}::uuid`))}) ORDER BY id FOR UPDATE`);const canonical=await repo.findProfile(input.workspaceId,input.canonicalId),source=await repo.findProfile(input.workspaceId,input.sourceId);if(!canonical||!source||canonical.id===source.id)throw new Error("MERGE_INVALID");const inventory={identifiers:0,membershipsMoved:0,membershipConflicts:0,propertiesMoved:0,propertyConflicts:0,flowRunsMoved:0,flowRunConflicts:0,messagesMoved:0};
    inventory.identifiers=(await db.profileIdentifier.updateMany({where:{workspaceId:input.workspaceId,profileId:source.id},data:{profileId:canonical.id}})).count;
    const memberships=await db.listMembership.findMany({where:{workspaceId:input.workspaceId,profileId:source.id}});for(const m of memberships){const existing=await db.listMembership.findUnique({where:{workspaceId_listId_profileId:{workspaceId:input.workspaceId,listId:m.listId,profileId:canonical.id}}});if(existing){await db.listMembership.update({where:{id:m.id},data:{state:"left",leftAt:new Date()}});inventory.membershipConflicts++}else{await db.listMembership.update({where:{id:m.id},data:{profileId:canonical.id}});inventory.membershipsMoved++}}
    await db.consentRecord.updateMany({where:{workspaceId:input.workspaceId,profileId:source.id},data:{profileId:canonical.id}});await db.suppression.updateMany({where:{workspaceId:input.workspaceId,profileId:source.id},data:{profileId:canonical.id}});
    const [canonicalProperties,sourceProperties]=await Promise.all([db.profilePropertyValue.findMany({where:{workspaceId:input.workspaceId,profileId:canonical.id},select:{definitionId:true}}),db.profilePropertyValue.findMany({where:{workspaceId:input.workspaceId,profileId:source.id}})]);const canonicalDefinitions=new Set(canonicalProperties.map((x:any)=>x.definitionId));for(const propertyValue of sourceProperties){if(canonicalDefinitions.has(propertyValue.definitionId)){await db.profilePropertyValue.delete({where:{id:propertyValue.id}});inventory.propertyConflicts++}else{await db.profilePropertyValue.update({where:{id:propertyValue.id},data:{profileId:canonical.id}});inventory.propertiesMoved++}}
    const [canonicalSubscription,sourceSubscription]=await Promise.all([db.subscriptionState.findUnique({where:{workspaceId_profileId_channel_purpose:{workspaceId:input.workspaceId,profileId:canonical.id,channel:"email",purpose:"marketing"}}}),db.subscriptionState.findUnique({where:{workspaceId_profileId_channel_purpose:{workspaceId:input.workspaceId,profileId:source.id,channel:"email",purpose:"marketing"}}})]);if(sourceSubscription){if(!canonicalSubscription||sourceSubscription.effectiveAt>canonicalSubscription.effectiveAt)await db.subscriptionState.upsert({where:{workspaceId_profileId_channel_purpose:{workspaceId:input.workspaceId,profileId:canonical.id,channel:"email",purpose:"marketing"}},create:{workspaceId:input.workspaceId,profileId:canonical.id,channel:"email",purpose:"marketing",currentStatus:sourceSubscription.currentStatus,effectiveAt:sourceSubscription.effectiveAt,sourceConsentRecordId:sourceSubscription.sourceConsentRecordId,revision:sourceSubscription.revision},update:{currentStatus:sourceSubscription.currentStatus,effectiveAt:sourceSubscription.effectiveAt,sourceConsentRecordId:sourceSubscription.sourceConsentRecordId,revision:{increment:1}}});await db.subscriptionState.delete({where:{workspaceId_profileId_channel_purpose:{workspaceId:input.workspaceId,profileId:source.id,channel:"email",purpose:"marketing"}}})}
    const sourceRuns=await db.flowRun.findMany({where:{workspaceId:input.workspaceId,profileId:source.id}});for(const run of sourceRuns){const conflict=await db.flowRun.findFirst({where:{workspaceId:input.workspaceId,profileId:canonical.id,flowVersionId:run.flowVersionId,deduplicationKey:run.deduplicationKey}});if(conflict){inventory.flowRunConflicts++;continue}await db.flowRun.update({where:{id:run.id},data:{profileId:canonical.id}});inventory.flowRunsMoved++}inventory.messagesMoved=(await db.message.updateMany({where:{workspaceId:input.workspaceId,profileId:source.id},data:{profileId:canonical.id}})).count;
    await db.profile.update({where:{id:source.id},data:{deletedAt:new Date()}});await db.profileMerge.create({data:{workspaceId:input.workspaceId,canonicalProfileId:canonical.id,sourceProfileId:source.id,policyJson:{standard:"canonical_wins_nonblank",suppressions:"preserve_all",inventory},actorId:input.actorId}});const x=await db.profile.update({where:{id:canonical.id},data:{rowVersion:{increment:1}}});return profile(x)})}
  async deleteProfile(input:{workspaceId:string;profileId:string}){return this.transaction(async tx=>{const repo=tx as PrismaPhase1Repository,db=repo.db as any,existing=await repo.findProfile(input.workspaceId,input.profileId);if(!existing)throw new Error("NOT_FOUND");const now=new Date();await db.listMembership.updateMany({where:{workspaceId:input.workspaceId,profileId:input.profileId,state:"active"},data:{state:"left",leftAt:now}});const x=await db.profile.update({where:{id:input.profileId},data:{deletedAt:now,rowVersion:{increment:1}}});return profile(x)})}

  async createList(input:{workspaceId:string;name:string;description?:string}){return list(await (this.db as any).audienceList.create({data:{workspaceId:input.workspaceId,name:input.name,description:input.description,status:"active"}}))}
  async listLists(workspaceId:string){return (await (this.db as any).audienceList.findMany({where:{workspaceId,status:{not:"deleted"}},orderBy:{createdAt:"desc"}})).map(list)}
  async findList(workspaceId:string,id:string){const x=await (this.db as any).audienceList.findFirst({where:{id,workspaceId,status:{not:"deleted"}}});return x?list(x):null}
  async updateList(input:{workspaceId:string;listId:string;name?:string;description?:string}){const data:any={};if(input.name!==undefined)data.name=input.name;if(input.description!==undefined)data.description=input.description;const changed=await (this.db as any).audienceList.updateMany({where:{id:input.listId,workspaceId:input.workspaceId,status:{not:"deleted"}},data});if(changed.count!==1)throw new Error("NOT_FOUND");return list(await (this.db as any).audienceList.findUniqueOrThrow({where:{id:input.listId}}))}
  async listMemberships(workspaceId:string,listId:string){return (await (this.db as any).listMembership.findMany({where:{workspaceId,listId},orderBy:{joinedAt:"desc"}})).map((x:any)=>({profileId:x.profileId,state:x.state,sourceType:x.sourceType,sourceId:x.sourceId,joinedAt:x.joinedAt,leftAt:x.leftAt}))}
  async setMembership(input:{workspaceId:string;listId:string;profileId:string;state:"active"|"left";sourceType:string;sourceId?:string;actorId:string}){const now=new Date(),db=this.db as any,old=await db.listMembership.findUnique({where:{workspaceId_listId_profileId:{workspaceId:input.workspaceId,listId:input.listId,profileId:input.profileId}}}),row=await db.listMembership.upsert({where:{workspaceId_listId_profileId:{workspaceId:input.workspaceId,listId:input.listId,profileId:input.profileId}},create:{workspaceId:input.workspaceId,listId:input.listId,profileId:input.profileId,state:input.state,joinedAt:now,leftAt:input.state==="left"?now:null,sourceType:input.sourceType,sourceId:input.sourceId,actorId:input.actorId},update:{state:input.state,joinedAt:input.state==='active'?now:undefined,leftAt:input.state==="left"?now:null,sourceType:input.sourceType,sourceId:input.sourceId,actorId:input.actorId}});if(input.state==='active'&&old?.state!=='active')await db.outboxEvent.create({data:{workspaceId:input.workspaceId,aggregateType:'list_membership',aggregateId:row.id,eventType:'phase3.audience.list.entered',eventVersion:1,payloadJson:{membershipId:row.id,listId:input.listId,profileId:input.profileId,occurredAt:row.joinedAt.toISOString()},deduplicationKey:`list-entered:${row.id}:${row.joinedAt.toISOString()}`}})}
  async archiveList(workspaceId:string,id:string){const x=await (this.db as any).audienceList.updateMany({where:{id,workspaceId,status:{not:"deleted"}},data:{status:"archived",archivedAt:new Date()}});if(x.count!==1)throw new Error("NOT_FOUND");return list(await (this.db as any).audienceList.findUniqueOrThrow({where:{id}}))}
  async deleteList(workspaceId:string,id:string){const deleted=await (this.db as any).audienceList.updateMany({where:{id,workspaceId,status:{not:"deleted"}},data:{status:"deleted",archivedAt:new Date()}});if(deleted.count!==1)throw new Error("LIST_NOT_FOUND")}

  async appendConsent(input:{workspaceId:string;profileId:string;status:ConsentStatus;source:string;occurredAt:Date;actorId:string;evidenceObjectKey?:string;jurisdiction?:string}){return this.transaction(async tx=>{const repo=tx as PrismaPhase1Repository;const c=await (repo.db as any).consentRecord.create({data:{workspaceId:input.workspaceId,profileId:input.profileId,channel:"email",purpose:"marketing",status:input.status,occurredAt:input.occurredAt,source:input.source,actorId:input.actorId,evidenceObjectKey:input.evidenceObjectKey,jurisdiction:input.jurisdiction}});const current=await (repo.db as any).subscriptionState.findUnique({where:{workspaceId_profileId_channel_purpose:{workspaceId:input.workspaceId,profileId:input.profileId,channel:"email",purpose:"marketing"}}});if(!current||input.occurredAt>=current.effectiveAt)await (repo.db as any).subscriptionState.upsert({where:{workspaceId_profileId_channel_purpose:{workspaceId:input.workspaceId,profileId:input.profileId,channel:"email",purpose:"marketing"}},create:{workspaceId:input.workspaceId,profileId:input.profileId,channel:"email",purpose:"marketing",currentStatus:input.status,effectiveAt:input.occurredAt,sourceConsentRecordId:c.id,revision:1},update:{currentStatus:input.status,effectiveAt:input.occurredAt,sourceConsentRecordId:c.id,revision:{increment:1}}});return {id:c.id}})}
  async currentSubscription(workspaceId:string,profileId:string){const x=await (this.db as any).subscriptionState.findUnique({where:{workspaceId_profileId_channel_purpose:{workspaceId,profileId,channel:"email",purpose:"marketing"}}});return (x?.currentStatus as ConsentStatus|undefined)??"unknown"}
  async listConsent(workspaceId:string,profileId:string){return (await (this.db as any).consentRecord.findMany({where:{workspaceId,profileId,channel:"email",purpose:"marketing"},orderBy:{occurredAt:"asc"}})).map((x:any)=>({id:x.id,status:x.status as ConsentStatus,source:x.source,occurredAt:x.occurredAt}))}
  async createSuppression(input:{workspaceId:string;profileId:string;reason:SuppressionReason;source:string;protected:boolean;expiresAt?:Date}){const current=await (this.db as any).suppression.findFirst({where:{workspaceId:input.workspaceId,profileId:input.profileId,channel:"email",reason:input.reason,revokedAt:null,OR:[{expiresAt:null},{expiresAt:{gt:new Date()}}]}});if(current)return {id:current.id,reason:current.reason as SuppressionReason,protected:current.protected,revokedAt:current.revokedAt,expiresAt:current.expiresAt};const x=await (this.db as any).suppression.create({data:{workspaceId:input.workspaceId,profileId:input.profileId,channel:"email",scope:"marketing",reason:input.reason,source:input.source,protected:input.protected,expiresAt:input.expiresAt}});return {id:x.id,reason:x.reason as SuppressionReason,protected:x.protected,revokedAt:x.revokedAt,expiresAt:x.expiresAt}}
  async listActiveSuppressions(workspaceId:string,profileId:string){return (await (this.db as any).suppression.findMany({where:{workspaceId,profileId,channel:"email",revokedAt:null,OR:[{expiresAt:null},{expiresAt:{gt:new Date()}}]}})).map((x:any)=>({id:x.id,reason:x.reason as SuppressionReason,protected:x.protected,revokedAt:x.revokedAt,expiresAt:x.expiresAt}))}
  async listSuppressions(workspaceId:string){return (await (this.db as any).suppression.findMany({where:{workspaceId,channel:"email"},orderBy:{createdAt:"desc"}})).map((x:any)=>({id:x.id,profileId:x.profileId,reason:x.reason as SuppressionReason,protected:x.protected,source:x.source,createdAt:x.createdAt,revokedAt:x.revokedAt,expiresAt:x.expiresAt}))}
  async revokeSuppression(workspaceId:string,id:string){const s=await (this.db as any).suppression.findFirst({where:{id,workspaceId}});if(!s)throw new Error("NOT_FOUND");if(s.protected)throw new Error("PROTECTED_SUPPRESSION");await (this.db as any).suppression.update({where:{id},data:{revokedAt:new Date()}})}

  async createImport(input:{workspaceId:string;objectKey:string;originalName:string;checksum:string;contentHash:string;createdBy:string}){return importJob(await (this.db as any).importJob.create({data:{...input,state:"uploaded"}}))}
  async findImport(workspaceId:string,id:string){const x=await (this.db as any).importJob.findFirst({where:{id,workspaceId}});return x?importJob(x):null}
  async findCompletedImportByHash(workspaceId:string,contentHash:string){const x=await (this.db as any).importJob.findFirst({where:{workspaceId,contentHash,state:{in:["completed","completed_with_errors"]}},orderBy:{createdAt:"desc"}});return x?importJob(x):null}
  async updateImport(input:{workspaceId:string;importId:string;state:string;mapping?:ImportMapping;policy?:ImportPolicy;totals?:unknown;completedAt?:Date}){const found=await (this.db as any).importJob.findFirst({where:{id:input.importId,workspaceId:input.workspaceId}});if(!found)throw new Error("NOT_FOUND");return importJob(await (this.db as any).importJob.update({where:{id:input.importId},data:{state:input.state,mappingJson:input.mapping,policyJson:input.policy,totalsJson:input.totals as any,completedAt:input.completedAt}}))}
  async replaceImportRows(workspaceId:string,importId:string,rows:Array<{rowNumber:number;state:string;errors:string[];profileId?:string}>){await (this.db as any).importRowResult.deleteMany({where:{workspaceId,importJobId:importId}});if(rows.length)await (this.db as any).importRowResult.createMany({data:rows.map(r=>({workspaceId,importJobId:importId,rowNumber:r.rowNumber,state:r.state,profileId:r.profileId,errorsJson:r.errors}))})}
  async replaceImportChunks(workspaceId:string,importId:string,chunks:Array<{chunkIndex:number;rowStart:number;rowEnd:number;state:string}>){await (this.db as any).importChunk.deleteMany({where:{workspaceId,importJobId:importId}});if(chunks.length)await (this.db as any).importChunk.createMany({data:chunks.map(c=>({workspaceId,importJobId:importId,...c}))})}
  async completeImportChunk(workspaceId:string,importId:string,chunkIndex:number){const x=await (this.db as any).importChunk.updateMany({where:{workspaceId,importJobId:importId,chunkIndex},data:{state:"completed",completedAt:new Date()}});if(x.count!==1)throw new Error("IMPORT_CHUNK_NOT_FOUND")}
  async restoreProfileSnapshot(input:{workspaceId:string;profileId:string;expectedRevision:bigint;snapshot:unknown}){const x=input.snapshot as any;const result=await (this.db as any).profile.updateMany({where:{id:input.profileId,workspaceId:input.workspaceId,rowVersion:input.expectedRevision,deletedAt:null},data:{firstName:x.firstName??null,lastName:x.lastName??null,locale:x.locale??null,timezone:x.timezone??null,countryCode:x.countryCode??null,region:x.region??null,city:x.city??null,rowVersion:{increment:1}}});return result.count===1}
  async recordImportChange(input:{workspaceId:string;importJobId:string;profileId:string;changeType:string;fieldKey?:string;before?:unknown;after?:unknown;revision?:bigint}){const {before,after,...data}=input;await (this.db as any).importChange.create({data:{...data,beforeJson:before as any,afterJson:after as any}})}
  async listImportChanges(workspaceId:string,importId:string){return (await (this.db as any).importChange.findMany({where:{workspaceId,importJobId:importId},orderBy:{createdAt:"desc"}})).map((x:any)=>({profileId:x.profileId,changeType:x.changeType,fieldKey:x.fieldKey,before:x.beforeJson,after:x.afterJson,revision:x.revision}))}
  async listImports(workspaceId:string){return (await (this.db as any).importJob.findMany({where:{workspaceId},orderBy:{createdAt:"desc"}})).map(importJob)}

  async createExport(input:{workspaceId:string;scope:unknown;fields:string[];purpose?:string;tokenHash:string;expiresAt:Date;createdBy:string}){return exportJob(await (this.db as any).exportJob.create({data:{workspaceId:input.workspaceId,state:"queued",scopeJson:input.scope as any,fieldsJson:input.fields,purpose:input.purpose,tokenHash:input.tokenHash,expiresAt:input.expiresAt,createdBy:input.createdBy}}))}
  async findExport(workspaceId:string,id:string){const x=await (this.db as any).exportJob.findFirst({where:{id,workspaceId}});return x?exportJob(x):null}
  async completeExport(input:{workspaceId:string;exportId:string;objectKey:string;recordCount:number}){const found=await (this.db as any).exportJob.findFirst({where:{id:input.exportId,workspaceId:input.workspaceId}});if(!found)throw new Error("EXPORT_NOT_FOUND");return exportJob(await (this.db as any).exportJob.update({where:{id:input.exportId},data:{state:"completed",objectKey:input.objectKey,recordCount:input.recordCount,completedAt:new Date()}}))}

  async createDomain(input:{workspaceId:string;domain:string;expectedRecords?:unknown;providerReference?:string;providerRegion?:string;providerStatus?:string;providerEvidence?:unknown;dkimStatus?:string|null;mailFromStatus?:string|null}){const data={expectedRecords:input.expectedRecords as any,providerReference:input.providerReference,providerRegion:input.providerRegion,providerStatus:input.providerStatus,providerEvidence:input.providerEvidence as any,dkimStatus:input.dkimStatus,mailFromStatus:input.mailFromStatus,lastCheckedAt:new Date()};try{const x=await (this.db as any).senderDomain.upsert({where:{workspaceId_domain:{workspaceId:input.workspaceId,domain:input.domain}},create:{workspaceId:input.workspaceId,workspacePrimary:true,domain:input.domain,status:"pending",...data},update:{...data,workspacePrimary:true}});return domain(x)}catch(error){if((error as any)?.code==="P2002")throw new Error("WORKSPACE_SENDING_DOMAIN_EXISTS");throw error}}
  async findDomain(workspaceId:string,id:string){const x=await (this.db as any).senderDomain.findFirst({where:{id,workspaceId}});return x?domain(x):null}
  async findDomainByName(workspaceId:string,domainName:string){const x=await (this.db as any).senderDomain.findFirst({where:{workspaceId,domain:domainName}});return x?domain(x):null}
  async findDomainOutsideWorkspace(workspaceId:string,domainName:string){const x=await (this.db as any).senderDomain.findFirst({where:{domain:domainName,workspaceId:{not:workspaceId}},select:{id:true}});return x?{id:x.id}:null}
  async listDomains(workspaceId:string){return (await (this.db as any).senderDomain.findMany({where:{workspaceId,workspacePrimary:true,archivedAt:null},orderBy:{createdAt:"desc"}})).map(domain)}
  async updateDomainSendingPurpose(workspaceId:string,domainId:string,purpose:"marketing"|"transactional"){return this.transaction(async tx=>{const repo=tx as PrismaPhase1Repository,db=repo.db as any;const found=await db.senderDomain.findFirst({where:{id:domainId,workspaceId,archivedAt:null}});if(!found)throw new Error("NOT_FOUND");await db.senderIdentity.updateMany({where:{workspaceId,domainId},data:{purpose}});return domain(await db.senderDomain.update({where:{id:domainId},data:{sendingPurpose:purpose}}))})}
  async deleteDomain(workspaceId:string,domainId:string){const result=await (this.db as any).senderDomain.deleteMany({where:{id:domainId,workspaceId}});if(result.count!==1)throw new Error("NOT_FOUND")}
  async countSenderIdentitiesForDomain(workspaceId:string,domainId:string){return (this.db as any).senderIdentity.count({where:{workspaceId,domainId}})}
  async deleteSenderIdentitiesForDomain(workspaceId:string,domainId:string){return this.transaction(async tx=>{const db=(tx as PrismaPhase1Repository).db as any,identities=await db.senderIdentity.findMany({where:{workspaceId,domainId},select:{id:true}}),ids=identities.map((identity:{id:string})=>identity.id);if(!ids.length)return 0;await db.emailDefinition.updateMany({where:{workspaceId,draftSenderIdentityId:{in:ids},archivedAt:null},data:{draftSenderIdentityId:null,draftReplyTo:"",lastPreflightJson:null,lastPreflightFingerprint:null,lastPreflightAt:null,rowVersion:{increment:1}}});const result=await db.senderIdentity.deleteMany({where:{workspaceId,id:{in:ids}}});return result.count})}
  async updateDomainCheck(input:{workspaceId:string;domainId:string;status:string;observedRecords:unknown;expectedRecords?:unknown;providerReference?:string;providerRegion?:string;providerStatus?:string;providerEvidence?:unknown;dkimStatus?:string|null;mailFromStatus?:string|null;verifiedAt?:Date}){const found=await (this.db as any).senderDomain.findFirst({where:{id:input.domainId,workspaceId:input.workspaceId}});if(!found)throw new Error("NOT_FOUND");return domain(await (this.db as any).senderDomain.update({where:{id:input.domainId},data:{status:input.status,observedRecords:input.observedRecords as any,expectedRecords:input.expectedRecords as any,providerReference:input.providerReference,providerRegion:input.providerRegion,providerStatus:input.providerStatus,providerEvidence:input.providerEvidence as any,dkimStatus:input.dkimStatus,mailFromStatus:input.mailFromStatus,lastCheckedAt:new Date(),verifiedAt:input.verifiedAt}}))}
  async upsertWorkspaceProviderConfig(input:{workspaceId:string;provider:string;region:string}){const x=await (this.db as any).workspaceProviderConfig.upsert({where:{workspaceId_provider:{workspaceId:input.workspaceId,provider:input.provider}},create:{workspaceId:input.workspaceId,provider:input.provider,region:input.region,providerStatus:"active"},update:{region:input.region,providerStatus:"active"}});return providerConfig(x)}
  async workspaceProviderConfig(workspaceId:string,provider:string){const x=await (this.db as any).workspaceProviderConfig.findFirst({where:{workspaceId,provider}});return x?providerConfig(x):null}
  async createSenderIdentity(input:{workspaceId:string;domainId:string;fromName:string;fromEmail:string;replyTo:string;purpose:"marketing"|"transactional"}){return identity(await (this.db as any).senderIdentity.upsert({where:{workspaceId_fromEmail:{workspaceId:input.workspaceId,fromEmail:input.fromEmail}},create:{...input,status:"active"},update:{domainId:input.domainId,fromName:input.fromName,replyTo:input.replyTo,purpose:input.purpose,status:"active"}}))}
  async listSenderIdentities(workspaceId:string){return (await (this.db as any).senderIdentity.findMany({where:{workspaceId,status:"active"}})).map(identity)}
  async upsertReadiness(workspaceId:string,checks:Array<{key:string;passed:boolean;evidence?:unknown}>){for(const c of checks)await (this.db as any).workspaceReadinessCheck.upsert({where:{workspaceId_checkKey:{workspaceId,checkKey:c.key}},create:{workspaceId,checkKey:c.key,status:c.passed?"passed":"blocked",evidenceJson:c.evidence as any},update:{status:c.passed?"passed":"blocked",evidenceJson:c.evidence as any,checkedAt:new Date()}})}

  async findProvisioningDomain(workspaceId:string,domainId:string){const x=await (this.db as any).senderDomain.findFirst({where:{id:domainId,workspaceId,archivedAt:null}});return x?domain(x) as any:null}
  async findProvisioningDomainByRoot(workspaceId:string,rootDomain:string){const x=await (this.db as any).senderDomain.findFirst({where:{workspaceId,OR:[{rootDomain},{domain:rootDomain}],archivedAt:null}});return x?domain(x) as any:null}
  async findWorkspacePrimaryProvisioningDomain(workspaceId:string){const x=await (this.db as any).senderDomain.findFirst({where:{workspaceId,workspacePrimary:true,archivedAt:null}});return x?domain(x) as any:null}
  async findProvisioningDomainOutsideWorkspace(workspaceId:string,rootDomain:string){const x=await (this.db as any).senderDomain.findFirst({where:{workspaceId:{not:workspaceId},OR:[{rootDomain},{domain:rootDomain}],archivedAt:null},select:{id:true}});return x?{id:x.id}:null}
  async createBrandedDomain(input:{workspaceId:string;rootDomain:string;delegatedSubdomain:string;region:string;provisioningVersion:string;provisioningMode?:string;setupMode?:string}){const mode=input.provisioningMode??"branded_delegation";try{const x=await (this.db as any).senderDomain.upsert({where:{workspaceId_domain:{workspaceId:input.workspaceId,domain:input.rootDomain}},create:{workspaceId:input.workspaceId,workspacePrimary:true,domain:input.rootDomain,rootDomain:input.rootDomain,delegatedSubdomain:input.delegatedSubdomain,provisioningMode:mode,setupMode:input.setupMode??(mode==="static_branded"?"STATIC_BRANDED":"MANAGED_DELEGATION"),provisioningVersion:input.provisioningVersion,provisioningCallerReference:"pending",lifecycleState:"CREATED",authenticationStatus:"pending",readinessStatus:"not_ready",readinessReasons:mode==="static_branded"?["STATIC_DNS_PENDING"]:["HOSTED_ZONE_PROVISIONING"],status:"pending",providerRegion:input.region},update:{workspacePrimary:true,rootDomain:input.rootDomain,delegatedSubdomain:input.delegatedSubdomain,providerRegion:input.region,provisioningMode:mode,setupMode:input.setupMode??(mode==="static_branded"?"STATIC_BRANDED":"MANAGED_DELEGATION"),provisioningVersion:input.provisioningVersion,lifecycleState:"CREATED",status:"pending",authenticationStatus:"pending",readinessStatus:"not_ready",readinessReasons:mode==="static_branded"?["STATIC_DNS_PENDING"]:["HOSTED_ZONE_PROVISIONING"],archivedAt:null,disconnectStatus:null,lastErrorCode:null,lastErrorMessage:null}});if(x.provisioningCallerReference==="pending")return domain(await (this.db as any).senderDomain.update({where:{id:x.id},data:{provisioningCallerReference:`sender-domain:${x.id}`}})) as any;return domain(x) as any}catch(error){if((error as any)?.code==="P2002")throw new Error("WORKSPACE_SENDING_DOMAIN_EXISTS");throw error}}
  async updateProvisioningDomain(input:{workspaceId:string;domainId:string;patch:Record<string,unknown>}){const found=await (this.db as any).senderDomain.findFirst({where:{id:input.domainId,workspaceId:input.workspaceId}});if(!found)throw new Error("NOT_FOUND");return domain(await (this.db as any).senderDomain.update({where:{id:input.domainId},data:input.patch as any})) as any}
  async upsertDnsEvidence(input:{workspaceId:string;senderDomainId:string;purpose:string;ownership:"customer"|"platform";record:{type:string;name:string;values:string[];ttl:number};verificationStatus:string;customerActionRequired:boolean;observedValues?:string[];validationMethod?:string;lastCheckedAt?:Date}){for(const value of input.record.values)await (this.db as any).senderDomainDnsEvidence.upsert({where:{senderDomainId_purpose_recordType_name_expectedValue:{senderDomainId:input.senderDomainId,purpose:input.purpose,recordType:input.record.type,name:input.record.name,expectedValue:value}},create:{workspaceId:input.workspaceId,senderDomainId:input.senderDomainId,purpose:input.purpose,ownership:input.ownership,recordType:input.record.type,name:input.record.name,expectedValue:value,observedValues:input.observedValues as any,verificationStatus:input.verificationStatus,customerActionRequired:input.customerActionRequired,validationMethod:input.validationMethod,lastCheckedAt:input.lastCheckedAt},update:{ownership:input.ownership,observedValues:input.observedValues as any,verificationStatus:input.verificationStatus,customerActionRequired:input.customerActionRequired,validationMethod:input.validationMethod,lastCheckedAt:input.lastCheckedAt}})}
  async retireCustomerDnsEvidence(workspaceId:string,senderDomainId:string){await (this.db as any).senderDomainDnsEvidence.updateMany({where:{workspaceId,senderDomainId,customerActionRequired:true},data:{customerActionRequired:false}})}
  async retireDnsEvidenceExceptName(workspaceId:string,senderDomainId:string,purpose:string,keepName:string){await (this.db as any).senderDomainDnsEvidence.updateMany({where:{workspaceId,senderDomainId,purpose,name:{not:keepName}},data:{customerActionRequired:false,verificationStatus:"archived"}})}
  async retireDnsEvidenceExceptExpected(workspaceId:string,senderDomainId:string,purpose:string,keepName:string,keepExpectedValue:string){await (this.db as any).senderDomainDnsEvidence.updateMany({where:{workspaceId,senderDomainId,purpose,name:keepName,expectedValue:{not:keepExpectedValue}},data:{customerActionRequired:false,verificationStatus:"archived"}})}
  async purgeDnsEvidenceExceptName(workspaceId:string,senderDomainId:string,purpose:string,keepName:string){await (this.db as any).senderDomainDnsEvidence.deleteMany({where:{workspaceId,senderDomainId,purpose,name:{not:keepName}}})}
  async purgeDnsEvidenceDuplicatesForPurposes(workspaceId:string,senderDomainId:string,purposes:string[]){for(const purpose of purposes){const rows=await (this.db as any).senderDomainDnsEvidence.findMany({where:{workspaceId,senderDomainId,purpose},orderBy:[{updatedAt:"desc"}]});if(rows.length<=1)continue;const keep=rows.find((row:any)=>row.verificationStatus==="verified")??rows[0];await (this.db as any).senderDomainDnsEvidence.deleteMany({where:{workspaceId,senderDomainId,purpose,id:{not:keep.id}}})}}
  async retireLegacyStaticDnsEvidence(workspaceId:string,senderDomainId:string){await (this.db as any).senderDomainDnsEvidence.updateMany({where:{workspaceId,senderDomainId,customerActionRequired:false,purpose:{in:["ownership","delegation","dkim"]}},data:{verificationStatus:"archived"}})}
  async listDnsEvidence(workspaceId:string,senderDomainId:string,customerOnly=false){const rows=await (this.db as any).senderDomainDnsEvidence.findMany({where:{workspaceId,senderDomainId,...(customerOnly?{customerActionRequired:true}:{})},orderBy:[{purpose:"asc"},{name:"asc"},{expectedValue:"asc"}]});return rows.map((x:any)=>({purpose:x.purpose,ownership:x.ownership,recordType:x.recordType,name:x.name,expectedValue:x.expectedValue,observedValues:x.observedValues,verificationStatus:x.verificationStatus,customerActionRequired:x.customerActionRequired,validationMethod:x.validationMethod,lastCheckedAt:x.lastCheckedAt}))}
  async upsertDeliveryRoute(input:{workspaceId:string;senderDomainId:string;provider:string;providerRegion:string;providerIdentityReference?:string;configurationSetName?:string;mailFromDomain?:string;trackingMode:string;trackingHostname?:string;status:string;holdReason?:string|null;rateLimitPerSecond?:number;warmingDailyLimit?:number}){return (this.db as any).emailDeliveryRoute.upsert({where:{workspaceId_senderDomainId_provider:{workspaceId:input.workspaceId,senderDomainId:input.senderDomainId,provider:input.provider}},create:input,update:{providerRegion:input.providerRegion,providerIdentityReference:input.providerIdentityReference,configurationSetName:input.configurationSetName,mailFromDomain:input.mailFromDomain,trackingMode:input.trackingMode,trackingHostname:input.trackingHostname,status:input.status,holdReason:input.holdReason,rateLimitPerSecond:input.rateLimitPerSecond,warmingDailyLimit:input.warmingDailyLimit,archivedAt:null}})}
  async senderIdentityCount(workspaceId:string,senderDomainId:string){return (this.db as any).senderIdentity.count({where:{workspaceId,domainId:senderDomainId,status:"active"}})}
  async workspaceOperationalReadiness(workspaceId:string){const [workspace,holds,providerConfig,gates]=await Promise.all([(this.db as any).workspace.findUnique({where:{id:workspaceId}}),(this.db as any).operationalHold.count({where:{workspaceId,state:"active"}}),(this.db as any).workspaceProviderConfig.findFirst({where:{workspaceId,provider:"ses",providerStatus:"active"},select:{configurationSetName:true}}),(this.db as any).phase0GateEvidence.findMany({where:{checkKey:{in:["real.sns.signature","real.sns.subscription","real.feedback.endpoint","real.unsubscribe.endpoint"]}},select:{checkKey:true,status:true}})]);const passed=new Set<string>(gates.filter((x:any)=>x.status==="passed").map((x:any)=>x.checkKey));return {businessReady:Boolean(workspace?.legalName?.trim()&&workspace?.businessAddress?.trim()),feedbackReady:Boolean(providerConfig?.configurationSetName&&passed.has("real.sns.signature")&&passed.has("real.sns.subscription")&&passed.has("real.feedback.endpoint")),unsubscribeReady:passed.has("real.unsubscribe.endpoint"),held:holds>0}}
  async updateWorkspaceProviderConfigurationSet(workspaceId:string,provider:string,name:string){await (this.db as any).workspaceProviderConfig.updateMany({where:{workspaceId,provider},data:{configurationSetName:name,providerStatus:"active"}})}
  async upsertProviderQuotaSnapshot(input:{provider:string;region:string;max24Hour?:number;maxSendRate?:number;sentLast24Hours?:number;fetchedAt:Date;expiresAt:Date}){await (this.db as any).providerQuotaSnapshot.upsert({where:{provider_region:{provider:input.provider,region:input.region}},create:input,update:{max24Hour:input.max24Hour,maxSendRate:input.maxSendRate,sentLast24Hours:input.sentLast24Hours,fetchedAt:input.fetchedAt,expiresAt:input.expiresAt}})}
  async scheduleDomainVerification(input:{workspaceId:string;senderDomainId:string;dueAt:Date;reason:string}){const key=`sender-domain.verify:${input.senderDomainId}`;await (this.db as any).scheduledAction.upsert({where:{deduplicationKey:key},create:{workspaceId:input.workspaceId,actionType:"sender_domain.verify",aggregateType:"sender_domain",aggregateId:input.senderDomainId,dueAt:input.dueAt,state:"pending",deduplicationKey:key,payloadJson:{reason:input.reason}},update:{dueAt:input.dueAt,state:"pending",leaseOwner:null,leaseExpiresAt:null,payloadJson:{reason:input.reason},completedAt:null}})}
  async archiveProvisioningDomain(workspaceId:string,senderDomainId:string,at:Date,reason?:string|null){await this.transaction(async tx=>{const db=(tx as PrismaPhase1Repository).db as any;await db.emailDeliveryRoute.updateMany({where:{workspaceId,senderDomainId,archivedAt:null},data:{status:"archived",holdReason:reason??"DOMAIN_ARCHIVED",archivedAt:at}});await db.scheduledAction.updateMany({where:{workspaceId,aggregateType:"sender_domain",aggregateId:senderDomainId,state:{notIn:["completed","cancelled"]}},data:{state:"cancelled",completedAt:at,leaseOwner:null,leaseExpiresAt:null}});await db.senderDomain.updateMany({where:{id:senderDomainId,workspaceId,archivedAt:null},data:{lifecycleState:"DELETED",readinessStatus:"not_ready",readinessReasons:["ROUTE_NOT_ACTIVE"],status:"archived",disconnectStatus:"completed",archivedAt:at,lastErrorCode:reason??null,lastErrorMessage:reason??null}})})}
  async holdDomainRoute(workspaceId:string,senderDomainId:string,reason:string){await (this.db as any).emailDeliveryRoute.updateMany({where:{workspaceId,senderDomainId,archivedAt:null},data:{status:"held",holdReason:reason}})}
  async hasActiveDeliveryAttempts(workspaceId:string,senderDomainId:string){const routes=await (this.db as any).emailDeliveryRoute.findMany({where:{workspaceId,senderDomainId,archivedAt:null},select:{id:true}}),ids=routes.map((row:any)=>row.id);if(!ids.length)return false;return (await (this.db as any).deliveryAttempt.count({where:{workspaceId,routeId:{in:ids},state:{in:["created","unknown"]}}}))>0}
  async claimDomainProvisioning(input:{workspaceId:string;senderDomainId:string;owner:string;leaseUntil:Date}){const now=new Date(),result=await (this.db as any).senderDomain.updateMany({where:{id:input.senderDomainId,workspaceId:input.workspaceId,archivedAt:null,OR:[{provisioningLeaseOwner:null},{provisioningLeaseExpiresAt:{lte:now}},{provisioningLeaseOwner:input.owner}]},data:{provisioningLeaseOwner:input.owner,provisioningLeaseExpiresAt:input.leaseUntil}});return result.count===1}
  async releaseDomainProvisioning(input:{workspaceId:string;senderDomainId:string;owner:string}){await (this.db as any).senderDomain.updateMany({where:{id:input.senderDomainId,workspaceId:input.workspaceId,provisioningLeaseOwner:input.owner},data:{provisioningLeaseOwner:null,provisioningLeaseExpiresAt:null}})}

  async audit(input:{workspaceId:string;actorId:string;action:string;objectType:string;objectId?:string;riskLevel:string;before?:unknown;after?:unknown;requestId?:string;correlationId?:string}){await (this.db as any).auditEvent.create({data:{workspaceId:input.workspaceId,actorType:"user",actorId:input.actorId,action:input.action,objectType:input.objectType,objectId:input.objectId,riskLevel:input.riskLevel,beforeJson:input.before as any,afterJson:input.after as any,requestId:input.requestId,correlationId:input.correlationId}})}
  async recordAudit(input:{workspaceId:string;action:string;objectId:string;riskLevel:string;after?:unknown;before?:unknown}){await (this.db as any).auditEvent.create({data:{workspaceId:input.workspaceId,actorType:"system",actorId:null,action:input.action,objectType:"sender_domain",objectId:input.objectId,riskLevel:input.riskLevel,beforeJson:input.before as any,afterJson:input.after as any}})}
  async listAudit(workspaceId:string,limit:number){return (await (this.db as any).auditEvent.findMany({where:{workspaceId},orderBy:{occurredAt:"desc"},take:Math.min(Math.max(limit,1),200)})).map((x:any)=>({id:x.id,action:x.action,objectType:x.objectType,objectId:x.objectId,riskLevel:x.riskLevel,occurredAt:x.occurredAt}))}
}
