import { randomUUID } from "node:crypto";
import { Prisma, type PrismaClient } from "@prisma/client";
import type { Phase2Repository, P2BrandKit, P2ContentVariable, P2DeliveryAttempt, P2DeliveryRoute, P2EmailTemplate, P2Hold, P2MediaAsset, P2Message, P2Profile, P2SenderDomain, P2SenderIdentity, P2TemplateUsage, P2TemplateVersion, P2TrackingLink, P2UniversalBlock, P2Workspace, P2WorkspaceProviderConfig } from "../../../application/src/ports/phase2-repository.js";
import type { EmailDraft, PublishedEmailVersion, StructuredEmailDocument } from "../../../domain/src/phase2/content.js";
import type { MessagePolicyDecision } from "../../../domain/src/phase2/message-policy.js";
import type { SendPolicyConfig } from "../../../domain/src/phase2/send-policy.js";
import { WORKSPACE_EMAILS_PER_SECOND } from "../../../domain/src/phase2/delivery-pacing.js";

function draft(x:any):EmailDraft{return {id:x.id,workspaceId:x.workspaceId,internalName:x.name,authoringMode:x.authoringMode,subject:x.draftSubject,preheader:x.draftPreheader,senderIdentityId:x.draftSenderIdentityId,replyTo:x.draftReplyTo,structuredDocument:x.draftDocumentJson as StructuredEmailDocument,htmlSource:x.draftHtmlSource,plainText:x.draftPlainText,plainTextMode:x.plainTextMode??"manual",plainTextStale:Boolean(x.plainTextStale),trackingEnabled:x.trackingEnabled,openTrackingEnabled:x.openTrackingEnabled,rowVersion:Number(x.rowVersion),state:x.archivedAt?"blocked":"draft",createdAt:x.createdAt.toISOString(),updatedAt:x.updatedAt.toISOString(),archivedAt:x.archivedAt?.toISOString()??null}}
function version(x:any):PublishedEmailVersion{return {id:x.id,workspaceId:x.workspaceId,emailDefinitionId:x.emailDefinitionId,versionNumber:x.versionNumber,authoringMode:x.authoringMode,authoringSchemaVersion:x.authoringSchemaVersion,sourceDocument:x.sourceDocumentJson as StructuredEmailDocument|null,sanitizedSource:x.sanitizedSource,compiledHtml:x.compiledHtml,compiledText:x.compiledText,subjectTemplate:x.subjectTemplate,preheaderTemplate:x.preheaderTemplate,senderIdentityId:x.senderIdentityId,replyTo:x.replyTo,trackingEnabled:x.trackingEnabled,openTrackingEnabled:x.openTrackingEnabled,senderSnapshot:x.senderSnapshotJson as any,contentHash:x.contentHash,compilerVersion:x.compilerVersion,sanitizerVersion:x.sanitizerVersion,preflight:x.preflightJson as any,publishedAt:x.publishedAt.toISOString(),publishedBy:x.publishedBy??"system"}}
function workspace(x:any):P2Workspace{return {id:x.id,businessAddress:x.businessAddress,timezone:x.timezone,legalName:x.legalName}}
function profile(x:any):P2Profile{return {id:x.id,workspaceId:x.workspaceId,normalizedEmail:x.normalizedEmail,originalEmail:x.originalEmail,firstName:x.firstName,lastName:x.lastName,timezone:x.timezone}}
function identity(x:any):P2SenderIdentity{return {id:x.id,workspaceId:x.workspaceId,domainId:x.domainId,fromName:x.fromName,fromEmail:x.fromEmail,replyTo:x.replyTo,purpose:x.purpose as "marketing"|"transactional",status:x.status}}
function domain(x:any):P2SenderDomain{return {id:x.id,workspaceId:x.workspaceId,domain:x.domain,rootDomain:x.rootDomain,sendingPurpose:x.sendingPurpose as "marketing"|"transactional"|null,workspacePrimary:x.workspacePrimary,status:x.status,providerRegion:x.providerRegion,providerReference:x.providerReference,provisioningMode:x.provisioningMode,provisioningVersion:x.provisioningVersion,authenticationStatus:x.authenticationStatus,readinessStatus:x.readinessStatus,dkimStatus:x.dkimStatus,mailFromStatus:x.mailFromStatus,mailFromDomain:x.mailFromDomain,dkimSigningMode:x.dkimSigningMode,delegatedSubdomain:x.delegatedSubdomain,trackingDomain:x.trackingDomain}}
function route(x:any):P2DeliveryRoute{return {id:x.id,workspaceId:x.workspaceId,senderDomainId:x.senderDomainId,provider:x.provider,providerRegion:x.providerRegion,providerIdentityReference:x.providerIdentityReference,configurationSetName:x.configurationSetName,mailFromDomain:x.mailFromDomain,trackingMode:x.trackingMode,trackingHostname:x.trackingHostname,status:x.status,holdReason:x.holdReason,rateLimitPerSecond:x.rateLimitPerSecond,warmingDailyLimit:x.warmingDailyLimit}}
function providerConfig(x:any):P2WorkspaceProviderConfig{return {provider:x.provider,region:x.region,configurationSetName:x.configurationSetName,providerStatus:x.providerStatus}}
function message(x:any):P2Message{return {id:x.id,workspaceId:x.workspaceId,sourceType:x.sourceType,sourceId:x.sourceId,flowRunId:x.flowRunId,nodeId:x.nodeId,profileId:x.profileId,emailVersionId:x.emailVersionId??x.emailTestSnapshotId,emailTestSnapshotId:x.emailTestSnapshotId,idempotencyKey:x.idempotencyKey,state:x.state,policyDecision:x.policyDecision,scheduledFor:x.scheduledFor,renderedAt:x.renderedAt,submittedAt:x.submittedAt,finalAt:x.finalAt,firstOpenedAt:x.firstOpenedAt, lastOpenedAt:x.lastOpenedAt,openCount:Number(x.openCount??0),createdAt:x.createdAt}}
function attempt(x:any):P2DeliveryAttempt{return {id:x.id,workspaceId:x.workspaceId,messageId:x.messageId,attemptNumber:x.attemptNumber,provider:x.provider,routeId:x.routeId,requestFingerprint:x.requestFingerprint,providerMessageId:x.providerMessageId,state:x.state}}
function hold(x:any):P2Hold{return {id:x.id,workspaceId:x.workspaceId,scopeType:x.scopeType,scopeId:x.scopeId,reason:x.reason,state:x.state,createdAt:x.createdAt,releasedAt:x.releasedAt}}
function tracking(x:any):P2TrackingLink{return {id:x.id,workspaceId:x.workspaceId,messageId:x.messageId,destination:x.destination}}
function template(x:any):P2EmailTemplate{return {id:x.id,workspaceId:x.workspaceId,name:x.name,category:x.category,document:x.documentJson as StructuredEmailDocument,subject:x.subjectTemplate,preheader:x.preheaderTemplate,plainText:x.plainText,settings:x.settingsJson as Record<string,unknown>|null,editorType:x.editorType??null,sourceType:x.sourceType??null,templateType:x.templateType??"native",importMethod:x.importMethod??null,originalFilename:x.originalFilename??null,originalSourceHtml:x.originalSourceHtml??null,sanitizedHtml:x.sanitizedHtml??null,conversionStatus:x.conversionStatus??"not_requested",importWarnings:(x.importWarningsJson as P2EmailTemplate["importWarnings"])??null,importedAt:x.importedAt??null,importedByUserId:x.importedByUserId??null,createdById:x.createdBy??null,updatedById:x.updatedBy??null,archivedAt:x.archivedAt,createdAt:x.createdAt,updatedAt:x.updatedAt}}
function universalBlock(x:any):P2UniversalBlock{return {id:x.id,workspaceId:x.workspaceId,name:x.name,category:x.category,blocks:x.blocksJson as StructuredEmailDocument["blocks"],archivedAt:x.archivedAt,createdAt:x.createdAt,updatedAt:x.updatedAt}}
function mediaAsset(x:any):P2MediaAsset{return {id:x.id,workspaceId:x.workspaceId,name:x.name,url:x.url,altText:x.altText,mimeType:x.mimeType,archivedAt:x.archivedAt,createdAt:x.createdAt,updatedAt:x.updatedAt}}
function brandKit(x:any):P2BrandKit{return {workspaceId:x.workspaceId,logoUrl:x.logoUrl,primaryColor:x.primaryColor,secondaryColor:x.secondaryColor,fontFamily:x.fontFamily,updatedAt:x.updatedAt}}
function contentVariable(x:any):P2ContentVariable{return {id:x.id,workspaceId:x.workspaceId,key:x.key,label:x.label,defaultValue:x.defaultValue,type:x.type,archivedAt:x.archivedAt,createdAt:x.createdAt,updatedAt:x.updatedAt}}
function templateVersion(x:any):P2TemplateVersion{return {id:x.id,workspaceId:x.workspaceId,templateId:x.templateId,versionNumber:x.versionNumber,document:x.documentJson as StructuredEmailDocument,subject:x.subjectTemplate,preheader:x.preheaderTemplate,plainText:x.plainText,settings:x.settingsJson as Record<string,unknown>|null,contentHash:x.contentHash,approvedAt:x.approvedAt,approvedBy:x.approvedBy}}

export class PrismaPhase2Repository implements Phase2Repository {
  constructor(private readonly db:PrismaClient|Prisma.TransactionClient){}
  async transaction<T>(fn:(tx:Phase2Repository)=>Promise<T>):Promise<T>{if(!("$transaction" in this.db))return fn(this);return (this.db as PrismaClient).$transaction(async tx=>fn(new PrismaPhase2Repository(tx)),{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
  async memberRole(w:string,u:string){const x=await (this.db as any).workspaceMember.findUnique({where:{workspaceId_userId:{workspaceId:w,userId:u}}});return x?.status==="active"?x.role:null}
  async workspace(w:string){const x=await (this.db as any).workspace.findUnique({where:{id:w}});return x?workspace(x):null}
  async profile(w:string,p:string){const x=await (this.db as any).profile.findFirst({where:{id:p,workspaceId:w,deletedAt:null}});return x?profile(x):null}
  async searchProfiles(w:string,query:string,limit:number){const q=query.trim();const where:any={workspaceId:w,deletedAt:null};if(q)where.OR=[{normalizedEmail:{contains:q.toLowerCase(),mode:"insensitive"}},{firstName:{contains:q,mode:"insensitive"}},{lastName:{contains:q,mode:"insensitive"}}];return (await (this.db as any).profile.findMany({where,orderBy:{updatedAt:"desc"},take:Math.max(1,Math.min(limit,25))})).map(profile)}
  async eventSample(w:string,eventId:string,profileId:string){const x=await (this.db as any).event.findFirst({where:{id:eventId,workspaceId:w,profileId}});return x?{id:x.id,eventName:x.eventName,schemaVersion:x.schemaVersion,occurredAt:x.occurredAt,properties:x.propertiesJson as Record<string,unknown>}:null}
  async subscriptionStatus(w:string,p:string){const x=await (this.db as any).subscriptionState.findUnique({where:{workspaceId_profileId_channel_purpose:{workspaceId:w,profileId:p,channel:"email",purpose:"marketing"}}});return x?.currentStatus??"unknown"}
  async activeProtectedSuppression(w:string,p:string){return (await (this.db as any).suppression.count({where:{workspaceId:w,profileId:p,channel:"email",protected:true,revokedAt:null,OR:[{expiresAt:null},{expiresAt:{gt:new Date()}}]}}))>0}
  async senderIdentity(w:string,id:string){const x=await (this.db as any).senderIdentity.findFirst({where:{id,workspaceId:w}});return x?identity(x):null}
  async senderDomain(w:string,id:string){const x=await (this.db as any).senderDomain.findFirst({where:{id,workspaceId:w}});return x?domain(x):null}
  async workspaceProviderConfig(w:string,provider:string){const x=await (this.db as any).workspaceProviderConfig.findFirst({where:{workspaceId:w,provider}});return x?providerConfig(x):null}
  async deliveryRoute(w:string,senderDomainId:string){const x=await (this.db as any).emailDeliveryRoute.findFirst({where:{workspaceId:w,senderDomainId,archivedAt:null},orderBy:{updatedAt:"desc"}});return x?route(x):null}
  async createEmail(input:{workspaceId:string;name:string;authoringMode:string;draftDocument:StructuredEmailDocument;plainText:string}){return draft(await (this.db as any).emailDefinition.create({data:{workspaceId:input.workspaceId,name:input.name,authoringMode:input.authoringMode,draftDocumentJson:input.draftDocument,draftPlainText:input.plainText}}))}
  async emailDraft(w:string,id:string){const x=await (this.db as any).emailDefinition.findFirst({where:{id,workspaceId:w}});return x?draft(x):null}
  async listEmails(w:string){return (await (this.db as any).emailDefinition.findMany({where:{workspaceId:w,archivedAt:null},orderBy:{updatedAt:"desc"}})).map(draft)}
  async listEmailLibrary(w:string,input:{cursor?:string;limit:number;query?:string;sort?:"updated"|"name";archived?:boolean}){const where:any={workspaceId:w,archivedAt:input.archived?{not:null}:null};if(input.cursor)where.id={lt:input.cursor};if(input.query)where.OR=[{name:{contains:input.query,mode:"insensitive"}},{draftSubject:{contains:input.query,mode:"insensitive"}}];const orderBy=input.sort==="name"?[{name:"asc"},{id:"desc"}]:[{updatedAt:"desc"},{id:"desc"}];const rows=await (this.db as any).emailDefinition.findMany({where,orderBy,take:input.limit+1,include:{versions:{orderBy:{versionNumber:"desc"},take:1}}});const page=rows.slice(0,input.limit);const ids=page.map((x:any)=>x.id);const dependencies=ids.length?await (this.db as any).emailFlowDependency.groupBy({by:["emailDefinitionId"],where:{workspaceId:w,emailDefinitionId:{in:ids}},_count:{_all:true}}).catch(()=>[]):[];const usage=new Map(dependencies.map((x:any)=>[x.emailDefinitionId,x._count._all]));return {items:page.map((x:any)=>({id:x.id,internalName:x.name,authoringMode:"structured",subject:x.draftSubject,rowVersion:Number(x.rowVersion),draftState:x.archivedAt?"archived":"draft",latestPublishedVersion:x.versions[0]?{id:x.versions[0].id,versionNumber:x.versions[0].versionNumber,publishedAt:x.versions[0].publishedAt}:null,usedByFlowCount:usage.get(x.id)??0,preflight:x.lastPreflightJson?{...(x.lastPreflightJson as any),fingerprint:x.lastPreflightFingerprint,checkedAt:x.lastPreflightAt}: {state:"not_run"},updatedAt:x.updatedAt})),nextCursor:rows.length>input.limit?page.at(-1)?.id??null:null}}
  async updateEmailDraft(input:{workspaceId:string;emailId:string;expectedRowVersion:number;patch:Partial<EmailDraft>}){const p=input.patch;const data:any={lastPreflightJson:null,lastPreflightFingerprint:null,lastPreflightAt:null};if(p.internalName!==undefined)data.name=p.internalName;if(p.authoringMode!==undefined)data.authoringMode=p.authoringMode;if(p.structuredDocument!==undefined){data.draftDocumentJson=p.structuredDocument;if(p.plainTextMode!=="auto")data.plainTextStale=true}if(p.htmlSource!==undefined)data.draftHtmlSource=p.htmlSource;if(p.subject!==undefined)data.draftSubject=p.subject;if(p.preheader!==undefined)data.draftPreheader=p.preheader;if(p.senderIdentityId!==undefined)data.draftSenderIdentityId=p.senderIdentityId;if(p.replyTo!==undefined)data.draftReplyTo=p.replyTo;if(p.plainText!==undefined){data.draftPlainText=p.plainText;data.plainTextStale=false}if(p.plainTextMode!==undefined)data.plainTextMode=p.plainTextMode;if(p.trackingEnabled!==undefined)data.trackingEnabled=p.trackingEnabled;if(p.openTrackingEnabled!==undefined)data.openTrackingEnabled=p.openTrackingEnabled;data.rowVersion={increment:1};const result=await (this.db as any).emailDefinition.updateMany({where:{id:input.emailId,workspaceId:input.workspaceId,archivedAt:null,rowVersion:BigInt(input.expectedRowVersion)},data});if(result.count!==1)throw new Error("CONCURRENCY_CONFLICT");return draft(await (this.db as any).emailDefinition.findUniqueOrThrow({where:{id:input.emailId}}))}
  async listEmailVersions(w:string,id:string){return (await (this.db as any).emailVersion.findMany({where:{workspaceId:w,emailDefinitionId:id},orderBy:{versionNumber:"asc"}})).map(version)}
  async emailVersion(w:string,id:string){const x=await (this.db as any).emailVersion.findFirst({where:{id,workspaceId:w}});if(x)return version(x);const t=await (this.db as any).emailTestSnapshot.findFirst({where:{id,workspaceId:w}});if(!t)return null;return {id:t.id,workspaceId:t.workspaceId,emailDefinitionId:t.emailDefinitionId,versionNumber:0,authoringMode:"structured",authoringSchemaVersion:1,sourceDocument:t.sourceDocumentJson,sanitizedSource:null,compiledHtml:t.compiledHtml,compiledText:t.compiledText,subjectTemplate:t.subjectTemplate,preheaderTemplate:t.preheaderTemplate,senderIdentityId:t.senderIdentityId,replyTo:t.replyTo,trackingEnabled:t.trackingEnabled,openTrackingEnabled:false,senderSnapshot:t.senderSnapshotJson,contentHash:t.contentHash,compilerVersion:t.compilerVersion,sanitizerVersion:"phase2-structured-v1",preflight:t.preflightJson,publishedAt:t.createdAt.toISOString(),publishedBy:"test"} as PublishedEmailVersion}
  async insertEmailVersion(v:PublishedEmailVersion){return version(await (this.db as any).emailVersion.create({data:{id:v.id,workspaceId:v.workspaceId,emailDefinitionId:v.emailDefinitionId,versionNumber:v.versionNumber,authoringMode:v.authoringMode,authoringSchemaVersion:v.authoringSchemaVersion,sourceDocumentJson:v.sourceDocument as any,sanitizedSource:v.sanitizedSource,subjectTemplate:v.subjectTemplate,preheaderTemplate:v.preheaderTemplate,compiledHtml:v.compiledHtml,compiledText:v.compiledText,senderIdentityId:v.senderIdentityId,replyTo:v.replyTo,trackingEnabled:v.trackingEnabled??true,openTrackingEnabled:v.openTrackingEnabled??false,senderSnapshotJson:v.senderSnapshot as any,contentHash:v.contentHash,compilerVersion:v.compilerVersion,sanitizerVersion:v.sanitizerVersion,preflightJson:v.preflight as any,publishedAt:new Date(v.publishedAt),publishedBy:v.publishedBy}}))}
  async savePreflight(i:{workspaceId:string;emailId:string;result:unknown;fingerprint:string}){await (this.db as any).emailDefinition.updateMany({where:{id:i.emailId,workspaceId:i.workspaceId},data:{lastPreflightJson:i.result as any,lastPreflightFingerprint:i.fingerprint,lastPreflightAt:new Date()}})}
  async archiveEmail(i:{workspaceId:string;emailId:string;actorId:string;archived:boolean}){const x=await (this.db as any).emailDefinition.updateMany({where:{id:i.emailId,workspaceId:i.workspaceId},data:i.archived?{archivedAt:new Date(),archivedBy:i.actorId}:{archivedAt:null,archivedBy:null}});if(x.count!==1)throw new Error("EMAIL_NOT_FOUND");return draft(await (this.db as any).emailDefinition.findUniqueOrThrow({where:{id:i.emailId}}))}
  async createTestSnapshot(i:any){return (this.db as any).emailTestSnapshot.create({data:i})}
  async testSnapshot(w:string,id:string){return (this.db as any).emailTestSnapshot.findFirst({where:{id,workspaceId:w}})}
  async emailDependencies(w:string,emailId:string){return (this.db as any).emailFlowDependency.findMany({where:{workspaceId:w,emailDefinitionId:emailId},orderBy:{createdAt:"desc"}}).catch(()=>[])}
  async listEmailTemplates(w:string,input:{cursor?:string;limit:number;query?:string;archived?:boolean}){const where:any={workspaceId:w,archivedAt:input.archived?{not:null}:null};if(input.query)where.OR=[{name:{contains:input.query,mode:"insensitive"}},{category:{contains:input.query,mode:"insensitive"}}];const rows=await (this.db as any).emailTemplate.findMany({where,orderBy:[{updatedAt:"desc"},{id:"desc"}],...(input.cursor?{cursor:{id:input.cursor},skip:1}:{}),take:input.limit+1});const page=rows.slice(0,input.limit);return {items:page.map(template),nextCursor:rows.length>input.limit?page.at(-1)?.id??null:null}}
  async emailTemplate(w:string,id:string,input:{includeArchived?:boolean}={}){const x=await (this.db as any).emailTemplate.findFirst({where:{id,workspaceId:w,...(input.includeArchived?{}:{archivedAt:null})}});return x?template(x):null}
  async createEmailTemplate(i:{workspaceId:string;name:string;category?:string;document:StructuredEmailDocument;subject:string;preheader:string;plainText:string;settings?:Record<string,unknown>;editorType?:"visual"|"html"|"text";sourceType?:string;actorId:string}){return template(await (this.db as any).emailTemplate.create({data:{workspaceId:i.workspaceId,name:i.name,category:i.category,documentJson:i.document as any,subjectTemplate:i.subject,preheaderTemplate:i.preheader,plainText:i.plainText,settingsJson:i.settings as any,editorType:i.editorType??"visual",sourceType:i.sourceType??"blank",createdBy:i.actorId,updatedBy:i.actorId}}))}
  async createImportedEmailTemplate(i:{workspaceId:string;name:string;category?:string;document:StructuredEmailDocument;subject:string;preheader:string;plainText:string;settings?:Record<string,unknown>;actorId:string;templateType:string;importMethod:string;originalFilename:string|null;originalSourceHtml:string;sanitizedHtml:string;conversionStatus:string;importWarnings:P2EmailTemplate["importWarnings"];importedAt:Date;importedByUserId:string}){return template(await (this.db as any).emailTemplate.create({data:{workspaceId:i.workspaceId,name:i.name,category:i.category,documentJson:i.document as any,subjectTemplate:i.subject,preheaderTemplate:i.preheader,plainText:i.plainText,settingsJson:i.settings as any,editorType:"html",sourceType:i.importMethod,createdBy:i.actorId,updatedBy:i.actorId,templateType:i.templateType,importMethod:i.importMethod,originalFilename:i.originalFilename,originalSourceHtml:i.originalSourceHtml,sanitizedHtml:i.sanitizedHtml,conversionStatus:i.conversionStatus,importWarningsJson:i.importWarnings as any,importedAt:i.importedAt,importedByUserId:i.importedByUserId}}))}
  async updateEmailTemplate(i:{workspaceId:string;templateId:string;name?:string;category?:string|null;document?:StructuredEmailDocument;subject?:string;preheader?:string;plainText?:string;settings?:Record<string,unknown>|null;originalSourceHtml?:string|null;sanitizedHtml?:string|null;conversionStatus?:string;templateType?:string;importWarnings?:P2EmailTemplate["importWarnings"];actorId?:string}){const x=await (this.db as any).emailTemplate.updateMany({where:{id:i.templateId,workspaceId:i.workspaceId,archivedAt:null},data:{...(i.name!==undefined?{name:i.name}:{}),...(i.category!==undefined?{category:i.category}:{}),...(i.document!==undefined?{documentJson:i.document as any}:{}),...(i.subject!==undefined?{subjectTemplate:i.subject}:{}),...(i.preheader!==undefined?{preheaderTemplate:i.preheader}:{}),...(i.plainText!==undefined?{plainText:i.plainText}:{}),...(i.settings!==undefined?{settingsJson:i.settings as any}:{}),...(i.originalSourceHtml!==undefined?{originalSourceHtml:i.originalSourceHtml}:{}),...(i.sanitizedHtml!==undefined?{sanitizedHtml:i.sanitizedHtml}:{}),...(i.conversionStatus!==undefined?{conversionStatus:i.conversionStatus}:{}),...(i.templateType!==undefined?{templateType:i.templateType}:{}),...(i.importWarnings!==undefined?{importWarningsJson:i.importWarnings as any}:{}),...(i.actorId!==undefined?{updatedBy:i.actorId}:{})}});if(x.count!==1)throw new Error("TEMPLATE_NOT_FOUND");return template(await (this.db as any).emailTemplate.findUniqueOrThrow({where:{id:i.templateId}}))}
  async archiveEmailTemplate(i:{workspaceId:string;templateId:string;archived:boolean}){const x=await (this.db as any).emailTemplate.updateMany({where:{id:i.templateId,workspaceId:i.workspaceId},data:{archivedAt:i.archived?new Date():null}});if(x.count!==1)throw new Error("TEMPLATE_NOT_FOUND");return template(await (this.db as any).emailTemplate.findUniqueOrThrow({where:{id:i.templateId}}))}
  async deleteEmailTemplate(i:{workspaceId:string;templateId:string}){const found=await (this.db as any).emailTemplate.findFirst({where:{id:i.templateId,workspaceId:i.workspaceId},select:{id:true}});if(!found)throw new Error("TEMPLATE_NOT_FOUND");await (this.db as any).templateImportAudit.updateMany({where:{workspaceId:i.workspaceId,templateId:i.templateId},data:{templateId:null}});const deleted=await (this.db as any).emailTemplate.deleteMany({where:{id:i.templateId,workspaceId:i.workspaceId}});if(deleted.count!==1)throw new Error("TEMPLATE_NOT_FOUND")}
  async listUniversalBlocks(w:string,input:{archived?:boolean}){return (await (this.db as any).universalBlock.findMany({where:{workspaceId:w,archivedAt:input.archived?{not:null}:null},orderBy:{updatedAt:"desc"}})).map(universalBlock)}
  async createUniversalBlock(i:{workspaceId:string;name:string;category?:string;blocks:StructuredEmailDocument["blocks"];actorId:string}){return universalBlock(await (this.db as any).universalBlock.create({data:{workspaceId:i.workspaceId,name:i.name,category:i.category,blocksJson:i.blocks as any,createdBy:i.actorId}}))}
  async updateUniversalBlock(i:{workspaceId:string;blockId:string;name?:string;category?:string|null;blocks?:StructuredEmailDocument["blocks"]}){const x=await (this.db as any).universalBlock.updateMany({where:{id:i.blockId,workspaceId:i.workspaceId,archivedAt:null},data:{...(i.name===undefined?{}:{name:i.name}),...(i.category===undefined?{}:{category:i.category}),...(i.blocks===undefined?{}:{blocksJson:i.blocks as any})}});if(x.count!==1)throw new Error("UNIVERSAL_BLOCK_NOT_FOUND");return universalBlock(await (this.db as any).universalBlock.findUniqueOrThrow({where:{id:i.blockId}}))}
  async archiveUniversalBlock(i:{workspaceId:string;blockId:string;archived:boolean}){const x=await (this.db as any).universalBlock.updateMany({where:{id:i.blockId,workspaceId:i.workspaceId},data:{archivedAt:i.archived?new Date():null}});if(x.count!==1)throw new Error("UNIVERSAL_BLOCK_NOT_FOUND");return universalBlock(await (this.db as any).universalBlock.findUniqueOrThrow({where:{id:i.blockId}}))}
  async listMediaAssets(w:string,input:{archived?:boolean}){return (await (this.db as any).mediaAsset.findMany({where:{workspaceId:w,archivedAt:input.archived?{not:null}:null},orderBy:{updatedAt:"desc"}})).map(mediaAsset)}
  async createMediaAsset(i:{workspaceId:string;name:string;url:string;altText:string;mimeType:string;actorId:string;objectKey?:string;assetId?:string}){return mediaAsset(await (this.db as any).mediaAsset.create({data:{id:i.assetId,workspaceId:i.workspaceId,name:i.name,url:i.url,objectKey:i.objectKey,altText:i.altText,mimeType:i.mimeType,createdBy:i.actorId}}))}
  async contentAssetObjectKey(w:string,assetId:string){const x=await (this.db as any).mediaAsset.findFirst({where:{id:assetId,workspaceId:w,archivedAt:null}});return x?.objectKey??null}
  async archiveMediaAsset(i:{workspaceId:string;assetId:string;archived:boolean}){const x=await (this.db as any).mediaAsset.updateMany({where:{id:i.assetId,workspaceId:i.workspaceId},data:{archivedAt:i.archived?new Date():null}});if(x.count!==1)throw new Error("MEDIA_ASSET_NOT_FOUND");return mediaAsset(await (this.db as any).mediaAsset.findUniqueOrThrow({where:{id:i.assetId}}))}
  async brandKit(w:string){const x=await (this.db as any).workspaceBrandKit.findUnique({where:{workspaceId:w}});return x?brandKit(x):null}
  async upsertBrandKit(i:{workspaceId:string;logoUrl:string|null;primaryColor:string;secondaryColor:string;fontFamily:string}){return brandKit(await (this.db as any).workspaceBrandKit.upsert({where:{workspaceId:i.workspaceId},create:i,update:{logoUrl:i.logoUrl,primaryColor:i.primaryColor,secondaryColor:i.secondaryColor,fontFamily:i.fontFamily}}))}
  async listContentVariables(w:string,input:{archived?:boolean}){return (await (this.db as any).contentVariable.findMany({where:{workspaceId:w,archivedAt:input.archived?{not:null}:null},orderBy:{label:"asc"}})).map(contentVariable)}
  async createContentVariable(i:{workspaceId:string;key:string;label:string;defaultValue:string;type:"text"|"url";actorId:string}){return contentVariable(await (this.db as any).contentVariable.create({data:{workspaceId:i.workspaceId,key:i.key,label:i.label,defaultValue:i.defaultValue,type:i.type,createdBy:i.actorId}}))}
  async archiveContentVariable(i:{workspaceId:string;variableId:string;archived:boolean}){const x=await (this.db as any).contentVariable.updateMany({where:{id:i.variableId,workspaceId:i.workspaceId},data:{archivedAt:i.archived?new Date():null}});if(x.count!==1)throw new Error("CONTENT_VARIABLE_NOT_FOUND");return contentVariable(await (this.db as any).contentVariable.findUniqueOrThrow({where:{id:i.variableId}}))}
  async listTemplateVersions(w:string,templateId:string){return (await (this.db as any).emailTemplateVersion.findMany({where:{workspaceId:w,templateId},orderBy:{versionNumber:"desc"}})).map(templateVersion)}
  async insertTemplateVersion(i:Omit<P2TemplateVersion,"id">){return templateVersion(await (this.db as any).emailTemplateVersion.create({data:{workspaceId:i.workspaceId,templateId:i.templateId,versionNumber:i.versionNumber,documentJson:i.document as any,subjectTemplate:i.subject,preheaderTemplate:i.preheader,plainText:i.plainText,settingsJson:i.settings as any,contentHash:i.contentHash,approvedAt:i.approvedAt,approvedBy:i.approvedBy}}))}
  async recordTemplateUsage(i:{workspaceId:string;templateId:string;templateVersionId?:string;usageType:"email";referenceId:string;label:string}){await (this.db as any).templateUsage.create({data:{workspaceId:i.workspaceId,templateId:i.templateId,templateVersionId:i.templateVersionId,usageType:i.usageType,referenceId:i.referenceId,label:i.label}})}
  async recordTemplateImportAudit(i:{workspaceId:string;userId:string;importMethod:string;filename:string|null;templateId:string;processingResult:string;warningCount:number}){await (this.db as any).templateImportAudit.create({data:{id:randomUUID(),workspaceId:i.workspaceId,userId:i.userId,importMethod:i.importMethod,filename:i.filename,templateId:i.templateId,processingResult:i.processingResult,warningCount:i.warningCount}})}
  async templateUsage(w:string,templateId:string){const direct:P2TemplateUsage[]=(await (this.db as any).templateUsage.findMany({where:{workspaceId:w,templateId},orderBy:{createdAt:"desc"}})).map((x:any)=>({id:x.id,workspaceId:x.workspaceId,templateId:x.templateId,templateVersionId:x.templateVersionId,usageType:x.usageType,referenceId:x.referenceId,label:x.label,createdAt:x.createdAt} as P2TemplateUsage)),emailIds=direct.filter((item:P2TemplateUsage)=>item.usageType==="email").map((item:P2TemplateUsage)=>item.referenceId);if(!emailIds.length)return direct;const dependencies=await (this.db as any).emailFlowDependency.findMany({where:{workspaceId:w,emailDefinitionId:{in:emailIds}},orderBy:{createdAt:"desc"}}).catch(()=>[]);const flows=dependencies.map((dependency:any)=>({id:`${templateId}:${dependency.flowVersionId}:${dependency.nodeId}`,workspaceId:w,templateId,templateVersionId:null,usageType:"flow" as const,referenceId:dependency.flowId,label:`Flow ${dependency.flowId}`,createdAt:dependency.createdAt}));return [...direct,...flows]}
  async audit(i:{workspaceId:string;actorId:string;action:string;objectType:string;objectId?:string;riskLevel:string;before?:unknown;after?:unknown}){await (this.db as any).auditEvent.create({data:{workspaceId:i.workspaceId,actorType:"user",actorId:i.actorId,action:i.action,objectType:i.objectType,objectId:i.objectId,riskLevel:i.riskLevel,beforeJson:i.before as any,afterJson:i.after as any}})}
  async createMessage(input:{workspaceId:string;sourceType:string;sourceId:string;flowRunId?:string;nodeId?:string;profileId:string;emailVersionId:string;idempotencyKey:string;scheduledFor:Date}){const existing=await (this.db as any).message.findUnique({where:{workspaceId_idempotencyKey:{workspaceId:input.workspaceId,idempotencyKey:input.idempotencyKey}}});if(existing)return message(existing);const x=await (this.db as any).message.create({data:{...input,state:"created"}});await this.addTrace({workspaceId:input.workspaceId,messageId:x.id,kind:"message.intent_created",detail:{sourceType:input.sourceType,sourceId:input.sourceId}});return message(x)}
  async message(w:string,id:string){const x=await (this.db as any).message.findFirst({where:{id,workspaceId:w}});return x?message(x):null}
  async messageByIdempotency(w:string,key:string){const x=await (this.db as any).message.findUnique({where:{workspaceId_idempotencyKey:{workspaceId:w,idempotencyKey:key}}});return x?message(x):null}
  async updateMessage(i:{workspaceId:string;messageId:string;state:string;policyDecision?:MessagePolicyDecision;renderedHash?:string;renderedAt?:Date;submittedAt?:Date;finalAt?:Date}){const found=await (this.db as any).message.findFirst({where:{id:i.messageId,workspaceId:i.workspaceId}});if(!found)throw new Error("MESSAGE_NOT_FOUND");return message(await (this.db as any).message.update({where:{id:i.messageId},data:{state:i.state,policyDecision:i.policyDecision as any,renderedHash:i.renderedHash,renderedAt:i.renderedAt,submittedAt:i.submittedAt,finalAt:i.finalAt}}))}
  async trace(w:string,id:string){return (await (this.db as any).traceEvent.findMany({where:{workspaceId:w,aggregateType:"message",aggregateId:id},orderBy:{occurredAt:"asc"}})).map((x:any)=>({kind:x.kind,occurredAt:x.occurredAt,detail:x.detailJson}))}
  async addTrace(i:{workspaceId:string;messageId:string;kind:string;detail:unknown}){await (this.db as any).traceEvent.create({data:{workspaceId:i.workspaceId,aggregateType:"message",aggregateId:i.messageId,kind:i.kind,detailJson:i.detail as any}})}
  async addFlowRunTrace(i:{workspaceId:string;flowRunId:string;kind:string;detail:unknown}){await (this.db as any).traceEvent.create({data:{workspaceId:i.workspaceId,aggregateType:"flow_run",aggregateId:i.flowRunId,kind:i.kind,detailJson:i.detail as any}})}
  async activeSendPolicy(w:string){const x=await (this.db as any).sendPolicy.findFirst({where:{workspaceId:w,active:true},orderBy:{policyVersion:"desc"}});if(!x)return {version:1,frequencyWindowSeconds:86400,frequencyMax:3};const q=x.quietHoursJson as any, warm=x.warmingJson as any;return {version:x.policyVersion,frequencyWindowSeconds:x.frequencyWindowSeconds,frequencyMax:x.frequencyMax,quietHours:q?.startHour!==undefined?{startHour:q.startHour,endHour:q.endHour}:undefined,warmingDailyLimit:warm?.dailyLimit,feedbackStaleAfterSeconds:warm?.feedbackStaleAfterSeconds}}
  async saveSendPolicy(w:string,actor:string,c:SendPolicyConfig){await (this.db as any).sendPolicy.updateMany({where:{workspaceId:w,active:true},data:{active:false}});const warming=c.warmingDailyLimit===undefined&&c.feedbackStaleAfterSeconds===undefined?undefined:{...(c.warmingDailyLimit===undefined?{}:{dailyLimit:c.warmingDailyLimit}),...(c.feedbackStaleAfterSeconds===undefined?{}:{feedbackStaleAfterSeconds:c.feedbackStaleAfterSeconds})};await (this.db as any).sendPolicy.create({data:{workspaceId:w,policyVersion:c.version,frequencyWindowSeconds:c.frequencyWindowSeconds,frequencyMax:c.frequencyMax,quietHoursJson:c.quietHours as any,warmingJson:warming as any,createdBy:actor,active:true}})}
  async activeHolds(w:string){return (await (this.db as any).operationalHold.findMany({where:{workspaceId:w,state:"active"},orderBy:{createdAt:"desc"}})).map(hold)}
  async createHold(i:{workspaceId:string;scopeType:string;scopeId?:string;reason:string;actorId:string}){return hold(await (this.db as any).operationalHold.create({data:{workspaceId:i.workspaceId,scopeType:i.scopeType,scopeId:i.scopeId,reason:i.reason,state:"active",createdBy:i.actorId}}))}
  async releaseHold(i:{workspaceId:string;holdId:string;reason:string}){const x=await (this.db as any).operationalHold.updateMany({where:{id:i.holdId,workspaceId:i.workspaceId,state:"active"},data:{state:"released",releasedAt:new Date(),releaseReason:i.reason}});if(x.count!==1)throw new Error("HOLD_NOT_FOUND")}
  async frequencyCount(w:string,p:string,since:Date){return (this.db as any).frequencyReservation.count({where:{workspaceId:w,profileId:p,reservedAt:{gte:since},releasedAt:null}})}
  async reserveFrequency(i:{workspaceId:string;profileId:string;messageId:string;expiresAt:Date}){try{await (this.db as any).frequencyReservation.create({data:{...i,purpose:"marketing"}});return true}catch(e:any){if(e?.code==="P2002")return true;throw e}}
  async consumeFrequency(w:string,m:string){await (this.db as any).frequencyReservation.updateMany({where:{workspaceId:w,messageId:m,releasedAt:null},data:{consumedAt:new Date()}})}
  async releaseFrequency(w:string,m:string){await (this.db as any).frequencyReservation.updateMany({where:{workspaceId:w,messageId:m,consumedAt:null},data:{releasedAt:new Date()}})}
  async submittedToday(w:string,since:Date){return (this.db as any).message.count({where:{workspaceId:w,submittedAt:{gte:since},sourceType:{not:"test"}}})}
  async feedbackSafetyCurrent(w:string,staleAfterSeconds:number,now:Date){const submitted=await (this.db as any).message.count({where:{workspaceId:w,sourceType:{not:"test"},submittedAt:{not:null}}});if(!submitted)return true;const latest=await (this.db as any).deliveryEvent.aggregate({where:{workspaceId:w},_max:{receivedAt:true}});return Boolean(latest._max.receivedAt&&latest._max.receivedAt.getTime()>=now.getTime()-staleAfterSeconds*1000)}
  async saveArtifact(i:{workspaceId:string;messageId:string;objectKey:string;contentHash:string;mimeHash:string;byteSize:number;compilerVersion:string;sanitizerVersion:string}){await (this.db as any).renderedMessageArtifact.upsert({where:{workspaceId_messageId:{workspaceId:i.workspaceId,messageId:i.messageId}},create:i,update:i})}
  async artifact(w:string,m:string){const x=await (this.db as any).renderedMessageArtifact.findUnique({where:{workspaceId_messageId:{workspaceId:w,messageId:m}}});return x?{objectKey:x.objectKey,mimeHash:x.mimeHash,contentHash:x.contentHash}:null}
  async createAttempt(i:{workspaceId:string;messageId:string;attemptNumber:number;provider:string;routeId?:string;requestFingerprint:string}){const existing=await (this.db as any).deliveryAttempt.findUnique({where:{messageId_attemptNumber:{messageId:i.messageId,attemptNumber:i.attemptNumber}}});if(existing)return attempt(existing);return attempt(await (this.db as any).deliveryAttempt.create({data:{...i,state:"created"}}))}
  async updateAttempt(i:{workspaceId:string;attemptId:string;state:string;providerMessageId?:string;errorCode?:string}){const x=await (this.db as any).deliveryAttempt.updateMany({where:{id:i.attemptId,workspaceId:i.workspaceId},data:{state:i.state,providerMessageId:i.providerMessageId,errorCode:i.errorCode,responseAt:new Date(),...(i.state==="submitted"?{submittedAt:new Date()}:{})}});if(x.count!==1)throw new Error("ATTEMPT_NOT_FOUND")}
  async attemptByProviderMessageId(id:string){const x=await (this.db as any).deliveryAttempt.findFirst({where:{providerMessageId:id}});return x?attempt(x):null}
  async feedbackAuthority(provider:string,providerMessageId:string){const row=await (this.db as any).deliveryAttempt.findUnique({where:{provider_providerMessageId:{provider,providerMessageId}}});if(!row)return null;const messageRow=await (this.db as any).message.findUnique({where:{id:row.messageId}});if(!messageRow||messageRow.workspaceId!==row.workspaceId)throw new Error("FEEDBACK_AUTHORITY_MISMATCH");let routeRow:any=null;if(row.routeId){routeRow=await (this.db as any).emailDeliveryRoute.findUnique({where:{id:row.routeId}});if(!routeRow||routeRow.workspaceId!==row.workspaceId)throw new Error("FEEDBACK_ROUTE_AUTHORITY_MISMATCH")}return {attempt:attempt(row),message:message(messageRow),route:routeRow?route(routeRow):null}}
  async reserveDeliveryCapacity(input:{workspaceId:string;route?:P2DeliveryRoute;messageId:string;now:Date}){
    const exhausted=new Error("DELIVERY_CAPACITY_EXHAUSTED");
    const reserve=async(db:any)=>{
      if(input.route?.warmingDailyLimit&&input.route.warmingDailyLimit>0){
        const day=new Date(input.now);day.setUTCHours(0,0,0,0);
        const used=await db.deliveryAttempt.count({where:{workspaceId:input.workspaceId,routeId:input.route.id,submittedAt:{gte:day}}});
        if(used>=input.route.warmingDailyLimit)throw exhausted;
      }
      const start=new Date(Math.floor(input.now.getTime()/1000)*1000);
      const scopes:Array<[string,string,number]>=[["workspace",input.workspaceId,WORKSPACE_EMAILS_PER_SECOND]];
      const routeRate=input.route?.rateLimitPerSecond;
      if(routeRate&&routeRate>0)scopes.push(
        ["provider_region",`${input.route!.provider}:${input.route!.providerRegion}`,routeRate],
        ["sender_domain",input.route!.senderDomainId,routeRate],
        ["route",input.route!.id,routeRate],
      );
      for(const [scopeType,scopeId,capacityLimit] of scopes){
        const key={scopeType_scopeId_windowStart_windowSeconds:{scopeType,scopeId,windowStart:start,windowSeconds:1}};
        await db.deliveryCapacityBucket.upsert({where:key,create:{scopeType,scopeId,windowStart:start,windowSeconds:1,capacityLimit,used:0},update:{capacityLimit}});
        const claimed=await db.deliveryCapacityBucket.updateMany({where:{scopeType,scopeId,windowStart:start,windowSeconds:1,used:{lt:capacityLimit}},data:{used:{increment:1}}});
        if(claimed.count!==1)throw exhausted;
      }
      return true;
    };
    try{
      if("$transaction" in (this.db as any))return await (this.db as any).$transaction((tx:any)=>reserve(tx),{isolationLevel:"Serializable"});
      return await reserve(this.db as any);
    }catch(error){if(error===exhausted)return false;throw error}
  }
  async recordControlledSubmissionGate(i:{workspaceId:string;messageId:string}){await (this.db as any).phase2GateEvidence.upsert({where:{checkKey:"controlled_submission"},create:{checkKey:"controlled_submission",status:"passed",evidenceJson:{messageId:i.messageId,workspaceId:i.workspaceId,recordedAt:new Date().toISOString()}},update:{status:"passed",evidenceJson:{messageId:i.messageId,workspaceId:i.workspaceId,recordedAt:new Date().toISOString()},checkedAt:new Date()}})}
  async recordDeliveryEvent(i:{workspaceId:string;messageId:string;provider:string;providerEventId:string;eventType:string;occurredAt:Date;payload:unknown}){try{await (this.db as any).deliveryEvent.create({data:{workspaceId:i.workspaceId,messageId:i.messageId,provider:i.provider,providerEventId:i.providerEventId,eventType:i.eventType,occurredAt:i.occurredAt,receivedAt:new Date(),normalizedPayload:i.payload as any}});return true}catch(e:any){if(e?.code==="P2002")return false;throw e}}
  async recordMessageOpen(i:{workspaceId:string;messageId:string;occurredAt:Date}){await (this.db as any).$executeRaw(Prisma.sql`UPDATE "message" SET "first_opened_at"=CASE WHEN "first_opened_at" IS NULL OR "first_opened_at">${i.occurredAt} THEN ${i.occurredAt} ELSE "first_opened_at" END,"last_opened_at"=CASE WHEN "last_opened_at" IS NULL OR "last_opened_at"<${i.occurredAt} THEN ${i.occurredAt} ELSE "last_opened_at" END,"open_count"="open_count"+1 WHERE "id"=${i.messageId}::uuid AND "workspace_id"=${i.workspaceId}::uuid`)}
  async createProtectedSuppression(i:{workspaceId:string;profileId:string;reason:"hard_bounce"|"complaint";sourceReference:string}){const existing=await (this.db as any).suppression.findFirst({where:{workspaceId:i.workspaceId,profileId:i.profileId,channel:"email",reason:i.reason,revokedAt:null}});if(existing)return;await (this.db as any).suppression.create({data:{workspaceId:i.workspaceId,profileId:i.profileId,channel:"email",scope:"marketing",reason:i.reason,source:"provider",sourceReference:i.sourceReference,protected:true}})}
  async createTrackingLink(i:{workspaceId:string;messageId:string;destination:string;destinationHash:string}){const existing=await (this.db as any).trackingLink.findFirst({where:{workspaceId:i.workspaceId,messageId:i.messageId,destinationHash:i.destinationHash}});if(existing)return tracking(existing);return tracking(await (this.db as any).trackingLink.create({data:i}))}
  async trackingLink(w:string,id:string){const x=await (this.db as any).trackingLink.findFirst({where:{id,workspaceId:w}});return x?tracking(x):null}
  async engagementFact(i:{workspaceId:string;messageId:string;kind:"click"|"open";classification:string;occurredAt:Date;metadata?:unknown}){await (this.db as any).traceEvent.create({data:{workspaceId:i.workspaceId,aggregateType:"message",aggregateId:i.messageId,kind:`engagement.${i.kind}`,detailJson:{classification:i.classification,metadata:i.metadata} as any,occurredAt:i.occurredAt}})}
  async analyticsSummary(w:string,since:Date){const [msgs,events]=await Promise.all([(this.db as any).message.findMany({where:{workspaceId:w,createdAt:{gte:since},sourceType:{not:"test"}},select:{state:true,submittedAt:true}}),(this.db as any).traceEvent.findMany({where:{workspaceId:w,aggregateType:"message",occurredAt:{gte:since},kind:{in:["engagement.click","engagement.open"]}},select:{kind:true}})]);const out:Record<string,number>={intents:msgs.length,submitted:0,delivered:0,bounced:0,complained:0,failed:0,held:0,skipped:0,cancelled:0,clicks:0,opens:0};for(const m of msgs){if(m.submittedAt)out.submitted!++;if(out[m.state]!==undefined)out[m.state]!++}for(const e of events)out[e.kind.endsWith("click")?"clicks":"opens"]!++;return out}
  async analyticsPeriod(w:string,from:Date,to:Date){const [submitted,events,engagement]=await Promise.all([(this.db as any).message.count({where:{workspaceId:w,sourceType:{not:"test"},submittedAt:{gte:from,lte:to}}}),(this.db as any).deliveryEvent.groupBy({by:["eventType"],where:{workspaceId:w,occurredAt:{gte:from,lte:to},eventType:{in:["delivery","delivered","bounce","soft_bounce","hard_bounce","complaint"]}},_count:{_all:true}}),(this.db as any).$queryRaw(Prisma.sql`SELECT COUNT(DISTINCT t.aggregate_id) FILTER (WHERE t.kind='engagement.click')::bigint AS clicks, COUNT(DISTINCT t.aggregate_id) FILTER (WHERE t.kind='engagement.open')::bigint AS opens FROM "trace_event" t JOIN "message" m ON m.id=t.aggregate_id AND m.workspace_id=t.workspace_id WHERE t.workspace_id=${w}::uuid AND t.aggregate_type='message' AND t.kind IN ('engagement.click','engagement.open') AND t.occurred_at>=${from} AND t.occurred_at<=${to} AND m.source_type<>'test'`)]);const count=(kind:string)=>Number(events.find((x:any)=>x.eventType===kind)?._count._all??0),row=(engagement as Array<{clicks:bigint;opens:bigint}>)[0];return {submitted,delivered:count("delivery")+count("delivered"),bounces:count("bounce")+count("soft_bounce")+count("hard_bounce"),complaints:count("complaint"),uniqueClicks:Number(row?.clicks??0),uniqueOpens:Number(row?.opens??0),from,to,freshness:new Date()}}
}
