import { createHash } from 'node:crypto';
import { Prisma, type PrismaClient } from '@prisma/client';
import type { Phase3Repository,Segment3,SegmentEstimate3,SegmentVersion3,StoredEvent3,Flow3,FlowVersion3 } from '../../../application/src/ports/phase3-repository.js';
import type { Phase3RuntimeRepository,RuntimeFlow3,RuntimeFlowVersion3,RuntimeFlowRun3,RuntimeNodeExecution3,RuntimeScheduledAction3,RuntimeProfileContext3,FlowRunState3 } from '../../../application/src/ports/phase3-runtime-repository.js';
import type { Phase3ProjectionRepository } from '../../../application/src/ports/phase3-projection-repository.js';
import type { Phase3ApiKeyRepository } from '../../../application/src/ports/phase3-api-key-repository.js';
import type { SegmentRule } from '../../../domain/src/phase3/segment-rules.js';
import { compileSegmentRule } from '../../../domain/src/phase3/segment-rules.js';
import type { GenericEventInput,GenericEventSchema } from '../../../domain/src/phase3/generic-events.js';
import type { FlowGraph3 } from '../../../domain/src/phase3/flow.js';
import { flowGraphHash, listTriggerIncludesExisting, normalizeFlowGraph3 } from '../../../domain/src/phase3/flow.js';
import { localCalendarDateInstant } from '../../../domain/src/phase3/runtime-time.js';

function seg(x:any):Segment3{return {id:x.id,workspaceId:x.workspaceId,name:x.name,description:x.description,status:x.status,draftRule:x.draftRuleJson as SegmentRule,createdAt:x.createdAt,updatedAt:x.updatedAt}}
function segv(x:any):SegmentVersion3{return {id:x.id,workspaceId:x.workspaceId,segmentId:x.segmentId,versionNumber:x.versionNumber,rule:x.ruleAstJson as SegmentRule,publishedAt:x.publishedAt}}
function event(x:any):StoredEvent3{return {id:x.id,workspaceId:x.workspaceId,eventId:x.externalEventId,name:x.eventName,occurredAt:x.occurredAt.toISOString(),profileId:x.profileId??undefined,source:x.source,schemaVersion:x.schemaVersion,properties:x.propertiesJson as Record<string,unknown>,idempotencyKey:x.idempotencyKey,receivedAt:x.receivedAt.toISOString()}}
function flow(x:any):Flow3 & RuntimeFlow3{return {id:x.id,workspaceId:x.workspaceId,name:x.name,status:x.status,draftGraph:x.draftGraphJson as FlowGraph3,activeVersionId:x.activeVersionId??undefined,activeVersionActivatedAt:x.activeVersionActivatedAt??null,rowVersion:Number(x.rowVersion),updatedAt:x.updatedAt,entryState:(x.entryState??'open') as any,executionState:(x.executionState??'running') as any,pausedAt:x.pausedAt}}
function flowv(x:any):FlowVersion3{return {id:x.id,workspaceId:x.workspaceId,flowId:x.flowId,versionNumber:x.versionNumber,graph:x.graphJson as FlowGraph3,graphHash:x.graphHash,publishedAt:x.publishedAt}}
function rflow(x:any):RuntimeFlow3{return {id:x.id,workspaceId:x.workspaceId,status:x.status,activeVersionId:x.activeVersionId??undefined,activeVersionActivatedAt:x.activeVersionActivatedAt??null,entryState:(x.entryState??'open') as any,executionState:(x.executionState??'running') as any,pausedAt:x.pausedAt}}
function rversion(x:any):RuntimeFlowVersion3{return {id:x.id,workspaceId:x.workspaceId,flowId:x.flowId,versionNumber:x.versionNumber,graph:x.graphJson as FlowGraph3,graphHash:x.graphHash}}
function rrun(x:any):RuntimeFlowRun3{return {id:x.id,workspaceId:x.workspaceId,flowId:x.flowId,flowVersionId:x.flowVersionId,profileId:x.profileId,triggerEventId:x.triggerEventId,deduplicationKey:x.deduplicationKey,state:x.state,currentNodeId:x.currentNodeId,enteredAt:x.enteredAt,nextActionAt:x.nextActionAt,endedAt:x.endedAt,exitReason:x.exitReason,rowVersion:Number(x.rowVersion)}}
function rexec(x:any):RuntimeNodeExecution3{return {id:x.id,workspaceId:x.workspaceId,flowRunId:x.flowRunId,nodeId:x.nodeId,attemptSequence:x.attemptSequence,state:x.state,scheduledAt:x.scheduledAt,startedAt:x.startedAt,completedAt:x.completedAt,inputSnapshot:x.inputSnapshot,evaluationResult:x.evaluationResult,error:x.errorJson}}
function raction(x:any):RuntimeScheduledAction3{return {id:x.id,workspaceId:x.workspaceId,flowRunId:x.aggregateId,nodeId:String((x.payloadJson as any)?.nodeId??''),deduplicationKey:x.deduplicationKey??`${x.aggregateId}|${(x.payloadJson as any)?.nodeId??''}`,dueAt:x.dueAt,state:x.state,leaseOwner:x.leaseOwner,leaseExpiresAt:x.leaseExpiresAt,attemptCount:x.attemptCount,createdAt:x.createdAt,completedAt:x.completedAt}}

export class PrismaPhase3Repository implements Phase3Repository,Phase3RuntimeRepository,Phase3ProjectionRepository,Phase3ApiKeyRepository{
  constructor(private readonly db:PrismaClient|Prisma.TransactionClient){}
  async transaction<T>(fn:(tx:any)=>Promise<T>):Promise<T>{if(!('$transaction' in this.db))return fn(this);return (this.db as PrismaClient).$transaction(async tx=>fn(new PrismaPhase3Repository(tx)),{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}

  async createSegment(i:{workspaceId:string;name:string;description?:string;rule:SegmentRule}){return seg(await (this.db as any).segment.create({data:{workspaceId:i.workspaceId,name:i.name,description:i.description??'',draftRuleJson:i.rule}}))}
  async updateSegment(i:{workspaceId:string;segmentId:string;name?:string;description?:string;rule?:SegmentRule}){const data:any={rowVersion:{increment:1}};if(i.name!==undefined)data.name=i.name;if(i.description!==undefined)data.description=i.description;if(i.rule!==undefined)data.draftRuleJson=i.rule;const n=await (this.db as any).segment.updateMany({where:{id:i.segmentId,workspaceId:i.workspaceId},data});if(n.count!==1)throw new Error('SEGMENT_NOT_FOUND');return seg(await (this.db as any).segment.findUniqueOrThrow({where:{id:i.segmentId}}))}
  async listSegments(w:string){return (await (this.db as any).segment.findMany({where:{workspaceId:w},orderBy:{updatedAt:'desc'}})).map(seg)}
  async segment(w:string,id:string){const x=await (this.db as any).segment.findFirst({where:{id,workspaceId:w}});return x?seg(x):null}
  async publishSegment(w:string,id:string){const s=await this.segment(w,id);if(!s)throw new Error('SEGMENT_NOT_FOUND');const last=await (this.db as any).segmentVersion.aggregate({where:{segmentId:id},_max:{versionNumber:true}}),v=await (this.db as any).segmentVersion.create({data:{workspaceId:w,segmentId:id,versionNumber:(last._max.versionNumber??0)+1,ruleAstJson:s.draftRule,ruleSchemaVersion:1}});await (this.db as any).segment.update({where:{id},data:{status:'active'}});return segv(v)}
  async estimateSegment(w:string,id:string):Promise<SegmentEstimate3>{const s=await this.segment(w,id);if(!s)throw new Error('SEGMENT_NOT_FOUND');const plan=compileSegmentRule(s.draftRule),wp=plan.params.length+1,sql=`SELECT p.id, p.normalized_email IS NOT NULL AND EXISTS (SELECT 1 FROM subscription_state ss WHERE ss.workspace_id=p.workspace_id AND ss.profile_id=p.id AND ss.channel='email' AND ss.purpose='marketing' AND ss.current_status='granted') AND NOT EXISTS (SELECT 1 FROM suppression sp WHERE sp.workspace_id=p.workspace_id AND sp.profile_id=p.id AND sp.channel='email' AND sp.revoked_at IS NULL AND (sp.expires_at IS NULL OR sp.expires_at>NOW())) AS eligible FROM profile p WHERE p.workspace_id=$${wp}::uuid AND p.deleted_at IS NULL AND (${plan.sql}) LIMIT 10001`;const rows=await (this.db as any).$queryRawUnsafe(sql,...plan.params,w);const exact=rows.length<=10000,count=exact?rows.length:10000,eligibleCount=rows.slice(0,10000).filter((x:any)=>x.eligible).length;return {segmentId:id,count,eligibleCount,sampleProfileIds:rows.slice(0,5).map((x:any)=>x.id),evaluatedAt:new Date(),status:'stale',exact,lowerBound:exact?undefined:10001}}

  async saveEventSchema(w:string,s:GenericEventSchema){await (this.db as any).eventSchema.upsert({where:{workspaceId_eventName_schemaVersion:{workspaceId:w,eventName:s.name,schemaVersion:s.version}},create:{workspaceId:w,eventName:s.name,schemaVersion:s.version,propertySchemaJson:{properties:s.properties},status:'active'},update:{propertySchemaJson:{properties:s.properties},status:'active'}})}
  async eventSchema(w:string,n:string,v:number){const x=await (this.db as any).eventSchema.findUnique({where:{workspaceId_eventName_schemaVersion:{workspaceId:w,eventName:n,schemaVersion:v}}});if(!x)return null;return {name:x.eventName,version:x.schemaVersion,properties:((x.propertySchemaJson as any)?.properties??{})}}
  async insertEvent(w:string,i:GenericEventInput){const existing=await (this.db as any).event.findUnique({where:{workspaceId_source_idempotencyKey:{workspaceId:w,source:i.source,idempotencyKey:i.idempotencyKey}}});if(existing)return {event:event(existing),duplicate:true};try{return this.transaction(async tx=>{const db=(tx as PrismaPhase3Repository).db as any,x=await db.event.create({data:{workspaceId:w,eventName:i.name,externalEventId:i.eventId,profileId:i.profileId,source:i.source,occurredAt:new Date(i.occurredAt),propertiesJson:i.properties,schemaVersion:i.schemaVersion,idempotencyKey:i.idempotencyKey,processingStatus:'accepted'}});await db.outboxEvent.create({data:{workspaceId:w,aggregateType:'event',aggregateId:x.id,eventType:'phase3.event.accepted',eventVersion:1,payloadJson:{eventId:x.id}}});return {event:event(x),duplicate:false}})}catch(e:any){if(e?.code==='P2002'){const x=await (this.db as any).event.findUniqueOrThrow({where:{workspaceId_source_idempotencyKey:{workspaceId:w,source:i.source,idempotencyKey:i.idempotencyKey}}});return {event:event(x),duplicate:true}}throw e}}
  async eventById(w:string,id:string){const x=await (this.db as any).event.findFirst({where:{id,workspaceId:w}});return x?event(x):null}
  async listEvents(w:string){return (await (this.db as any).event.findMany({where:{workspaceId:w},orderBy:{receivedAt:'desc'},take:500})).map(event)}

  async createFlow(i:{workspaceId:string;name:string;graph:FlowGraph3}){const graph=normalizeFlowGraph3(i.graph);return flow(await (this.db as any).flow.create({data:{workspaceId:i.workspaceId,name:i.name,draftGraphJson:graph,status:'draft'}}))}
  async updateFlow(i:{workspaceId:string;flowId:string;graph:FlowGraph3;rowVersion:number;name?:string}){const name=i.name?.trim();if(i.name!==undefined&&!name)throw new Error('FLOW_NAME_REQUIRED');const graph=normalizeFlowGraph3(i.graph);const n=await (this.db as any).flow.updateMany({where:{id:i.flowId,workspaceId:i.workspaceId,rowVersion:BigInt(i.rowVersion)},data:{draftGraphJson:graph,...(name?{name}:{}),rowVersion:{increment:1}}});if(n.count!==1)throw new Error('FLOW_CONFLICT');return flow(await (this.db as any).flow.findUniqueOrThrow({where:{id:i.flowId}}))}
  async flow(w:string,id:string):Promise<any>{const x=await (this.db as any).flow.findFirst({where:{id,workspaceId:w}});return x?flow(x):null}
  async listFlows(w:string){return (await (this.db as any).flow.findMany({where:{workspaceId:w},orderBy:{updatedAt:'desc'}})).map(flow)}
  async publishFlow(w:string,id:string,expectedRowVersion?:number){return this.transaction(async tx=>{const db=(tx as PrismaPhase3Repository).db as any;await db.$queryRawUnsafe('SELECT id FROM "flow" WHERE id=$1::uuid AND workspace_id=$2::uuid FOR UPDATE',id,w);const raw=await db.flow.findFirst({where:{id,workspaceId:w}});if(!raw)throw new Error('FLOW_NOT_FOUND');const f=flow(raw) as Flow3;if(expectedRowVersion!==undefined&&f.rowVersion!==expectedRowVersion)throw new Error('FLOW_CONFLICT');f.draftGraph=normalizeFlowGraph3(f.draftGraph);const nodes=f.draftGraph.nodes.filter((n:any)=>n.type==='email') as Array<{id:string;emailVersionId:string}>;const emails=[] as Array<{id:string;emailDefinitionId:string;publishedAt:Date}>;for(const node of nodes){const email=await db.emailVersion.findFirst({where:{id:node.emailVersionId,workspaceId:w,definition:{archivedAt:null}},select:{id:true,emailDefinitionId:true,publishedAt:true}});if(!email?.publishedAt)throw new Error('EMAIL_VERSION_NOT_PUBLISHED');emails.push(email)}const last=await db.flowVersion.aggregate({where:{flowId:id},_max:{versionNumber:true}}),v=await db.flowVersion.create({data:{workspaceId:w,flowId:id,versionNumber:(last._max.versionNumber??0)+1,graphJson:f.draftGraph,graphSchemaVersion:1,graphHash:flowGraphHash(f.draftGraph),entryPolicyJson:f.draftGraph.entryPolicy,exitRulesJson:f.draftGraph.exitRules,publishedAt:new Date()}});for(let index=0;index<nodes.length;index++){const node=nodes[index]!,email=emails[index]!;await db.emailFlowDependency.create({data:{workspaceId:w,emailDefinitionId:email.emailDefinitionId,emailVersionId:email.id,flowId:id,flowVersionId:v.id,nodeId:node.id}})}const trigger=f.draftGraph.trigger;await db.flowTriggerDependency.create({data:{workspaceId:w,flowId:id,flowVersionId:v.id,triggerType:trigger.type,referenceId:trigger.type==='list_joined'?trigger.listId:trigger.type==='segment_entered'?trigger.segmentId:null,eventName:trigger.type==='generic_event'?trigger.eventName:null,schemaVersion:trigger.type==='generic_event'?trigger.schemaVersion:null,dateField:trigger.type==='profile_date'?trigger.field:null}});return flowv(v)})}
  async activateFlow(w:string,id:string,v:string,status:'testing'|'active'){const version=await (this.db as any).flowVersion.findFirst({where:{id:v,workspaceId:w,flowId:id}});if(!version)throw new Error('FLOW_VERSION_NOT_FOUND');return flow(await (this.db as any).flow.update({where:{id,workspaceId:w},data:{activeVersionId:v,activeVersionActivatedAt:new Date(),status,entryState:'open',executionState:'running',pausedAt:null}}))}
  async scheduleListJoinEntries(i:{workspaceId:string;flowId:string;flowVersionId:string;activatedAt:Date}){const version=await (this.db as any).flowVersion.findFirst({where:{id:i.flowVersionId,workspaceId:i.workspaceId,flowId:i.flowId},select:{graphJson:true}}),graph=version?.graphJson as FlowGraph3|undefined,trigger=graph?.trigger;if(!trigger||trigger.type!=='list_joined'||!trigger.listId||!listTriggerIncludesExisting(trigger))return {scheduled:0,skipped:0};const memberships=await (this.db as any).listMembership.findMany({where:{workspaceId:i.workspaceId,listId:trigger.listId,state:'active'},select:{id:true,listId:true,profileId:true,joinedAt:true}});let scheduled=0,skipped=0;for(const membership of memberships){try{await (this.db as any).outboxEvent.create({data:{workspaceId:i.workspaceId,aggregateType:'list_membership',aggregateId:membership.id,eventType:'phase3.audience.list.entered',eventVersion:1,payloadJson:{membershipId:membership.id,listId:membership.listId,profileId:membership.profileId,occurredAt:i.activatedAt.toISOString(),activationReplay:true,flowVersionId:i.flowVersionId},deduplicationKey:`list-activation:${i.flowVersionId}:${membership.id}`}});scheduled++}catch(e:any){if(e?.code==='P2002')skipped++;else throw e}}return {scheduled,skipped}}
  async scheduleProfileDateEntries(i:{workspaceId:string;flowId:string;flowVersionId:string;activatedAt:Date}){const version=await (this.db as any).flowVersion.findFirst({where:{id:i.flowVersionId,workspaceId:i.workspaceId,flowId:i.flowId},select:{graphJson:true}}),trigger=(version?.graphJson as any)?.trigger;if(trigger?.type!=='profile_date')return {scheduled:0,skipped:0};const definition=await (this.db as any).profilePropertyDefinition.findFirst({where:{workspaceId:i.workspaceId,key:trigger.field,status:'active'},select:{id:true,dataType:true}});if(!definition||!['date','datetime'].includes(String(definition.dataType)))throw new Error('DATE_TRIGGER_PROPERTY_INVALID');const values=await (this.db as any).profilePropertyValue.findMany({where:{workspaceId:i.workspaceId,definitionId:definition.id,datetimeValue:{not:null},profile:{deletedAt:null}},select:{profileId:true,datetimeValue:true,profile:{select:{timezone:true,workspace:{select:{timezone:true}}}}}});let scheduled=0,skipped=0;for(const value of values){try{const timezone=value.profile.timezone??value.profile.workspace.timezone,dueAt=localCalendarDateInstant({date:value.datetimeValue,timeZone:timezone,hour:trigger.hour,minute:trigger.minute});if(dueAt<i.activatedAt){skipped++;continue}await (this.db as any).flowDateTriggerSchedule.upsert({where:{flowVersionId_profileId:{flowVersionId:i.flowVersionId,profileId:value.profileId}},create:{workspaceId:i.workspaceId,flowId:i.flowId,flowVersionId:i.flowVersionId,profileId:value.profileId,dateField:trigger.field,sourceDate:value.datetimeValue,dueAt,state:'pending'},update:{sourceDate:value.datetimeValue,dueAt,state:'pending',leaseOwner:null,leaseExpiresAt:null,dispatchedAt:null}});scheduled++}catch{skipped++}}return {scheduled,skipped}}
  async phase2ExternalGatePassed(){const x=await (this.db as any).phase2GateEvidence.findUnique({where:{checkKey:'controlled_submission'}});return x?.status==='passed'}

  async publishedFlowVersion(w:string,id:string){const x=await (this.db as any).flowVersion.findFirst({where:{id,workspaceId:w}});return x?flowv(x):null}
  async flowVersion(w:string,id:string){const x=await (this.db as any).flowVersion.findFirst({where:{id,workspaceId:w}});return x?rversion(x):null}
  async profileContext(w:string,id:string):Promise<RuntimeProfileContext3|null>{const x=await (this.db as any).profile.findFirst({where:{id,workspaceId:w,deletedAt:null},select:{id:true,workspaceId:true,timezone:true,workspace:{select:{timezone:true}}}});return x?{id:x.id,workspaceId:x.workspaceId,timezone:x.timezone,workspaceTimezone:x.workspace.timezone}:null}
  async latestRunForProfile(w:string,f:string,p:string){const x=await (this.db as any).flowRun.findFirst({where:{workspaceId:w,flowId:f,profileId:p},orderBy:{enteredAt:'desc'}});return x?rrun(x):null}
  async createRunIfAbsent(i:{workspaceId:string;flowId:string;flowVersionId:string;profileId:string;triggerEventId?:string;deduplicationKey:string;firstNodeId:string;enteredAt:Date}){const existing=await (this.db as any).flowRun.findUnique({where:{workspaceId_flowVersionId_deduplicationKey:{workspaceId:i.workspaceId,flowVersionId:i.flowVersionId,deduplicationKey:i.deduplicationKey}}});if(existing)return {run:rrun(existing),duplicate:true};try{const x=await (this.db as any).flowRun.create({data:{workspaceId:i.workspaceId,flowId:i.flowId,flowVersionId:i.flowVersionId,profileId:i.profileId,triggerEventId:i.triggerEventId,deduplicationKey:i.deduplicationKey,state:'active',currentNodeId:i.firstNodeId,enteredAt:i.enteredAt,nextActionAt:i.enteredAt}});return {run:rrun(x),duplicate:false}}catch(e:any){if(e?.code==='P2002'){const x=await (this.db as any).flowRun.findUniqueOrThrow({where:{workspaceId_flowVersionId_deduplicationKey:{workspaceId:i.workspaceId,flowVersionId:i.flowVersionId,deduplicationKey:i.deduplicationKey}}});return {run:rrun(x),duplicate:true}}throw e}}
  async run(w:string,id:string){const x=await (this.db as any).flowRun.findFirst({where:{id,workspaceId:w}});return x?rrun(x):null}
  async listRuns(w:string,f:string){return (await (this.db as any).flowRun.findMany({where:{workspaceId:w,flowId:f},orderBy:{enteredAt:'desc'}})).map(rrun)}
  async updateRun(i:{workspaceId:string;runId:string;state?:FlowRunState3;currentNodeId?:string;nextActionAt?:Date|null;endedAt?:Date|null;exitReason?:string|null}){const data:any={rowVersion:{increment:1}};for(const k of ['state','currentNodeId','nextActionAt','endedAt','exitReason'] as const)if(i[k]!==undefined)data[k]=i[k];const n=await (this.db as any).flowRun.updateMany({where:{id:i.runId,workspaceId:i.workspaceId},data});if(n.count!==1)throw new Error('FLOW_RUN_NOT_FOUND');return rrun(await (this.db as any).flowRun.findUniqueOrThrow({where:{id:i.runId}}))}
  async beginNodeExecution(i:{workspaceId:string;flowRunId:string;nodeId:string;scheduledAt?:Date;inputSnapshot?:unknown}){const prior=await (this.db as any).flowNodeExecution.findFirst({where:{flowRunId:i.flowRunId,nodeId:i.nodeId},orderBy:{attemptSequence:'desc'}});if(prior&&prior.state!=='failed')return {execution:rexec(prior),duplicate:true};const attempt=(prior?.attemptSequence??0)+1;try{const x=await (this.db as any).flowNodeExecution.create({data:{workspaceId:i.workspaceId,flowRunId:i.flowRunId,nodeId:i.nodeId,attemptSequence:attempt,state:'started',scheduledAt:i.scheduledAt,startedAt:new Date(),inputSnapshot:i.inputSnapshot as any}});return {execution:rexec(x),duplicate:false}}catch(e:any){if(e?.code==='P2002'){const x=await (this.db as any).flowNodeExecution.findUniqueOrThrow({where:{flowRunId_nodeId_attemptSequence:{flowRunId:i.flowRunId,nodeId:i.nodeId,attemptSequence:attempt}}});return {execution:rexec(x),duplicate:x.state!=='failed'}}throw e}}
  async completeNodeExecution(i:{workspaceId:string;executionId:string;evaluationResult?:unknown}){const n=await (this.db as any).flowNodeExecution.updateMany({where:{id:i.executionId,workspaceId:i.workspaceId},data:{state:'completed',completedAt:new Date(),evaluationResult:i.evaluationResult as any}});if(n.count!==1)throw new Error('NODE_EXECUTION_NOT_FOUND')}
  async failNodeExecution(i:{workspaceId:string;executionId:string;error:unknown}){await (this.db as any).flowNodeExecution.updateMany({where:{id:i.executionId,workspaceId:i.workspaceId},data:{state:'failed',completedAt:new Date(),errorJson:i.error as any}})}
  async scheduleAction(i:{workspaceId:string;flowRunId:string;nodeId:string;deduplicationKey:string;dueAt:Date}){const old=await (this.db as any).scheduledAction.findUnique({where:{deduplicationKey:i.deduplicationKey}});if(old)return raction(old);try{return raction(await (this.db as any).scheduledAction.create({data:{workspaceId:i.workspaceId,actionType:'flow.node',aggregateType:'flow_run',aggregateId:i.flowRunId,dueAt:i.dueAt,state:'pending',payloadVersion:1,payloadJson:{nodeId:i.nodeId},deduplicationKey:i.deduplicationKey}}))}catch(e:any){if(e?.code==='P2002')return raction(await (this.db as any).scheduledAction.findUniqueOrThrow({where:{deduplicationKey:i.deduplicationKey}}));throw e}}
  async claimDueActions(i:{now:Date;leaseOwner:string;leaseMs:number;limit:number}){if(!('$transaction' in this.db))throw new Error('LEASE_CLAIM_REQUIRES_PRISMA_CLIENT');return (this.db as PrismaClient).$transaction(async tx=>{const rows:any[]=await tx.$queryRawUnsafe(`SELECT * FROM "scheduled_action" WHERE "state"='pending' AND "due_at" <= $1 ORDER BY "due_at" ASC FOR UPDATE SKIP LOCKED LIMIT ${Math.max(1,Math.min(i.limit,1000))}`,i.now);if(!rows.length)return [];const ids=rows.map(x=>x.id);await (tx as any).scheduledAction.updateMany({where:{id:{in:ids}},data:{state:'leased',leaseOwner:i.leaseOwner,leaseExpiresAt:new Date(i.now.getTime()+i.leaseMs),attemptCount:{increment:1}}});return (await (tx as any).scheduledAction.findMany({where:{id:{in:ids}},orderBy:{dueAt:'asc'}})).map(raction)})}
  async scheduledAction(w:string,id:string){const x=await (this.db as any).scheduledAction.findFirst({where:{id,workspaceId:w}});return x?raction(x):null}
  async completeAction(w:string,id:string){await (this.db as any).scheduledAction.updateMany({where:{id,workspaceId:w},data:{state:'completed',completedAt:new Date(),leaseOwner:null,leaseExpiresAt:null}})}
  async releaseExpiredLeases(now:Date){const x=await (this.db as any).scheduledAction.updateMany({where:{state:'leased',leaseExpiresAt:{lte:now}},data:{state:'pending',leaseOwner:null,leaseExpiresAt:null}});return x.count}
  async addTrace(w:string,r:string,kind:string,detail:Record<string,unknown>,occurredAt=new Date()){await (this.db as any).traceEvent.create({data:{workspaceId:w,aggregateType:'flow_run',aggregateId:r,kind,detailJson:detail as any,occurredAt}})}
  async trace(w:string,r:string){return (await (this.db as any).traceEvent.findMany({where:{workspaceId:w,aggregateType:'flow_run',aggregateId:r},orderBy:{occurredAt:'asc'}})).map((x:any)=>({kind:x.kind,occurredAt:x.occurredAt,detail:x.detailJson as Record<string,unknown>}))}
  async setFlowExecutionState(i:{workspaceId:string;flowId:string;entryState:'open'|'blocked';executionState:'running'|'paused';pausedAt?:Date|null;status?:RuntimeFlow3['status']}){const n=await (this.db as any).flow.updateMany({where:{id:i.flowId,workspaceId:i.workspaceId},data:{entryState:i.entryState,executionState:i.executionState,pausedAt:i.pausedAt,status:i.status}});if(n.count!==1)throw new Error('FLOW_NOT_FOUND')}
  async holdPendingActions(w:string,f:string){const ids=(await (this.db as any).flowRun.findMany({where:{workspaceId:w,flowId:f,state:{in:['active','waiting','held']}},select:{id:true}})).map((x:any)=>x.id);if(!ids.length)return 0;const a=await (this.db as any).scheduledAction.updateMany({where:{workspaceId:w,aggregateId:{in:ids},state:{in:['pending','leased']}},data:{state:'held',leaseOwner:null,leaseExpiresAt:null}});await (this.db as any).flowRun.updateMany({where:{workspaceId:w,id:{in:ids},state:{in:['active','waiting']}},data:{state:'held'}});return a.count}
  async resumeHeldActions(i:{workspaceId:string;flowId:string;now:Date;pausedAt?:Date|null;overduePolicy:'immediate'|'shift_by_pause_duration'}){const ids=(await (this.db as any).flowRun.findMany({where:{workspaceId:i.workspaceId,flowId:i.flowId,state:'held'},select:{id:true}})).map((x:any)=>x.id);if(!ids.length)return 0;const actions=await (this.db as any).scheduledAction.findMany({where:{workspaceId:i.workspaceId,aggregateId:{in:ids},state:'held'}}),shift=i.pausedAt?Math.max(0,i.now.getTime()-i.pausedAt.getTime()):0;for(const a of actions){const due=i.overduePolicy==='shift_by_pause_duration'?new Date(a.dueAt.getTime()+shift):(a.dueAt<i.now?i.now:a.dueAt);await (this.db as any).scheduledAction.update({where:{id:a.id},data:{state:'pending',dueAt:due}})}await (this.db as any).flowRun.updateMany({where:{workspaceId:i.workspaceId,id:{in:ids}},data:{state:'waiting'}});return actions.length}
  async cancelPendingRunsAndActions(w:string,f:string,now:Date){const runs=await (this.db as any).flowRun.findMany({where:{workspaceId:w,flowId:f,state:{in:['active','waiting','held','failed']}},select:{id:true}}),ids=runs.map((x:any)=>x.id);if(!ids.length)return {runs:0,actions:0,runIds:[]};const a=await (this.db as any).scheduledAction.updateMany({where:{workspaceId:w,aggregateId:{in:ids},state:{notIn:['completed','cancelled']}},data:{state:'cancelled',completedAt:now,leaseOwner:null,leaseExpiresAt:null}});await (this.db as any).flowRun.updateMany({where:{workspaceId:w,id:{in:ids}},data:{state:'cancelled',endedAt:now,exitReason:'OPERATOR_CANCEL'}});return {runs:ids.length,actions:a.count,runIds:ids}}
  async exitRunAndCancelPending(i:{workspaceId:string;runId:string;actionId:string;now:Date;reason:string;detail:Record<string,unknown>}){const run=await (this.db as any).flowRun.findFirst({where:{id:i.runId,workspaceId:i.workspaceId},select:{id:true}});if(!run)throw new Error('FLOW_RUN_NOT_FOUND');const cancelledActions=await (this.db as any).scheduledAction.updateMany({where:{workspaceId:i.workspaceId,aggregateId:i.runId,id:{not:i.actionId},state:{notIn:['completed','cancelled']}},data:{state:'cancelled',completedAt:i.now,leaseOwner:null,leaseExpiresAt:null}}),cancelledMessages=await (this.db as any).message.updateMany({where:{workspaceId:i.workspaceId,flowRunId:i.runId,state:{in:['created','evaluating','eligible','held','rendered','queued']}},data:{state:'cancelled',finalAt:i.now,policyDecision:{decision:'CANCEL',reason:i.reason}}});await (this.db as any).scheduledAction.updateMany({where:{id:i.actionId,workspaceId:i.workspaceId},data:{state:'completed',completedAt:i.now,leaseOwner:null,leaseExpiresAt:null}});await (this.db as any).flowRun.updateMany({where:{id:i.runId,workspaceId:i.workspaceId},data:{state:'exited',endedAt:i.now,nextActionAt:null,exitReason:i.reason,rowVersion:{increment:1}}});await (this.db as any).traceEvent.create({data:{workspaceId:i.workspaceId,aggregateType:'flow_run',aggregateId:i.runId,kind:'flow.exited',detailJson:i.detail as any,occurredAt:i.now}});return {cancelledActions:cancelledActions.count,cancelledMessages:cancelledMessages.count}}
  async runCounts(w:string,f:string){const rows=await (this.db as any).flowRun.groupBy({by:['state'],where:{workspaceId:w,flowId:f},_count:{_all:true}}),out:Record<string,number>={total:0,active:0,waiting:0,held:0,completed:0,exited:0,cancelled:0,failed:0};for(const r of rows){out[r.state]=r._count._all;out.total!+=r._count._all}return out}
  async latestSegmentVersion(w:string,s:string){const x=await (this.db as any).segmentVersion.findFirst({where:{workspaceId:w,segmentId:s},orderBy:{versionNumber:'desc'}});return x?{id:x.id,workspaceId:w,segmentId:s,rule:x.ruleAstJson as SegmentRule,versionNumber:x.versionNumber}:null}
  async matchingProfileIds(w:string,rule:SegmentRule){const plan=compileSegmentRule(rule),wp=plan.params.length+1,rows=await (this.db as any).$queryRawUnsafe(`SELECT p.id FROM profile p WHERE p.workspace_id=$${wp}::uuid AND p.deleted_at IS NULL AND (${plan.sql})`,...plan.params,w);return rows.map((x:any)=>x.id)}
  async startSegmentEvaluation(i:{workspaceId:string;segmentId:string;segmentVersionId:string;trigger:string;startedAt:Date}){const x=await (this.db as any).segmentEvaluationRun.create({data:{workspaceId:i.workspaceId,segmentId:i.segmentId,segmentVersionId:i.segmentVersionId,state:'refreshing',trigger:i.trigger,startedAt:i.startedAt}});return {id:x.id}}
  async completeSegmentEvaluation(i:{id:string;memberCount:number;evaluatedAt:Date;completedAt:Date}){if(!i.id)return;await (this.db as any).segmentEvaluationRun.update({where:{id:i.id},data:{state:'current',memberCount:i.memberCount,evaluatedAt:i.evaluatedAt,completedAt:i.completedAt,errorCode:null}})}
  async failSegmentEvaluation(i:{id:string;errorCode:string;completedAt:Date}){if(!i.id)return;await (this.db as any).segmentEvaluationRun.update({where:{id:i.id},data:{state:'failed',errorCode:i.errorCode,completedAt:i.completedAt}})}
  async refreshSegmentProjection(i:{workspaceId:string;segmentId:string;segmentVersionId:string;memberProfileIds:string[];evaluatedAt:Date}){return this.transaction(async tx=>{const db=(tx as PrismaPhase3Repository).db as any,oldRows=await db.segmentMembershipProjection.findMany({where:{workspaceId:i.workspaceId,segmentVersionId:i.segmentVersionId,isMember:true},select:{profileId:true}}),old=new Set<string>((oldRows as any[]).map((x:any)=>String(x.profileId))),next=new Set<string>(i.memberProfileIds),entered=[...next].filter(x=>!old.has(x)),left=[...old].filter(x=>!next.has(x));for(const p of new Set<string>([...old,...next]))await db.segmentMembershipProjection.upsert({where:{segmentVersionId_profileId:{segmentVersionId:i.segmentVersionId,profileId:p}},create:{workspaceId:i.workspaceId,segmentId:i.segmentId,segmentVersionId:i.segmentVersionId,profileId:p,isMember:next.has(p),evaluatedAt:i.evaluatedAt},update:{isMember:next.has(p),evaluatedAt:i.evaluatedAt,evaluationRevision:{increment:1}}});const keys:string[]=[];for(const [transition,ids] of [['entered',entered],['left',left]] as const)for(const profileId of ids){const transitionKey=createHash('sha256').update(`${i.segmentVersionId}|${profileId}|${transition}`).digest('hex');try{const row=await db.segmentMembershipTransition.create({data:{workspaceId:i.workspaceId,segmentId:i.segmentId,segmentVersionId:i.segmentVersionId,profileId,transition,transitionKey,occurredAt:i.evaluatedAt}});keys.push(transitionKey);if(transition==='entered')await db.outboxEvent.create({data:{workspaceId:i.workspaceId,aggregateType:'segment_membership_transition',aggregateId:row.id,eventType:'phase3.audience.segment.entered',eventVersion:1,payloadJson:{transitionId:row.id,segmentId:i.segmentId,segmentVersionId:i.segmentVersionId,profileId,occurredAt:i.evaluatedAt.toISOString()},deduplicationKey:`segment-entered:${row.id}`}})}catch(e:any){if(e?.code!=='P2002')throw e}}return {segmentId:i.segmentId,segmentVersionId:i.segmentVersionId,members:next.size,entered:entered.length,left:left.length,evaluatedAt:i.evaluatedAt,transitionKeys:keys}})}

  async createCredential(i:{workspaceId:string;name:string;prefix:string;secretHash:string;scopes:string[];expiresAt?:Date}){const x=await (this.db as any).apiCredential.create({data:{workspaceId:i.workspaceId,name:i.name,prefix:i.prefix,secretHash:i.secretHash,scopesJson:i.scopes,expiresAt:i.expiresAt}});return {id:x.id,workspaceId:x.workspaceId,name:x.name,prefix:x.prefix,secretHash:x.secretHash,scopes:x.scopesJson as string[],createdAt:x.createdAt,lastUsedAt:x.lastUsedAt,expiresAt:x.expiresAt,revokedAt:x.revokedAt}}
  async credentialByPrefix(prefix:string){const x=await (this.db as any).apiCredential.findFirst({where:{prefix},orderBy:{createdAt:'desc'}});return x?{id:x.id,workspaceId:x.workspaceId,name:x.name,prefix:x.prefix,secretHash:x.secretHash,scopes:x.scopesJson as string[],createdAt:x.createdAt,lastUsedAt:x.lastUsedAt,expiresAt:x.expiresAt,revokedAt:x.revokedAt}:null}
  async revokeCredential(w:string,id:string,at:Date){const n=await (this.db as any).apiCredential.updateMany({where:{id,workspaceId:w,revokedAt:null},data:{revokedAt:at}});if(n.count!==1)throw new Error('API_KEY_NOT_FOUND')}
  async touchCredential(w:string,id:string,at:Date){await (this.db as any).apiCredential.updateMany({where:{id,workspaceId:w},data:{lastUsedAt:at}})}
  async listCredentials(w:string){return (await (this.db as any).apiCredential.findMany({where:{workspaceId:w},orderBy:{createdAt:'desc'}})).map((x:any)=>({id:x.id,workspaceId:x.workspaceId,name:x.name,prefix:x.prefix,secretHash:x.secretHash,scopes:x.scopesJson as string[],createdAt:x.createdAt,lastUsedAt:x.lastUsedAt,expiresAt:x.expiresAt,revokedAt:x.revokedAt}))}

  async recordDeadLetter(i:{workspaceId:string;resourceType:string;resourceId:string;jobType:string;businessKey:string;error:unknown}){const old=await (this.db as any).deadLetterItem.findFirst({where:{workspaceId:i.workspaceId,businessKey:i.businessKey,state:'open'}});if(old)return {id:old.id,workspaceId:old.workspaceId,resourceType:old.resourceType,resourceId:old.resourceId,jobType:old.jobType,businessKey:old.businessKey,error:old.errorJson,state:old.state,createdAt:old.createdAt,replayedAt:old.replayedAt};const x=await (this.db as any).deadLetterItem.create({data:{workspaceId:i.workspaceId,resourceType:i.resourceType,resourceId:i.resourceId,jobType:i.jobType,businessKey:i.businessKey,errorJson:i.error as any,state:'open'}});return {id:x.id,workspaceId:x.workspaceId,resourceType:x.resourceType,resourceId:x.resourceId,jobType:x.jobType,businessKey:x.businessKey,error:x.errorJson,state:x.state,createdAt:x.createdAt,replayedAt:x.replayedAt}}
  async listDeadLetters(w:string,flowId?:string){const items=await (this.db as any).deadLetterItem.findMany({where:{workspaceId:w},orderBy:{createdAt:'desc'}});if(!flowId)return items.map((x:any)=>({id:x.id,workspaceId:x.workspaceId,resourceType:x.resourceType,resourceId:x.resourceId,jobType:x.jobType,businessKey:x.businessKey,error:x.errorJson,state:x.state,createdAt:x.createdAt,replayedAt:x.replayedAt}));const runIds=new Set((await (this.db as any).flowRun.findMany({where:{workspaceId:w,flowId},select:{id:true}})).map((x:any)=>x.id)),actions=await (this.db as any).scheduledAction.findMany({where:{id:{in:items.map((x:any)=>x.resourceId)}},select:{id:true,aggregateId:true}}),by=new Map(actions.map((x:any)=>[x.id,x.aggregateId]));return items.filter((x:any)=>runIds.has(by.get(x.resourceId))).map((x:any)=>({id:x.id,workspaceId:x.workspaceId,resourceType:x.resourceType,resourceId:x.resourceId,jobType:x.jobType,businessKey:x.businessKey,error:x.errorJson,state:x.state,createdAt:x.createdAt,replayedAt:x.replayedAt}))}
  async replayDeadLetter(w:string,id:string,at:Date){return this.transaction(async tx=>{const db=(tx as PrismaPhase3Repository).db as any,d=await db.deadLetterItem.findFirst({where:{id,workspaceId:w,state:'open'}});if(!d)throw new Error('DEAD_LETTER_NOT_REPLAYABLE');if(d.resourceType!=='scheduled_action')throw new Error('DEAD_LETTER_UNSUPPORTED');const a=await db.scheduledAction.findFirst({where:{id:d.resourceId,workspaceId:w}});if(!a)throw new Error('SCHEDULED_ACTION_NOT_FOUND');if(['completed','cancelled'].includes(a.state))throw new Error('DEAD_LETTER_ALREADY_FINAL');const next=await db.scheduledAction.update({where:{id:a.id},data:{state:'pending',leaseOwner:null,leaseExpiresAt:null,dueAt:at}});await db.deadLetterItem.update({where:{id:d.id},data:{state:'replayed',replayedAt:at}});return raction(next)})}

}
