import { createHash } from 'node:crypto';
import type { PrismaClient } from '@prisma/client';
import type { FlowRuleEvaluationPort,Phase2FlowMessagePort } from '../../../application/src/ports/phase3-runtime-repository.js';
import type { SegmentRule } from '../../../domain/src/phase3/segment-rules.js';
import { compileSegmentRule } from '../../../domain/src/phase3/segment-rules.js';

export class PrismaFlowRuleEvaluationPort implements FlowRuleEvaluationPort{
  constructor(private readonly db:PrismaClient){}
  async evaluate(i:{workspaceId:string;profileId:string;flowRunId?:string;rule:unknown;at:Date}){const evaluate=async(rule:SegmentRule):Promise<any>=>{if(rule.type==='group'){const children=await Promise.all(rule.children.map(evaluate)),result=rule.operator==='and'?children.every(child=>child.result):children.some(child=>child.result);return {type:'group',operator:rule.operator,result,children}}const plan=compileSegmentRule(rule,{at:i.at,flowRunId:i.flowRunId}),wp=plan.params.length+1,pp=plan.params.length+2,rows:any[]=await this.db.$queryRawUnsafe(`SELECT EXISTS(SELECT 1 FROM profile p WHERE p.workspace_id=$${wp}::uuid AND p.id=$${pp}::uuid AND p.deleted_at IS NULL AND (${plan.sql})) AS result`,...plan.params,i.workspaceId,i.profileId);return {type:rule.type,result:Boolean(rows[0]?.result),ruleHash:createHash('sha256').update(JSON.stringify(rule)).digest('hex'),complexity:plan.complexity}};const evidence=await evaluate(i.rule as SegmentRule);return {result:evidence.result,evidence:{...evidence,ruleHash:createHash('sha256').update(JSON.stringify(i.rule)).digest('hex'),evaluatedAt:i.at.toISOString(),profileId:i.profileId,flowRunId:i.flowRunId??null,activityScope:i.flowRunId?'current_flow_run':'profile_history'}}}
}

export class PrismaPhase2FlowMessagePort implements Phase2FlowMessagePort{
  constructor(private readonly db:PrismaClient){}
  async createFlowMessage(i:{workspaceId:string;flowRunId:string;nodeId:string;profileId:string;emailVersionId:string;sequence:number;mode:'test'|'live'}){const key=createHash('sha256').update([i.workspaceId,'flow',i.mode,i.flowRunId,i.nodeId,i.profileId,i.emailVersionId,String(i.sequence)].join('|')).digest('hex');try{return await (this.db as any).$transaction(async(tx:any)=>{const existing=await tx.message.findUnique({where:{workspaceId_idempotencyKey:{workspaceId:i.workspaceId,idempotencyKey:key}}});if(existing)return {messageId:existing.id,duplicate:true};const sourceType=i.mode==='test'?'test':'flow',x=await tx.message.create({data:{workspaceId:i.workspaceId,sourceType,sourceId:i.flowRunId,flowRunId:i.flowRunId,nodeId:i.nodeId,profileId:i.profileId,emailVersionId:i.emailVersionId,idempotencyKey:key,state:'created',scheduledFor:new Date()}});await tx.traceEvent.create({data:{workspaceId:i.workspaceId,aggregateType:'message',aggregateId:x.id,kind:'message.intent_created',detailJson:{sourceType,flowRunId:i.flowRunId,nodeId:i.nodeId,emailVersionId:i.emailVersionId}}});await tx.outboxEvent.create({data:{workspaceId:i.workspaceId,aggregateType:'message',aggregateId:x.id,eventType:'phase2.message.policy',eventVersion:1,payloadJson:{messageId:x.id},deduplicationKey:`phase2-policy:${x.id}`}});return {messageId:x.id,duplicate:false}})}catch(e:any){if(e?.code==='P2002'){const x=await (this.db as any).message.findUniqueOrThrow({where:{workspaceId_idempotencyKey:{workspaceId:i.workspaceId,idempotencyKey:key}}});return {messageId:x.id,duplicate:true}}throw e}}
  async cancelPendingForRuns(i:{workspaceId:string;runIds:string[]}){if(!i.runIds.length)return 0;const result=await (this.db as any).message.updateMany({where:{workspaceId:i.workspaceId,flowRunId:{in:i.runIds},state:{in:['created','evaluating','eligible','held','rendered','queued']}},data:{state:'cancelled',finalAt:new Date()}});return result.count}
}
