'use client';
import {useEffect,useState} from 'react';
import {phase3Api} from '../../lib/phase3-api';

type Tab='runs'|'messages'|'analytics'|'versions'|'activity';
export function RunInspector({workspaceId,flowId}:{workspaceId:string;flowId:string}){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[dead,setDead]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[analytics,setAnalytics]=useState<any>(null),[versions,setVersions]=useState<any[]>([]),[activity,setActivity]=useState<any[]>([]),[tab,setTab]=useState<Tab>('runs'),[state,setState]=useState('all'),[msg,setMsg]=useState('');
 async function load(){try{const stateQuery=state==='all'?'':`?state=${state}`;const [runs,letters,messageRows,metricRows,versionRows,auditRows]=await Promise.all([phase3Api<any>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/runs${stateQuery}`),phase3Api<{items:any[]}>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/dead-letters`),phase3Api<{items:any[]}>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/messages`).catch(()=>({items:[]})),phase3Api<any>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/analytics`).catch(()=>null),phase3Api<{items:any[]}>(`/api/v1/workspaces/${workspaceId}/flows/${flowId}/versions`).catch(()=>({items:[]})),phase3Api<{items:any[]}>(`/api/v1/workspaces/${workspaceId}/audit?objectType=flow`).catch(()=>({items:[]}))]);setData(runs);setDead(letters.items??[]);setMessages(messageRows.items??[]);setAnalytics(metricRows);setVersions(versionRows.items??[]);setActivity((auditRows.items??[]).filter((item:any)=>item.objectId===flowId));setMsg('')}catch(error){setMsg(error instanceof Error?error.message:'Unable to load Flow monitoring.')}}
 useEffect(()=>{void load()},[workspaceId,flowId,state]);
 async function open(id:string){try{setSelected(await phase3Api(`/api/v1/workspaces/${workspaceId}/flow-runs/${id}`))}catch(error){setMsg(error instanceof Error?error.message:'Unable to open run.')}}
 async function replay(id:string){try{await phase3Api(`/api/v1/workspaces/${workspaceId}/dead-letters/${id}/replay`,{method:'POST',body:'{}'});setMsg('Replay was scheduled with its original business identity.');await load()}catch(error){setMsg(error instanceof Error?error.message:'Replay was not available.')}}
 return <div className="stack-gap"><section className="panel flow-monitor"><div className="toolbar"><div><h2>Flow monitoring</h2><a href={`/w/${workspaceId}/flows/${flowId}/builder`}>Back to builder</a></div><div className="flow-monitor-tabs">{(['runs','messages','analytics','versions','activity'] as Tab[]).map(item=><button type="button" key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item[0]!.toUpperCase()+item.slice(1)}</button>)}</div></div>
 {tab==='runs'&&<><label>Run state<select value={state} onChange={event=>setState(event.target.value)}><option value="all">All states</option><option value="active">Active</option><option value="waiting">Waiting</option><option value="completed">Completed</option><option value="exited">Exited</option><option value="cancelled">Cancelled</option><option value="failed">Failed</option></select></label>{data?.report&&<p>Active {data.report.active??0} · Waiting {data.report.waiting??0} · Completed {data.report.completed??0} · Exited {data.report.exited??0}</p>}<div className="table-scroll"><table><thead><tr><th>Profile</th><th>Version</th><th>State</th><th>Current node</th><th>Next action</th><th>Exit / error</th></tr></thead><tbody>{(data?.items??[]).map((run:any)=><tr key={run.id}><td><button type="button" onClick={()=>void open(run.id)}>{run.profileId}</button></td><td>{run.flowVersionId}</td><td>{run.state}</td><td>{run.currentNodeId}</td><td>{run.nextActionAt?new Date(run.nextActionAt).toLocaleString():'—'}</td><td>{run.exitReason??'—'}</td></tr>)}</tbody></table></div>{selected&&<section className="flow-run-trace"><h3>Run trace</h3><p>{selected.run?.state} · entered {selected.run?.enteredAt&&new Date(selected.run.enteredAt).toLocaleString()}</p><ol>{(selected.events??[]).map((event:any,index:number)=>{const decision=event.kind==='node.completed'&&event.detail?.nodeType==='conditional'?event.detail.evaluation:null;return <li key={`${event.kind}-${index}`}><strong>{decision?'Conditional split':event.kind}</strong> · {new Date(event.occurredAt).toLocaleString()}{decision&&<div className="flow-contract"><p>Decision: <strong>{decision.result?'YES':'NO'}</strong> → {event.detail.nextNodeId}</p><p>Rule evidence: {decision.evidence?.ruleHash??'published rule'}</p></div>}</li>})}</ol></section>}</>}
 {tab==='messages'&&<div className="table-scroll"><table><thead><tr><th>Profile</th><th>Node</th><th>Email version</th><th>Message state</th><th>Latest delivery / action needed</th></tr></thead><tbody>{messages.map((message:any)=><tr key={message.id} className={message.state==='held'||message.state==='skipped'?'flow-message-warning':message.state==='submitted'||message.state==='delivered'?'flow-message-success':undefined}><td>{message.profile?.originalEmail??message.profileId}</td><td>{message.nodeId}</td><td>{message.emailVersion?.versionNumber??message.emailVersionId}</td><td>{message.state}{message.submittedAt?` · ${new Date(message.submittedAt).toLocaleString()}`:''}</td><td>{message.delivery?.eventType??message.policyHold?.explanation??message.attempt?.explanation??message.attempt?.errorCode??(message.state==='held'?'Waiting on delivery policy…':'—')}</td></tr>)}</tbody></table>{!messages.length&&<p>No Flow messages have been created yet.</p>}{messages.some((message:any)=>message.state==='held'||message.state==='skipped')&&<p className="flow-contract">A held or skipped test message did not reach the inbox. Open Deliverability to confirm DNS is verified, then restart the API and worker so the latest delivery rules load.</p>}</div>}
 {tab==='analytics'&&<div className="flow-monitor-metrics">{analytics?<><p>Last {analytics.period.days} days · refreshed {new Date(analytics.freshness).toLocaleString()}</p><dl><dt>Entries</dt><dd>{analytics.entries}</dd><dt>Messages created</dt><dd>{analytics.messages.created}</dd><dt>Submitted</dt><dd>{analytics.messages.submitted}</dd><dt>Delivered</dt><dd>{analytics.messages.delivered}</dd><dt>Bounced</dt><dd>{analytics.messages.bounced}</dd></dl></>:<p>Analytics are unavailable for this role or Flow.</p>}</div>}
 {tab==='versions'&&<div className="table-scroll"><table><thead><tr><th>Version</th><th>Published</th><th>Graph hash</th><th>Execution guarantee</th></tr></thead><tbody>{versions.map(version=><tr key={version.id}><td>v{version.versionNumber}</td><td>{new Date(version.publishedAt).toLocaleString()}</td><td><code>{String(version.graphHash).slice(0,16)}…</code></td><td>New runs pin this version at entry</td></tr>)}</tbody></table>{!versions.length&&<p>No immutable version has been published yet.</p>}</div>}
 {tab==='activity'&&<div className="activity-list">{activity.length?activity.map(item=><article key={item.id}><strong>{String(item.action).replaceAll('.',' ')}</strong><span>{new Date(item.occurredAt).toLocaleString()}</span><small>{item.riskLevel} risk · {item.actorId??'System'}</small></article>):<p>No Flow audit activity is available for this role.</p>}</div>}
 </section><section className="panel"><h3>Dead letters</h3>{dead.length===0?<p>No open operational failures.</p>:<table><thead><tr><th>Job</th><th>Resource</th><th>State</th><th>Action</th></tr></thead><tbody>{dead.map(item=><tr key={item.id}><td>{item.jobType}</td><td>{item.resourceId}</td><td>{item.state}</td><td><button type="button" disabled={item.state!=='open'} onClick={()=>void replay(item.id)}>Safe replay</button></td></tr>)}</tbody></table>}</section>{msg&&<p role="status">{msg}</p>}</div>
}
