import {createHash,randomUUID} from 'node:crypto';
import {requiredCapacityScenarios4,validateCapacityEvidence4,type CapacityEvidence4} from '../../../domain/src/phase4/capacity.js';
import {hardeningEvidenceGate4,validateHardeningEvidence4,type HardeningCheckKey4,type HardeningStatus4} from '../../../domain/src/phase4/hardening.js';
import {canApproveRelease4,canEnterPilot4,nextPilotStage4,type EvidenceArea4,type PilotStopCode4,type ReleaseState4,type SecuritySeverity4} from '../../../domain/src/phase4/launch.js';
import {validateMigrationRehearsal4,type MigrationRehearsal4} from '../../../domain/src/phase4/migration.js';
import {requiredSloIndicators4,validateSloObservation4,type SloIndicator4} from '../../../domain/src/phase4/operations.js';
import {validatePilotObservation4,type PilotObservation4} from '../../../domain/src/phase4/pilot.js';
import {canAdvanceDeletion4,type DeletionState4} from '../../../domain/src/phase4/privacy.js';
import {requiredRecoveryScenarios4,type RecoveryScenario4} from '../../../domain/src/phase4/recovery.js';
import type {Phase4Repository} from '../ports/phase4-repository.js';

function latestBy<T>(items:T[],key:(x:T)=>string,time:(x:T)=>Date){const m=new Map<string,T>();for(const x of [...items].sort((a,b)=>time(a).getTime()-time(b).getTime()))m.set(key(x),x);return m}
export class Phase4Service{
 constructor(private readonly repo:Phase4Repository){}
 async recordSecurityFinding(i:{title:string;severity:SecuritySeverity4;workspaceId?:string;owner?:string;reviewAt?:Date}){if(!i.title.trim())throw new Error('SECURITY_FINDING_TITLE_REQUIRED');const x={id:randomUUID(),workspaceId:i.workspaceId,title:i.title.trim(),severity:i.severity,status:'open' as const,owner:i.owner,reviewAt:i.reviewAt,createdAt:new Date()};await this.repo.saveSecurityFinding(x);return x}
 async closeSecurityFinding(id:string){const all=await this.repo.securityFindings(),f=all.find(x=>x.id===id);if(!f)throw new Error('SECURITY_FINDING_NOT_FOUND');const x={...f,status:'closed' as const,closedAt:new Date()};await this.repo.saveSecurityFinding(x);return x}
 async recordHardeningEvidence(i:{checkKey:HardeningCheckKey4;status:HardeningStatus4;summary:string;owner?:string;evidence?:Record<string,unknown>;reviewAt?:Date}){const x=validateHardeningEvidence4({id:randomUUID(),...i,evidence:i.evidence??{},recordedAt:new Date()});await this.repo.saveHardeningEvidence(x);return x}
 async recordLaunchEvidence(i:{area:EvidenceArea4;status:'pending'|'passed'|'blocked';summary:string;approver?:string}){if(i.status==='passed'&&!i.approver)throw new Error('LAUNCH_EVIDENCE_APPROVER_REQUIRED');const x={id:randomUUID(),...i,recordedAt:new Date()};await this.repo.saveLaunchEvidence(x);return x}
 async recordStopSignal(i:{code:PilotStopCode4;detail:string}){if(!i.detail.trim())throw new Error('STOP_SIGNAL_DETAIL_REQUIRED');const x={id:randomUUID(),...i,active:true,observedAt:new Date()};await this.repo.saveStopSignal(x);const pilot=await this.repo.pilot();if(pilot.state==='running'||pilot.state==='ready')await this.repo.savePilot({...pilot,state:'held',holdReason:i.code});return x}
 async clearStopSignal(id:string){const all=await this.repo.stopSignals(),x=all.find(s=>s.id===id);if(!x)throw new Error('STOP_SIGNAL_NOT_FOUND');const next={...x,active:false,clearedAt:new Date()};await this.repo.saveStopSignal(next);return next}
 async recordCapacity(e:Omit<CapacityEvidence4,'id'>){const x=validateCapacityEvidence4({id:randomUUID(),...e});await this.repo.saveCapacityEvidence(x);return x}
 async recordRecovery(i:{scenario:RecoveryScenario4;status:'planned'|'passed'|'failed';evidence?:Record<string,unknown>;rpoMinutes?:number;rtoMinutes?:number}){if(i.status==='passed'&&i.scenario==='backup_restore'&&(i.rpoMinutes==null||i.rtoMinutes==null))throw new Error('BACKUP_RECOVERY_RPO_RTO_REQUIRED');const now=new Date(),x={id:randomUUID(),scenario:i.scenario,status:i.status,startedAt:now,finishedAt:i.status==='planned'?null:now,rpoMinutes:i.rpoMinutes,rtoMinutes:i.rtoMinutes,evidence:i.evidence??{}};await this.repo.saveRecoveryExercise(x);return x}
 async recordSloObservation(i:{indicator:SloIndicator4;windowStart:Date;windowEnd:Date;observed:number|boolean;objective:string;passed:boolean;evidence?:Record<string,unknown>}){const x=validateSloObservation4({id:randomUUID(),...i,evidence:i.evidence??{},recordedAt:new Date()});await this.repo.saveSloObservation(x);return x}
 async recordMigrationRehearsal(i:Omit<MigrationRehearsal4,'id'>){const x=validateMigrationRehearsal4({id:randomUUID(),...i});await this.repo.saveMigrationRehearsal(x);await this.recordHardeningEvidence({checkKey:'migration.rehearsal',status:'passed',summary:`Reconciled representative migration from ${x.sourceLabel}`,owner:x.owner,evidence:{migrationRehearsalId:x.id,sourceRows:x.sourceRows,acceptedRows:x.acceptedRows,rejectedRows:x.rejectedRows}});return x}
 async recordPilotObservation(i:Omit<PilotObservation4,'id'|'recordedAt'>){const current=await this.repo.pilot();if(current.stage!==i.stage)throw new Error('PILOT_OBSERVATION_STAGE_MISMATCH');const x=validatePilotObservation4({id:randomUUID(),...i,recordedAt:new Date()});await this.repo.savePilotObservation(x);return x}

 async hardeningStatus(){
  const [p2,p3,findings,signals,hardening,capacity,recovery,slo,migrations]=await Promise.all([this.repo.phase2ExternalPassed(),this.repo.phase3RealPassed(),this.repo.securityFindings(),this.repo.stopSignals(),this.repo.hardeningEvidence(),this.repo.capacityEvidence(),this.repo.recoveryExercises(),this.repo.sloObservations(),this.repo.migrationRehearsals()]);
  const hard=hardeningEvidenceGate4(hardening);
  const capLatest=latestBy(capacity,x=>x.scenario,x=>x.finishedAt);const missingCapacity=requiredCapacityScenarios4.filter(k=>!capLatest.get(k)?.passed||!(capLatest.get(k)?.safeCeiling!>0));
  const recLatest=latestBy(recovery,x=>x.scenario,x=>x.finishedAt??x.startedAt??new Date(0));const missingRecovery=requiredRecoveryScenarios4.filter(k=>recLatest.get(k)?.status!=='passed');
  const backup=recLatest.get('backup_restore');const recoveryObjectivePassed=Boolean(backup&&backup.status==='passed'&&(backup.rpoMinutes??Infinity)<=15&&(backup.rtoMinutes??Infinity)<=240);
  const sloLatest=latestBy(slo,x=>x.indicator,x=>x.recordedAt);const missingSlo=requiredSloIndicators4.filter(k=>!sloLatest.get(k)?.passed);
  const migrationPassed=migrations.some(x=>x.reconciled);
  const hardeningPassed=hard.passed&&missingCapacity.length===0&&missingRecovery.length===0&&recoveryObjectivePassed&&missingSlo.length===0&&migrationPassed;
  const gate=canEnterPilot4({phase2ExternalPassed:p2,phase3RealPassed:p3,hardeningPassed,findings,signals});
  const reasons=[...gate.reasons];if(hard.missing.length)reasons.push(...hard.missing.map(x=>`HARDENING_${x.toUpperCase().replaceAll('.','_')}`));if(missingCapacity.length)reasons.push(...missingCapacity.map(x=>`CAPACITY_${x.toUpperCase()}`));if(missingRecovery.length)reasons.push(...missingRecovery.map(x=>`RECOVERY_${x.toUpperCase()}`));if(!recoveryObjectivePassed)reasons.push('RECOVERY_RPO_RTO_OBJECTIVE');if(missingSlo.length)reasons.push(...missingSlo.map(x=>`SLO_${x.toUpperCase()}`));if(!migrationPassed)reasons.push('MIGRATION_REHEARSAL');
  return {passed:reasons.length===0,reasons:[...new Set(reasons)],phase2ExternalPassed:p2,phase3RealPassed:p3,hardeningEvidence:hard,missingCapacity,missingRecovery,recoveryObjectivePassed,missingSlo,migrationPassed};
 }
 async launchStatus(){const [findings,evidence,signals,pilot,release,hardening,observations]=await Promise.all([this.repo.securityFindings(),this.repo.launchEvidence(),this.repo.stopSignals(),this.repo.pilot(),this.repo.releaseState(),this.hardeningStatus(),this.repo.pilotObservations()]);const pilotGate={allowed:hardening.passed,reasons:hardening.reasons};const releaseGate=canApproveRelease4({pilot,findings,evidence,signals,hardeningPassed:hardening.passed});return {gate:pilotGate,pilotGate,releaseGate,pilot,release,findings,evidence,signals,hardening,observations}}
 async startPilot(){const s=await this.launchStatus();if(!s.pilotGate.allowed)throw new Error(`PILOT_GATE_BLOCKED:${s.pilotGate.reasons.join(',')}`);if(s.pilot.state==='completed')throw new Error('PILOT_ALREADY_COMPLETED');if(s.pilot.state==='running')return s.pilot;const next={...s.pilot,state:'running' as const,startedAt:s.pilot.startedAt??new Date(),completedAt:null,holdReason:null};await this.repo.savePilot(next);return next}
 async completePilotStage(){const s=await this.launchStatus();if(s.pilot.state!=='running')throw new Error('PILOT_NOT_RUNNING');const observation=s.observations.find(x=>x.stage===s.pilot.stage);if(!observation)throw new Error(`PILOT_STAGE_${s.pilot.stage}_OBSERVATION_REQUIRED`);const nextStage=nextPilotStage4(s.pilot.stage);const next=nextStage===s.pilot.stage?{...s.pilot,state:'completed' as const,completedAt:new Date()}:{...s.pilot,stage:nextStage,state:'ready' as const,completedAt:null};await this.repo.savePilot(next);return next}
 async approveRelease1(i:{approvedBy:string;notes?:string}){if(!i.approvedBy.trim())throw new Error('RELEASE_APPROVER_REQUIRED');const s=await this.launchStatus();if(!s.releaseGate.allowed)throw new Error(`RELEASE_GATE_BLOCKED:${s.releaseGate.reasons.join(',')}`);const x:ReleaseState4={status:'approved',approvedAt:new Date(),approvedBy:i.approvedBy,notes:i.notes};await this.repo.saveReleaseState(x);return x}
 async requestDeletion(workspaceId:string,profileId:string){const old=await this.repo.deletionJob(workspaceId,profileId);if(old&&old.state!=='failed')return old;await this.repo.placeProfileDeletionHold(workspaceId,profileId);await this.repo.cancelPendingMarketing(workspaceId,profileId);const now=new Date(),x={id:randomUUID(),workspaceId,profileId,state:'requested' as const,requestedAt:now,updatedAt:now};await this.repo.saveDeletionJob(x);return x}
 async advanceDeletion(workspaceId:string,profileId:string,to:DeletionState4){const job=await this.repo.deletionJob(workspaceId,profileId);if(!job)throw new Error('DELETION_JOB_NOT_FOUND');if(!canAdvanceDeletion4(job.state,to))throw new Error(`DELETION_TRANSITION_INVALID:${job.state}->${to}`);const next=await this.repo.performDeletionStep(job,to);if(to==='tombstoned'&&!next.tombstoneHash){const withHash={...next,tombstoneHash:createHash('sha256').update(`${workspaceId}|${profileId}|deleted`).digest('hex')};await this.repo.saveDeletionJob(withHash);return withHash}return next}
}
